### PR TITLE
fix(telemetry): Geo Location and population data placement

### LINKED ISSUE #10123: bug: IP Geolocation API Rate Limiting Causes Warnings (ipapi.co)
### Describe the bug

Warning: file_get_contents(https://ipapi.co/23.30.162.118/json/): Failed to open stream: HTTP request failed! HTTP/1.1 429 Too Many Requests

then see this:

Warning: file_get_contents(http://www.geoplugin.net/json.gp?ip=23.30.162.118): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #10123

#### Changes proposed in this pull request:
refactored how geo handled requests and caching.
moved population data up one level in payload.
minor fix for weno sync record parse.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Want to look over and merge if okay? Good work on test @kojiromike seem to be running much quicker.

File: src/Telemetry/GeoTelemetry.php [hunk 1]
```diff
@@ -28,6 +30,8 @@
 class GeoTelemetry implements GeoTelemetryInterface
 {
     private const GET_IP_URL = 'https://api.ipify.org';
+    private const CACHE_FILE = '/tmp/openemr_geo_cache.json';
```
Comment (bradymiller) [inline src/Telemetry/GeoTelemetry.php]: hi @sjpadgett , shouldn't this use the global setting for temp directory rather than hardcoding?

Comment (sjpadgett) [reply src/Telemetry/GeoTelemetry.php]: @bradymiller good catch thanks. Test okay. Going back to bed. I was hoping to get in before dev resets.
Getting some really cool stats from telemetry. It's becoming addictive writing reports. Be amazed really how much we collect!
