### PR TITLE
fix(superbill_custom_full): code search previous button goes forward

### LINKED ISSUE #9320: Code Search `<<` button goes forward instead of backward
# Bug: Code Search Pagination "Previous" Button Goes Forward Instead of Backward

## Issue Summary
The pagination navigation in the code search interface is broken - both the "Next" and "Previous" buttons advance forward through pages. The "Previous" button fails to go backward to previous pages.

## Environment
- **OpenEMR Version:** 7.0.3.4 (also reproducible on demo site)
- **Code Type:** ICD-10 codes
- **Interface:** Admin > Coding > External Data Loads

## Steps to Reproduce
1. Install OpenEMR 7.0.3.4
2. Load ICD-10 codes via Admin > Coding > External Data Loads
3. View loaded codes without entering search criteria
4. Click "Search" to display results (shows items 1-100)
5. Click the **next arrow** to advance (displays items 101-200)
6. Click the **back arrow** to return to the previous page

## Expected Behavior
- **Next button:** Should advance forward to the next page (e.g., 1-100 → 101-200 → 201-300)
- **Previous button:** Should go backward to the previous page (e.g., 201-300 → 101-200 → 1-100)

## Actual Behavior
- **Next button:** ✓ Works correctly, advances forward (1-100 → 101-200)
- **Previous button:** ✗ ALSO advances forward (101-200 → 201-300) instead of going backward

Both buttons go in the same direction (forward). The Previous button completely fails to navigate backward.

## Root Cause

**File:** `interface/patient_file/encounter/superbill_custom_full.php`
**Line:** 709

Both the Previous (`<<`) and Next (`>>`) buttons call the same function with the same positive value:

```php
<!-- Line 709: Previous button - BUG! -->
<a href="javascript:submitList(<?php echo attr_js($pagesize); ?>)">
    &lt;&lt;
</a>

<!-- Line 715: Next button - Correct -->
<a href="javascript:submitList(<?php echo attr_js($pagesize); ?>)">
    &gt;&gt;
</a>
```

The `submitList(offset)` function adds the offset to the current position. Since both buttons pass a positive offset, both advance forward.

### PR DESCRIPTION
**Pull request by kojiromike**
fixes #9320

### CODE REVIEW

File: interface/patient_file/encounter/superbill_custom_full.php [hunk 1]
```diff
@@ -706,7 +706,7 @@ class="col-form-label col-form-label-sm col-md-1"><?php echo xlt('Revenue Code')
             </div>
             <div class="col-md text-right">
                 <?php if ($fstart) { ?>
-                    <a href="javascript:submitList(<?php echo attr_js($pagesize); ?>)">
+                    <a href="javascript:submitList(-<?php echo attr_js($pagesize); ?>)">
```
Comment (stephenwaite) [inline interface/patient_file/encounter/superbill_custom_full.php:709]: Image

**Review by stephenwaite — APPROVED** [review]
