### PR TITLE
fix(payments): Fix double-escaping and some raw SQL

### LINKED ISSUE #10361: bug(payments): double-escaped values following refactor
https://github.com/openemr/openemr/pull/10246#discussion_r2714067608

I mistakenly thought these calls were raw values, and it was pointed out they get escaped deeper down the call stack.

### PR DESCRIPTION
**Pull request by Firehed**
Fixes #10361

#### Short description of what this resolves:
Values could be double-escaped following a refactor to use prepared statements

#### Changes proposed in this pull request:
Changes most calls to `formData` to a new wrapper function that _does not_ escape, which is safe to use with the prepared statements.

For the few places not directly passed in, I verified that they either were on a different prepared statement path (in which case they were already double-escaped prior to the refactor) or converted them to a PS.

This eliminates _most_ calls to `formData`. There are a few left which will be more complex to update (see the dbal comment inline)

#### Does your code include anything generated by an AI Engine? Yes / No
No

### CODE REVIEW

File: interface/billing/edit_payment.php [hunk 1]
```diff
@@ -101,27 +102,33 @@
...
+        $updatedValues['modified_time'] = trim($modified_time);
+        $updatedValues['payment_type'] = trimPost('type_name');
+        $updatedValues['description'] = trimPost('description');
+        $updatedValues['adjustment_code'] = trimPost('adjustment_code');
+        $updatedValues['post_to_date'] = trim($post_to_date);
+        $updatedValues['payment_method'] = trimPost('payment_method');
+
+        // This becomes MUCH more straightforward with actual dbal, but this is
+        // still safe from SQLI since the keys are all string literals.
+        $query = 'UPDATE ar_session SET ';
```
Comment (Firehed) [inline interface/billing/edit_payment.php:125]: ar_session interactions need a similar treatment to what was done in the refactor that prompted this cleanup.

**Comment by bradymiller** [comment]
nice stuff!
(do not plan to port this to rel-800 (unless you think should go there))

**Comment by Firehed** [comment]
@bradymiller This and #10246 should stay as a pair. I think both should stay out.
