### PR TITLE
fixes CQM source of payment for ins search

### LINKED ISSUE #5349: CQM source of payment for demographics ins search
### Describe the bug

need to bring new `cqm_sop` field from insurance_companies to other insurance lookup

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5349

#### Short description of what this resolves:
fixes above issue
also restores ability to search by fixing SQL query that failed to match if no phone number was entered for an insurance
also fixes `ct_key` in database.sql and reverts the change made in find_code_popup.php to circumvent
also adds `order` to `order_types` for QRDA I Procedure performed

### CODE REVIEW

File: interface/patient_file/summary/demographics_full.php [hunk 1]
```diff
@@ -1158,9 +1158,7 @@ class='text'>(<?php echo xlt('Browse'); ?>)</a>
             var fval = $('#form_' + flds[i]).val();
             duplicateFieldsArray['#form_' + flds[i]] = fval;
         }
-        $(".sel2").select2({
-            <?php require($GLOBALS['srcdir'] . '/js/xl/select2.js.php'); ?>
-        });
```
Comment (stephenwaite) [inline interface/patient_file/summary/demographics_full.php:1163]: pretty sure this require is satisfied when select2 is brought in with the core header

Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: Select2 may have several instances each requiring its own library. That's why you see the way it is. So this is a no no!:)

Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: Also may have different setups.

File: sql/6_1_0-to-7_0_0_upgrade.sql [hunk 2]
```diff
@@ -666,4 +666,8 @@ SET sql_mode = @currentSQLMode;
 
 #IfMissingColumn insurance_companies cqm_sop
 ALTER TABLE `insurance_companies` ADD `cqm_sop` int DEFAULT NULL COMMENT 'HL7 Source of Payment for eCQMs';
+#EndIf
+
+#IfNotRow2D list_options list_id order_type option_id order
+INSERT INTO list_options ( list_id, option_id, title, seq, is_default ) VALUES ('order_type','order','Order',90,0);
 #EndIf
```
Comment (sjpadgett) [inline sql/6_1_0-to-7_0_0_upgrade.sql:673]: needs new line at end of file. There are several reason for this one being it helps ensure our upgrade parser get the last item. Most times it may work but, I wouldn't count on it!

File: src/Services/InsuranceCompanyService.php [hunk 3]
```diff
@@ -256,7 +257,8 @@ public function insert($data)
                 $data["ins_type_code"],
                 $data["x12_receiver_id"],
                 $data["x12_default_partner_id"] ?? '',
-                $data["alt_cms_id"]
+                $data["alt_cms_id"],
+                $data["cqm_sop"] ?? null,
```
Comment (sjpadgett) [inline src/Services/InsuranceCompanyService.php:261]: Looks like a new column. If so, Do I need to change import destination for payer. Also payer cqm service.

File: interface/patient_file/summary/demographics_full.php (hunk 1 above)
Comment (stephenwaite) [reply interface/patient_file/summary/demographics_full.php:1163]: you already bring it in
https://github.com/openemr/openemr/blob/master/interface/patient_file/summary/demographics_full.php#L96

Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: I don't understand. You're removing the lines the permalink points to. What you're doing is removing the class link to select2 and the translations. Where is the class sel2 already inited?

Comment (stephenwaite) [reply interface/patient_file/summary/demographics_full.php:1163]: am removing lines 1161-1163, it's already required from line 96 right?

Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: I see your confusion. Each instance of select2 needs the translations pulled in by the required. Otherwise the select2 defaults untranslated would be used plus, all the html tags where the sel2 class is used prob won't work.

Comment (stephenwaite) [reply interface/patient_file/summary/demographics_full.php:1163]: ok, I'll revert and start another issue for it, try to figure out why that is breaking the returned entry from appearing in the select label

Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: Most likely the styling. I noticed this is the only select2 that is not using the bootstrap stylings. Checkout one of my select2's and emulate setup.
I should have done that when I was putting in the new ones. The one we are looking at was the only select2 when I put in the others. It has been there for awhile.

**Review by bradymiller — APPROVED** [review]

File: interface/patient_file/summary/demographics_full.php (hunk 1 above)
Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: do you have a screen shot of issue?

File: src/Services/InsuranceCompanyService.php (hunk 3 above)
Comment (sjpadgett) [reply src/Services/InsuranceCompanyService.php:261]: okay. please remind me when merged.

File: interface/patient_file/summary/demographics_full.php (hunk 1 above)
Comment (sjpadgett) [reply interface/patient_file/summary/demographics_full.php:1163]: Thinking about it @stephenwaite , do we need select2 for the two places it is used(sel2 class that is). It was put in for searching

File: interface/patient_file/summary/demographics_full.php [hunk 4]
```diff
@@ -1158,7 +1158,10 @@ class='text'>(<?php echo xlt('Browse'); ?>)</a>
             var fval = $('#form_' + flds[i]).val();
             duplicateFieldsArray['#form_' + flds[i]] = fval;
         }
-
+        $(".sel2").select2({
+            <?php require($GLOBALS['srcdir'] . '/js/xl/select2.js.php'); ?>
+        });
```
Comment (sjpadgett) [inline interface/patient_file/summary/demographics_full.php:1163]: Could try:
```
$(".sel2").select2({
    theme: "bootstrap4",
    dropdownAutoWidth: true,
    width: 'resolve',
<?php require($GLOBALS['srcdir'] . '/js/xl/select2.js.php'); ?>
});
```

**Comment by sjpadgett** [comment]
@stephenwaite Are we okay on licensing on this https://github.com/openemr/openemr/pull/5350/files#diff-506f53abf55f1b6a8944c6c5042520a5d630b24a5c108d4f89b5bae12d013c35 i.e. contrib/cqm_valueset/ep_ec_only_cms_20210506.xml.zip

**Comment by stephenwaite** [comment]
thanks @sjpadgett , just removed it

File: interface/patient_file/summary/demographics_full.php (hunk 4 above)
Comment (stephenwaite) [reply interface/patient_file/summary/demographics_full.php:1163]: works like a champ :boxing_glove: 
pushed it to #5352 and now passing cms147v11
sheep

Comment (bradymiller) [reply interface/patient_file/summary/demographics_full.php:1163]: munchkin-wizard-of-oz
