### PR TITLE
fix: Smarty cal php82 warnings

### LINKED ISSUE #6281: Bunch of PHP 8.2 warnings at Admin->Clinic->Calendar->Categories
Bunch of PHP 8.2 warnings at Admin->Clinic->Calendar->Categories

Do not worry about the deprecated messages. I have fixed those in my ongoing PHP 8.2 sweep :)

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6281

### CODE REVIEW

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 1]
```diff
@@ -680,14 +680,15 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
 
-    $form_hidden = "<input type=\"hidden\" name=\"is_update\" value=\"" . attr($is_update) . "\" />";
-    $form_hidden .= "<input type=\"hidden\" name=\"pc_event_id\" value=\"" . attr($pc_event_id) . "\" />";
+    $form_hidden = "<input type=\"hidden\" name=\"is_update\" value=\"" . attr($is_update ?? '') . "\" />";
+    $form_hidden .= "<input type=\"hidden\" name=\"pc_event_id\" value=\"" . attr($pc_event_id ?? '') . "\" />";
     if (isset($data_loaded)) {
         $form_hidden .= "<input type=\"hidden\" name=\"data_loaded\" value=\"" . attr($data_loaded) . "\" />";
-        $tpl->assign('FormHidden', $form_hidden);
     }
+    $tpl->assign('FormHidden', $form_hidden);
```
Comment (stephenwaite) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php:688]: not sure about this here, might have to add an else that blanks the `value` attribute maybe

Comment (bradymiller) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php:688]: Odd since looks like $form_hidden elements not added unless isset($data_loaded). Maybe something like:
```
    if (isset($data_loaded)) {
        $form_hidden = "<input type=\"hidden\" name=\"is_update\" value=\"" . attr($is_update ?? '') . "\" />";
        $form_hidden .= "<input type=\"hidden\" name=\"pc_event_id\" value=\"" . attr($pc_event_id ?? '') . "\" />";
        $form_hidden .= "<input type=\"hidden\" name=\"data_loaded\" value=\"" . attr($data_loaded ?? '') . "\" />";
        $tpl->assign('FormHidden', $form_hidden);
    }
```
And then in smarty if it is outputting FormHidden, only do it there if FormHidden is not empty

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear
