### PR TITLE
Fix User Admin screen Google Email for Login does not save when creating new user

### LINKED ISSUE #7393: bug: User Admin screen 	Google Email for Login does not save when creating new user
### Describe the bug
If you navigate to the Admin Users screen and attempt to add a new user with an email address and save the user, the email address does not display when you go back to edit the user.  If you edit an existing user the email address saves.

- Browser:
- OpenEMR version: development release (7.0.2+)
- Operating system: Ubuntu Linux 22.04

### PR DESCRIPTION
**Pull request by AlceaDev**
Fixes #7393

#### Short description of what this resolves:
Not exist insert statement for google_signin_email column in users table.
So add insert statement value to column in interface/usergroup/usergroup_admin.php.

### CODE REVIEW

File: interface/usergroup/usergroup_admin.php [hunk 1]
```diff
@@ -351,6 +351,7 @@
             "', mname = '"         . add_escape_custom(trim((isset($_POST['mname']) ? $_POST['mname'] : ''))) .
             "', lname = '"         . add_escape_custom(trim((isset($_POST['lname']) ? $_POST['lname'] : ''))) .
             "', suffix = '"         . add_escape_custom(trim((isset($_POST['suffix']) ? $_POST['suffix'] : ''))) .
+            "', google_signin_email = '" . add_escape_custom(trim((isset($_POST['google_signin_email']) ? $_POST['google_signin_email'] : ''))) .
```
Comment (sjpadgett) [inline interface/usergroup/usergroup_admin.php:354]: This could be written as
`add_escape_custom(trim($_POST['google_signin_email'] ?? ''))`
What you have is acceptable as well so, is this done?

**Review by sjpadgett — APPROVED** [review]
