### PR TITLE
Fix Dicom Viewer 404 image load

### LINKED ISSUE #8065: Dicom view image load fails
### Describe the bug
Path build is missing web root when server domain isn't aliased where web_root being empty would work.
We see this often. Problem is $web_root wasn't being passed in to viewer twig template

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
twig template missing web_root var init

Fixes #8065 

#### Short description of what this resolves:
image loading

### CODE REVIEW

File: library/dicom_frame.php [hunk 1]
```diff
@@ -44,6 +44,7 @@
 $twig = (new TwigContainer(null, $GLOBALS['kernel']))->getTwig();
 echo $twig->render("dicom/dicom-viewer.html.twig", [
     'assets_static_relative' => $GLOBALS['assets_static_relative']
+    ,'web_root' => $web_root
```
Comment (adunsulag) [inline library/dicom_frame.php:47]: I was scratching my head thinking what broke, but apparently the bug was that the twig file expects **web_root** when the global twig value defined here is **webroot** https://github.com/openemr/openemr/blob/3a1343e3861caf760d199e8385f17f26419d5d13/src/Common/Twig/TwigExtension.php#L72

Ouch, my bad.

Comment (adunsulag) [reply library/dicom_frame.php:47]: So this solves the problem but I should have used webroot when I did the refactor.  Keep forgetting to check the webroot extension when doing twig refactors.

Comment (sjpadgett) [reply library/dicom_frame.php:47]: If this is all from a refactor to twig i'd say you got off pretty good! :)

**Comment by HARI-14052002** [comment]
Thanks for the fix brother.It worked perfectly.
