### PR TITLE
bug fixes and feature changes

### LINKED ISSUE #6588: Create event to send SMS and Email notifications
Just an event to dispatch a notification from various places in core.
Mostly assessments notify patient to complete or do and scheduled portal documents.

### PR DESCRIPTION
**Pull request by sjpadgett**
- more dark theme changes

Fixes #6588 

I can't help myself. The dark theme now works.

### CODE REVIEW

**Comment by sjpadgett** [comment]
how aggravating!

**Comment by stephenwaite** [comment]
smaller_excited_elephant

**Comment by sjpadgett** [comment]
@adunsulag May be of interest

File: interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    public static function getSubscribedEvents(): array
+    {
+        return [
+            SendNotificationEvent::class => 'onNotifyEvent',
+        ];
+    }
+
+    public function subscribeToEvents(EventDispatcher $eventDispatcher)
+    {
+        $eventDispatcher->addListener('sendNotification.sendSMS', [$this, 'onNotifyEvent']);
```
Comment (adunsulag) [inline interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php:43]: @sjpadgett So it looks like I would just need to fire off the sendNotifiction.sendSMS event when the appointment is saved.  

I'm wondering if it makes sense to name this sendNotification.send since it handles both SMS and email?

Comment (sjpadgett) [reply interface/modules/custom_modules/oe-module-faxsms/src/Events/NotificationEventListener.php]: renamed. will need to pass in args (see example in event class) to support what is included in message  minimum is pid and a message body.

**Comment by sjpadgett** [comment]
merging to make available to @adunsulag

File: sql/7_0_1-to-7_0_2_upgrade.sql [hunk 2]
```diff
@@ -208,3 +208,7 @@ CREATE TABLE `patient_settings` (
 PRIMARY KEY (`setting_patient`, `setting_label`)
 ) ENGINE=InnoDB;
 #EndIf
+
+#IfNotRow2D list_options list_id lists option_id notification_template
```
Comment (bradymiller) [inline sql/7_0_1-to-7_0_2_upgrade.sql:212]: gonna fix above line up in a quick follow up commit :)
```
#IfNotRow2D list_options list_id Document_Template_Categories option_id notification_template
```

Comment (sjpadgett) [reply sql/7_0_1-to-7_0_2_upgrade.sql:212]: Hmm @bradymiller sorry and thanks.
@stephenwaite thanks for catching that last one also.
I think I’ll start waiting for reviews. I did test this and seem to work. But wanted to get it in to continue development.
I’m thinking I should retire soon

Comment (bradymiller) [reply sql/7_0_1-to-7_0_2_upgrade.sql:212]: no prob at all! keep flying :)
