### PR TITLE
Fix #3070 refine test table

### LINKED ISSUE #3070: Test table refine to use Bootstrap
### Describe the bug

Test table still used legacy style and outdated syntax.

### To Reproduce

1. Go to the Administrator > Clinic 
2. Click the Calendar
3. Choose Test system
4. See the table.

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3070 

#### Short description of what this resolves:
Refine the test table style.
Used Bootstrap style to replace outdated syntax.

Untitled

### CODE REVIEW

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 1]
```diff
@@ -39,21 +40,20 @@ function postcalendar_admin_modifyconfig($msg = '', $showMenu = true)
...
+
     $output->Text($header);
-    if ($showMenu) {
-        $output->Text(postcalendar_adminmenu());
-    }
 
     if (!empty($msg)) {
-        $output->Text('<center><div style="padding:5px; border:1px solid green; background-color: lightgreen;">');
+        $output->Text(postcalendar_adminmenu("clearCache"));
+        $output -> Text('<div class="alert alert-success ml-5 mr-5" role="alert">');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `ml-1 mr-1`. Padding isn't measured in pixels in Bootstrap. [Please read the documentation on how to do this correctly](https://getbootstrap.com/docs/4.4/utilities/spacing/).

Also there was a `<center>` tag here that wasn't addressed by adding the `text-center` class to this element.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 2]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
     }
 
-    $output->Text(postcalendar_adminmenu());
+    $output->Text(postcalendar_adminmenu("category"));
 
     if (!empty($e)) {
-        $output->Text('<div style="padding:5px; border:1px solid red; background-color: pink;">');
-        $output->Text('<center><b>' . text($e) . '</b></center>');
-        $output->Text('</div><br />');
+        $output -> Text('<div class="alert alert-danger ml-5 mr-5" role="alert">');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `ml-1 mr-1`. Padding isn't measured in pixels in Bootstrap. [Please read the documentation on how to do this correctly](https://getbootstrap.com/docs/4.4/utilities/spacing/).

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 3]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
+        $output->Text('<b>'. text($e) .'</b>');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `<span class="text-center font-weight-bold">` instead of using the outdated `<b>` tag. You also forgot to address the `<center>` tag that was previously here.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 4]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
+        $output -> Text('</div><br />');
     }
 
     if (!empty($msg)) {
-        $output->Text('<div style="padding:5px; border:1px solid green; background-color: lightgreen;">');
-        $output->Text('<center><b>' . text($msg) . '</b></center>');
-        $output->Text('</div><br />');
+        $output -> Text('<div class="alert alert-success ml-5 mr-5" role="alert">');
+        $output->Text('<b>' . text($msg) . '</b>');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `<span class="text-center font-weight-bold">` instead of using the outdated `<b>` tag. You also forgot to address the `<center>` tag that was previously here.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 5]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
+        $output -> Text('<div class="alert alert-danger ml-5 mr-5" role="alert">');
+        $output->Text('<b>'. text($e) .'</b>');
+        $output -> Text('</div><br />');
     }
 
     if (!empty($msg)) {
-        $output->Text('<div style="padding:5px; border:1px solid green; background-color: lightgreen;">');
-        $output->Text('<center><b>' . text($msg) . '</b></center>');
-        $output->Text('</div><br />');
+        $output -> Text('<div class="alert alert-success ml-5 mr-5" role="alert">');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `ml-1 mr-1`. Padding isn't measured in pixels in Bootstrap. [Please read the documentation on how to do this correctly](https://getbootstrap.com/docs/4.4/utilities/spacing/).

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 6]
```diff
@@ -813,26 +843,24 @@ function postcalendar_admin_testSystem()
...
+	<body>
 EOF;
-    $header .= '"' . attr($GLOBALS['style']['BGCOLOR2']) . '">';
     $output .= $header;
-    $output  = postcalendar_adminmenu();
-    $output .= '<table border="1" cellpadding="3" cellspacing="1">';
-    $output .= '  <tr><th align="left">' . xlt('Name') . '</th><th align="left">' . xlt('Value') . '</th>';
-    $output .= '</tr>';
+    $output  = postcalendar_adminmenu("testSystem");
+    $output .= '<div class="container"><table class="table table-bordered table-striped"><thead>';
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This table should have `<div class="table-responsive">` wrapped around it. [See here for further documentation](https://getbootstrap.com/docs/4.4/content/tables/#responsive-tables).

**Comment by stu01509** [comment]
Hi @tywrenn,

I've been modify and change CSS style, Please review it again.
Thanks.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 7]
```diff
@@ -47,9 +47,9 @@ function postcalendar_admin_modifyconfig($msg = '', $showMenu = true)
 
     if (!empty($msg)) {
         $output->Text(postcalendar_adminmenu("clearCache"));
-        $output -> Text('<div class="alert alert-success ml-5 mr-5" role="alert">');
+        $output -> Text('<center><div class="alert alert-success ml-1 mr-1" role="alert">');
```
Comment (tywrenn) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: This should be `text-center` unless it didn't work

**Comment by stu01509** [comment]
Modify Done.

**Comment by bradymiller** [comment]
hi @stu01509 , Code looks great. I fixed the conflict (since I ended up causing it with my prior subsequent commit to yours :) ) and will bring this in after it passes travis. thanks for the improvement! -brady

**Comment by bradymiller** [comment]
@sjpadgett , 'squash and merge' is now working again, which was used to bring this PR in. I am betting it was just a temporary bug with github.
