### PR TITLE
fix: inadequate date time format in log viewer

### LINKED ISSUE #7335: bug: Inadequate time format in logs
### Describe the bug
ASVS 7.1.4 (Verify that each log event includes necessary information that would allow for a detailed investigation of the timeline when an event happens)
The OpenEMR logs events into the system which are sorted in order by date and time. The time is displayed in the format Hours:Minutes which is insufficient for tracking the timeline in which events happen. It should be changed to Hours:Minutes:Seconds

### To Reproduce
1. Login to OpenEMR using correct credentials
2. Navigate to Admin --> System --> Logs
3. Click on Submit button

image

### Expected behavior
The Logs are displayed in the format Hours:Minutes

### Client configuration

- Browser: Arc Version 1.37.0 (48361) Chromium Engine Version 123.0.6312.106
- OpenEMR version: v7.0.2
- Operating system: MacOS

### PR DESCRIPTION
**Pull request by manoj-ayyappan**
Fixes #7335

#### Short description of what this resolves:
The OpenEMR logs uses the time format as Hours:Minutes which is inadequate to determine the timeline of events. This fix changes the time format to Hours:Minutes:Seconds

image

#### Changes proposed in this pull request:
Add the parameter for seconds as true in two echo statements

### CODE REVIEW

File: interface/logview/logview.php [hunk 1]
```diff
@@ -380,7 +380,7 @@ function setpatient(pid, lname, fname, dob) {
                                                 }
                                                 ?>
                                                 <tr>
-                                                    <td><?php echo text(oeFormatDateTime($iter["date"])); ?></td>
+                                                    <td><?php echo text(oeFormatDateTime($iter["date"], 0, true)); ?></td>
```
Comment (bradymiller) [inline interface/logview/logview.php:383]: hi, should use the default 'global' value for second parameter

File: interface/logview/logview.php [hunk 2]
```diff
@@ -412,7 +412,7 @@ function setpatient(pid, lname, fname, dob) {
                                                     $comments = xl('Recipient Name') . ":" . $iter["recipient"] . ";" . xl('Disclosure Info') . ":" . $iter["description"];
                                                     ?>
                                                     <tr>
-                                                        <td><?php echo text(oeFormatDateTime($iter["date"])); ?></td>
+                                                        <td><?php echo text(oeFormatDateTime($iter["date"], 0, true)); ?></td>
```
Comment (bradymiller) [inline interface/logview/logview.php:415]: hi, should use the default 'global' value for second parameter

File: interface/logview/logview.php (hunk 1 above)
Comment (bradymiller) [reply interface/logview/logview.php:383]:
```
 <td><?php echo text(oeFormatDateTime($iter["date"], 'global', true)); ?></td>
```

File: interface/logview/logview.php (hunk 2 above)
Comment (bradymiller) [reply interface/logview/logview.php:415]:
```
<td><?php echo text(oeFormatDateTime($iter["date"], 'global', true)); ?></td>
```

**Comment by stephenwaite** [comment]
hi @manoj-ayyappan , then you can edit the title of the PR to be `fix: inadequate date time format in log viewer`

**Review by bradymiller — APPROVED** [review]
