### PR TITLE
Fixes #5480 treatment plan extension date.

### LINKED ISSUE #5480: CCDA Referral Section Treatment Plan Missing Extension Date
Referral Document types for CCDA require the Plan of Care/Treatment Plan section to have an extension of "2014-06-09".  Otherwise the section fails to be found by the ONC b1 referral document type validation.

http://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.10.html

The error that occurs is the following:
image

With the following xml for the assessment and treatment plan section:
image

### PR DESCRIPTION
**Pull request by adunsulag**
Referral document type was failing because we were missing the treatment
plan extension date.

Fixes #5480

### CODE REVIEW

File: ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js [hunk 1]
```diff
@@ -365,6 +365,9 @@ exports.planOfCareSection = function (htmlHeader, na) {
             key: "section",
             attributes: condition.isNullFlavorSection('plan_of_care'),
             content: [
+                // @see http://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.2.10.html
+                // They keep renaming this section, but ccda calls this Plan of Treatment Section (V2)
+                fieldLevel.templateIdExt("2.16.840.1.113883.10.20.22.2.10", "2014-06-09"),
```
Comment (sjpadgett) [inline ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js:370]: Thought I got all the rel2.1 headers. We use assessment and a plan of care and not the combined.

**Review by sjpadgett — APPROVED** [review]
want me to bring in or is there more?

**Comment by adunsulag** [comment]
@sjpadgett I don't have anything more just yet, this gets us passing on both the referral and ccd for scenario 1.  Next is scenario 2 & 3.
