### PR TITLE
Wrap Globals save in a transaction.

### LINKED ISSUE #4804: Occasional Globals corruption on save.
### Describe the bug
@adunsulag first saw this a month or so ago when I then encountered a couple days later.
I believe has something to do with session timeout/corruption.
The result appears that data is deleted but never written and seems to happen somewhere in the globals save. 
The symptom after is user can't log in causing user to embark on a mission to overwrite secure password. A frustrating adventure no doubt!
The only solution to issue is import globals from backup or anew from default database.

My solution will be to a least prevent the corruption to table by wrapping global save in a transaction to revert.
This of course relies on an exception, redirect or fatal error that breaks out of the save routine.

### PR DESCRIPTION
**Pull request by sjpadgett**
See issue

Fixes #4804

### CODE REVIEW

File: interface/super/edit_globals.php [hunk 1]
```diff
@@ -267,6 +269,9 @@ function checkBackgroundServices()
             ++$i;
         }
     }
+    // end of transaction
+    sqlStatementNoLog('COMMIT');
+    sqlStatementNoLog('SET autocommit=1');
```
Comment (bradymiller) [inline interface/super/edit_globals.php:274]: nice!

2DV

**Comment by sjpadgett** [comment]
Bringing in. My xmas gift to community!:)

Seriously, @adunsulag recommended awhile back and I concur, we need to go through core and add transactions where appropriate. Namely some of our more DB intensive queries and those with inserts and updates etc.. Will speed up the query by more than a 100%....
