### PR TITLE
fix(security): parameterize SQL and filter request inputs in add_edit_event

### LINKED ISSUE #11184: refactor: add_edit_event.php — parameterize SQL at line 722 and filter $_REQUEST at line 1067
Two pre-existing issues noticed during #11077 review:

### 1. SQL string concatenation at line 722

```php
"WHERE pc_eid = '" . add_escape_custom($eid) . "'"
```

All other 12+ SQL statements in this file use parameterized queries (`WHERE pc_eid = ?` with `[$eid]`). This one should be converted for consistency and defense-in-depth.

### 2. Unfiltered `$_REQUEST` at line 1067

```php
$eid = $_REQUEST["eid"] ?? null;
```

This overwrites the `filter_input(INPUT_GET, 'eid', FILTER_VALIDATE_INT)` value set at line 69. Should use `filter_input` here as well.

Per @kojiromike's request in #11077.

### PR DESCRIPTION
**Pull request by haoyu-haoyu**
## Summary

Follow-up from #11077 review, per @kojiromike's request.

### 1. Parameterize SQL UPDATE (line 701)

The only non-parameterized SQL statement in `add_edit_event.php` — all other 12+ queries already use `?` placeholders.

```diff
-sqlStatement("UPDATE openemr_postcalendar_events SET " .
-"pc_catid = '" . add_escape_custom($_POST['form_category']) . "', " .
-...
-"WHERE pc_eid = '" . add_escape_custom($eid) . "'");

+sqlStatement(
+    "UPDATE openemr_postcalendar_events SET " .
+    "pc_catid = ?, pc_aid = ?, pc_pid = ?, ..." .
+    "WHERE pc_eid = ?",
+    [$_POST['form_category'], $prov, ..., $eid]
+);
```

### 2. Replace `$_REQUEST` with `$_GET` + `filter_input` (line 1091)

The tab navigation variables used `$_REQUEST` which includes POST data unnecessarily. Changed to `$_GET` for string params and `filter_input(INPUT_GET, ..., FILTER_VALIDATE_INT)` for `$eid` and `$uid`, matching the pattern from line 69.

## Test plan

- [ ] Create/edit calendar events in all modes (single, recurring, provider, group)
- [ ] Verify tab navigation (Patient/Provider/Group) preserves URL parameters
- [ ] Confirm no SQL errors in PHP error log

Fixes #11184

### CODE REVIEW

File: interface/main/calendar/add_edit_event.php [hunk 1]
```diff
@@ -698,28 +698,52 @@ function setEventDate($start_date, $recurrence)
...
-                "pc_recurrspec = '" . add_escape_custom(serialize($recurrspec)) . "', " .
-                "pc_startTime = '" . add_escape_custom($starttime) . "', " .
-                "pc_endTime = '" . add_escape_custom($endtime) . "', " .
-                "pc_alldayevent = '" . add_escape_custom($_POST['form_allday']) . "', " .
-                "pc_apptstatus = '" . add_escape_custom($_POST['form_apptstatus']) . "', "  .
-                "pc_prefcatid = '" . add_escape_custom($_POST['form_prefcat']) . "' ,"  .
-                "pc_facility = '" . add_escape_custom((int)$_POST['facility']) . "' ,"  . // FF stuff
-                "pc_billing_location = '" . add_escape_custom((int)$_POST['billing_facility']) . "' "  .
-                "WHERE pc_eid = '" . add_escape_custom($eid) . "'");
+                sqlStatement(
```
Comment (kojiromike) [inline interface/main/calendar/add_edit_event.php]: Instead of sqlStatement, can you switch this to QueryUtils?

**Comment by haoyu-haoyu** [comment]
Done — switched to `QueryUtils::sqlStatementThrowException()` and added the `use` import.

**Comment by kojiromike** [comment]
Nice cleanup on the `$_REQUEST` → `$_GET` switch — all of these params arrive via query string only, so this is safe and tightens the input surface.

A few suggestions to take it further:

### Validate the remaining numeric params as integers

`$startm` (AM/PM flag: 1 or 2), `$starth` (hour), `$starttm` (minute), and `$cid` (category ID) are always integers from the callers. Same `filter_input(INPUT_GET, ..., FILTER_VALIDATE_INT) ?: 0` pattern you already use for `$eid` and `$uid`. And `$dt` can use `filter_input` without a validation filter to get a clean `string` type instead of `mixed`:

```php
$eid     = filter_input(INPUT_GET, 'eid', FILTER_VALIDATE_INT) ?: 0;
$startm  = filter_input(INPUT_GET, 'startampm', FILTER_VALIDATE_INT) ?: 0;
$starth  = filter_input(INPUT_GET, 'starttimeh', FILTER_VALIDATE_INT) ?: 0;
$uid     = filter_input(INPUT_GET, 'userid', FILTER_VALIDATE_INT) ?: 0;
$starttm = filter_input(INPUT_GET, 'starttimem', FILTER_VALIDATE_INT) ?: 0;
$dt      = filter_input(INPUT_GET, 'date') ?: '';
$cid     = filter_input(INPUT_GET, 'catid', FILTER_VALIDATE_INT) ?: 0;
```

### Merge the two PHP blocks and build the query string once

The assignments currently in the second `<?php ?>` block (line 1092 in the PR) can move into the first block (line 1079) that sets up the tab active classes. That eliminates an unnecessary PHP open/close, and lets you build the tab query string once with `http_build_query` instead of repeating it three times:

```php
<?php
    $provider_class = '';
    $group_class = '';
    $normal = '';
    if (!empty($_GET['prov']) && ($_GET['prov'] == true)) {
        $provider_class = " active ";
    } elseif ($_GET['group'] == true) {
        $group_class = " active";
    } else {
        $normal = " active";
    }

    $eid     = filter_input(INPUT_GET, 'eid', FILTER_VALIDATE_INT) ?: 0;
    $startm  = filter_input(INPUT_GET, 'startampm', FILTER_VALIDATE_INT) ?: 0;
    $starth  = filter_input(INPUT_GET, 'starttimeh', FILTER_VALIDATE_INT) ?: 0;
    $uid     = filter_input(INPUT_GET, 'userid', FILTER_VALIDATE_INT) ?: 0;
    $starttm = filter_input(INPUT_GET, 'starttimem', FILTER_VALIDATE_INT) ?: 0;
    $dt      = filter_input(INPUT_GET, 'date') ?: '';
    $cid     = filter_input(INPUT_GET, 'catid', FILTER_VALIDATE_INT) ?: 0;

    $tabParams = array_filter([
        'startampm'  => $startm,
        'starttimeh' => $starth,
        'userid'     => $uid,
        'starttimem' => $starttm,
        'date'       => $dt,
        'catid'      => $cid,
    ]);
    $baseQuery = http_build_query($tabParams);
?>
```

Then the three tab links simplify to:

```php
<a class="nav-link<?php echo $normal; ?>"
   href="add_edit_event.php?<?php echo attr($baseQuery); ?>"><?php echo xlt('Patient'); ?></a>

<a class="nav-link<?php echo $provider_class; ?>"
   href="add_edit_event.php?prov=true&<?php echo attr($baseQuery); ?>"><?php echo xlt('Provider'); ?></a>

<a class="nav-link<?php echo $group_class; ?>"
   href="add_edit_event.php?group=true&<?php echo attr($baseQuery); ?>"><?php echo xlt('Group'); ?></a>
```

`http_build_query` handles URL encoding, `attr()` handles HTML attribute escaping, and `array_filter` drops zero/empty values so you don't get `&catid=0` in the URL. The validated integers don't need individual `attr()` calls (which expect `string` and would cause PHPStan errors with `int`).

**Comment by haoyu-haoyu** [comment]
Done — both suggestions adopted:

1. **All numeric params validated as int**: `$startm`, `$starth`, `$starttm`, `$cid` now use `filter_input(INPUT_GET, ..., FILTER_VALIDATE_INT) ?: 0`. `$dt` uses `filter_input(INPUT_GET, 'date') ?: ''` for clean string typing.

2. **Merged PHP blocks + `http_build_query`**: Single PHP block builds `$tabParams` with `array_filter` (drops zero/empty), then `$baseQuery = http_build_query($tabParams)`. Three tab links simplified to one `attr($baseQuery)` each.

**Comment by kojiromike** [comment]
Please run `composer install && composer phpcbf && composer phpstan-baseline` and commit the results.

**Comment by haoyu-haoyu** [comment]
I don't have a local PHP/Composer environment set up — would you be able to run those commands and push, or should I set up the Docker dev environment from `docker/development-easy/` to run them?  I will try re-run it on my server

**Comment by kojiromike** [comment]
I'll take care of it. Thanks for your help.

**Comment by haoyu-haoyu** [comment]
Actually, I went ahead and set up PHP 8.5 + Composer locally and ran all three commands:

```
composer install
composer phpcbf -- interface/main/calendar/add_edit_event.php
composer phpstan-baseline
```

- `phpcbf` fixed 1 code style issue in `add_edit_event.php`
- `phpstan-baseline` regenerated the baseline (updated `.phpstan/baseline/argument.type.php`)

Results committed and pushed in 88e569d.

File: interface/main/calendar/add_edit_event.php [hunk 2]
```diff
@@ -698,28 +699,52 @@ function setEventDate($start_date, $recurrence)
...
+                    "pc_recurrtype = ?, " .
+                    "pc_recurrspec = ?, " .
+                    "pc_startTime = ?, " .
+                    "pc_endTime = ?, " .
+                    "pc_alldayevent = ?, " .
+                    "pc_apptstatus = ?, " .
+                    "pc_prefcatid = ?, " .
+                    "pc_facility = ?, " .
+                    "pc_billing_location = ? " .
+                    "WHERE pc_eid = ?",
```
Comment (kojiromike) [inline interface/main/calendar/add_edit_event.php]: sorry I didn't see this before, but this could all be a single string now.

Comment (haoyu-haoyu) [reply interface/main/calendar/add_edit_event.php]: Good catch — consolidated into a single multi-line string in c88aba4.

**Comment by haoyu-haoyu** [comment]
While running `phpcbf` and `phpstan-baseline`, I noticed there was a second `add_escape_custom()` UPDATE block (the multi-provider path at line 607) that I'd missed — identical pattern to the single-provider one I already converted. Fixed in 494761c:

- **Parameterized the multi-provider UPDATE** — converted 20 `add_escape_custom()` string concatenations to bind parameters
- **Migrated 9 more `sqlStatement()` → `QueryUtils::sqlStatementThrowException()`** in the save/update code path (UPDATE facility, UPDATE recurrspec, UPDATE enddate, DELETE events, UPDATE patient DOB)
- PHPStan baseline updated: deprecated `sqlStatement()` count for this file dropped from 23 → 14
