### PR TITLE
Recent patients fixes

### LINKED ISSUE #7035: Recent Patient tab in finder not displaying patient date of birth.
### Describe the bug
OpenEMR version 7.0.2 running from the production docker does not show patient date of birth for any of the patients in the "Recent Patients" tab / list.

write concise description of what the bug is.
7.0.2 added a "Recent Patient" tab to the finder.  Looking through previous issues, this is to keep the last 10 (or 20?) patients for the user in a list that persists through logout/login cycles.

### To Reproduce

0)  Browser does not matter -- same behavior with either Firefox, Chrome, Vivaldi, .
1)  Search for a patient & go into their dashboard.
2)  Click the (x) button to close the patient.
3)  Go into patient finder -> Recent Patients
4)  See the recent patient's last name, first name, but not their date of birth.

Viewing the Admin->Forms->Lists->Recent Patient Columns it appears there is a typo for the ID.  The default has "dob".  The column in patient_data table is "DOB" (note lower -vs- upper case).

I Tried changing the ID from "dob" to "DOB" and re-loading the patient finder -> Recent Patients.

Now, for each patient THE CURRENT DATE AND TIME are displayed (not the patient's date of birth).  I have tried to locate the code that produces this error -- I cannot find it...Please help.
### Expected behavior
Patient's date of birth should be displayed in that column...

### Client configuration

- Browser:  doesn't matter
- OpenEMR version: openEMR 7.0.2
- Operating system:  Production Docker version 7.0.2

### PR DESCRIPTION
**Pull request by DrBassman**
Fixes #7035

#### Short description of what this resolves:
I had previously reported that the new "Recent Patients" tab in the Patient Finder is not updated if the Admin->Forms->Lists->Recent Pateint Columns is changed.  I opened this issue, and @stephenwaite submitted a fix before I prepared mine.  This is my fix for this issue.  I'd like feedback on it, etc.  Thank you.

### CODE REVIEW

**Comment by stephenwaite** [comment]
nice @DrBassman ! will check it out

**Comment by DrBassman** [comment]
I'm concerned that this code likely introduces a SQL injection opportunity?  This example uses the concat() function to have lname, fname mname as a column in the Recent Patients finder.  Does my code need to be modified to prevent this?  See pics:

edit_list

finder

**Comment by stephenwaite** [comment]
hi @DrBassman , don't think it's an issue since the list column ids are embedded in a `SELECT` statement.

File: interface/main/finder/dynamic_finder.php [hunk 1]
```diff
@@ -398,7 +398,62 @@ function rp()
...
+    $datetime_cols = [];
+    foreach ($pd_dtCols as $k => $v) {
+        if ($v['data_type'] == "datetime") {
+            $datetime_cols[] = $v['column_name'];
+        } else if ($v['data_type'] == "date") {
+            $date_cols[] = $v['column_name'];
+        }
+    }
+    // Build SQL statement to pull desired columns from patient_data table...
+    $pd_sql = "SELECT id as pid";
```
Comment (stephenwaite) [inline interface/main/finder/dynamic_finder.php:418]: can't consider `id` and `pid` to be interchangeable

File: templates/patient_finder/finder.html.twig [hunk 2]
```diff
@@ -44,11 +44,15 @@
                                 </thead>
                                 <tbody>
                                     {% for p in rp %}
-                                        <tr>
```
Comment (stephenwaite) [inline templates/patient_finder/finder.html.twig:47]: above here can you add a translate to the title text as [pointed out by Luis](https://community.open-emr.org/t/recent-patients-tab-has-empty-date-of-birth-column/21535/4?u=stephenwaite)?
```
                                            <th scope="col">{{ h.title|xlt }}</th>

File: interface/main/finder/dynamic_finder.php (hunk 1 above)
Comment (DrBassman) [reply interface/main/finder/dynamic_finder.php:418]: Ah,  there isn't a PRIMARY KEY on patient_data.  Would it be better to use id or pid as the way of identifying the patients we want to have in the recent patient list?

Comment (stephenwaite) [reply interface/main/finder/dynamic_finder.php:418]: `pid`

File: templates/patient_finder/finder.html.twig (hunk 2 above)
Comment (DrBassman) [reply templates/patient_finder/finder.html.twig:47]: I have made this change.

File: interface/main/finder/dynamic_finder.php (hunk 1 above)
Comment (DrBassman) [reply interface/main/finder/dynamic_finder.php]: I've updated my code to use pid.

File: templates/patient_finder/finder.html.twig (hunk 2 above)
Comment (DrBassman) [reply templates/patient_finder/finder.html.twig:47]: It looks like "Recent Patients" (on the tab) is not being translated.  I looked at the code, and I think it is correct...(this is with my install set for standard French).  Is this something that needs to be fixed with this PR?

xlate

Comment (stephenwaite) [reply templates/patient_finder/finder.html.twig:47]: hi @DrBassman, no need to fix, it's just missing the constant in the translation engine. You can see it work by adding the constant and then load a new definition under Admin->System->Language

**Review by stephenwaite — APPROVED** [review]
southpark_cheering

File: templates/patient_finder/finder.html.twig [hunk 3]
```diff
@@ -38,17 +38,21 @@
                                 <thead class="thead-light">
                                     <tr>
                                         {% for h in headers %}
-                                            <th scope="col">{{ h.title|text }}</th>
+                                            <th scope="col">{{ h.title|xlt }}</th>
```
Comment (bradymiller) [inline templates/patient_finder/finder.html.twig:41]: Rather than `xlt`, use `xlListLabel` above. This is because some users will put their translations directly in list_options title and in that case they will turn off translations of lists (a setting in globals).

Otherwise, code looks great!

Comment (DrBassman) [reply templates/patient_finder/finder.html.twig]: Thank you.  I have pushed this change.  RKL

**Comment by bradymiller** [comment]
2DV
