### PR TITLE
fix: Update patient_tracker.php

### LINKED ISSUE #6596: bug: flow board stuck on appointment with status CALL
### Describe the bug

flow board stuck on appointment with status CALL

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by ophthal**
fixes php8 error not showing up in the logs - related to the implode function blocking FlowBoard from proceeding when a patient replies "CALL" indicating they need a callback regarding an appointment reminder they received.

It also removes the ability to add a note about the Callback request.  Instead it is replaced with an icon to directly open the SMS Bot so staff/front desk can directly reply to the patient via SMS, if SMS is allowed and they have a mobile/cell phone listed in demographics.  If not, just the CALL icon is displayed.

Fixes #6596

### CODE REVIEW

**Comment by stephenwaite** [comment]
hi @ophthal , I created an issue for this in case we create a changelog, thanks for the pr

**Comment by ophthal** [comment]
Thanks Steven. I noticed a couple of spaces came up in the php error check but otherwise it is testing well.On Jun 21, 2023, at 12:04 PM, stephen waite ***@***.***> wrote:﻿
hi @ophthal , I created an issue for this in case we create a changelog, thanks for the pr

File: interface/patient_tracker/patient_tracker.php [hunk 1]
```diff
@@ -550,29 +535,18 @@
...
-                                        <textarea name='txtCALLback' id='txtCALLback' rows=6 cols=20></textarea>
-                                        <input type='submit' name='saveCALLback' id='saveCALLback' value='" . xla("Save") . "'>
-                                      </form>
-                                    </span>
-                                      ";
+                                if ($row['msg_reply'] == "CALL") {
+                                    $icon_here[$row['msg_type']] = $icons[$row['msg_type']]['CALL']['html'];
+                                    if (($appointment['allow_sms'] != "NO") && ($appointment['phone_cell'] > '')) {
+                                        $icon_4_CALL = "<span class='input-group-addon'
+                                                              onclick='SMS_bot(" . $row['msg_pid'] . ");'>
```
Comment (stephenwaite) [inline interface/patient_tracker/patient_tracker.php:542]: think this needs to be 
```
                                                              onclick='SMS_bot(" . attr_js($row['msg_pid']) . ");'>

**Review by bradymiller — APPROVED** [review]
