### PR TITLE
Openemr fix #5496 vital form bugs

### LINKED ISSUE #5496: several vital form bugs
hi @adunsulag , was testing this and noted several bugs

1. After adding vitals with all entries filled out, the encounter screen does not show it with following php error in log:
```
PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php:106\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php(106): round()\n#1 /var/www/localhost/htdocs/openemr/interface/patient_file/encounter/forms.php(987): vitals_report()\n#2 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/forms/vitals/report.php on line 106, referer: http://localhost:8300/interface/patient_file/encounter/forms.php
```

2. And then if try to edit that form, it breaks here (pasted log under the screenshot):
image
```
[Thu Jun 16 08:08:37.969430 2022] [php:error] [pid 1057] [client 172.27.0.1:39880] PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php:32\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php(32): round()\n#1 /var/www/localhost/htdocs/openemr/src/Common/Forms/FormVitals.php(250): OpenEMR\\Common\\Utils\\MeasurementUtils::inchesToCm()\n#2 /var/www/localhost/htdocs/openemr/sites/default/documents/smarty/main/%%F0^F06^F068F682%%vitals_textbox_conversion.tpl.php(116): OpenEMR\\Common\\Forms\\FormVitals->get_height_metric()\n#3 /var/www/localhost/htdocs/openemr/vendor/smarty/smarty/libs/Smarty.class.php(1875): include('...')\n#4 /var/www/localhost/htdocs/openemr/sites/default/documents/smarty/main/%%E5^E50^E50519AD%%general_new.html.php(113): Smarty->_smarty_include()\n#5 /var/www/localhost/htdocs/openemr/vendor/smarty/smarty/libs/Smarty.class.php(1269): include('...')\n#6 /var/www/localhost/htdocs/openemr/interface/forms/vitals/C_FormVitals.class.php(128): Smarty->fetch()\n#7 /var/www/localhost/htdocs/openemr/interface/forms/vitals/view.php(19): C_FormVitals->default_action()\n#8 /var/www/localhost/htdocs/openemr/interface/patient_file/encounter/view_form.php(26): include_once('...')\n#9 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Common/Utils/MeasurementUtils.php on line 32, referer: http://localhost:8300/interface/patient_file/encounter/encounter_top.php
```

3. Looks like vitals are being saved in metric form rather than imperial form:
image
image
image
(above form save is the last row of the screenshot)

4. javascript error when type in weight in lb (and the kg is not populated):
image

### LINKED ISSUE #5500: Add ability for a text input form elements to skip double click popup template editor
Currently we bind to all text input and textarea values in OpenEMR to allow the template editor to popup and to be able to add linked issues to the input.  However, some areas we don't WANT to have the double click option to popup the editor.  We need to be able to opt-out of the editor by adding a class prefix to the input to skip popping up the dialog.

### PR DESCRIPTION
**Pull request by adunsulag**
Fixes #5496 
Fixes #5500 

kg to lb was throwing an error as we tried calling a Number method on a
string.

Vitals were saving in metric if you had metric set as the main unit and
entered in data that way.

Setting a vitals value to be empty was not emptying out the
corresponding conversion field and the saved input.

I haven't been able to reproduce this typecast error on my version of php but on
some versions of php this was throwing a type conversion error.  We
parse as floats the values before we put them through number_format to
fix the type conversion problem.

Made it so double clicking the vitals form doesn't popup the dialog
template editor.

### CODE REVIEW

**Comment by adunsulag** [comment]
@stephenwaite or @bradymiller if someone wants to test out this PR and give me a 2nd opinion that this is solving the problems. I believe I've tested all the locale scenario options to tease out any other problems, but I'd feel better having someone do a 2nd pass through this haha.

**Comment by stephenwaite** [comment]
sure, I left a cpl comments over @ https://github.com/openemr/openemr/pull/5494/files, looks like you fixed one of them here.

**Comment by adunsulag** [comment]
@stephenwaite Thanks for reviewing the code.  I believe I fixed all the issues you identified as well with my last commit.

**Review by stephenwaite — APPROVED** [review]
super job!

File: library/js/CustomTemplateApi.js [hunk 1]
```diff
@@ -28,7 +28,7 @@ function doTemplateEditor(_this, event, oContext = '') {
 }
 
 const bindTextArea = function () {
-    const teventElement = document.querySelectorAll("textarea, input[type='text']");
+    const teventElement = document.querySelectorAll("textarea, input[type='text']:not(.skip-template-editor)");
```
Comment (sjpadgett) [inline library/js/CustomTemplateApi.js:31]: Just remove the input[type='text']

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
testing well!

2DV-2
