### PR TITLE
fix: check for empty array before looking for offsite document

### LINKED ISSUE #7390: bug: document display fail on empty array key
### Describe the bug

write concise description of what the bug is.

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7390 #7401

### CODE REVIEW

File: src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php [hunk 1]
```diff
@@ -18,19 +18,24 @@ class PatientRetrieveOffsiteDocument extends Event
...
-    private $offsiteurl;
-    public function __construct($url)
+    private $offsiteUrl;
+    public function __construct(string $url)
     {
         $this->url = $url;
     }
 
-    public function setOffsiteUrl(string $offsitedUrl): void
+    public function getOpenEMRDocumentUrl(): string
```
Comment (adunsulag) [inline src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php:27]: @juggernautsei Please look over this file.  I exposed the $url property via getOpenEMRDocumentUrl() and fixed the setter in the setOffsiteUrl.

I'm not sure how this was working for you before, but it should be working now.

**Comment by adunsulag** [comment]
@sjpadgett This needs to come in alongside your PR since yours has the offsite document stuff that is broken.

File: controllers/C_Document.class.php [hunk 2]
```diff
@@ -801,14 +796,19 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
...
             $url = $temp_url;
         }
-        //fire a remote call to see if the file is stored somewhere else
-        $s3Key = explode("//", $temp_url); //split the url to get the s3 key
-        $retrieveOffsiteDocument = new PatientRetrieveOffsiteDocument("/" . $s3Key[1]);
-        $this->eventDispatcher->dispatch($retrieveOffsiteDocument, PatientRetrieveOffsiteDocument::REMOTE_DOCUMENT_LOCATION);
-        //this is for the s3 bucket module. If the file is not found locally, it will be found remotely
-        if ($retrieveOffsiteDocument->getOffsiteUrl() != null) {
+
+        $retrieveOffsiteDocument = new PatientRetrieveOffsiteDocument($temp_url);
```
[the remark this answers is not in the document]
Comment (juggernautsei) [reply controllers/C_Document.class.php:800]: I understand

File: src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php (hunk 1 above)
Comment (juggernautsei) [reply src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php:27]: @adunsulag I see the temp_url being passed in whole. The getOpenEMRDocumentUrl() may not be needed for me. But it could be useful for the future of someone else's module. My module catches the $this->url already. Then I will move the logic into there to get the file name.  

Now my logic in the module looks like this.

    public function retrieveFromS3(PatientRetrieveOffsiteDocument $event): void
    {
        $url = $event->url;
        $s3Key = explode("//", $url); //split the url to get the s3 key
        $s3model = new S3Model();
        $credentials = new Credentials($s3model);
        $s3Client = $credentials->authenticateCredentials();
        $getBucket = $s3model->getAllCredentials();
        $cmd = $s3Client->getCommand('GetObject', [
            'Bucket' => $getBucket['s3_bucket'],
            'Key' => $s3Key[1]
        ]);
        $request = $s3Client->createPresignedRequest($cmd, '+5 minutes');
        $presignedUrl = (string) $request->getUri();
        $event->setOffsiteUrl($presignedUrl);
    }

File: controllers/C_Document.class.php [hunk 3]
```diff
@@ -801,18 +796,20 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
...
+        $updatedOffsiteDocumentEvent = $GLOBALS['kernel']->getEventDispatcher()->dispatch(
+            $retrieveOffsiteDocument,
+            PatientRetrieveOffsiteDocument::REMOTE_DOCUMENT_LOCATION
+        );
+        // if a module writer has an independent offsite storage mechanism used this accomdoates that.
+        // If the file is not found locally, it will be found remotely.  Systems like s3, blob stores, etc, can
+        // be tied and and use those urls.  Note NO security is handled here so any kind of security mechanism must
+        // be handled on the receiving end's URL (s3/azure for example use signed urls with signature verification)
+        if (!empty($updatedOffsiteDocumentEvent) && $updatedOffsiteDocumentEvent->getOffsiteUrl() != null) {
```
Comment (juggernautsei) [inline controllers/C_Document.class.php:809]: @adunsulag can you clarify what this part is doing?

        if (!empty($updatedOffsiteDocumentEvent)

File: controllers/C_Document.class.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (juggernautsei) [reply controllers/C_Document.class.php:800]: I have tested on my end all the changes and all is well. 
@adunsulag thank you all for my education. If any of you would like a copy of the module let me know.

**Comment by sjpadgett** [comment]
So I didn't have this and missed the notification so oh well.
Is this ready?

File: controllers/C_Document.class.php [hunk 4]
```diff
@@ -801,18 +796,20 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
         if (file_exists($temp_url)) {
             $url = $temp_url;
         }
-        //fire a remote call to see if the file is stored somewhere else
-        $s3Key = explode("//", $temp_url); //split the url to get the s3 key
-        // if the s3 key isn't empty then ...
-        if (!empty($s3Key[1])) {
```
Comment (juggernautsei) [inline controllers/C_Document.class.php]: if (!empty($s3Key[1])) {

This would prevent the event from being fired if the file name is empty. Now, I moved that logic into the module. It sends and empty return if there is no file name connected to the URL. i.e.  " C:/xampp/htdocs/openemr/sites/default/documents// " occurs. 

    if (!file_exists($url)) {

This logic should keep the system from falling through. It should exit because the file won't exist on the local drive.

File: controllers/C_Document.class.php (hunk 3 above)
Comment (adunsulag) [reply controllers/C_Document.class.php:809]: The first clause protects OpenEMR if someone in their module decides to return null for their event in the dispatched event handler. I think Symfony may catch this and just return the passed in argument but I get a little paranoid at times when interfacing with third party software.  I probably should have done a type check using instanceof instead of !empty which I can go ahead and do that.

File: src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php (hunk 1 above)
Comment (adunsulag) [reply src/Events/PatientDocuments/PatientRetrieveOffsiteDocument.php:27]: The PatientRetrieveOffsiteDocument->url property is marked private so I'm not sure how you've been able to access it in your module.  That's why I exposed the getOpenEMRDocumentUrl() method.

File: controllers/C_Document.class.php [hunk 5]
```diff
@@ -801,14 +796,19 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
         if (file_exists($temp_url)) {
             $url = $temp_url;
         }
```
[the remark this answers is not in the document]
Comment (adunsulag) [reply controllers/C_Document.class.php]: @juggernautsei and @sjpadgett I changed this up to take care of the check on the $from_filename.

File: controllers/C_Document.class.php [hunk 6]
```diff
@@ -774,42 +769,53 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
...
+            $updatedOffsiteDocumentEvent = $GLOBALS['kernel']->getEventDispatcher()->dispatch(
+                $retrieveOffsiteDocument,
+                PatientRetrieveOffsiteDocument::REMOTE_DOCUMENT_LOCATION
+            );
+            // if a module writer has an independent offsite storage mechanism used this accomdoates that.
+            // If the file is not found locally, it will be found remotely.  Systems like s3, blob stores, etc, can
+            // be tied and and use those urls.  Note NO security is handled here so any kind of security mechanism must
+            // be handled on the receiving end's URL (s3/azure for example use signed urls with signature verification)
+            if (
+                $updatedOffsiteDocumentEvent instanceof PatientRetrieveOffsiteDocument
```
Comment (adunsulag) [inline controllers/C_Document.class.php:812]: @juggernautsei I changed this up to be instanceof to protect the event better and make sure it always follows its class contract.

**Review by sjpadgett — APPROVED** [review]
Didn't test and assume others have. I don't see anything else.

**Comment by sjpadgett** [comment]
@juggernautsei I suggest you do a final live test with latest changes and report back.

File: controllers/C_Document.class.php [hunk 7]
```diff
@@ -774,42 +769,53 @@ public function retrieve_action(string $patient_id = null, $document_id, $as_fil
...
-        //this is for the s3 bucket module. If the file is not found locally, it will be found remotely
-        if ($retrieveOffsiteDocument->getOffsiteUrl() != null) {
-            header('Content-Description: File Transfer');
-            header("Location: " . $retrieveOffsiteDocument->getOffsiteUrl());
-            exit;
+            if (file_exists($temp_url)) {
+                $url = $temp_url;
+            }
+
+            $retrieveOffsiteDocument = new PatientRetrieveOffsiteDocument($d->get_url(), $d);
```
[the remark this answers is not in the document]
Comment (juggernautsei) [reply controllers/C_Document.class.php:802]: I am going to throw @bradymiller under the bus here on that 
" I didn't realize that $temp_url ends up becoming some wierd non-existant path".
It was done because of issues with upgrading and some other things as @bradymiller explained. To process the documents it was cut off and not used even though it was saved in the database table.

**Review by juggernautsei — APPROVED** [review]

**Comment by sjpadgett** [comment]
Thank you @adunsulag for the diligent review and effort. Merging.
