### PR TITLE
The toencounter and toinsurance issue.

### LINKED ISSUE #7874: bug: toencounter billing manager bug
### Describe the bug

https://community.open-emr.org/t/billing-manager-errors/23974

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #7874 

#### Changes proposed in this pull request:
- create async/await functionality to make bit more synchronous
- new async loadtab function.
- added javascript function in top to fetch session key/value pairs.

### CODE REVIEW

**Comment by sjpadgett** [comment]
@stephenwaite I still need to test this version on Linux.

**Comment by stephenwaite** [comment]
southpark_cheering

File: library/ajax/set_pt.php [hunk 1]
```diff
@@ -22,3 +24,10 @@
 if ($_GET["set_pid"] && $_GET["set_pid"] != $_SESSION["pid"]) {
     setpid($_GET["set_pid"]);
 }
+
+// For future use, if needed
```
Comment (bradymiller) [inline library/ajax/set_pt.php:28]: There is a security issue here allowing access to all session values. For example, if bad actor has access to 'csrf_private_key' session value (which can be done ), then they can broadly bypass all the csrf protections.

We should whitelist which session values that a user can get from this script.

Comment (sjpadgett) [reply library/ajax/set_pt.php:28]: Agreed, thanks Brady. Though I decided I didn't need the feature I think I'll move ajax to utility.js and limit key access.

Comment (stephenwaite) [reply library/ajax/set_pt.php:28]: removed it in my pending PR, https://github.com/openemr/openemr/pull/7896/commits/dcb644aa3822745a88840cac0a2a98887a535e02

Comment (adunsulag) [reply library/ajax/set_pt.php:28]: I saw @stephenwaite removed some of the functionality used in main.php, but doesn't this break the getSessionValue functionality in billing.php?  Since the set_pt.php no longer returns a pid value it seems like all of that needs to be changed.  Or am I missing something?

see here https://github.com/openemr/openemr/blob/master/interface/billing/billing_report.php#L355C13-L355C59

Do we need to cleanup the main.php method where getSessionValue is still stored?
