### PR TITLE
weno fixes

### LINKED ISSUE #5140: weno erx button not displaying in overhauled twig demographics
### Describe the bug

write concise description of what the bug is.

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5140

#### Short description of what this resolves:
adds weno back to the prescription dashboard plus some minor php8 fixes

### CODE REVIEW

File: interface/patient_file/summary/stats.php [hunk 1]
```diff
@@ -127,7 +127,7 @@ function load_location(location) {
     }
 
     if ($old_key == "medication" && $GLOBALS['erx_enable'] && $erx_upload_complete == 1) {
-        $display_current_medications_below = 1;
+        $display_current_medications_below = 0;
```
Comment (stephenwaite) [inline interface/patient_file/summary/stats.php:130]: went back into the original overhaul and thinking that this makes the most sense since without it the value is always `1`

File: templates/patient/card/card_base.html.twig [hunk 2]
```diff
@@ -14,6 +14,7 @@
                 {% endif %}
                 {# Display the Edit button #}
                 <a class="{{ btnClass|attr }}" href="{{ linkMethod == "html" ? btnLink : "#" }}" {{ (linkMethod == "html" and requireRestore == true) ? "onclick=\"top.restoreSession()\"" : ""}} {{ linkMethod == "javascript" ? "onclick=\"" ~ btnLink ~ "\"" : ''}}><i class="fa {{ btnIcon }} fa-sm">&nbsp;</i></a>
+                {% block weno %}{% endblock %}
```
Comment (robertdown) [inline templates/patient/card/card_base.html.twig:17]: We shouldn't define special blocks in this template. This should be content and module agnostic to remain as flexible as possible.

**Review by robertdown — CHANGES_REQUESTED** [review]
I have a PR that impacts Cards a bit. Let me submit that and see if there is a better way to go about solving this problem. I'll submit here within the hour.

**Comment by robertdown** [comment]
Looks good

File: templates/patient/card/rx.html.twig [hunk 3]
```diff
@@ -1,5 +1,15 @@
 {% extends "patient/card/card_base.html.twig" %}
 
 {% block content %}
+
+    {# Display the Edit button for openemr prescriptions#}
+    {% if weno == true %}
+        <div class="card-title mb-0 d-flex p-1 justify-content-between">
+            <span class="font-weight-bolder text-primary">Prescription History</span>
```
Comment (bradymiller) [inline templates/patient/card/rx.html.twig:8]: translate:
```
{{ "Prescription History"|xlt }}
```

**Comment by bradymiller** [comment]
2DV

File: templates/patient/card/rx.html.twig (hunk 3 above)
Comment (stephenwaite) [reply templates/patient/card/rx.html.twig:8]: thanks @bradymiller
