### PR TITLE
fix(Phreeze\QueryBuilder): actually strip parens

### LINKED ISSUE #8980: Bug in QueryBuilder.php: Incorrect string comparison for parenthesis matching
## Bug Description

There is a bug in `portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php` at line 178 in the `RemoveWherePrefix()` method.

## Current Code (Line 178)
```php
while (substr($sql, 0, 1) == "(" && substr($sql, 0, -1) == ")") {
    $sql = trim(substr($sql, 1, -1));
}
```

## Problem
The condition `substr($sql, 0, -1) == ")"` checks if all characters **except the last one** equal `")"`, which is incorrect. This will never match properly.

## Expected Code
```php
while (substr($sql, 0, 1) == "(" && substr($sql, -1) == ")") {
    $sql = trim(substr($sql, 1, -1));
}
```

The fix should use `substr($sql, -1)` to check if the **last character** is `")"`.

## Impact
This bug prevents the method from correctly identifying and removing surrounding parentheses from SQL query strings, which could lead to malformed queries.

## Location
- File: `portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php`
- Line: 178
- Method: `RemoveWherePrefix()`

## Reference
Discovered in review: https://github.com/openemr/openemr/pull/8949#pullrequestreview-3278641725

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #8980

#### Short description of what this resolves:

Phreeze\QueryBuilder::RemoveWherePrefix wants to strip parentheses around the query, but doesn't correctly look for parentheses at the end of the query string.

#### Changes proposed in this pull request:

- [x] use `str_ends_with` for an easier way to check the end of a string.

### CODE REVIEW

File: portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php [hunk 1]
```diff
@@ -166,16 +166,15 @@ private function GetTableJoinSQL($criteria)
...
      */
-    private function RemoveWherePrefix($sql)
+    private function RemoveWherePrefix(string $sql): string
     {
         $sql = trim($sql);
 
-        // remove if the query is surrounded by parenths
-        while (substr($sql, 0, 1) == "(" && substr($sql, 0, - 1) == ")") {
+        // remove if the query is surrounded by parentheses
+        while (str_starts_with($sql, '(') && str_ends_with($sql, ')')) {
```
Comment (kojiromike) [inline portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php:177]: I hope they are sure the query can't end with a semicolon or comment after the closing paren.
