### PR TITLE
Modal does not appear after closing it once

### LINKED ISSUE #2983: Problem appears when you try to add a patient after reject him once
### Describe the bug

write a concise description of what the bug is.

### To Reproduce

https://www.loom.com/share/e4f7ce4823d34bd9bfe45d014e4e2c15

### Expected behavior
OpenEMR - problem with adding a patient

### Client configuration

- Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by im-Amitto**
fixes #2983 
Scope of the variable  is corrected

**Previous behavior**: Modal does not appear after closing it once
**Current behavior**: If there are any changes after clicking the create patient for the first time modal will appear or else the patient will be saved.

### CODE REVIEW

File: interface/new/new_comprehensive.php [hunk 1]
```diff
@@ -857,11 +857,11 @@ function end_group()
     $('#create').click(function() { check()});
 
     var check = function(e) {
+        var f = document.forms[0];
```
Comment (sjpadgett) [inline interface/new/new_comprehensive.php]: while this will fix the immediate error however, when you click Create New Patient afterwards(dialog cancel) form will force submit anyway where you'd expect a new dup dialog. Caused by a force_submit flag set by default in new_search_popup.php. That logic should go away.
Also, appears it's not catching duplicates on popup open!

Comment (sjpadgett) [reply interface/new/new_comprehensive.php]: also remember that dialog is opened inside a submit validation routine where returning false from open will prevent default submit.

Comment (im-Amitto) [reply interface/new/new_comprehensive.php]: > the immediate error however, when you click Create New Patient afterwards(dialog cancel) form will force submit anyway where you'd expect a new dup dialog. Caused by a force_submit flag set by default in new_search_popup.php. That logic should go away.
> Also, appears it's not catching duplicates on popup open!

Ok, I thought the force submit was expected behavior as there was a comment mentioning it just above the method call. Thanks, for the review I will do the needed changes.

Comment (sjpadgett) [reply interface/new/new_comprehensive.php]: That's from old workflow where dup popup would set the confirm button in new patient form and submit took place on that event after user returned and clicked confirm. We want user to actually confirm in popup or select new patient to go fetch. A cancel would mean I want to go back to what I was doing.

Comment (im-Amitto) [reply interface/new/new_comprehensive.php]: I have removed the flag and duplicate check is working as expected.

Comment (sjpadgett) [reply interface/new/new_comprehensive.php]: Thanks, will bring in after tarvis. Nice work.
