### PR TITLE
fix testing for property thats not an array

### LINKED ISSUE #9727: Portal Phreezable controller causing errors
### Describe the bug
[09-Dec-2025 19:12:12 America/New_York] PHP Fatal error:  Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, array given in C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\Phreezable.php:118
Stack trace:
#0 C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\Phreezable.php(118): property_exists(Array, 'Patient')
#1 C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\Phreezable.php(195): Phreezable->GetPublicProperties()
#2 C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\DataSet.php(277): Phreezable->ToObject(Array)
#3 C:\xampp\htdocs\openemr\portal\patient\libs\Controller\PatientController.php(164): DataSet->ToObjectArray(true, Array)
#4 C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\Dispatcher.php(172): PatientController->Query()
#5 C:\xampp\htdocs\openemr\portal\patient\index.php(54): Dispatcher::Dispatch(Object(Phreezer), Object(SavantRenderEngine), '', NULL, Object(GenericRouter))
#6 {main}
  thrown in C:\xampp\htdocs\openemr\portal\patient\fwk\libs\verysimple\Phreeze\Phreezable.php on line 118

### PR DESCRIPTION
**Pull request by sjpadgett**
PHP 8+ strict type check: property_exists() no longer tolerates being given an array as the first argument

Fixes #9727

### CODE REVIEW

File: portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php [hunk 1]
```diff
@@ -115,7 +115,7 @@ public function GetPublicProperties()
     {
         $className = static::class;
 
-        if (! property_exists(self::$PublicPropCache, $className)) {
+        if (! isset(self::$PublicPropCache[$className])) {
```
Comment (kojiromike) [inline portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php:118]: This is actually a behavior change. In PHP prior to 8, since `self::$PublicPropCache` is an array, then `property_exists` would've returned `false`, so this block of code would never have run. Now, using `isset`, maybe it will. Obviously, this is correct, but we will need to look for the consequences of the inner code running, that has never run before.
