### PR TITLE
Query error

### LINKED ISSUE #3354: Query Error in Observation Form
### Describe the bug

Just confronted a query error in find_code_popup.php

### To Reproduce

1. Open any Encounter 
2. Open 'Observation Form'
3. Click input field 'Code'
4. A popup will showup Select Code type blank (dont select LONIC)
4. Now search blank or sanything & See error

image

### PR DESCRIPTION
**Pull request by adad20**
Fixes #3354

### CODE REVIEW

File: interface/forms/observation/new.php [hunk 1]
```diff
@@ -114,7 +114,7 @@ function sel_code(id)
                 id = id.split('tb_row_');
                 var checkId = '_' + id[1];
                 document.getElementById('clickId').value = checkId;
-                dlgopen('<?php echo $GLOBALS['webroot'] . "/interface/patient_file/encounter/" ?>find_code_popup.php?codetype=LOINC,PHIN Questions', '_blank', 700, 400);
+                dlgopen('<?php echo $GLOBALS['webroot'] . "/interface/patient_file/encounter/" ?>find_code_popup.php?"codetype=LOINC, PHIN Questions"', '_blank', 400, 400);
```
Comment (bradymiller) [inline interface/forms/observation/new.php:117]: i think you just need to urlencode to original for this to work:
```
dlgopen('<?php echo $GLOBALS['webroot'] . "/interface/patient_file/encounter/" ?>find_code_popup.php?codetype=' + encodeURIComponent('LOINC,PHIN Questions'), '_blank', 700, 400);
```

Comment (adad20) [reply interface/forms/observation/new.php]: hi @bradymiller Sorry it was a mistake, you may have a look

**Comment by bradymiller** [comment]
hi @adad20 , Code looks good and bringing into codebase. Thanks for the fix! -brady
