### PR TITLE
Accept assign fix

### LINKED ISSUE #5699: Fix assignment acceptance inconsistency
### Describe the bug

OpenEMR does not allow a provider to properly NOT accept assignment on a claim, and it prevents that in different ways depending on if submitting the claim by paper or electronically.

[forum thread](https://community.open-emr.org/t/hcfa-x12-accept-assignment-calculation)

CMS 1500 Box 13 = X12 837P CLM08
CMS 1500 Box 27 = X12 837P CLM07

...according to:
https://www.availity.com/documents/support/CMS1500_QuickReferenceGuide.pdf
https://www.cgsmedicare.com/pdf/5010_jobaid.pdf
https://nucc.org/images/stories/PDF/1500_claim_form_map_to_837P_v3-3_2012_02.pdf
https://med.noridianmedicare.com/web/jeb/topics/claim-submission/cms-1500-crosswalk-emc-loops-segments
https://www.ngsmedicare.com/documents/20124/229628/ngsmedicare_7495e8a4_5930_4768_8248_e787c7e455a9_CMS1500_Crosswalk_%2BANSI_837P.pdf/e66514c5-b4fe-6909-3c6b-82807e00e206?t=1611700291665
https://www.palmettogba.com/Palmetto/Providers.Nsf/files/CMS1500_837v5010_Crosswalk.pdf/$File/CMS1500_837v5010_Crosswalk.pdf

Payors use Box 27 / CLM07 to determine assignment of benefits, but they also use Box 13 / CLM08, following [CMS guidance](https://www.cms.gov/Regulations-and-Guidance/Guidance/Transmittals/Downloads/R1369CP.pdf).

When generating a paper claim, OpenEMR hardcodes Box 13 / CLM08 assignment acceptance.

When generating a 837 electronic claim, OpenEMR hardcodes Box 27 / CLM07 assignment acceptance.

I propose the following fix:

https://github.com/openemr/openemr/compare/master...surfacehazard:openemr:master?diff=unified

I would submit a PR, but the fix would be clobbered by [this PR](https://github.com/openemr/openemr/pull/5691).

### PR DESCRIPTION
**Pull request by surfacehazard**
Fixes #5699

### CODE REVIEW

File: src/Billing/X125010837P.php [hunk 1]
```diff
@@ -626,7 +626,7 @@ public static function genX12837P($pid, $encounter, &$log, $encounter_claim = fa
         "*" .
         "*" . sprintf('%02d', $claim->facilityPOS()) . ":" . "B" . ":" . $claim->frequencyTypeCode() .
         "*" . "Y" .
-        "*" . "A" .
+        "*" . ($claim->billingFacilityAssignment() ? 'A' : 'C') .
```
Comment (stephenwaite) [inline src/Billing/X125010837P.php:629]: would make the same change for now on
https://github.com/openemr/openemr/blob/99b01d1525c81948df5d86b8c1c246a80807b98b/src/Billing/X125010837P.php#L2159

even though like you said it maybe moot going forward

**Comment by stephenwaite** [comment]
thanks @surfacehazard , will bring in once tests are green, just a formality
