### PR TITLE
fix: remove only-null annotations

### LINKED ISSUE #8829: `null` is never correct as an _only_ type
There are quite a few places in the code where a docblock has something like:

```
/**
 * …
 * @param null $name
 * …
 */
function haveFun($name = null) …
```

This makes phpstan think the variable can only ever be null. Then in the function body, a check like `($name ?? "fishy")` triggers an erroneous phpstan finding. Of course, we surely don't intend for `$name` here to be always null, or we wouldn't make it a parameter at all. So we probably need at least to remove all these docblock bugs, if not replace them with a more apt type.

There are also cases where a function is annotated as `@return false`, but it doesn't only return false.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #8829

#### Short description of what this resolves:

Fix cases where phpstan is misled by annotations saying a parameter is `null` or a function returns `false` when the type can be other things.

#### Changes proposed in this pull request:

- [x] describe `null` and `false` union types more thoroughly
- [x] remove fixed phpstan complaints from baseline
- [x] fix new phpstan findings

### CODE REVIEW

File: src/Services/QuestionnaireResponseService.php [hunk 1]
```diff
@@ -397,20 +397,18 @@ public function saveQuestionnaireResponse(
         }
 
         $version = 1;
-        if (!empty($fhirQuestionnaireOb)) {
```
Comment (kojiromike) [inline src/Services/QuestionnaireResponseService.php:400]: were this value empty we would have hit the `throw` on 383.

Comment (adunsulag) [reply src/Services/QuestionnaireResponseService.php:400]: I agree.

**Review by adunsulag — APPROVED** [review]
Looks good.  I didn't see any problems.
