### PR TITLE
FHIR API Error Response

### LINKED ISSUE #3195: No Error Response in FHIR
### Describe the bug

There is no error response in FHIR api.
Extension of https://community.open-emr.org/t/project-fhir-integration/13701/13?u=yashrajbothra
### Expected behavior
Something like this would be nice.
image

Additional Context : Currently working on it. Feel Free to assign me 😄

### PR DESCRIPTION
**Pull request by yashrajbothra**
Signed-off-by: Yash Bothra <yashrajbothra786@gmail.com>

Fixes #3195 

#### Short description of what this resolves:
Added Error Response with OperationOutcome Resource
http://hl7.org/fhir/operationoutcome.html

#### Changes proposed in this pull request:

- added OperationOutcomeResouce for 404

### CODE REVIEW

**Comment by yashrajbothra** [comment]
Hey @sjpadgett Does this looks good?

I think we should separate each Resource Services.

File: src/Services/FhirResourcesService.php [hunk 1]
```diff
@@ -15,15 +15,19 @@
...
 use OpenEMR\FHIR\R4\FHIRElement\FHIRCodeableConcept;
 use OpenEMR\FHIR\R4\FHIRElement\FHIRHumanName;
 use OpenEMR\FHIR\R4\FHIRElement\FHIRId;
 use OpenEMR\FHIR\R4\FHIRElement\FHIRReference;
+use OpenEMR\FHIR\R4\FHIRElement\FHIRIssueSeverity;
+use OpenEMR\FHIR\R4\FHIRElement\FHIRIssueType;
 use OpenEMR\FHIR\R4\FHIRResource\FHIREncounter\FHIREncounterParticipant;
 use OpenEMR\FHIR\R4\FHIRResource\FHIRBundle;
 use OpenEMR\FHIR\R4\FHIRResource\FHIRBundle\FHIRBundleLink;
+use OpenEMR\FHIR\R4\FHIRResource\FHIROperationOutcome\FHIROperationOutcomeIssue;
```
Comment (sjpadgett) [inline src/Services/FhirResourcesService.php]: You don't want to modify these classes because they are built strictly to the Fhir spec. The R4 version is current release but when we hit R5 and bring in that version well. where'd your mods go.
If you must, extend the class. that way any new version we point to will still be covered.
Still, nice!

**Comment by sjpadgett** [comment]
oh wait! @yashrajbothra 
Looks like you just added missing classes! Not sure how we want to handle value sets but this is okay till I figure out a version structure. Sorry...

File: src/Services/FhirResourcesService.php (hunk 1 above)
Comment (yashrajbothra) [reply src/Services/FhirResourcesService.php]: Thanks for pointing it, I will figure it out👍

**Comment by yashrajbothra** [comment]
@sjpadgett I was about to ask the valueset part. Are you having any idea about how to integrate that.

**Comment by sjpadgett** [comment]
@yashrajbothra I misinterpreted this PR. You were just adding the class use and I thought they were file includes to R4. Bringing in and nice job. On the other hand, I should be fired:)

**Comment by yashrajbothra** [comment]
Thank You @sjpadgett Sir, Btw I have few doubts regarding the FHIR implementation. Is it a good place to discuss?

Side note: I have posted project proposal for FHIR implementation in GSOC dashboard. Just take a look if incase having some leftover time from quarantine😄.

**Comment by sjpadgett** [comment]
> Sir, Btw I have few doubts regarding the FHIR implementation

Best place is on the FHIR forum. This way others can contribute with doubts or suggestions.
