### PR TITLE
fix: js error when samesite param missing

### LINKED ISSUE #10096: JavaScript error when session cookie samesite parameter is empty
## Description

A JavaScript syntax error occurs in `library/restoreSession.php` when the `samesite` session cookie parameter is empty or not set.

## Current Behavior

When `$scparams['samesite']` is empty, the code outputs:
```javascript
var oemr_scp_samesite = ;
```
This is invalid JavaScript syntax and causes a script error.

## Expected Behavior

The variable should be assigned a valid JavaScript value even when the samesite parameter is empty.

## Steps to Reproduce

1. Configure OpenEMR with a session cookie that has no `samesite` attribute
2. Load a page that includes `library/restoreSession.php`
3. Observe JavaScript error in browser console

## Affected File

- `library/restoreSession.php` (line 37)

## Environment

- OpenEMR version: latest/master

### PR DESCRIPTION
**Pull request by mdsupport**
Fixes #10096

#### Short description of what this resolves:

Fixes a JavaScript syntax error that occurs when the session cookie `samesite` parameter is empty or not set. The generated JavaScript was outputting an empty value without quotes, resulting in invalid syntax.

#### Changes proposed in this pull request:

- Changed the fallback value from empty string `''` to string `'false'` when `$scparams['samesite']` is empty in `library/restoreSession.php`

#### Does your code include anything generated by an AI Engine? Yes / No

No

#### If you answered yes: Verify that each file that has AI generated code has a description that describes what AI engine was used and that the file includes AI generated code. Sections of code that are entirely or mostly generated by AI should be marked with a comment header and footer that includes the AI engine used and stating the code was AI.

N/A

### CODE REVIEW

File: library/restoreSession.php [hunk 1]
```diff
@@ -34,7 +34,7 @@
 var oemr_scp_path = <?php echo js_escape($scparams['path']); ?>;
 var oemr_scp_domain = <?php echo js_escape($scparams['domain']); ?>;
 var oemr_scp_secure = <?php echo js_escape($scparams['secure']); ?>;
-var oemr_scp_samesite = <?php echo empty($scparams['samesite']) ? '' : js_escape($scparams['samesite']); ?>;
+var oemr_scp_samesite = <?php echo empty($scparams['samesite']) ? 'false' : js_escape($scparams['samesite']); ?>;
```
Comment (kojiromike) [inline library/restoreSession.php:37]: good fix. One minor suggestion:

```suggestion
var oemr_scp_samesite = <?php echo js_escape($scparams['samesite'] ?: false); ?>
```

Both produce identical output, but the second version uses js_escape() for both branches, which is more consistent with the above implementations.
