### PR TITLE
Assessment service update to relevant period

### LINKED ISSUE #5370: CDA Referral Note document requires informationRecipient
### Describe the bug
Missing from current generator so will add. The informationRecipient is part of the recordTarget for the document.
Though this is required for referral, not sure if applicable for CCD so for test purpose, I'll only include in referral notes.
Wish me luck!

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5370

#### Short description of what this resolves:
looked at failure in cypress and compared to a known good result
instead of datetime use date period

#### Changes proposed in this pull request:
borrow `makeQdmModel()` from AbstractObservationService.php and tweak it to suit the purpose

testing well

### CODE REVIEW

**Comment by stephenwaite** [comment]
maybe could change the abstract service but can do later if know more

**Comment by sjpadgett** [comment]
You shouldn't need to do this. What cat1 report is this and did you look at the sample report.
I need the details so I can look over.
These mustache templates are the same ones cypress uses so it follows if cypress generates a report then it came from these templates. The samples came from cypress I'd assume. Also a helper function can probably achieve the same w/o all the service work.

**Comment by stephenwaite** [comment]
from the CMS122v10 sample patient, 0_Amber_Roy.xml
Screenshot from 2022-05-19 06-32-26

**Comment by stephenwaite** [comment]
looks like this has something to do with an exclusion condition since all patients with this are `DENEX`

**Comment by sjpadgett** [comment]
yeah that'd make sense. dates are really important. I don't have a problem with what you are doing just we should be able to use the existing assessment service with a helper.

**Comment by sjpadgett** [comment]
@stephenwaite you should be able to populate the service with a var name 'relevantPeriod' or 'relevantDatetime' and mustache parser will take care of the rest!

**Comment by kchapple** [comment]
@stephenwaite 
@sjpadgett is right, you shouldn't have to change the templates. and that could potentially break a bunch of other templates. If one Observation is broken, then they all are, so it doesn't make sense to just fix one. If you send me the original XML for the Cat 1 I can take a look.

**Comment by kchapple** [comment]
@sjpadgett is right, this is the helper function in src/Services/Qrda/Helpers/Date.php that should be returning your XML. It's possible that this hadn't been tested yet, and the port from Ruby doesn't work in PHP in this case. It looks like we return a string "relevant_period" but I'm not sure if that will actually call the function relevant_period() which is further up in the Date.php file. We may just need to call the function explicitly? I don't think any of the QDM models need to change to fix the issue you describe, though.

```
    /**
     * Returns the helper function to call for the relevent date period or returns null flavor if there is no date period
     * If the current context has a period we return the period helpfunction, otherwise if we have a dateTime we return
     * the date time helper function
     * @param Mustache_Context $context The current stack context
     * @return string Helper function name or null flavor xml
     */
    public function relevant_date_period_or_null_flavor(Mustache_Context $context)
    {
        $relevantPeriod = $context->find('relevantPeriod');
        if (!empty($relevantPeriod) && (isset($relevantPeriod['low']) || isset($relevantPeriod['high']))) {
            // we return the function name to call here
            return 'relevant_period';
        } else if (!empty($context->find('relevantDatetime'))) {
            return $this->relevant_date_time_value($context);
        } else {
            "<effectiveTime nullFlavor='UNK'/>";
        }
    }
```

**Comment by kchapple** [comment]
@stephenwaite I would first try adding 'relevantPeriod' to the AssessmentService.php something like this. And if it doesn't populate in the template because of the relevant_date_period_or_null_flavor() function returning a string, may need to adjust it to call the relevant_period() function explicitly instead.

```
    public function makeQdmModel(array $record)
    {
        $qdmModel = new AssessmentPerformed([
            'relevantDatetime' => new DateTime([
                'date' => $record['date']
            ]),
            'relevantPeriod' => new Interval([
                'low' =>  new DateTime([
                    'date' => $record['date']
                ]),
                'high' => new DateTime([
                    'date' => $record['date']
                ]),
                'lowClosed' => $record['date'] ? true : false,
                'highClosed' => $record['date'] ? true : false
            ]),
            'authorDatetime' => new DateTime([
                'date' => $record['date']
            ]),
            'result' => $this->makeQdmCode($record['ob_code']),
            'negationRationale' => $this->makeQdmCode($record['ob_reason_code'])
        ]);

        $codes = $this->explodeAndMakeCodeArray($record['code']);
        foreach ($codes as $code) {
            $qdmModel->addCode($code);
        }

        return $qdmModel;
    }
```

**Comment by kchapple** [comment]
@stephenwaite updated my comment above.

File: src/Services/Qdm/Services/AbstractObservationService.php [hunk 1]
```diff
@@ -63,8 +69,13 @@ public function makeQdmModel(QdmRecord $recordObj)
         $qdmModel = new $modelClass([
             '_id' => $id,
             'id' => $id,
-            'relevantDatetime' => new DateTime([
-                'date' => $record['date']
+            'relevantPeriod' => new Interval([
+                'low' => new DateTime([
+                    'date' => $record['date']
+                ]),
```
Comment (sjpadgett) [inline src/Services/Qdm/Services/AbstractObservationService.php:75]: The test ask for relevantPeriod in some measures and relevantDateTime in others. So both need to work depending on how you want to report. However this was a known issue reported in the 2021 reporting period so interpret how you want.

Guidance for reporting eCQMs with QDM data types allowing 
either relevantDatetime or relevantPeriod attributes for the 2021 
reporting/performance period
For all eCQMs where QDM data types support both relevantDatetime and 
relevantPeriod attributes, the Cypress, QualityNet, and The Joint Commission 
systems will allow submitters to submit data either as relevantDatetime 
(effectiveTime/@value) or relevantPeriod (effectiveTime/low and 
effectiveTime/high) in a QRDA Category I file.
For example, for CMS129v10, even though the measure specification uses 
relevantPeriod for ["Procedure, Performed": "Prostate Cancer Treatment"], 
submitters may submit the timing of this data element either as relevantDatetime 
or relevantPeriod in QRDA Category I.
For purposes of hospital measure calculation:
1. If a relevantDatetime is reported, it will be converted to a relevantPeriod.
2. When a relevantPeriod is reported and a relevantDatetime is needed for evaluation, 
the low value will be used unless not provided, then the high time will be used.

Comment (kchapple) [reply src/Services/Qdm/Services/AbstractObservationService.php:75]: Yes, @stephenwaite you need to have both relevantPeriod and relevantDatetime, sorry for the confusion

Comment (stephenwaite) [reply src/Services/Qdm/Services/AbstractObservationService.php:75]: the `relevant_date_period_or_null_flavor` function in the date helper returns either I think based on what's sent

Comment (stephenwaite) [reply src/Services/Qdm/Services/AbstractObservationService.php:75]: so should be all good now

Screenshot from 2022-05-19 13-47-36

Comment (stephenwaite) [reply src/Services/Qdm/Services/AbstractObservationService.php:75]: oh, I get what you're saying sorry

**Review by sjpadgett — APPROVED** [review]
This is looking good to me however, check other QDM's that might require this fix. Looks like only two measures in our testing.
Also wouldn't hurt to run a full import of cat1s and test on my server for any measure affected by this change.
Good work Stephen but looky at what I've done finally!

image

**Comment by stephenwaite** [comment]
the peculiar way cypress wants to see the test imported, in this particular case on Jerry's cypress CMS122v10 wants assessment performed with relevantPeriod
Screenshot from 2022-05-19 16-13-41
but for CMS69v10 physical exam performed it wants relevantDatetime
Screenshot from 2022-05-19 16-18-42

not sure if this is going to change on another test batch but we'll see

**Comment by stephenwaite** [comment]
looking more closely at 122v10 data elements
Screenshot from 2022-05-19 16-22-22
so if it's going to be naegated then we can't use relevantPeriod, holy cow

**Comment by sjpadgett** [comment]
@stephenwaite Please call me. too much to try to explain here.

**Comment by sjpadgett** [comment]
if you haven't looked here are testing for c1 on SLI
image

**Comment by stephenwaite** [comment]
> so if it's going to be naegated then we can't use relevantPeriod, holy cow

ok, that's just for `author`

Jerry helped me see this more clearly and found we're missing `date_end` field from `form_observation` will see if can finally get this right :)

File: interface/forms/care_plan/new.php [hunk 2]
```diff
@@ -102,7 +102,7 @@
                                             <div class="forms col-md-2">
                                                 <label for="code_<?php echo attr($key) + 1; ?>" class="h5"><?php echo xlt('Code'); ?>:</label>
                                                 <input type="text" id="code_<?php echo attr($key) + 1; ?>" name="code[]" class="form-control code" 
-                                                  value="<?php echo attr($obj["code"]); ?>"  onclick='sel_code(<?php echo js_url($GLOBALS['webroot']) ?>,
+                                                  value="<?php echo attr($obj["code"]); ?>"  onclick='sel_code(<?php echo attr_js($GLOBALS['webroot']) ?>,
```
Comment (bradymiller) [inline interface/forms/care_plan/new.php:105]: 2DV

**Review by bradymiller — APPROVED** [review]
