### PR TITLE
fixes for track anything

### LINKED ISSUE #5880: track anything bugs
### Describe the bug

notified of a [potential issue on the forum](https://community.open-emr.org/t/track-anything-and-dashboard/19362?u=stephenwaite)
### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5880

### CODE REVIEW

File: interface/patient_file/summary/track_anything_fragment.php [hunk 1]
```diff
@@ -42,7 +42,7 @@
 } else {  // We have some tracks here...
     echo "<span class='text'>";
     echo xlt('Available Tracks') . ":";
-    echo text($result);
+    echo json_encode($result);
```
Comment (stephenwaite) [inline interface/patient_file/summary/track_anything_fragment.php:45]: is there a better way to escape an array here @bradymiller ?

Screenshot from 2022-10-26 14-28-11

Comment (stephenwaite) [reply interface/patient_file/summary/track_anything_fragment.php:45]: oh, nvm, this is trivial

Comment (bradymiller) [reply interface/patient_file/summary/track_anything_fragment.php:45]: That is an odd line where was basically echoing an array.
is that line even needed, since basically the same query is done below that and then outputted in a human readable form?

Comment (bradymiller) [reply interface/patient_file/summary/track_anything_fragment.php:45]: i think can remove lines 45 and 47

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
nice!!!

118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a
