### PR TITLE
ci(inferno): fix missing main_build

### LINKED ISSUE #9239: Cache more to avoid repetitive steps in CI testing
We can improve the speed of our ci tests by caching more. We can cache the vendor directory itself, as well as the outputs of npm ci/build and npm ci in ccdaservice.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #9239

#### Short description of what this resolves:

`main_build` was removed in #9239 and that broke the inferno tests. This fixes that.

### CODE REVIEW

File: ci/inferno/run.sh [hunk 1]
```diff
@@ -70,35 +70,35 @@ initialize_openemr() {
     echo 'Initializing OpenEMR'
     local -x DOCKER_DIR=inferno
     local -x OPENEMR_DIR=/var/www/localhost/htdocs/openemr
-    (
```
Comment (kojiromike) [inline ci/inferno/run.sh:73]: @adunsulag These subshells were just for managing the directory, right? They're triggering a shellcheck issue that's a little obnoxious, and I think the easiest fix is to remove the subshell. WDYT?
