### PR TITLE
Fixes #7214 pass action status to listener

### LINKED ISSUE #7214: bug: InstallerController needs to pass current status to ModuleManagerAfterActionListener action methods
If the module action fails the ModuleManagerAfterActionListener needs to be aware that the system is already in a failure state.  We need to pass the current action status into InstallerController.  It looks like this was the original intent but was likely overlooked.

This is in InstallerController.php#L216

### PR DESCRIPTION
**Pull request by adunsulag**
Action status was not being passed in the listener. Fixes #7214

### CODE REVIEW

File: interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php [hunk 1]
```diff
@@ -213,7 +213,7 @@ private function callModuleAfterAction($action, $modId, $dirModule, $currentStat
         $instance = $className::initListenerSelf();
         if (class_exists($instance::class)) {
             if (method_exists($instance, 'moduleManagerAction')) {
-                return call_user_func([$instance, 'moduleManagerAction'], $methodName, $modId);
+                return call_user_func([$instance, 'moduleManagerAction'], $methodName, $modId, $currentStatus);
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php:216]: oops! good catch.

**Review by sjpadgett — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV
