### PR TITLE
Disable unruly modules on start

### LINKED ISSUE #8349: Module Manager locks system
### Describe the bug

If for any reason that the module manager can't load modules bootstrap it causes somewhat of a race condition.
Previously I added a retry mechanism but forgot to disable unruly module.

### To Reproduce

enable a module and remove bootstrap.

### Expected behavior
Module gets disabled.
12-May-2025 01:15:49 America/New_York] Custom module bootstrap file C:/xampp/htdocs/openemr/interface/modules/custom_modules/oe-module-telemetry/openemr.bootstrap.php is not readable. Retry Count:1
[12-May-2025 01:15:54 America/New_York] Custom module bootstrap file C:/xampp/htdocs/openemr/interface/modules/custom_modules/oe-module-telemetry/openemr.bootstrap.php is not readable. Retry Count:2
[12-May-2025 01:15:59 America/New_York] Custom module bootstrap file C:/xampp/htdocs/openemr/interface/modules/custom_modules/oe-module-telemetry/openemr.bootstrap.php is not readable. Retry Count:3
[12-May-2025 01:16:04 America/New_York] Custom module C:/xampp/htdocs/openemr/interface/modules/custom_modules/oe-module-telemetry/openemr.bootstrap.php is enabled but after 3 tries can not read the bootstrap script. System will force disable module.

### Client configuration

- Browser:
- OpenEMR version: all
- Operating system: all

### PR DESCRIPTION
**Pull request by sjpadgett**
Disable in table after 3 attempts.

Fixes #8349

### CODE REVIEW

**Comment by sjpadgett** [comment]
@adunsulag This will take care of missing module. Any other suggestions while I'm here?

File: src/Core/ModulesApplication.php [hunk 1]
```diff
@@ -140,8 +141,10 @@ private function bootstrapCustomModules(ModulesClassLoader $classLoader, $eventD
                 // Can't include a missing bootstrap. Notify user and log the error.
                 error_log("Custom module " . errorLogEscape($customModulePath . $row['mod_directory'])
                     . '/' . self::CUSTOM_MODULE_BOOSTRAP_NAME
-                    . " is enabled but after 3 tries can not read the bootstrap.php script. Uninstall and or disable in module manager.");
+                    . " is enabled but after 3 tries can not read the bootstrap script. System will force disable module.");
                 $failed_modules[] = ["name" => $row["mod_name"], "directory" => $row['mod_directory'], "path" => $customModulePath . $row['mod_directory'], "available" => false, "error" => "Module is missing bootstrap."];
+                // disable
+                sqlStatementNoLog("UPDATE modules SET mod_active = 0 WHERE mod_directory = ? AND type != 1", [$row['mod_directory']]);
```
Comment (adunsulag) [inline src/Core/ModulesApplication.php:147]: could this statement ever fail?  I don't think so but if it does would we want to log that as well?  Other than that I don't see any problems.

**Comment by bradymiller** [comment]
2DV

**Comment by bradymiller** [comment]
hi @sjpadgett , Is this ready for patch 4 (just let me know and I'll bring it over to rel-703).

**Comment by bradymiller** [comment]
Brought in rel-703 for patch 7.0.3.4: #8356
