### PR TITLE
Fax issues

### LINKED ISSUE #9725: etherFAX display renders faxes in wrong tab
### Describe the bug

Received fax are appearing in the Sent tab.
Should render in the Received tab

Image

### Client configuration

- Browser:
- OpenEMR version: 7.0.3
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
move receive details to correct tab.

Fixes #9725

### CODE REVIEW

File: interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php [hunk 1]
```diff
@@ -561,45 +561,156 @@ public function formatFax($encodedFax): string
...
             } else {
-                $response['message'] = 'Failed to write file';
+                $parts[] = $segment;
             }
-        } elseif ($action == 'setup') {
-            $response['success'] = true;
-            $response['url'] = $where;
         }
+        $prefix = DIRECTORY_SEPARATOR;
+        if (preg_match('/^[A-Za-z]:\\/', $path) === 1) { // Windows drive
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php]: I think that regex is fragile, dealing with backslashes. This is more verbose, but maybe easier to maintain… WDYT?

```suggestion
        $isWindowsDrive = strlen($path) >= 3 && ctype_alpha($path[0]) && $path[1] === ':' && ($path[2] === DIRECTORY_SEPARATOR);
        if ($isWindowsDrive) {
```

Comment (sjpadgett) [reply interface/modules/custom_modules/oe-module-faxsms/src/Controller/EtherFaxActions.php]: I agree thanks

**Review by kojiromike — APPROVED** [review]
