### PR TITLE
fix(portal): Fixed the onetime token notification.

### LINKED ISSUE #10517: bug(portal): one-time token for portal document notification broken
### Describe the bug

The one-time for patient notification that a portal document needs attention is broken for both release v8 and 8.0.1-dev.
For dev version onetime is being redirected to openemr login
For v8.0.0 getting a fatal error
`
Fatal error: Uncaught OpenEMR\Common\Auth\Exception\OneTimeAuthException: Onetime decode failed Onetime auth: 007IzS92CV91uu1A1PtJc4iceosNtpQCiHgXYfcNh+2lVRVAakjvZpHJ0MtOX5ZFXtb7aJ9+pnfAHQdzsQRTZS3/C35XGNcZU2SRaa/O62+vBIAFylO5AwMtMvQ0AUMSadY in C:\xampp\htdocs\openemr\src\Common\Auth\OneTimeAuth.php:172 Stack trace: #0 C:\xampp\htdocs\openemr\portal\index.php(106): OpenEMR\Common\Auth\OneTimeAuth->decodePortalOneTime('007IzS92CV91uu1...', NULL, false) #1 {main} thrown in C:\xampp\htdocs\openemr\src\Common\Auth\OneTimeAuth.php on line 172
`
I'm pretty sure works in 7.0.4 but I'm not going to retest that.

### To Reproduce

- Ensure a valid email account is setup
- Ensure email is enabled in Choices and a valid test email address is enter as patient contact email
- Install and enable Email service in faxsms module
- Create or have a document template assigned and scheduled to a test patient.
- Be sure the Profile is active Profiles in Portal
- Select template from Patient Assigned Templates and click Notify.

### Client configuration

- Browser:
- OpenEMR version: 8.0.0
- Operating system:

### LINKED ISSUE #10552: bug: Prior Authorization Module adding new authorization generates fatal error.
### Describe the bug

Prior Authorization module is throwing error in Dashboard -> Auths screen.

[Wed Feb 04 00:02:51.713708 2026] [php:error] [pid 3084:tid 3084] [client 172.20.0.1:53288] PHP Fatal error:  Uncaught TypeError: Cannot assign string to property Juggernaut\\OpenEMR\\Modules\\PriorAuthModule\\Controller\\AuthorizationService::$id of type ?int in /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/AuthorizationService.php:71\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/public/index.php(37): Juggernaut\\OpenEMR\\Modules\\PriorAuthModule\\Controller\\AuthorizationService->setId()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/AuthorizationService.php on line 71, referer: https://localhost:9300/interface/modules/custom_modules/oe-module-prior-authorizations/public/index.php

### To Reproduce

Image

1. Open a patient's dashboard
2. Click on the Auths on the patient dashboard navigation menu
3. Enter in the information as seen in the screenshot
4. Hit the save button
5. See a white screen with fatal error

### Expected behavior
The authorization is added to the list of auths.

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### LINKED ISSUE #10553: bug(session): various session and type errors.
### Describe the bug
- Profile dialog fails
[03-Feb-2026 18:55:18 America/New_York] PHP Fatal error:  Uncaught Error: Class "OpenEMR\Common\Session\SessionWrapperFactory" not found in C:\xampp\htdocs\openemr-prod\portal\import_template.php:21
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\openemr-prod\portal\import_template.php on line 21
- Submitted questionnaire fails recall for edits
[03-Feb-2026 20:05:47 America/New_York] PHP Fatal error:  Uncaught TypeError:  OpenEMR\Common\Forms\CoreFormToPortalUtility::confirmFormBootstrapPatient(): Argument #4 ($patientId) must be of type int, null given, called in C:\xampp\htdocs\openemr\interface\forms\questionnaire_assessments\questionnaire_assessments.php on line 80 and defined in C:\xampp\htdocs\openemr\src\Common\Forms\CoreFormToPortalUtility.php:65
Stack trace:
#0 C:\xampp\htdocs\openemr\interface\forms\questionnaire_assessments\questionnaire_assessments.php(80): OpenEMR\Common\Forms\CoreFormToPortalUtility::confirmFormBootstrapPatient(true, 18, 'questionnaire_a...', NULL)
#1 {main}
  thrown in C:\xampp\htdocs\openemr\src\Common\Forms\CoreFormToPortalUtility.php on line 65
- Questionnaire save fails 
[03-Feb-2026 20:45:43 America/New_York] PHP Fatal error:  Uncaught TypeError: OpenEMR\Common\Forms\CoreFormToPortalUtility::confirmFormBootstrapPatient(): Argument #4 ($patientId) must be of type int, null given, called in C:\xampp\htdocs\openemr\interface\forms\questionnaire_assessments\save.php on line 53 and defined in C:\xampp\htdocs\openemr\src\Common\Forms\CoreFormToPortalUtility.php:65
- Advanced Prior Auth fatal on save new.
[03-Feb-2026 21:18:05 America/New_York] PHP Fatal error:  Uncaught TypeError: Cannot assign string to property Juggernaut\OpenEMR\Modules\PriorAuthModule\Controller\AuthorizationService::$id of type ?int in C:\xampp\htdocs\openemr-prod\interface\modules\custom_modules\oe-module-prior-authorizations\src\Controller\AuthorizationService.php:71
- Portal audit delete fails [03-Feb-2026 22:07:40 America/New_York] OpenEMR CSRF token authentication error

### To Reproduce
Edit portal dashboard Profiles.

### Client configuration

- Browser:
- OpenEMR version: v8.0.0+
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
Refactored the $_SESSION to use SessionWrapperFactory
Refactored globals to use globalbags
Move SessionWrapperFactory below autoload for #10553

Fixes #10517
Fixes #10553 
Fixes #10552

### CODE REVIEW

File: src/Common/Auth/OneTimeAuth.php [hunk 1]
```diff
@@ -229,31 +235,34 @@ private function encodeLink($site_addr, $token_encrypt, $encrypted_redirect = nu
             }
         }
         $format = "%s&%s";
-        if (stripos((string) $site_addr, "?") === false) {
+        if (stripos((string)$site_addr, "?") === false) {
             $format = "%s?%s";
         }
+        // Use RFC3986 so + and / in base64-like tokens are encoded as %2B and %2F,
+        // preventing query string parsing from turning + into space (issue #10517).
+        $enc_type = defined('PHP_QUERY_RFC3986') ? PHP_QUERY_RFC3986 : 2;
```
Comment (kojiromike) [inline src/Common/Auth/OneTimeAuth.php]: `PHP_QUERY_RFC3986` has been available since PHP 5.4, and OpenEMR requires >=8.2. Could this `defined()` check be dropped in favor of using the constant directly?

```suggestion
        $enc_type = PHP_QUERY_RFC3986;
```

File: interface/forms/questionnaire_assessments/questionnaire_assessments.php [hunk 2]
```diff
@@ -77,7 +80,7 @@
         if (empty($form)) {
             throw new RuntimeException("Can not find encounter form.");
         }
-        CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $_SESSION['pid']);
+        CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $session->get('pid'));
```
Comment (kojiromike) [inline interface/forms/questionnaire_assessments/questionnaire_assessments.php]: `$session->get('pid')` returns `mixed` (default `null`), but `confirmFormBootstrapPatient()` declares `int $patientId`. Without strict types, PHP coerces `null` → `0` with a deprecation notice on 8.x. Since #10553 reports a `TypeError` for exactly this case, would it make sense to cast or default here?

```suggestion
        CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', (int)$session->get('pid', 0));
```

File: interface/forms/questionnaire_assessments/save.php [hunk 3]
```diff
@@ -50,7 +53,7 @@
 unset($_POST['select_item']);
 // security
 if ($isPortal && $mode == 'update' && !empty($formid)) {
-    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $_SESSION['pid']);
+    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $session->get('pid'));
```
Comment (kojiromike) [inline interface/forms/questionnaire_assessments/save.php]: Same `mixed` → `int` concern as in `questionnaire_assessments.php`. Should this also cast to int?

```suggestion
    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', (int)$session->get('pid', 0));
```

File: interface/forms/questionnaire_assessments/save.php [hunk 4]
```diff
@@ -114,7 +117,7 @@
     $formid = $newid;
 } elseif (!empty($formid)) {
     // just to be sure
-    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $_SESSION['pid']);
+    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', $session->get('pid'));
```
Comment (kojiromike) [inline interface/forms/questionnaire_assessments/save.php]: And here as well — third call site with the same pattern.

```suggestion
    CoreFormToPortalUtility::confirmFormBootstrapPatient($isPortal, $formid, 'questionnaire_assessments', (int)$session->get('pid', 0));
```

**Comment by sjpadgett** [comment]
@rollingventures Hi Chris if you could help me test more portal or take a look see at audit Print I'd be grateful.
Just go to portal Clinical Document, select a template, edit and Submit.
Then from Misc Portal Dashboard audit, select doc in table and try Print at top left.

**Comment by adunsulag** [comment]
@sjpadgett I attempted to do the audit print and it doesn't appear to be working for me.  I'll see if I can dig into it.

**Comment by adunsulag** [comment]
@sjpadgett appears to be a mismatch on the CSRF generation and CSRF verification for the audit piece. Still tracing further.

**Comment by sjpadgett** [comment]
@adunsulag I found same issue with CSRF in one of my fixes. Prob need to do a search for more in of the same.

**Comment by sjpadgett** [comment]
this is done will merge when can
