### PR TITLE
fix: ccdaservice needed bump libxmljs2:0.33.0

### LINKED ISSUE #7131: bug: ccdaservice doesn't start in flex:3-19 with node20
```
Failed to connect to ccdaservice. Verify your environment is setup correctly by following the instructions in the ccdaservice`s Readme file

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7131

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
tenor99

**Review by sjpadgett — COMMENTED** [review]
Hold up on this until I can test on windows. I need to see if a compiled version for windows is available and works. To have to bump this library most likely came from a deprecated function and though bumping version may allow compiling doesn't mean the functionality still works.

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php [hunk 1]
```diff
@@ -63,7 +63,7 @@ public function socket_get($data)
                     exec($cmd . " > /dev/null &");
                 }
                 sleep(2); // give cpu a rest
-                $result = socket_connect($socket, "127.0.0.1", "6661");
+                $result = socket_connect($socket, "localhost", "6661");
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php:66]: Why? Did you have issue using the address 127.0.0.1? Generally it's a better idea to use this IP address because localhost is not guaranteed to resolve to 127.0.0.1 and is a loopback and has to be looked up as any other domain/DNS.
The only issue I can think of using 127.0.0.1 is firewall. localhost is not passed through network card and firewall however all firewalls i've seen 127.0.0.1 and 0.0.0.0 are automatic.

QRDA service manager and other places using node is using 127.0.0.1 for socket including the ccda service which listens to 127.0.0.1. Using localhost makes me feel nervous and 127.0.0.1 has always been used since I put node into openemr.

If this proves to be an issue and localhost is found to be a better way to go then we need to refactor everywhere 127.0.0.1 is used.

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php [hunk 2]
```diff
@@ -49,7 +49,7 @@ public function socket_get($data)
                         error_log("Failed to close pipehandle for ccdaservice");
                     }
                 } else {
-                    $command = 'nodejs';
+                    $command = 'node';
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceDocumentRequestor.php:52]: Are we sure that people installing on linux with apt that the apt package doesn't still assign node to nodejs alias?
Newer snap doesn't. Making 'node' the primary check is fine but to be safe we still need to check for nodejs. For windows this isn't an issue as it always used 'node'.

File: ccdaservice/README.md [hunk 3]
```diff
@@ -38,7 +38,7 @@ Navigate to: openemr/ccdaservice and run the following from an elevated PowerShe
 - `npm install --global --omit=dev windows-build-tools` (Recommended) Though compiling libxmljs is no longer required, if for some reason your environment doesn't have download  compiled libxmljs2 binary available then npm will try to compile.
 - `npm install --omit=dev`
 ### Use
-* CCDA service must be enabled in OpenEMR's menu Globals->Connectors.
+* CCDA service must be enabled in OpenEMR's menu Admin->Config->Connectors->Enable C-CDA Service.
 * This service will automatically start on demand when required by OpenEMR.
```
Comment (sjpadgett) [inline ccdaservice/README.md:42]: Can you change the upgrade instruction for update/upgrading using npm install followed by npm ci to stress the importance of following that workflow. Also add that it is necessary to kill all node processes or at least the ones using port 6660,6661 and 6662.
It may be worthwhile to add scripts to auto kill node before install or provide a batch/bat.
I'd prefer changing back to 127.0.0.1 as I know that to be working since start of the service where localhost could dig up some unexpected issues. Although docker and proxies probably need research for what is recommended.

You can change that the service has be tested on 20.1 and v18 for new libxmljs2 version. Thanks

**Review by sjpadgett — APPROVED** [review]
Thanks for doing this! I don't see any immediate issues generating ccda document but I haven't tested validator or QRDA. I may later today but have something else pending to work on.

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php [hunk 4]
```diff
@@ -1099,8 +1099,8 @@ public function getAllergies($pid)
                 <startdate>" . xmlEscape($row['begdate'] ? preg_replace('/-/', '', $row['begdate']) : "00000000") . "</startdate>
                 <enddate>" . xmlEscape($row['enddate'] ? preg_replace('/-/', '', $row['enddate']) : "00000000") . "</enddate>
                 <reaction_text>" . xmlEscape($reaction_text ? Listener::z_xlt($reaction_text) : "") . "</reaction_text>
-                <reaction_code>" . xmlEscape($reaction_code[1] ?: '') . "</reaction_code>
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php:1102]: I'm curious, did parser complain about the short hand if reation_text was undefined or null? The important thing is that null isn't inserted into string for render. What you have is fine but was curious about warning being issued.

**Review by sjpadgett — APPROVED** [review]
Not sure if you're waiting for me to merge. This looks good to me where I've tested the package lib change to 0.33.0 and found as long as node v19,16 isn't used and user follows the upgrade instructions but not the class changes,  this change updates very well so thanks for this effort.

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php (hunk 4 above)
Comment (stephenwaite) [reply interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php:1102]: it's that php8 warning 
Screenshot from 2024-01-01 13-34-02

happy new year @sjpadgett :partying_face:

Comment (sjpadgett) [reply interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php:1102]: Thanks, same to you!

**Comment by bradymiller** [comment]
2DV-2
