### PR TITLE
fix #5849, handle all zeroes from old form_vitals date field; display date at top of table

### LINKED ISSUE #5849: form_vitals vestigial '0000-00-00 00:00:00' datetimes
### Describe the bug
Screenshot from 2022-10-16 18-07-55

### To Reproduce
use an openemr demo with data
edit someone's 2014-02-01 vitals form:

1. Add a '....'

### Expected behavior
Screenshot from 2022-10-16 18-18-31

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5849

### CODE REVIEW

File: src/Common/Twig/TwigExtension.php [hunk 1]
```diff
@@ -282,7 +282,11 @@ function ($string) {
             new TwigFilter(
                 'dateToTime',
                 function ($str) {
-                    return strtotime($str);
+                    // when there's zeros in the form_vitals entry, it's a date of "00000000000000"
+                    if ($str !== "00000000000000") {
```
Comment (stephenwaite) [inline src/Common/Twig/TwigExtension.php:286]: wondering if instead of handling it like this to add a new function to `SQLUpgradeService.php` that could change these dates to `null`

Comment (sjpadgett) [reply src/Common/Twig/TwigExtension.php:286]: All dates should default to null. Never anything but null. Also if a date datatype is stored as an empty string "" then table date will result in the weird 000000 stuff.

Brady caught most of this when he and a student changed all the date data times in queries.

Comment (sjpadgett) [reply src/Common/Twig/TwigExtension.php:286]: @stephenwaite
You prob should test the $str arg first
`if (($str = strtotime($str)) === false) return  strtotime('now') else return strtotime($str)`

or something like that.

Comment (stephenwaite) [reply src/Common/Twig/TwigExtension.php:286]: I think this is a different situation where the table was already defined with date `null` but data was being inserted with `0000-00-00`.

Comment (stephenwaite) [reply src/Common/Twig/TwigExtension.php:286]: oh, I see, you said that above, thanks @sjpadgett 

> Also if a date datatype is stored as an empty string "" then table date will result in the weird 000000 stuff.

Comment (sjpadgett) [reply src/Common/Twig/TwigExtension.php]: you're welcome. any invalid dates in strtotime will pass a false to table and thus 000000000 that's why it's best to validate false to null when stored. hope okay for me to ramble but this gave me a heck of a time in QRDA and CCDA

Comment (stephenwaite) [reply src/Common/Twig/TwigExtension.php]: I'm thinking we should have a function in the sql upgrade that will convert the date to the date of the encounter if it's zeroes.

Comment (sjpadgett) [reply src/Common/Twig/TwigExtension.php]: Good idea. Might be idea to scan all our important tables and fix dates.
If you need help, let me know and maybe the two of us can come up with something clever. Well at least in our minds!:)

File: src/Common/Twig/TwigExtension.php [hunk 2]
```diff
@@ -282,7 +282,12 @@ function ($string) {
             new TwigFilter(
                 'dateToTime',
                 function ($str) {
-                    return strtotime($str);
+                    // handle vestigial dates of 0000-00-00 00:00:00
+                    if ((strtotime($str)) <= 0) {
+                        return strtotime('now');
```
Comment (bradymiller) [inline src/Common/Twig/TwigExtension.php:287]: will this still be needed with your vitals upgrade database fix? (especially considering your upgrade database fix will give an accurate date/time where this will just give the current date/time)
(If we expect this to happen in other places, then prob best to fix where it's happening like did in vitals.)

Comment (stephenwaite) [reply src/Common/Twig/TwigExtension.php:287]: yeah, was wondering about that, okay, will revert this

**Review by bradymiller — APPROVED** [review]
