### PR TITLE
Reindex, Remove scopes, Add encounter forms

### LINKED ISSUE #8354: Track events API event save error
### Describe the bug
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.545776-04:00] OpenEMR.DEBUG: dispatch.php authenticating user [] []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.554976-04:00] OpenEMR.DEBUG: dispatch.php valid role and user has access to api/fhir resource {"resource":"/api/patient"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.555686-04:00] OpenEMR.DEBUG: dispatch.php request setup for user role {"authUserID":"1","authUser":"Administrator"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.558449-04:00] OpenEMR.DEBUG: HttpRestRouteHandler::dispatch() start request {"resource":"","method":"GET","user":"","role":"users","client":"cOKirYwlRehm34G0yDe3ODTT_LoZitbimiY7bNCEGaU","apiType":"oemr","route":"/api/patient","queryParams":[]} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.559403-04:00] OpenEMR.DEBUG: HttpRestParsedRoute->__construct() matched {"routePath":"GET /api/patient","requestPath":"/api/patient","method":"GET","routeParams":[],"resource":"patient","operation":""} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.559997-04:00] OpenEMR.DEBUG: HttpRestRouteHandler->dispatch() dispatching route {"route":"GET /api/patient"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.592071-04:00] OpenEMR.DEBUG: RestControllerHelper::handleFhirProcessingResult() Records found {"count":"4"} []
[13-May-2025 20:16:03 America/New_York] SQL Error with statement:query failed: INSERT INTO track_events (event_type, event_label, event_url, event_target, first_event, last_event, label_count)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON DUPLICATE KEY UPDATE 
              event_url    = ?,
              event_target = ?,
              last_event   = ?,
              label_count  = label_count + 1--Duplicate entry &#039;OEMR-GET /api/patient-[&quot;openid&quot;,&quot;offline_access&quot;,&quot;api:oemr&quot;,&quot;...&#039; for key &#039;unique_event_label&#039;==&gt;C:\xampp\htdocs\openemr\src\Telemetry\TelemetryRepository.php at 46:sqlStatementNoLog

### To Reproduce
Do an API endpoint request for FHIR or Standard.

1. Add a '....'

### Client configuration

- Browser: My new API Explorer
- OpenEMR version: 7.0.4 dev
- Operating system: windows

### PR DESCRIPTION
**Pull request by sjpadgett**
add user role in place of scopes for api tracking

Fixes #8354

### CODE REVIEW

**Comment by sjpadgett** [comment]
@claimrevolution Nice job on results!
Though I have only look at one result it shows everywhere we'd expect.
Please ask DORN about why compendium doesn't have AOE.

Has DORN provided a turn up/cert testing spec so we can get on with troubleshooting that.
I am so relieved that resulting appears to be working so well Brad, good job!

image

**Comment by sjpadgett** [comment]
@bradymiller SN and I decided to forego the scopes and track context/role.

Working well and once approved I'll redo patch 4. New log
image

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 1]
```diff
@@ -160,6 +160,6 @@ ALTER TABLE `product_registration` ADD `last_ask_version` TINYTEXT;
 ALTER TABLE `product_registration` ADD `options` TEXT COMMENT 'JSON array of scope options';
 #EndIf
 
-#IfNotIndex track_events unique_event_label_url
-ALTER TABLE `track_events` DROP INDEX `unique_event_label`, ADD UNIQUE `unique_event_label_url` (`event_label`, `event_url`(255));
+#IfNotIndex track_events unique_event_label_target
+ALTER TABLE `track_events` DROP INDEX `unique_event_label_url`, ADD UNIQUE `unique_event_label_target` (`event_label`, `event_url`(255), `event_target`(255));
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql:164]: To avoid issues with lingering indexes, would do following:
```
#IfIndex track_events unique_event_label
ALTER TABLE `track_events` DROP INDEX `unique_event_label`;
#EndIf

#IfIndex track_events unique_event_label_url
ALTER TABLE `track_events` DROP INDEX `unique_event_label_url`;
#EndIf

#IfNotIndex track_events unique_event_label_target
ALTER TABLE `track_events` ADD UNIQUE `unique_event_label_target` (`event_label`, `event_url`(255), `event_target`(255));
#EndIf
```

File: sql/database.sql [hunk 2]
```diff
@@ -13744,5 +13744,5 @@ CREATE TABLE `track_events` (
     `last_event`     DATETIME NULL,
     `label_count`    INT UNSIGNED NOT NULL DEFAULT 1,
     PRIMARY KEY (`id`),
-    UNIQUE KEY `unique_event_label_url` (`event_label`, `event_url`(255))
+    UNIQUE KEY `unique_event_label_target` (`event_label`, `event_url`(255))
```
Comment (bradymiller) [inline sql/database.sql:13747]:
```
UNIQUE KEY `unique_event_label_target` (`event_label`, `event_url`(255), `event_target`(255))
```

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
Brought in rel-703 for patch 7.0.3.4: #8361
