### PR TITLE
bug fixes password expired global

### LINKED ISSUE #7067: Login Fails after upgrade
### Describe the bug
- Even though user has a valid password/username user is unable to login to system. In this case the reason is because the password global password_expiration_days is set to blank/empty string.
- Legacy Logo placement global causes twig template not found. This is because the previous versions used screen location whereas v7.0.2 uses twig template path and name.
### Expected behavior

Treat blank as 0 is source code.
Reset position of logo (left/right/center) to correct template path on database upgrade 

### Client configuration

- Browser: N/A
- OpenEMR version: 7.0.2
- Operating system: all

### PR DESCRIPTION
**Pull request by sjpadgett**
Fixes #7067 

#### Short description of what this resolves:
 include in 7.0.2 patch 1
- wrap login twig loader in try/catch so user is notified
- ignore ($GLOBALS['password_expiration_days'] if is set to blank/empty string in password auth validation.
- report password expired to error log as a notice.

### CODE REVIEW

File: src/Common/Auth/AuthUtils.php [hunk 1]
```diff
@@ -106,6 +106,11 @@ public function __construct($mode = '')
                 privStatement("UPDATE `globals` SET `gl_value` = ? WHERE `gl_name` = 'hidden_auth_dummy_hash'", [$this->dummyHash]);
             }
         }
+        if ($GLOBALS['password_expiration_days'] === '') {
```
Comment (bradymiller) [inline src/Common/Auth/AuthUtils.php:109]: like the premise here (set it to 0 when it is blank).
To ensure security (in case this class is ever loaded with globals not correctly loaded (maybe in a bad module or something like that where it would revert a openemr instance to a less secure setting; ie. change the password expiration setting to a set value to 0) would consider something like this:
```
        if ($GLOBALS['password_expiration_days'] === '') {
            $sqlQuery = sqlQuery("SELECT 'gl_value' FROM `globals` WHERE `gl_name` = 'password_expiration_days'");
            if ($sqlQuery['gl_value'] === '') {
                $GLOBALS['password_expiration_days'] = 0;
                sqlQuery("UPDATE `globals` SET `gl_value` = '0' WHERE `globals`.`gl_name` = 'password_expiration_days' AND `globals`.`gl_index` = '0'");
                error_log("Blank global password_expiration_days updated to 0");
            } else {
                error_log("OpenEMR ERROR: global password_expiration_days was not defined");
                die();            
        }
```
