### PR TITLE
Fix sql error track events

### LINKED ISSUE #8354: Track events API event save error
### Describe the bug
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.545776-04:00] OpenEMR.DEBUG: dispatch.php authenticating user [] []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.554976-04:00] OpenEMR.DEBUG: dispatch.php valid role and user has access to api/fhir resource {"resource":"/api/patient"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.555686-04:00] OpenEMR.DEBUG: dispatch.php request setup for user role {"authUserID":"1","authUser":"Administrator"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.558449-04:00] OpenEMR.DEBUG: HttpRestRouteHandler::dispatch() start request {"resource":"","method":"GET","user":"","role":"users","client":"cOKirYwlRehm34G0yDe3ODTT_LoZitbimiY7bNCEGaU","apiType":"oemr","route":"/api/patient","queryParams":[]} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.559403-04:00] OpenEMR.DEBUG: HttpRestParsedRoute->__construct() matched {"routePath":"GET /api/patient","requestPath":"/api/patient","method":"GET","routeParams":[],"resource":"patient","operation":""} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.559997-04:00] OpenEMR.DEBUG: HttpRestRouteHandler->dispatch() dispatching route {"route":"GET /api/patient"} []
[13-May-2025 20:16:03 America/New_York] [2025-05-13T20:16:03.592071-04:00] OpenEMR.DEBUG: RestControllerHelper::handleFhirProcessingResult() Records found {"count":"4"} []
[13-May-2025 20:16:03 America/New_York] SQL Error with statement:query failed: INSERT INTO track_events (event_type, event_label, event_url, event_target, first_event, last_event, label_count)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON DUPLICATE KEY UPDATE 
              event_url    = ?,
              event_target = ?,
              last_event   = ?,
              label_count  = label_count + 1--Duplicate entry &#039;OEMR-GET /api/patient-[&quot;openid&quot;,&quot;offline_access&quot;,&quot;api:oemr&quot;,&quot;...&#039; for key &#039;unique_event_label&#039;==&gt;C:\xampp\htdocs\openemr\src\Telemetry\TelemetryRepository.php at 46:sqlStatementNoLog

### To Reproduce
Do an API endpoint request for FHIR or Standard.

1. Add a '....'

### Client configuration

- Browser: My new API Explorer
- OpenEMR version: 7.0.4 dev
- Operating system: windows

### PR DESCRIPTION
**Pull request by sjpadgett**
add additional col event_url to unique key. key is now event_label, event_url

Fixes #8354 

#### Short description of what this resolves:
sql duplicate errors.

### CODE REVIEW

**Review by stephenwaite — APPROVED** [review]

**Comment by sjpadgett** [comment]
@bradymiller just go ahead and merge if you don't have questions. I put up a PR to put these changes in patch 4.

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Just making sure your api telemetry code is same as master (looks like your eventLabel may be different from abvoe error message. Either way though, still need to include the eventUrl in the key for the below master code to work):
```
// Report to Telemetry
// Be nice to find a centralized place to catch failed requests.
try {
    (new TelemetryService())->trackApiRequestEvent([
        'eventType' => 'API',
        'eventLabel' => strtoupper($_SESSION['api'] ?? 'UNKNOWN'),
        'eventUrl' => $restRequest->getRequestMethod() . ' ' . $resource,
        'eventTarget' => json_encode($GLOBALS['oauth_scopes'] ?? []),
    ]);
    exit;
} catch (\Exception $e) {
    $logger->error("dispatch.php telemetry error", ['exception' => $e]);
}
```

**Comment by sjpadgett** [comment]
@bradymiller Nothing in code has changed. The error codes were based on a unique index of label, url and target. I had forgotten to put this index in my last PR after adding API event but was in my dev machine. So the current source where unique index was only the label, api would still break. 
In the end the three col index I originally designed that I forgot to commit was working well until I hit a situation where indexing on the target(scopes) with a standard api endpoint caused the error. 
I never did figure out why MariaDB didn't like the query as it should have worked.
Concerning my source compared to master, I merged master with my system to be sure.
I didn't realize my table structure was different until after I opened issue and is why the error is confusing.
I've been testing by hitting standard, fhir in both public and confidential. I post screenshot before I merge.

**Comment by bradymiller** [comment]
database screenshot beautiful!

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 1]
```diff
@@ -159,3 +159,7 @@ ALTER TABLE `product_registration` ADD `last_ask_version` TINYTEXT;
 #IfMissingColumn product_registration options
 ALTER TABLE `product_registration` ADD `options` TEXT COMMENT 'JSON array of scope options';
 #EndIf
+
+#IfTable track_events
+ALTER TABLE `track_events` DROP INDEX `unique_event_label`, ADD UNIQUE `unique_event_label` (`event_label`, `event_url`(255));
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql:164]: recommend renaming the index on change and instead checking the index via #IfNotIndex
(this way the index won't keep getting reset when run upgrade script more than once)

Comment (sjpadgett) [reply sql/7_0_3-to-7_0_4_upgrade.sql:164]: how #IfNotIndex track_events event_url won't work

Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql:164]: Would try:
```
#IfNotIndex track_events unique_event_label_url
ALTER TABLE `track_events` DROP INDEX `unique_event_label`, ADD UNIQUE `unique_event_label_url` (`event_label`, `event_url`(255));
#EndIf
```

Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql:164]: fyi, then would need to rename the key in database.sql to unique_event_label_url

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
Looks good and upgrade testing well (both in setting of whether the new index exists or does not exist).
Bringing in :)

**Comment by sjpadgett** [comment]
> won't the API scope stuff only be correctly recorded for the last hit on the api endpoint?

Yep and this is why I tried including target in key however I then got the duplicate key error. Best guess is because are using a TEXT data type which is a no no unless a char limit is placed on key. I think when this limit was exceeded it is what caused the issue.
My problem is I am really stingy concerning large tables especially when speed is a factor. I was trying to keep the table small and easier to manage.
I don't know how important tracking scopes will turn out to be where the resource is the more important.

I leave up to you guys @adunsulag I can remove the keys altogether and consolidate the reporting before sending off. i.e. emulate what keys are doing by counting.

**Comment by bradymiller** [comment]
Brought in rel-703 for patch 7.0.3.4: #8361
