### PR TITLE
sql error and php8 Eye form warnings resolved

### LINKED ISSUE #5031: sql typo in advance directives and php8 probs in eye form
### Describe the bug

write concise description of what the bug is.
[sql error](https://community.open-emr.org/t/6-1-sql-query-error-advance-directives-on-mariadb/18083?u=stephenwaite)
[php8 probs eye form](https://community.open-emr.org/t/eye-form-error-v6-1-0/18078?u=stephenwaite)
### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5031

### CODE REVIEW

File: interface/forms/eye_mag/php/eye_mag_functions.php [hunk 1]
```diff
@@ -2615,42 +2628,49 @@ function show_PMSFH_report($PMSFH)
...
         }
     }
 
     foreach ($PMSFH[0]['FH'] as $key => $value) {
         if ($value['display'] == '') {
-            $total_PMSFH--;
-            $count['FH']--;
+            if (!empty($total_PMSFH)) {
+                $total_PMSFH--;
+            }            $count['FH']--;
```
Comment (bradymiller) [inline interface/forms/eye_mag/php/eye_mag_functions.php:2658]: this line looks odd, prob need a newline after the } bracket

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
nice!!

118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a
