### PR TITLE
fix(claimrev): add mailto: protocol to email links

### LINKED ISSUE #10745: ClaimRev: Malformed email links missing mailto: protocol
## Summary

The support and sales email links are missing the `mailto:` protocol, causing them to be treated as relative URLs.

## Location

`interface/modules/custom_modules/oe-module-claimrev-connect/public/index.php` lines 68-70

## Current Code

```php
<li> <?php echo xlt("Email Support"); ?>: <a href = "support@claimrev.com">support@claimrev.com</a> </li>
<li> <?php echo xlt("Email Sales"); ?>: <a href = "sales@claimrev.com">sales@claimrev.com</a> </li>
```

## Problem

Without `mailto:`, clicking the link tries to navigate to a relative URL like `/interface/modules/.../public/support@claimrev.com`, resulting in a 404 error.

## Fix

```php
<li><?php echo xlt("Email Support"); ?>: <a href="mailto:support@claimrev.com">support@claimrev.com</a></li>
<li><?php echo xlt("Email Sales"); ?>: <a href="mailto:sales@claimrev.com">sales@claimrev.com</a></li>
```

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #10745

## Summary

- Add `mailto:` protocol to email support and sales links on ClaimRev home page
- Fix malformed closing anchor tag on phone number link (`<a>` → `</a>`)

## Test plan

- [ ] Open ClaimRev module home page
- [ ] Click phone number link → should open dialer
- [ ] Click support email → should open email client with `support@claimrev.com`
- [ ] Click sales email → should open email client with `sales@claimrev.com`

## AI Disclosure

- [x] Yes, AI-assisted code was used in this PR

### CODE REVIEW

File: interface/modules/custom_modules/oe-module-claimrev-connect/public/index.php [hunk 1]
```diff
@@ -65,9 +65,9 @@
 
                 <h6><?php echo xlt("Support/Sales"); ?></h6>
                 <ul>
-                    <li> <?php echo xlt("Call"); ?>: <a href="tel:9189430020">1-918-943-0020<a>   </li>
-                    <li> <?php echo xlt("Email Support"); ?>: <a href = "support@claimrev.com">support@claimrev.com</a> </li>
-                    <li> <?php echo xlt("Email Sales"); ?>: <a href = "sales@claimrev.com">sales@claimrev.com</a> </li>
+                    <li> <?php echo xlt("Call"); ?>: <a href="tel:9189430020">1-918-943-0020</a>   </li>
+                    <li> <?php echo xlt("Email Support"); ?>: <a href="mailto:support@claimrev.com">support@claimrev.com</a> </li>
+                    <li> <?php echo xlt("Email Sales"); ?>: <a href="mailto:sales@claimrev.com">sales@claimrev.com</a> </li>
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/public/index.php]:
```suggestion
                    <li><?php echo xlt("Call"); ?>: <a href="tel:9189430020">1-918-943-0020</a></li>
                    <li><?php echo xlt("Email Support"); ?>: <a href="mailto:support@claimrev.com">support@claimrev.com</a></li>
                    <li><?php echo xlt("Email Sales"); ?>: <a href="mailto:sales@claimrev.com">sales@claimrev.com</a></li>
```
