### PR TITLE
Fix: Carry over NDC info from previous encounters in Fee Sheet

### LINKED ISSUE #8557: Fix: Carry over NDC info from previous encounters in Fee Sheet
### Describe the bug
The fee sheet's "Review" feature, which allows copying billing codes and diagnoses from previous encounters, was not copying over the National Drug Code (NDC) information (including the NDC code itself, quantity, and units) for HCPCS codes. While other procedure details were copied, the NDC-related data was lost in the process, requiring users to re-enter it manually.

### To Reproduce

1. Select Patient: Choose the desired patient.
2. Create Encounter: Initiate a new patient encounter.
3. Open Fee Sheet: Access the Fee Sheet for the current encounter.
4. Review and Copy: Click the "Review and Copy" option.
5. HCPCS Codes: 
- Previous HCPCS billing codes will be copied over.
- NDC Information: NDC (National Drug Code) information will NOT be carried over.

### Expected behavior
NDC Information: NDC (National Drug Code) information will be carried over

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by moussa854**
Modified the fee sheet's review functionality to correctly copy NDC codes, quantity, and units for HCPCS codes from previous encounters to the current one.

Changes include:
- Updated PHP classes and queries to handle ndc_info.
- Updated JavaScript view model to include ndc_info in data sent to the server.
- Ensured ndc_info is correctly passed to the procedure constructor in the AJAX handler.

Fixes #8557

#### Short description of what this resolves:
Modified the fee sheet's review functionality to correctly copy NDC codes, quantity, and units for HCPCS codes from previous encounters to the current one.

#### Changes proposed in this pull request:
Changes include:
- Updated PHP classes and queries to handle ndc_info.
- Updated JavaScript view model to include ndc_info in data sent to the server.
- Ensured ndc_info is correctly passed to the procedure constructor in the AJAX handler.

### CODE REVIEW

File: interface/forms/fee_sheet/review/fee_sheet_ajax.php [hunk 1]
```diff
@@ -95,7 +95,10 @@
             $proc->justify,
             $proc->modifiers,
             $proc->units,
-            0
+            /** ai generated code by google-labs-jules starts */
+            0, // mod_size
```
Comment (stephenwaite) [inline interface/forms/fee_sheet/review/fee_sheet_ajax.php]: hi @moussa854, thanks for the PR, might as well make this `$proc->mod_size` to fix the hard coding while we're here.

File: interface/forms/fee_sheet/review/fee_sheet_review_view_model.js [hunk 2]
```diff
@@ -31,6 +31,9 @@ function procedure(json_source) {
     retval.fee = ko.observable(json_source.fee);
     retval.modifiers = ko.observable(json_source.modifiers);
     retval.units = ko.observable(json_source.units);
```
Comment (stephenwaite) [inline interface/forms/fee_sheet/review/fee_sheet_review_view_model.js:33]: and add 
```
retval.mod_size = ko.observable(json_source.mod_size);
```
here

edit: nothing here to be added, my mistake, see below

File: interface/forms/fee_sheet/review/fee_sheet_review_view_model.js [hunk 3]
```diff
@@ -81,6 +84,9 @@ function procedure(json_source) {
         json_return.fee = this.fee();
         json_return.modifiers = this.modifiers();
         json_return.units = this.units();
```
Comment (stephenwaite) [inline interface/forms/fee_sheet/review/fee_sheet_review_view_model.js:86]: and add 
```
json_return.mod_size = this.mod_size();
```
here

**Comment by stephenwaite** [comment]
hi @moussa854, just noted a minor fix that is nice to make while you're updating the ndc info. If you can make that I think this is ready to be commited, thank you!

**Comment by moussa854** [comment]
Hi @stephenwaite ,
Thank you for looking into this. For some reason I missed the email from github. However, I made the changes that you suggested

File: interface/forms/fee_sheet/review/fee_sheet_queries.php [hunk 4]
```diff
@@ -290,7 +292,9 @@ function common_diagnoses($limit = 10)
 function fee_sheet_items($pid, $encounter, &$diagnoses, &$procedures): void
 {
     $param = [$encounter];
-    $sql = "SELECT code,code_type,code_text,fee,modifier,justify,units,ct_diag,ct_fee,ct_mod "
+    /** ai generated code by google-labs-jules starts */
+    $sql = "SELECT code,code_type,code_text,fee,modifier,justify,units,ndc_info,ct_diag,ct_fee,ct_mod "
+    /** ai generated code by google-labs-jules end */
           . " FROM billing, code_types as ct "
           . " WHERE encounter=? AND billing.activity>0 AND ct.ct_key=billing.code_type "
           . " ORDER BY id";
```
Comment (kojiromike) [inline interface/forms/fee_sheet/review/fee_sheet_queries.php]: if we replace from line 295 to 300, we can make it clear exactly what the AI did by rewriting the SQL as a now document:

```suggestion
    $sql = <<<'SQL'
        SELECT code,
               code_type,
               code_text,
               fee,
               modifier,
               justify,
               units,
               ndc_info, -- added by google-labs-jules
               ct_diag,
               ct_fee,
               ct_mod
          FROM billing,
               code_types as ct
         WHERE encounter = ?
           AND billing.activity > 0
           AND ct.ct_key = billing.code_type
      ORDER BY id
    SQL
```

Just a thought, to make the sql more legible and reviewable.
