### PR TITLE
fix(tracker): trim leading '#' from color setting in PatientTrackerService

### LINKED ISSUE #8190: bug: Flow board does not change color
### Describe the bug

The flow board should reflect the appointment status color

### To Reproduce

Open flowboard. the background is white.

### Expected behavior
Background color of each appointment should change with status color.

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.3 Demo
- Operating system: Unknown (Possible ubuntu)

### PR DESCRIPTION
**Pull request by ophthal**
Fixes #8190, #9401

#### Short description of what this resolves:
The Flow Board color problem when appointment status colors are changed. The base DB `list_option.notes` has hex values without `#` but appointment status color updates include the `#`. This caused color mismatches.

#### Changes proposed in this pull request:
- Trim leading `#` from color value in `PatientTrackerService::collectApptStatusSettings()` at the service layer, so all callers benefit

Supersedes #9461 which fixed it at the view layer.

#### Does your code include anything generated by an AI Engine? No

### CODE REVIEW

File: src/Services/PatientTrackerService.php [hunk 1]
```diff
@@ -292,6 +292,7 @@ public static function collectApptStatusSettings($option)
         }
 
         [$color_settings['color'], $color_settings['time_alert']] = explode("|", (string) $row['notes']);
+        $color_setting['color'] = ltrim($color_settings['color'],'#');
```
Comment (kojiromike) [inline src/Services/PatientTrackerService.php]:
```suggestion
        $color_settings['color'] = ltrim($color_settings['color'],'#');
```
