### PR TITLE
[SQL]: Fix #3378 fix default timestamp issue

### LINKED ISSUE #3378: Timestamp SQL Mode Issue
### Describe the bug

After changing the modes in the Installer.class.php and try running installation via GUI following error occurs:

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `amendments` ( `amendment_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Amendment ID', `amendment_date` date NOT NULL COMMENT 'Amendement request date', `amendment_by` varchar(50) NOT NULL COMMENT 'Amendment requested from', `amendment_status` varchar(50) NULL COMMENT 'Amendment status accepted/rejected/null', `pid` bigint(20) NOT NULL COMMENT 'Patient ID from patient_data', `amendment_desc` text COMMENT 'Amendment Details', `created_by` int(11) NOT NULL COMMENT 'references users.id for session owner', `modified_by` int(11) NULL COMMENT 'references users.id for session owner', `created_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'created time', `modified_time` timestamp NULL COMMENT 'modified time', PRIMARY KEY amendments_id(`amendment_id`), KEY amendment_pid(`pid`)) ENGINE = InnoDB' due to: Invalid default value for 'created_time'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `amendments_history` ( `amendment_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Amendment ID', `amendment_note` text COMMENT 'Amendment requested from', `amendment_status` VARCHAR(50) NULL COMMENT 'Amendment Request Status', `created_by` int(11) NOT NULL COMMENT 'references users.id for session owner', `created_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'created time',KEY amendment_history_id(`amendment_id`)) ENGINE = InnoDB' due to: Invalid default value for 'created_time'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `batchcom` ( `id` bigint(20) NOT NULL auto_increment, `patient_id` bigint(20) NOT NULL default '0', `sent_by` bigint(20) NOT NULL default '0', `msg_type` varchar(60) default NULL, `msg_subject` varchar(255) default NULL, `msg_text` mediumtext, `msg_date_sent` datetime NOT NULL default '0000-00-00 00:00:00', PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'msg_date_sent'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `drug_inventory` ( `inventory_id` int(11) NOT NULL auto_increment, `drug_id` int(11) NOT NULL, `lot_number` varchar(20) default NULL, `expiration` date default NULL, `manufacturer` varchar(255) default NULL, `on_hand` int(11) NOT NULL default '0', `warehouse_id` varchar(31) NOT NULL DEFAULT '', `vendor_id` bigint(20) NOT NULL DEFAULT 0, `last_notify` date NOT NULL default '0000-00-00', `destroy_date` date default NULL, `destroy_method` varchar(255) default NULL, `destroy_witness` varchar(255) default NULL, `destroy_notes` varchar(255) default NULL, PRIMARY KEY (`inventory_id`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'last_notify'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `drugs` ( `drug_id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL DEFAULT '', `ndc_number` varchar(20) NOT NULL DEFAULT '', `on_order` int(11) NOT NULL default '0', `reorder_point` float NOT NULL DEFAULT 0.0, `max_level` float NOT NULL DEFAULT 0.0, `last_notify` date NOT NULL default '0000-00-00', `reactions` text, `form` int(3) NOT NULL default '0', `size` varchar(25) NOT NULL default '', `unit` int(11) NOT NULL default '0', `route` int(11) NOT NULL default '0', `substitute` int(11) NOT NULL default '0', `related_code` varchar(255) NOT NULL DEFAULT '' COMMENT 'may reference a related codes.code', `cyp_factor` float NOT NULL DEFAULT 0 COMMENT 'quantity representing a years supply', `active` TINYINT(1) DEFAULT 1 COMMENT '0 = inactive, 1 = active', `allow_combining` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = allow filling an order from multiple lots', `allow_multiple` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 = allow multiple lots at one warehouse', `drug_code` varchar(25) NULL, `consumable` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 = will not show on the fee sheet', `dispensable` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0 = pharmacy elsewhere, 1 = dispensed here', PRIMARY KEY (`drug_id`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'last_notify'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `insurance_data` ( `id` bigint(20) NOT NULL auto_increment, `type` enum('primary','secondary','tertiary') default NULL, `provider` varchar(255) default NULL, `plan_name` varchar(255) default NULL, `policy_number` varchar(255) default NULL, `group_number` varchar(255) default NULL, `subscriber_lname` varchar(255) default NULL, `subscriber_mname` varchar(255) default NULL, `subscriber_fname` varchar(255) default NULL, `subscriber_relationship` varchar(255) default NULL, `subscriber_ss` varchar(255) default NULL, `subscriber_DOB` date default NULL, `subscriber_street` varchar(255) default NULL, `subscriber_postal_code` varchar(255) default NULL, `subscriber_city` varchar(255) default NULL, `subscriber_state` varchar(255) default NULL, `subscriber_country` varchar(255) default NULL, `subscriber_phone` varchar(255) default NULL, `subscriber_employer` varchar(255) default NULL, `subscriber_employer_street` varchar(255) default NULL, `subscriber_employer_postal_code` varchar(255) default NULL, `subscriber_employer_state` varchar(255) default NULL, `subscriber_employer_country` varchar(255) default NULL, `subscriber_employer_city` varchar(255) default NULL, `copay` varchar(255) default NULL, `date` date NOT NULL default '0000-00-00', `pid` bigint(20) NOT NULL default '0', `subscriber_sex` varchar(25) default NULL, `accept_assignment` varchar(5) NOT NULL DEFAULT 'TRUE', `policy_type` varchar(25) NOT NULL default '', PRIMARY KEY (`id`), UNIQUE KEY `pid_type_date` (`pid`,`type`,`date`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'date'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `onsite_documents` ( `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, `pid` bigint(20) UNSIGNED DEFAULT NULL, `facility` int(10) UNSIGNED DEFAULT NULL, `provider` int(10) UNSIGNED DEFAULT NULL, `encounter` int(10) UNSIGNED DEFAULT NULL, `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `doc_type` varchar(255) NOT NULL, `patient_signed_status` smallint(5) UNSIGNED NOT NULL, `patient_signed_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `authorize_signed_time` datetime DEFAULT NULL, `accept_signed_status` smallint(5) NOT NULL, `authorizing_signator` varchar(50) NOT NULL, `review_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `denial_reason` varchar(255) NOT NULL, `authorized_signature` text, `patient_signature` text, `full_document` mediumblob, `file_name` varchar(255) NOT NULL, `file_path` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'patient_signed_time'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `onsite_documents` ( `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, `pid` bigint(20) UNSIGNED DEFAULT NULL, `facility` int(10) UNSIGNED DEFAULT NULL, `provider` int(10) UNSIGNED DEFAULT NULL, `encounter` int(10) UNSIGNED DEFAULT NULL, `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, `doc_type` varchar(255) NOT NULL, `patient_signed_status` smallint(5) UNSIGNED NOT NULL, `patient_signed_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, `authorize_signed_time` datetime DEFAULT NULL, `accept_signed_status` smallint(5) NOT NULL, `authorizing_signator` varchar(50) NOT NULL, `review_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `denial_reason` varchar(255) NOT NULL, `authorized_signature` text, `patient_signature` text, `full_document` mediumblob, `file_name` varchar(255) NOT NULL, `file_path` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=1 ' due to: Invalid default value for 'review_date'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `openemr_postcalendar_events` ( `pc_eid` int(11) unsigned NOT NULL auto_increment, `pc_catid` int(11) NOT NULL default '0', `pc_multiple` int(10) unsigned NOT NULL, `pc_aid` varchar(30) default NULL, `pc_pid` varchar(11) default NULL, `pc_gid` int(11) default 0, `pc_title` varchar(150) default NULL, `pc_time` datetime default NULL, `pc_hometext` text, `pc_comments` int(11) default '0', `pc_counter` mediumint(8) unsigned default '0', `pc_topic` int(3) NOT NULL default '1', `pc_informant` varchar(20) default NULL, `pc_eventDate` date NOT NULL default '0000-00-00', `pc_endDate` date NOT NULL default '0000-00-00', `pc_duration` bigint(20) NOT NULL default '0', `pc_recurrtype` int(1) NOT NULL default '0', `pc_recurrspec` text, `pc_recurrfreq` int(3) NOT NULL default '0', `pc_startTime` time default NULL, `pc_endTime` time default NULL, `pc_alldayevent` int(1) NOT NULL default '0', `pc_location` text, `pc_conttel` varchar(50) default NULL, `pc_contname` varchar(50) default NULL, `pc_contemail` varchar(255) default NULL, `pc_website` varchar(255) default NULL, `pc_fee` varchar(50) default NULL, `pc_eventstatus` int(11) NOT NULL default '0', `pc_sharing` int(11) NOT NULL default '0', `pc_language` varchar(30) default NULL, `pc_apptstatus` varchar(15) NOT NULL default '-', `pc_prefcatid` int(11) NOT NULL default '0', `pc_facility` int(11) NOT NULL default '0' COMMENT 'facility id for this event', `pc_sendalertsms` VARCHAR(3) NOT NULL DEFAULT 'NO', `pc_sendalertemail` VARCHAR( 3 ) NOT NULL DEFAULT 'NO', `pc_billing_location` SMALLINT (6) NOT NULL DEFAULT '0', `pc_room` varchar(20) NOT NULL DEFAULT '', PRIMARY KEY (`pc_eid`), KEY `basic_event` (`pc_catid`,`pc_aid`,`pc_eventDate`,`pc_endDate`,`pc_eventstatus`,`pc_sharing`,`pc_topic`), KEY `pc_eventDate` (`pc_eventDate`)) ENGINE=InnoDB AUTO_INCREMENT=7 ' due to: Invalid default value for 'pc_eventDate'
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `openemr_postcalendar_events` ( `pc_eid` int(11) unsigned NOT NULL auto_increment, `pc_catid` int(11) NOT NULL default '0', `pc_multiple` int(10) unsigned NOT NULL, `pc_aid` varchar(30) default NULL, `pc_pid` varchar(11) default NULL, `pc_gid` int(11) default 0, `pc_title` varchar(150) default NULL, `pc_time` datetime default NULL, `pc_hometext` text, `pc_comments` int(11) default '0', `pc_counter` mediumint(8) unsigned default '0', `pc_topic` int(3) NOT NULL default '1', `pc_informant` varchar(20) default NULL, `pc_eventDate` date NOT NULL default CURRENT_DATE, `pc_endDate` date NOT NULL default '0000-00-00', `pc_duration` bigint(20) NOT NULL default '0', `pc_recurrtype` int(1) NOT NULL default '0', `pc_recurrspec` text, `pc_recurrfreq` int(3) NOT NULL default '0', `pc_startTime` time default NULL, `pc_endTime` time default NULL, `pc_alldayevent` int(1) NOT NULL default '0', `pc_location` text, `pc_conttel` varchar(50) default NULL, `pc_contname` varchar(50) default NULL, `pc_contemail` varchar(255) default NULL, `pc_website` varchar(255) default NULL, `pc_fee` varchar(50) default NULL, `pc_eventstatus` int(11) NOT NULL default '0', `pc_sharing` int(11) NOT NULL default '0', `pc_language` varchar(30) default NULL, `pc_apptstatus` varchar(15) NOT NULL default '-', `pc_prefcatid` int(11) NOT NULL default '0', `pc_facility` int(11) NOT NULL default '0' COMMENT 'facility id for this event', `pc_sendalertsms` VARCHAR(3) NOT NULL DEFAULT 'NO', `pc_sendalertemail` VARCHAR( 3 ) NOT NULL DEFAULT 'NO', `pc_billing_location` SMALLINT (6) NOT NULL DEFAULT '0', `pc_room` varchar(20) NOT NULL DEFAULT '', PRIMARY KEY (`pc_eid`), KEY `basic_event` (`pc_catid`,`pc_aid`,`pc_eventDate`,`pc_endDate`,`pc_eventstatus`,`pc_sharing`,`pc_topic`), KEY `pc_eventDate` (`pc_eventDate`)) ENGINE=InnoDB AUTO_INCREMENT=7 ' due to: Invalid default value for 'pc_endDate'
```

```sql
ERROR. unable to execute SQL: 'INSERT INTO `automatic_notification` (`notification_id`, `sms_gateway_type`, `next_app_date`, `next_app_time`, `provider_name`, `message`, `email_sender`, `email_subject`, `type`, `notification_sent_date`) VALUES (1, 'CLICKATELL', '0000-00-00', ':', 'EMR GROUP 1 .. SMS', 'Welcome to EMR GROUP 1.. SMS', '', '', 'SMS', '0000-00-00 00:00:00'),(2, '', '2007-10-02', '05:50', 'EMR GROUP', 'Welcome to EMR GROUP . Email', 'EMR Group', 'Welcome to EMR GROUP', 'Email', '2007-09-30 00:00:00')' due to: Incorrect date value: '0000-00-00' for column `openemr`.`automatic_notification`.`next_app_date` at row 1
```

```sql
ERROR. unable to execute SQL: 'INSERT INTO `automatic_notification` (`notification_id`, `sms_gateway_type`, `next_app_date`, `next_app_time`, `provider_name`, `message`, `email_sender`, `email_subject`, `type`, `notification_sent_date`) VALUES (1, 'CLICKATELL', CURRENT_DATE, ':', 'EMR GROUP 1 .. SMS', 'Welcome to EMR GROUP 1.. SMS', '', '', 'SMS', '0000-00-00 00:00:00'),(2, '', '2007-10-02', '05:50', 'EMR GROUP', 'Welcome to EMR GROUP . Email', 'EMR Group', 'Welcome to EMR GROUP', 'Email', '2007-09-30 00:00:00')' due to: Incorrect datetime value: '0000-00-00 00:00:00' for column `openemr`.`automatic_notification`.`notification_sent_date` at row 1
```

```sql
ERROR. unable to execute SQL: 'CREATE TABLE `medex_recalls` ( `r_ID` int(11) NOT NULL AUTO_INCREMENT, `r_PRACTID` int(11) NOT NULL, `r_pid` int(11) NOT NULL COMMENT 'PatientID from pat_data', `r_eventDate` date NOT NULL COMMENT 'Date of Appt or Recall', `r_facility` int(11) NOT NULL, `r_provider` int(11) NOT NULL, `r_reason` varchar(255) DEFAULT NULL, `r_created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`r_ID`), UNIQUE KEY `r_PRACTID` (`r_PRACTID`,`r_pid`)) ENGINE=InnoDB' due to: Invalid default value for 'r_created'
```

### To Reproduce

1. Change SQL mode in the `Installer.class.php`
2. Run GUI installation (https://github.com/openemr/openemr/issues/3207)
3. See error

### Expected behavior
1. Runs without any error

### Client configuration

- Browser: Chrome
- Operating system: Mac OS X

### PR DESCRIPTION
**Pull request by ShubhamBansal1997**
Fixes #3378

#### Short description of what this resolves:
We removed the wrong default timestamp and instead of that made the `created_time` column of the table `amendments` nullable.

#### Changes proposed in this pull request:

- Changed in the database schema file (sql/database.sql)
- Added the upgrade script
-

### CODE REVIEW

File: sql/5_0_2-to-5_0_3_upgrade.sql [hunk 1]
```diff
@@ -439,3 +439,7 @@ ALTER TABLE `form_eye_mag_prefs` MODIFY `ordering` smallint(6) DEFAULT NULL;
 #IfNotColumnType codes code_text_short varchar(255)
 ALTER TABLE `codes` MODIFY `code_text_short` varchar(255) NOT NULL default '';
 #EndIf
+
+#IfNotColumnType amendments created_time timestamp
```
Comment (bradymiller) [inline sql/5_0_2-to-5_0_3_upgrade.sql:443]: I am willing to bet this won't work, since it is timestamp already. What if you try:
```
#IfNotColumnType amendments created_time timestamp NULL
```
(we will need to test this)

Comment (stephenwaite) [reply sql/5_0_2-to-5_0_3_upgrade.sql:443]: :game_die:

Comment (ShubhamBansal1997) [reply sql/5_0_2-to-5_0_3_upgrade.sql]: Updated!!

File: sql/5_0_2-to-5_0_3_upgrade.sql [hunk 2]
```diff
@@ -439,3 +439,7 @@ ALTER TABLE `form_eye_mag_prefs` MODIFY `ordering` smallint(6) DEFAULT NULL;
 #IfNotColumnType codes code_text_short varchar(255)
 ALTER TABLE `codes` MODIFY `code_text_short` varchar(255) NOT NULL default '';
 #EndIf
+
+#IfNotColumnType amendments created_time timestamp NULL
+ALTER TABLE `amendments` MODIFY `created_time` timestamp NULL COMMENT 'created time';
```
Comment (bradymiller) [inline sql/5_0_2-to-5_0_3_upgrade.sql:444]: hi @ShubhamBansal1997 ,
sadly, on testing, this always gets run (even when the column has already been changed to timestamp NULL), which makes sense since Type and Default are stored in separate columns:
image

To support this, we get to make another "crazy" function called `#IfNotColumnTypeDefault` to support the above call. Will need to add a block of code in the long elseif statement in sql_upgrade_fx.php that will look like this:
https://github.com/openemr/openemr/blob/master/library/sql_upgrade_fx.php#L665-L675

And then you can duplicate the following function with name `columnHasTypeDefault` to have al 4th parameter which carries/checks the default value:
https://github.com/openemr/openemr/blob/master/library/sql_upgrade_fx.php#L70-L78

**Comment by ShubhamBansal1997** [comment]
@bradymiller Updated the PR as mentioned. Please review again

**Comment by ShubhamBansal1997** [comment]
@bradymiller What's blocking on this? anything to work on?

File: library/sql_upgrade_fx.php [hunk 3]
```diff
@@ -77,6 +77,23 @@ function columnHasType($tblname, $colname, $coltype)
...
+ */
+function columnHasDefault($tblname, $colname)
+{
+    $row = sqlQuery("SHOW COLUMNS FROM $tblname LIKE '$colname'");
+    if (empty($row)) {
+        return true;
+    }
+
+    return $row['Default'] ? false: true;
+}
```
Comment (bradymiller) [inline library/sql_upgrade_fx.php:95]: Should look something like this:
```
/**
* Check if a Sql column has a certain type and a certain default value.
*
* @param  string  $tblname  Sql Table Name
* @param  string  $colname  Sql Column Name
* @param  string  $coltype  Sql Column Type
* @param  string  $coldefault  Sql Column Default
* @return boolean           returns true if the sql column is of the specified type
*/
function columnHasTypeDefault($tblname, $colname, $coltype, $coldefault)
{
    $row = sqlQuery("SHOW COLUMNS FROM $tblname LIKE '$colname'");
    if (empty($row)) {
        return true;
    }

    return ((strcasecmp($row['Type'], $coltype) == 0) && (strcasecmp($row['Default'], $coldefault) == 0));
}
```

File: library/sql_upgrade_fx.php [hunk 4]
```diff
@@ -526,6 +543,10 @@ function convertLayoutProperties()
 *   arguments: table_name colname value
 *   behavior:  If the table table_name does not have a column colname with a data type equal to value, then the block will be executed
 *
+* #IfNotColumnTypeDefault
+*   arguments: table_name colname
+*   behavior:  If the table table_name does not have a column colname without a default value, then the block will be executed
```
Comment (bradymiller) [inline library/sql_upgrade_fx.php:548]: Should look something like this:
```
* #IfNotColumnTypeDefault
*   arguments: table_name colname value value2
*   behavior:  If the table table_name does not have a column colname with a data type equal to value and a default equal to value2, then the block will be executed
*
```

File: sql/5_0_2-to-5_0_3_upgrade.sql [hunk 5]
```diff
@@ -21,6 +21,10 @@
 --    arguments: table_name colname value
 --    behavior:  If the table table_name does not have a column colname with a data type equal to value, then the block will be executed
 
+--  #IfNotColumnTypeDefault
+--    arguments: table_name colname
+--    behavior:  If the table table_name does not have a column colname without a default value, then the block will be executed
+
```
Comment (bradymiller) [inline sql/5_0_2-to-5_0_3_upgrade.sql:27]: Should look something like this:
```
* #IfNotColumnTypeDefault
*   arguments: table_name colname value value2
*   behavior:  If the table table_name does not have a column colname with a data type equal to value and a default equal to value2, then the block will be executed
```

File: library/sql_upgrade_fx.php [hunk 6]
```diff
@@ -659,6 +680,17 @@ function upgradeFromSqlFile($filename, $path = '')
...
+            if ($skipping) {
+                echo "<font color='green'>Skipping section $line</font><br />\n";
+            }
+        } elseif (preg_match('/^#IfNotColumnTypeDefault\s+(\S+)\s+(\S+)\s+(.+)/', $line, $matches)) {
+            if (tableExists($matches[1])) {
+                $skipping = columnHasDefault($matches[1], $matches[2]);
+            } else {
+                // If no such table then the column type is deemed not "missing".
+                $skipping = true;
+            }
```
Comment (bradymiller) [inline library/sql_upgrade_fx.php:692]: should look something like:
```
        } elseif (preg_match('/^#IfNotColumnTypeDefault\s+(\S+)\s+(\S+)\s+(\S+)\s+(.+)/', $line, $matches)) {
            if (tableExists($matches[1])) {
                $skipping = columnHasTypeDefault($matches[1], $matches[2], $matches[3], $matches[4]);
            } else {
                // If no such table then the column type is deemed not "missing".
                $skipping = true;
            }
```

**Comment by bradymiller** [comment]
hi @ShubhamBansal1997 , Just reviewed and left comments. Guessing will be ready for testing on next revision. thanks! -brady

**Comment by ShubhamBansal1997** [comment]
@bradymiller updated as per the comments, feel free to do testing

File: library/sql_upgrade_fx.php (hunk 3 above)
Comment (ShubhamBansal1997) [reply library/sql_upgrade_fx.php:97]: updated!

File: sql/5_0_2-to-5_0_3_upgrade.sql (hunk 5 above)
Comment (ShubhamBansal1997) [reply sql/5_0_2-to-5_0_3_upgrade.sql:27]: updated

File: library/sql_upgrade_fx.php (hunk 6 above)
Comment (ShubhamBansal1997) [reply library/sql_upgrade_fx.php:694]: updated

File: library/sql_upgrade_fx.php [hunk 7]
```diff
@@ -77,6 +77,25 @@ function columnHasType($tblname, $colname, $coltype)
...
+ */
+function columnHasTypeDefault($tblname, $colname, $coltype, $coldefault)
+{
+    $row = sqlQuery("SHOW COLUMNS FROM $tblname LIKE '$colname'");
+    if (empty($row)) {
+        return true;
+    }
+
+    return ((strcasecmp($row['Type'], $coltype) == 0) && (strcasecmp($row['Default'], $coldefault) == 0));
+}
```
Comment (bradymiller) [inline library/sql_upgrade_fx.php:97]: Not yet working, but I think I know why. The NULL is throwing things off. Will put some more thought into this tomorrow.

**Comment by mdsupport** [comment]
@ShubhamBansal1997 Since you are trying to fix _all_ invalid defaults, it is better to use adodb data dictionary methods to detect offending columns and submit adodb generated alter statements in an array of sql statements as a single transaction.  That ensures it is all or nothing fix.

**Comment by bradymiller** [comment]
hi @ShubhamBansal1997 , This got a bit complicated. Just brought in a commit (check it out to see what I did) that got this working for all types of defaults (NULL, blank, or a actual value). It will be a very useful functionality to have as we fix other places in the database. Testing well, so will bring this into codebase after I get it to pass travis.

hi @mdsupport , Looks like the data dictionary methods is more for supporting basic functions across different database types: http://adodb.org/dokuwiki/doku.php?id=v5:dictionary:dictionary_index

**Comment by bradymiller** [comment]
Passes travis, so bringing this in. Thanks for the improvements @ShubhamBansal1997 ! -brady

**Comment by mdsupport** [comment]
From that same link here is the generic iterator using objects  ...

```
foreach ($db2->metaTables('TABLES') as $tblix => $tblname) {
    foreach ($db2->MetaColumns($tblname) as $colix => $oCol) {
        if (
            (($oCol->type == 'datetime') || ($oCol->type == 'timestamp')) &&
            ($oCol->has_default) &&
            (!($oCol->default_value == 'CURRENT_TIMESTAMP'))
            ) {
            ...

```
