### PR TITLE
Fixed-alignment

### LINKED ISSUE #3233: UI of Procedure Statistics Report is not up-to the mark
### Describe the bug
UI of this page is not according to standards. 

### To Reproduce
Go to Reports -> Procedures -> Statistics 

### Expected behavior
Nice alignment of form.

### Actual behavior
Screenshot (101)

PS: I want to work on this issue.

### PR DESCRIPTION
**Pull request by adad20**
Fixes #3233

#### Short description of what this resolves:
Fixed the allignment of the form fields.

Screenshot (107)

### CODE REVIEW

File: interface/orders/procedure_stats.php [hunk 1]
```diff
@@ -331,119 +331,117 @@ function process_result_code($row)
...
+                echo " />" . text($value) . " &nbsp;";
+            }
+            ?>
+        </div>
+    </div>
+</div>
+<br>
+<div class="col-4 col-md-4">
+    <div class="col">
+         <input type='submit' class='btn btn-primary' name='form_submit' value='<?php echo xla('Submit'); ?>' title='<?php echo xla('Click to generate the report'); ?>' />
```
Comment (stu01509) [inline interface/orders/procedure_stats.php]: submit button need add font awesome icon.

Comment (adad20) [reply interface/orders/procedure_stats.php]: Okay

Comment (stu01509) [reply interface/orders/procedure_stats.php]: Hi @adad20 

Check out FontAwesome.scss this file, This file contains OpenEMR common icons. Use `btn-save` will suitable in this button.

File: interface/orders/procedure_stats.php [hunk 2]
```diff
@@ -331,119 +331,117 @@ function process_result_code($row)
...
+                }
 
-        echo "    <option value='" . attr($key) . "'";
-        if (is_array($form_show) && in_array($key, $form_show)) {
-            echo " selected";
-        }
+                echo ">" . text($value) . "</option>\n";
+            }
+            ?>
+        </select>
```
Comment (stu01509) [inline interface/orders/procedure_stats.php]: Indent need to adjust.

File: interface/orders/procedure_stats.php [hunk 3]
```diff
@@ -331,119 +331,117 @@ function process_result_code($row)
...
+            <?php dropdown_facility($form_facility, 'form_facility', false); ?>
+        </div>
+        <div class="col">
+            <?php echo xlt('From'); ?>
+            <input type='text' class='form-control datepicker' name='form_from_date' id='form_from_date' size='10' value='<?php echo attr(oeFormatShortDate($from_date)); ?>' />
+            </div>
+            <div class="col">
+            <?php echo xlt('To{{Range}}'); ?>
+        <input type='text' class='form-control datepicker' name='form_to_date' id='form_to_date' size='10' value='<?php echo attr(oeFormatShortDate($to_date)); ?>' />
+        </div>
```
Comment (stu01509) [inline interface/orders/procedure_stats.php]: Indent need to adjust.

File: interface/orders/procedure_stats.php (hunk 1 above)
Comment (adad20) [reply interface/orders/procedure_stats.php]: hi @stu01509 Then should I add text too in the button or the icon only?

**Comment by bradymiller** [comment]
Note that there appear to be 4 different groupings here:
1. Rows (one selector)
2. Columns (one selector)
3. To (toggle)
4. Filters (4 selectors)

Drop the Filters label and place the  Facility - From - To item at top
Then place Rows - Sex next row
Then place Columns at next row
Then place To at last row

**Comment by adad20** [comment]
hi @bradymiller also should I use font-awesome icon in place of submit text in the button as suggested by @stu01509 ?

**Comment by adad20** [comment]
Screenshot (109)

File: interface/orders/procedure_stats.php (hunk 1 above)
Comment (bradymiller) [reply interface/orders/procedure_stats.php]: hi @adad20 , Just add btn-save to the class:
```
btn btn-primary btn-save
```
And then test it out (it places a nice icon on the button along with the text that is already there)

**Comment by bradymiller** [comment]
hi @adad20 , initial testing looks good. I just gotta figure out how to get it to output results (to complete the testing) by setting up some procedures; once I confirm that is testing well, then will bring this into codebase.

**Comment by tywrenn** [comment]
This entire form needs to be modernized and fixed when we do GSoC

**Comment by adad20** [comment]
@tywrenn so I think #3267 should also be under GSoC project.

**Comment by tywrenn** [comment]
@adad20 Continue working on it as the fix is still needed

File: interface/orders/procedure_stats.php [hunk 4]
```diff
@@ -331,119 +331,114 @@ function process_result_code($row)
...
+                    echo " />" . text($value) . " &nbsp;";
+                }
+            ?>
+        </div>
+    </div>
+</div>
+<br>
+<div class="col-4 col-md-4">
+    <div class="col">
+         <button type='submit' class='btn btn-primary btn-save' name='form_submit' title='<?php echo xla('Click to generate the report'); ?>'><?php echo xla('Submit') ?></button>
```
Comment (bradymiller) [inline interface/orders/procedure_stats.php:436]: Finally was able to get the submit button to work. To get the submit button to work, it needs a value:
```
<button type='submit' class='btn btn-primary btn-save' name='form_submit' value='form_submit' title='<?php echo xla('Click to generate the report'); ?>'><?php echo xla('Submit') ?></button
```
If there is no value then it never passes the conditional on line 444 when submit the form

Comment (bradymiller) [reply interface/orders/procedure_stats.php:436]: After this is fixed, then will bring this PR into codebase.

File: interface/orders/procedure_stats.php [hunk 5]
```diff
@@ -331,119 +331,114 @@ function process_result_code($row)
...
+                    echo " />" . text($value) . " &nbsp;";
+                }
+            ?>
+        </div>
+    </div>
+</div>
+<br>
+<div class="col-4 col-md-4">
+    <div class="col">
+         <button type='submit' class='btn btn-primary btn-save' name='form_submit' value='<?php echo xla('Submit') ?>' title='<?php echo xla('Click to generate the report'); ?>'></button>
```
Comment (bradymiller) [inline interface/orders/procedure_stats.php]: I am pretty sure that won't work (it will likely show an empt button). Let me know if it is testing to work. The button "label" needs to be outside the html attributes (like a link) like you had it previously. The value is just used in the POST setting. So, doing:
```
<button type='submit' class='btn btn-primary btn-save' name='form_submit' value='form_submit' title='<?php echo xla('Click to generate the report'); ?>'><?php echo xlt('Submit') ?></button>
```
will do the following:
1. The label of the button with be "Submit"
2. When click this Submit, it will pass a POST variable with name `form_submit` that has value `form_submit`. This then allows it to pass the conditional on line 444 since the `form_submit` POST value is not empty

**Comment by bradymiller** [comment]
dang, that was a quick turn around :)
Code looks good and bringing into codebase. Thanks for the improvements @adad20 ! -brady
