### PR TITLE
fix: add missing use statement in facility admin script

### LINKED ISSUE #7427: bug: missing use aclmain statement in prior commit
### Describe the bug

[bug in prior commit](https://github.com/openemr/openemr/commit/513ebf7910aa52a8180ef4ad6600c9a9a78bd08a#diff-9b500d0b429ee26c6286eb4cbd311f9156178ae82cdecbed10d7d78a88c53912)

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7427

### CODE REVIEW

File: ccr/createCCR.php [hunk 1]
```diff
@@ -12,26 +12,32 @@
  * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
  */
 
+use OpenEMR\Common\Acl\AclMain;
+use OpenEMR\Common\Session\SessionUtil;
```
Comment (bradymiller) [inline ccr/createCCR.php:16]: This should work on the portal, but would make sure it works on the portal.

File: ccr/createCCR.php [hunk 2]
```diff
@@ -12,26 +12,32 @@
...
         $ignoreAuth = true;
         global $ignoreAuth;
     } else {
-        OpenEMR\Common\Session\SessionUtil::portalSessionCookieDestroy();
+        SessionUtil::portalSessionCookieDestroy();
         header('Location: ' . $landingpage . '?w');
         exit;
     }
 } else {
     // Check authorization.
```
Comment (bradymiller) [inline ccr/createCCR.php:39]: this is a weird block (try best to never include globals.php twice). Would just have this block set up a flag such as notPatientPortal = true

Then use that flag to run the auth after the includes below (so will then be below the globals.php below)

File: ccr/createCCR.php [hunk 3]
```diff
@@ -12,26 +12,32 @@
  * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
  */
 
+use OpenEMR\Common\Acl\AclMain;
+use OpenEMR\Common\Session\SessionUtil;
+use OpenEMR\Common\Twig\TwigContainer;
+use PHPMailer\PHPMailer\PHPMailer;
```
Comment (bradymiller) [inline ccr/createCCR.php:18]: also generally try to do the use block after globals.php is brought to avoid ever messing up things in that core script. in this case could just put the use for SessionUtil here and the put the other after globals.php is brought in below

File: ccr/createCCRActor.php [hunk 4]
```diff
@@ -141,7 +141,7 @@
     $e_InformationSystem = $ccr->createElement('InformationSystem');
     $e_Actor->appendChild($e_InformationSystem);
 
-    $e_Name = $ccr->createElement('Name', $row1['facility']);
+    $e_Name = $ccr->createElement('Name', htmlentities($row1['facility'] ?? ''));
```
Comment (bradymiller) [inline ccr/createCCRActor.php:144]: hi @stephenwaite , Just checking why the htmlentities() function call is being used here?

Comment (stephenwaite) [reply ccr/createCCRActor.php:144]: The facility has an & in its name  :)

Comment (bradymiller) [reply ccr/createCCRActor.php:144]: Will text() function get what you need? Been avoiding htmlentities since I don't understand it :)

**Review by bradymiller — APPROVED** [review]
