### PR TITLE
edit layout fixes (sticky menu and showing filter stuff)

### LINKED ISSUE #3810: Layout top menu not fixed
### Describe the bug
image

This action bar is supposed to be fixed. I spent a lot of time in v501 and v502 making this fixed and other changes so user isn't scrolling to top as they design.
Back up to v502 and check out how this form works.

Also the Save Changes button is only supposed to change to red when click where it should also be disabled.

Also, also:) otherwise the form looks great. Please fix fixed action bar...

### PR DESCRIPTION
**Pull request by bradymiller**
Partial fix for:
https://github.com/openemr/openemr/issues/3810

### CODE REVIEW

File: interface/super/edit_layout.php [hunk 1]
```diff
@@ -1350,7 +1350,7 @@ function myChangeCheck() {
 <input type="hidden" name="selectedfields" id="selectedfields" value="" />
 <input type="hidden" id="targetgroup" name="targetgroup" value="" />
 
-<div class="menubar" style='padding:5px 0;'>
+<div class="menuBar" style='padding:5px 0;'>
```
Comment (sjpadgett) [inline interface/super/edit_layout.php:1353]: This class menuBar can go away because it has a fixed color background.
I'd just do
```<div class="fixed-top py-2 px-1 bg-light text-dark">```
and remove the class in interface/themes/theme-defaults.scss

Comment (bradymiller) [reply interface/super/edit_layout.php:1353]: k, will do

Comment (bradymiller) [reply interface/super/edit_layout.php]: proposed change looks good and will bring in after pass travis

Comment (sjpadgett) [reply interface/super/edit_layout.php]: cool thanks. May have to hold patch as someone responded with billing issue. I'm looking over now!!

Comment (bradymiller) [reply interface/super/edit_layout.php]: bringing in :)
