### PR TITLE
fix(deprecations): Comlink module

### LINKED ISSUE #10510: fix(8.2 deprecation) Update Comlink Telehealth
The module shows deprecation warnings in PHP 8.2. Refactoring globals to globalbag

Changes Made deprecation warnings

1. TeleHealthRemoteRegistrationService.php - Added explicit type declarations to 9 properties:
•  $apiURL, $apiId, $apiPassword, $apiCMSID → private ?string
•  $httpClient → private ?Client
•  $institutionId, $institutionName → private ?string
•  $logger → private ?SystemLogger
•  $userRepository → private ?TeleHealthUserRepository

2. TeleHealthCalendarController.php - Added explicit type declarations to 3 properties:
•  $loggedInUserId → private ?int
•  $calendarEventCategoryRepository → private ?CalendarEventCategoryRepository
•  $apptService → private ?AppointmentService

✅ Verification Results

•  PHP Syntax Check: All 30+ module files pass validation with zero errors
•  Type Declarations: All properties now have explicit, nullable types
•  PHP 8.2 Compliance: No dynamic property deprecation warnings
•  Backward Compatibility: All changes are non-breaking

✅ Key Benefits

•  Eliminates PHP 8.2 deprecation warnings
•  Improves IDE autocomplete and type checking
•  Enables better static analysis (PHPStan compatible)
•  Follows modern PHP standards (PSR-12)
•  Maintains 100% backward compatibility

Changes Completed for globals

Files Modified: 3

1. Bootstrap.php (9 changes)
◦  Added OEGlobalsBag import
◦  Removed global $GLOBALS; declaration from constructor
◦  Refactored getURLPath() - $GLOBALS['webroot'] → OEGlobalsBag::getInstance()->get('webroot')
◦  Refactored getPublicPathFQDN() - $GLOBALS['qualified_site_addr'] → OEGlobalsBag::getInstance()->get('qualified_site_addr')
2. TelehealthGlobalConfig.php (8 changes)
◦  Added OEGlobalsBag import
◦  Refactored getGlobalSetting() - Simplified to use OEGlobalsBag::getInstance()->get()
◦  Refactored setupConfiguration() - Replaced global $GLOBALS with OEGlobalsBag::getInstance()->get()
3. TeleconferenceRoomController.php (5 changes)
◦  Added OEGlobalsBag import
◦  Refactored getProviderSettings() - 1 GLOBALS access updated
◦  Refactored getPatientSettings() - 1 GLOBALS access updated

✅ Verification

•  PHP Syntax: All 30+ module files pass validation ✓
•  Global Access Refactoring: 9/9 references (100%) ✓
•  Backward Compatibility: Fully maintained ✓
•  Best Practices: Fully aligned with OpenEMR guidelines ✓

Benefits

•  ✓ Improved testability (easier to mock globals)
•  ✓ Better static analysis compatibility
•  ✓ Enhanced security (centralized global access)
•  ✓ Improved maintainability (consistent patterns)
•  ✓ Aligns with modern OpenEMR development practices

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #10510 

#### Short description of what this resolves:
There are deprecation warning showing in php 8.2 for the module.

#### Changes proposed in this pull request:
See issue for all changes made to the module

### CODE REVIEW

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php [hunk 1]
```diff
@@ -27,52 +27,48 @@ class TeleHealthRemoteRegistrationService
 {
     /**
      * API url endpoint to send registration requests to.
-     * @var string
      */
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php:31]: This property is always assigned in the constructor (line 85: `$this->userRepository = new TeleHealthUserRepository()`), so widening it to `?string` introduces nullability that can never actually occur at runtime.

Same applies to `$apiURL`, `$apiId`, `$apiPassword`, `$apiCMSID`, `$httpClient`, `$institutionId`, `$institutionName`, `$logger`, and `$userRepository` — they're all unconditionally assigned in `__construct()`. Would it make sense to use non-nullable types instead and remove the `= null` defaults? That would more accurately express the invariant and let static analysis catch uninitialized-property bugs.

If the goal is purely to add explicit types to suppress the PHP 8.2 deprecation (dynamic properties), typed non-nullable properties without a default would achieve that:
```suggestion
    private string $apiURL;
```

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthCalendarController.php [hunk 2]
```diff
@@ -31,37 +31,34 @@
...
 
     /**
      * @param TelehealthGlobalConfig $config
      * @param Environment $twig Twig container
      * @param SystemLogger $logger
      * @param mixed $assetPath
-     * @param mixed $loggedInUserId
+     * @param ?int $loggedInUserId Database record ID of the currently logged in user
      */
     public function __construct(
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthCalendarController.php:55]: Since the other constructor dependencies (`$twig`, `$logger`) are typed, would it make sense to also type `$assetPath`? It's always a string (comes from `Bootstrap::getAssetPath()` which returns a concatenated path). Leaving it untyped is a bit inconsistent with the rest of the signature:
```suggestion
        private readonly string $assetPath,
```

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php [hunk 3]
```diff
@@ -462,14 +461,13 @@ private function isLocaleConfigured()
 
     public function setupConfiguration(GlobalsService $service)
     {
-        global $GLOBALS;
         $section = xlt("TeleHealth");
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php:465]: Worth double-checking: `OEGlobalsBag::get()` returns `null` for missing keys, and `null ?? $config['default']` correctly falls back — so this is semantically equivalent to the old `$GLOBALS[$key] ?? $config['default']`. Just flagging it since this is the one spot where the fallback chain matters (the other call sites don't use `??`).

**Review by kojiromike — COMMENTED** [review]
Overall this is a solid modernization of the Comlink telehealth module — the `$GLOBALS` → `OEGlobalsBag` migration is the right direction and the type declarations improve clarity.

A few items to consider below, mostly around consistency and one semantic question about the `setupConfiguration` fallback chain.

Also: the CI check for PR title (Conventional Commits) is failing — looks like it needs a colon after the scope, e.g. `fix(deprecations): Comlink module`.

**Comment by juggernautsei** [comment]
@kojiromike, I'm curious as to why the checks did not complete. Is there something I did wrong?

**Comment by adunsulag** [comment]
@juggernautsei I think github had an issue.  If you push again it will probably re-run the tests.

Since you're in here working on this do you want to address a fatal error that is happening with this module when you go to the Admin -> Config?

When you enable a fresh install of the module it throws the following error:
==> /var/log/apache2/error.log <==
[Tue Feb 03 23:44:23.767752 2026] [php:error] [pid 2939:tid 2939] [client 172.20.0.1:44838] PHP Fatal error:  Uncaught TypeError: OpenEMR\\Common\\Utils\\ValidationUtils::isValidUrl(): Argument #1 ($url) must be of type string, null given, called in /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php on line 427 and defined in /var/www/localhost/htdocs/openemr/src/Common/Utils/ValidationUtils.php:196\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php(427): OpenEMR\\Common\\Utils\\ValidationUtils::isValidUrl()\n#1 /var/www/localhost/htdocs/openemr/interface/super/templates/field_html_display_section.php(14): Comlink\\OpenEMR\\Modules\\TeleHealthModule\\TelehealthGlobalConfig->renderFooterBox()\n#2 /var/www/localhost/htdocs/openemr/interface/super/edit_globals.php(494): include('...')\n#3 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Common/Utils/ValidationUtils.php on line 196, referer: https://localhost:9300/interface/main/tabs/main.php?token_main=IpxZC83m7sj8zbzCntGYAsGgDOADmHB7KNQVSh0y

I'm going to open an issue for it, but figure you may as well address it in this PR if you can.

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php (hunk 3 above)
Comment (adunsulag) [reply interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php:465]: OEGlobalsBag::get() default behavior is to return null for missing keys.

**Review by adunsulag — APPROVED** [review]
Looks like you fixed all the identified suggestions.  I don't have any other concerns. @kojiromike I believe you're concerns are addressed. If so I think we can bring this in which will also fix the blocker for release 8.0.

**Comment by kojiromike** [comment]
@aisle-analyzer

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php (hunk 1 above)
Comment (kojiromike) [reply interface/modules/custom_modules/oe-module-comlink-telehealth/src/Services/TeleHealthRemoteRegistrationService.php:31]: Addressed in the current state — all of these properties are now typed non-nullable (most `readonly`):
- `private readonly string $apiURL` / `$apiId` / `$apiPassword` / `$apiCMSID` / `$institutionId` / `$institutionName`
- `private readonly LoggerInterface $logger`
- `private Client $httpClient` (not readonly because `setHttpClient()` reassigns it)
- `private TeleHealthUserRepository $userRepository`

Resolving.

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthCalendarController.php (hunk 2 above)
Comment (kojiromike) [reply interface/modules/custom_modules/oe-module-comlink-telehealth/src/Controller/TeleHealthCalendarController.php:55]: Addressed — `$assetPath` is now `private readonly string $assetPath` (and `$loggedInUserId` is `private readonly ?int $loggedInUserId`). Resolving.

File: interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php (hunk 3 above)
Comment (kojiromike) [reply interface/modules/custom_modules/oe-module-comlink-telehealth/src/TelehealthGlobalConfig.php:465]: Confirmed by @adunsulag and the line is now outdated after the merge. Resolving.

**Comment by kojiromike** [comment]
Thanks @aisle-analyzer — valid CWE-532 finding. This is pre-existing logging behavior untouched by this PR (diff only updates property typings and removes a redundant httpClient guard), so I've tracked it separately as #11738 rather than expanding scope here.
