### PR TITLE
Batch Payments bug fixes

### LINKED ISSUE #3621: fees->batch payments : can't edit and save the edited payment
### Describe the bug

fees->batch payments : can't edit and save the edited payment 

### To Reproduce

add a payment with fees->batch payments, then search for it and edit it by clicking somewhere on the payment
Screenshot from 2020-06-13 19-45-17

Screenshot from 2020-06-13 19-46-03

### Expected behavior

edit a payment and have it save the new details

### PR DESCRIPTION
**Pull request by sjpadgett**
- mainly wrong action buttons presented in edit payments
- leading to fixing styles to be useable
- removed modal and replaced back dialog. There's a reason we have dialog!

Fixes #3621

#### Short description of what this resolves:
Still trying to figure that out!
-
-

### CODE REVIEW

**Comment by sjpadgett** [comment]
no need to review styles because I won't do anything about. Mission here was to get useable for our folks that run master in production and so i'm not aggravated testing for bugs. For sure these scripts need to be gone through and made responsive. I think BS4 has bug dealing with grids where pattern row>col-12>col-3.. has issues.

**Comment by sjpadgett** [comment]
image

**Comment by sjpadgett** [comment]
Looks like I need to add a full screen option to dialog. Jesh, will it ever end!:) I just wanted to fix a bug...
image

**Comment by sjpadgett** [comment]
I like sharing
image

**Comment by tywrenn** [comment]
@sjpadgett hold up - BS4 has a native modal-lg class

**Comment by sjpadgett** [comment]
Dialog is NOT a modal. It's a dialog that does things a modal doesn't. Like span the entire viewport in top. Run events, promises etc. So just leave dialog to me!

**Comment by sjpadgett** [comment]
Also, I don't want modals used where a dialog can be used. I firm on this...

File: library/dialog.js [hunk 1]
```diff
@@ -486,7 +488,7 @@ function dlgopen(url, winname, width, height, forceNewWindow, title, opts) {
         ('<div id="%id%" class="modal fade dialogModal" tabindex="-1" role="dialog">%sizeStyle%' +
```
Comment (tywrenn) [inline library/dialog.js:488]: @sjpadgett Then how come the JS code involves the CSS modal class... 😂😂😂

Comment (sjpadgett) [reply library/dialog.js:488]: @tywrenn 
Dialog uses the modal class and more. I wrote dialog mainly because modal is to restrictive when they reside in the iframe. Our viewports keep shrinking so I open dialog in top window where it uses all the viewport of main.php. Also a dialog needs to be able to have callbacks, run functions, custom sizing, render HTML, ajax and nicely return promises on init/shown or close. 

Note the screenshot above where the dialog is outside the batch payment iframe and all the business fields that show in one view then compare a current batch payment modal.(really try it in your local 5.0.2)

Previously we were using a jquery-ui dialog which was pretty nice but we needed to replace, so, instead of bringing in another custom library that will eventually have to be replaced at some point, I wrote a dialog custom to openemr. This is why we also have utility.js.
I'm a firm believer in this concept, if we can write it specific for openemr, we should.

This help ya?

Comment (sjpadgett) [reply library/dialog.js:488]: oh! plus I hate modals...

Comment (sjpadgett) [reply library/dialog.js:488]: Hope we're on the same page now but, if not, just ask...

Comment (tywrenn) [reply library/dialog.js:488]: This is gonna suck when we have to get rid of frames eventually :(

Comment (sjpadgett) [reply library/dialog.js:488]: We already got rid of frames. IFrames are here to stay

Comment (tywrenn) [reply library/dialog.js:488]: Yeah but they might get rid of those as welllll

Comment (sjpadgett) [reply library/dialog.js:488]: That's what I like about you @tywrenn, eager.

**Comment by sjpadgett** [comment]
@stephenwaite Looks like I finally see the light! Batch payments really should be used only if era or medicare/medicaid for that's what it's designed for.

Remainders were not reflecting debit/credit correctly causing some confusion in UI however, in some cases on a recalculation from database remainers and undistributed could recalculate and straighten out. Causing for one confused developer!

Now that undistributed and remainders are calculated correctly, it is next to impossible to not allocate entire payment to move on which, is what original developer had in mind.

Lot's of changes where I hope you will test and give feedback before I bring fix back to 502.

**Comment by sjpadgett** [comment]
What do ya know. Travis is my friend again! Bringing in.

File: library/dialog.js (hunk 1 above)
Comment (bradymiller) [reply library/dialog.js:488]: dang, iframes are now bad. When will it end :)

**Comment by stephenwaite** [comment]
> Looks like I finally see the light! Batch payments really should be used only if era or medicare/medicaid for that's what it's designed for.
@sjpadgett , so you're saying that it was intended to be used in tandem with ERA? Like after you post an ERA you should navigate to search payments and make sure it was distributed? That's odd. I assumed it was just for a large paper eob, like 1 check but many patients on the remit, kind of like how the medigaps like aarp are posted by many small offices who don't realize that they can get the 835 (ERA) for those as well thru their clearinghouse.

**Comment by sjpadgett** [comment]
> era or medicare/medicaid

Note the or. I think if you're going to do ERA one should be in EOB Posting anyway.

**Comment by stephenwaite** [comment]
thanks @sjpadgett , so do you seen any issues with using it for 2ndaries like aarp?

**Comment by sjpadgett** [comment]
Not off hand.The insurances are advancing correctly plus with the dif color indicators and toggles for payment status it's pretty simple. As long as when doing a New Payment user allocates all the payment. Edit Payment troubles me some.
Have eye surgery this a.m so see ya later.(SEE what I did there):)

**Comment by stephenwaite** [comment]
ok :), break a :leg:

**Comment by sjpadgett** [comment]
Hi @stephenwaite 
Have you had a chance to play with Batch Payments? Does it seem to calculate correctly?

**Comment by stephenwaite** [comment]
hi @sjpadgett , how are you doing?
not much yet, just merged and spun it up last night, should i move all alerts to asyncalerts?

**Comment by sjpadgett** [comment]
I could have sworn I brought the alerts into my PR but looks like not! I've no idea want is going on in my head.
I doing okay, thanks for asking.
I'm worried about how batch payments work. Seems like something is missing fro payment management!!!!

**Comment by stephenwaite** [comment]
ok, will test after lunch :hungary:

**Comment by sjpadgett** [comment]
Okay. Working now on 502 Many fixes for 503 were not relevant to 502 except menu in edit payments. I think we need better report back to user somehow! I may go ahead and get rid of modal in 502 as well! A pain but worth it imo...

**Comment by stephenwaite** [comment]
hi @sjpadgett , have you replaced the `confirm`s before?

**Comment by sjpadgett** [comment]
No. I have an alert in dialog where html can be passed in and i've prepared for confirm but haven't written yet. Let me write one real quick and put up a PR. Batch payments is not calculating correctly if amounts are in the thousands anyway so i'll need to put up that fix along with v502.
Maybe an hour or so...

**Comment by sjpadgett** [comment]
@stephenwaite You think we ought to have a running payments balance in batch payments? Allocate is confusing to me so I figure f I can understand then, well, anyone can! Umm, even Brady.:)

**Comment by stephenwaite** [comment]
sure, lol, he's pretty limited though, like with dockers :)

**Comment by bradymiller** [comment]
What is billing and where does billing live? Maybe on an island somewhere sunny?

**Comment by stephenwaite** [comment]
always sunny and islandy on pilates ball 
external-content duckduckgo com

**Comment by bradymiller** [comment]
I heard a bowl is also very comfortable.

tenor (29)

**Comment by sjpadgett** [comment]
Alright u'ens! Get back to work!!!!

**Comment by stephenwaite** [comment]
external-content duckduckgo com

**Comment by sjpadgett** [comment]
@stephenwaite 
Something like this?
image
It will be a promise returned so it doesn't stop js like js alert and confirm. What should it return?

**Comment by stephenwaite** [comment]
am only good at gifs, not js logic :)
tenor

**Comment by sjpadgett** [comment]
okay, i'll setup an example and send you dialog.js to play with.

**Comment by stephenwaite** [comment]
more at my reading level :)
https://medium.com/javascript-in-plain-english/javascript-async-await-and-promises-explained-like-youre-five-years-old-61733751e9a5

**Comment by sjpadgett** [comment]
@stephenwaite Learning is learning no matter on what level and once you get the promise pattern, a whole new world opens up!
Here is what i'm thinking for confirm:. edit_payment.php araoun L-480 add
```
dialog.confirm(<?php echo xlj('Would you like to Modify Payments?'); ?>)
            .then(returned => {
                if( returned === true) {
                    document.getElementById('mode').value = 'ModifyPayments';
                    top.restoreSession();
                    document.forms[0].submit();
                } else {
                    dialog.close();
                    return false;
                }
            });
```
here's dialog.js

[dialog.zip](https://github.com/openemr/openemr/files/4828092/dialog.zip)

**Comment by sjpadgett** [comment]
What the hell is happening to my country!

**Comment by stephenwaite** [comment]
What's up?

**Comment by sjpadgett** [comment]
Just Frustrated with people! I found a new  bug that i'm really surprised no one has seen. Deals with table header not displayed after a payment search in certain circumstance. An AR query is suspect.  Have we had a lot of issues with Batch in the past?

**Comment by stephenwaite** [comment]
oh, ok, you take the UI seriously :), never really used it but suspecting so

**Comment by stephenwaite** [comment]
i turned on the radio after you posted that thinking our resident in chief had sad something stupid again

**Comment by sjpadgett** [comment]
At least he doesn't lose his train of thought every other sentence! We'd better leave this subject alone!

**Comment by sjpadgett** [comment]
> oh, ok, you take the UI seriously :),

lol, no I meant, how looting is allowed as excuse for protest! One is terrorism the other, seeking change.

**Comment by sjpadgett** [comment]
I gotta tell you, batch payments is really badly broken. Delete a partially allocated  payment distribution and we delete the entire charge but keep distribution of funds for deleted charge!!!

We will display patients with 0.00 charges in search causing validation to fail if validate for new payment allocation.... 

Unsure if we should keep non normal accounting principles for showing debit/credits in remainders e.g. partial past payments on encounter may have balance due(remainder) however, remainder keeps a calculated remainder from charge/payment etc running total of payments for encounter but, displays remainder as debit against total charge i.e total chrg: 900.00 payments: 800.00 remainder: -800.00. umm not true, remainder is 100.00. Current remainder shows past payments debits/credits and not amount due! 

Even for a general ledger, current remainder would be a credit column with the amount due becoming what we call remainder. How confusing this must be to billing folks if they follow normal accounting practices unless they learn to ignore column headings!

So, need to change calculation for remainder imo.

Am I boring everyone yet?:)

**Comment by bradymiller** [comment]
You've still got the "cat in the bowl"'s attention, so you must be doing something right :)

tenor (29)

**Comment by sjpadgett** [comment]
I quit using FF developer, it su$#s now! just saying....

**Comment by sjpadgett** [comment]
> so you must be doing something right :)

Am I? Or just digging a hole even too deep for the cat!:)

**Comment by stephenwaite** [comment]
so what would you like me to do here? finish my merge and include the dialog addition you sent?

**Comment by sjpadgett** [comment]
Prob best to wait for my merge. I pulled in your async alerts and did a dialog.confirm example so you can go through adding/replacing rest of them.
