### PR TITLE
encounter bug fix issue #3449

### LINKED ISSUE #3449: Facility, Billing location and POS Issues
### Describe the bug
see forum https://community.open-emr.org/t/pos-problem/9468/

This entire process is off imo, which I want to see fixed once and for all time.  
- Default facility should be users assigned facility else error and force facility assignment in Users.
- Billing facility should default to user facility if a billing location else first facility flagged as business entity.

### Expected behavior
Currently unsure! 
Big question is should POS track with selected facility or selected billing facility???

### Client configuration

- Browser:
- Operating system:

### PR DESCRIPTION
**Pull request by sjpadgett**
- only show active authorized user in pull down
- fix POS setting disabled control
- allow non providers to save by reasoning they already have permissions.

Fixes #3449

### CODE REVIEW

File: interface/forms/newpatient/common.php [hunk 1]
```diff
@@ -438,6 +441,9 @@ function cancelClickedOld() {
                                         $userService = new UserService();
                                         $users = $userService->getActiveUsers();
                                         foreach ($users as $activeUser) {
+                                            if ($activeUser->getAuthorized() !== true) {
+                                                continue;
+                                            }
                                             echo "<option value='" . attr($activeUser->getId()) . "'";
```
Comment (stephenwaite) [inline interface/forms/newpatient/common.php:447]: nice, the entity has the `getAuthorized()` method

File: interface/forms/newpatient/save.php [hunk 2]
```diff
@@ -47,8 +47,8 @@
 
 $nexturl = $normalurl;
 
-$provider_id = $userauthorized ? $_SESSION['authUserID'] : 0;
-$provider_id = $provider_id ? $encounter_provider : $provider_id;
+$provider_id = $_SESSION['authUserID'] ? $_SESSION['authUserID'] : 0;
+$provider_id = $encounter_provider ? $encounter_provider : $provider_id;
```
Comment (stephenwaite) [inline interface/forms/newpatient/save.php:52]: whoa, cool, since the only way `$encounter_provider` gets loaded is if it is an auth provider in the dropdown...

File: interface/forms/newpatient/common.php (hunk 1 above)
Comment (sjpadgett) [reply interface/forms/newpatient/common.php:447]: This service is fully hydrated where all columns have getter/setters

**Comment by bradymiller** [comment]
Prob be easier and less prone for errors to just make a patch 4 (they are easy to build now via script). Any other fixes that need to go in? I'll delay the package rebuilds then also (was getting ready to rebuild packages on most recent patch so installs work on mysql8 and most recent mariadb version).

**Comment by sjpadgett** [comment]
I was hoping to get to bottom of https://community.open-emr.org/t/openemr-5-0-2-patch/13007/70?u=sjpadgett and there may be a couple others I can fix.
