### PR TITLE
restore missing hcfa text file

### LINKED ISSUE #5036: missing hcfa text file
### Describe the bug

when the billing was overhauled the text hcfa was left out

### To Reproduce
tried to download text file
Screenshot from 2022-03-24 23-32-22
nothing happens
Screenshot from 2022-03-24 23-32-58

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5036

### CODE REVIEW

**Comment by stephenwaite** [comment]
testing well

File: src/Common/Crypto/CryptoGen.php [hunk 1]
```diff
@@ -75,7 +75,7 @@ public function encryptStandard($value, $customPassword = null, $keySource = 'dr
     /**
      * Standard function to decrypt
      *
-     * @param  string  $value           This is the data to encrypt.
+     * @param  string  $value           This is the data to decrypt.
```
Comment (bradymiller) [inline src/Common/Crypto/CryptoGen.php:78]: 2DV-2

**Review by bradymiller — APPROVED** [review]

File: src/Billing/BillingProcessor/Tasks/AbstractGenerator.php [hunk 2]
```diff
@@ -100,7 +100,15 @@ public function complete(array $context)
                 $this->getAction() === BillingProcessor::VALIDATE_ONLY ||
                 $this->getAction() === BillingProcessor::VALIDATE_AND_CLEAR
             ) {
-                $this->completeToScreen($context);
+                if (
+                    ($context['post']['bn_process_hcfa'] ?? '') ||
+                    ($context['post']['bn_process_hcfa_form'] ?? '') ||
+                    ($context['post']['bn_hcfa_txt_file'] ?? '')
+                ) {
+                    $this->completeToFile($context);
```
Comment (surfacehazard) [inline src/Billing/BillingProcessor/Tasks/AbstractGenerator.php:108]: Is this backwards?  Wouldn't validating complete to screen?
