### PR TITLE
alter document api response body to include file name and hash

### LINKED ISSUE #8304: no filename in document api response
### Describe the bug

The document API returns the last part of the url field in the database, for me this is a uuid not the filename.

example:
```
[{'docdate': '2025-04-18',
  'filename': '9eb49ed5-31d1-4576-a9ef-8c72988398a0',
  'id': 341,
  'mimetype': 'image/png'},
 {'docdate': '2025-04-24',
  'filename': '9ec06625-a7b3-4bd5-9cf4-4d14c8d6a77c',
  'id': 346,
  'mimetype': 'image/png'}]
```

### To Reproduce
GET `https://emr.my-domain.nl/apis/default/api/patient/1/document?path=/MedicalRecord`

### Expected behavior

```
[{'docdate': '2025-04-18',
  'filename': 'image.png',
  'id': 341,
  'mimetype': 'image/png'},
 {'docdate': '2025-04-24',
  'filename': 'image.png',
  'id': 346,
  'mimetype': 'image/png'}]
```

### PR DESCRIPTION
**Pull request by aapjeisbaas**
Fixes #8304

#### Short description of what this resolves:
Return the filename as it is stored in the database in the documents api.

#### Changes proposed in this pull request:
Don't use the file path basename but get the name field from the documents table.

I also added the hash field to the api, this makes preventing duplicate uploads a lot easier.

### CODE REVIEW

File: src/Services/DocumentService.php [hunk 1]
```diff
@@ -111,7 +111,8 @@ public function getAllAtPath($pid, $path)
         $fileResults = array();
         while ($row = sqlFetchArray($documentResults)) {
             array_push($fileResults, array(
-                "filename" => basename($row["url"]),
```
Comment (bradymiller) [inline src/Services/DocumentService.php:114]: yep, above is from the old days when filenames were the document names (until they then became encrypted files with uuid names).

**Comment by bradymiller** [comment]
What are your thoughts on fixing the /api/patient/:pid/document/:did endpoint while you are doing this. Basically is the same type of fix you did except in the getFile() function of the DocumentService.php class (substitute filename url with name instead).

**Comment by aapjeisbaas** [comment]
Just tested the code, I get the correct filename in the return headers on downloading the file.
```
'Content-Description': 'File Transfer', 'Content-Disposition': 'attachment; filename=music.png'
```
Was that the fix you we're looking for?

**Comment by bradymiller** [comment]
Brought in rel-703 for patch 7.0.3.4: #8338
