### PR TITLE
fix: whitelist session pid setting pt from billing manager

### LINKED ISSUE #7874: bug: toencounter billing manager bug
### Describe the bug

https://community.open-emr.org/t/billing-manager-errors/23974

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7874

### CODE REVIEW

File: library/ajax/set_pt.php [hunk 1]
```diff
@@ -21,6 +21,15 @@
...
 }
+
+// For gotos from billing manager we are whitelisting pid
+if (($_POST['mode'] ?? '') == 'session_key') {
+    $key = $_POST['key'] ?? '';
+    if ($key == 'pid') {
+        $current = $_SESSION[$key] ?? $pid ?? 0;
+        echo(js_escape($current));
+    }
+}
```
Comment (sjpadgett) [inline library/ajax/set_pt.php:35]: If you want:
```
if (($_POST['mode'] ?? '') === 'session_key') {
    $key = $_POST['key'] ?? '';
    // (whitelist)
    $allowedKeys = ['pid', 'encounter'];

    if (in_array($key, $allowedKeys, true)) {
        $current = $_SESSION[$key] ?? ($key === 'pid' ? ($pid ?? 0) : 0);
        echo js_escape($current);
    }
}
```

File: interface/billing/billing_report.php [hunk 2]
```diff
@@ -355,7 +355,9 @@ function set_button_states() {
             let curpid = await top.getSessionValue('pid');
             try {
                 if (curpid != pid) { // set patient
-                    top.clearPatient(false);
+                    if (curpid != 0) {
+                        top.clearPatient(false);
```
Comment (sjpadgett) [inline interface/billing/billing_report.php:359]: I don't think this will work. I believe that the new patient will show the last/old in the Summary but name will be correct in patient bar.
Also you could move getSessionValue() to library/js/utility.js I'd hope it would be in scope anywhere header class is called.

**Review by sjpadgett — APPROVED** [review]
Just my two point five cents! lol

File: library/ajax/set_pt.php [hunk 3]
```diff
@@ -21,6 +21,15 @@
...
+if ($_GET["set_pid"] ?? '' && ($_GET["set_pid"] != $_SESSION["pid"])) {
     setpid($_GET["set_pid"]);
 }
+
+// For gotos from billing manager we are whitelisting pid
+if (($_POST['mode'] ?? '') == 'session_key') {
+    $key = $_POST['key'] ?? '';
+    if ($key == 'pid') {
+        $current = $_SESSION[$key] ?? $pid ?? 0;
+        echo(js_escape($current));
```
Comment (bradymiller) [inline library/ajax/set_pt.php:33]: need to surround this with text()

File: interface/billing/billing_report.php (hunk 2 above)
Comment (stephenwaite) [reply interface/billing/billing_report.php:359]: thanks @sjpadgett , it's working fine. Problem with moving it to `utility.js` is the lack of context for the login page so the embedded php calls will fail.
