### PR TITLE
Fixes #6396 webroot path for safe filter

### LINKED ISSUE #6396: ModulesApplication.filterSafeLocalModuleFiles blocks module script/style files when used with subfolder OpenEMR installation
If OpenEMR is installed in a subfolder or anywhere other than the root of the web server (IE web_root is NOT empty) the safety check we use for filtering module files blocks the module script / style files from being included.  This can easily be seen by running the Telehealth module in a webroot installation.

For example if your OpenEMR installation is at **https://oe-build.somedomain.com/openemr/** then the calendar icons will fail to show as the scripts are not injected into the OpenEMR installation in the header whereas if OpenEMR runs at **https://oe-build.somedomain.com/** it will work fine.

### PR DESCRIPTION
**Pull request by adunsulag**
Fixes #6396

Makes it so the webroot path still functions in the safe filter. Prevents injection of scripts in the header unless the file actually exists in OpenEMR and that its locked down to the module directory.

### CODE REVIEW

File: src/Core/ModulesApplication.php [hunk 1]
```diff
@@ -189,7 +189,14 @@ public static function filterSafeLocalModuleFiles(array $files): array
                 // scripts that have any kind of parameters in them such as a cache buster mess up finding the real path
                 // we need to strip that out and then check against the real path
                 $scriptSrcPath = parse_url($scriptSrc, PHP_URL_PATH);
-                $realPath = realpath($GLOBALS['fileroot'] . $scriptSrcPath);
+                // need to remove the web root as that is included in the $scriptSrc and also in the fileroot
+                $pos = strpos($scriptSrcPath, $GLOBALS['web_root']);
```
Comment (sjpadgett) [inline src/Core/ModulesApplication.php:193]: You think for safety should use stripos? Windows is case sensitive.

Comment (adunsulag) [reply src/Core/ModulesApplication.php:193]: @sjpadgett You mean case insensitive right?  Could this introduce subtle errors where the script doesn't really exist on linux due to to a misnamed filename?  Yet, in the same vein could create problems on windows if the web server path is misconfigured when the windows file system doesn't care.  

I'm fine with using stripos, seems like either way we can have different problems.

Comment (sjpadgett) [reply src/Core/ModulesApplication.php:193]: You're right Windows doesn't care but window folks get use to using caps in paths and filenames.
Do what you think best.

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV-2
