### PR TITLE
fix: create custom temp directory for html purify serializer

### LINKED ISSUE #7520: bug: create custom temp directory for htmlpurify
### Describe the bug

need to have one :)

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7520

### CODE REVIEW

**Comment by stephenwaite** [comment]
testing well

File: src/Services/DocumentTemplates/DocumentTemplateRender.php [hunk 1]
```diff
@@ -109,7 +109,15 @@ public function doRender($template_id, $template_content = null, $json_data = nu
         // purify html (and remove js)
         $isLegacy = stripos($template, 'portal_version') === false;
         $config = HTMLPurifier_Config::createDefault();
-        $config->set('Cache.SerializerPath', $GLOBALS['temporary_files_dir']);
+        $purifyTempFile = $GLOBALS['temporary_files_dir'] . DIRECTORY_SEPARATOR . 'htmlpurifier';
+        if (
+            !file_exists($purifyTempFile) &&
+            !is_dir($purifyTempFile)
+        ) {
+            mkdir($purifyTempFile);
```
Comment (adunsulag) [inline src/Services/DocumentTemplates/DocumentTemplateRender.php:117]: not sure it matters, but this will fail if $purifyTempFile is a regular file, you could grab the error and log it, but again pretty trivial thing.

**Review by adunsulag — APPROVED** [review]

**Review by bradymiller — APPROVED** [review]
