### PR TITLE
Demographics pnote completed button doesn't work

### LINKED ISSUE #4481: Clicking "Completed" on a message in patient dashboard is broken
### Describe the bug

There is a "Completed" button next to messages in the patient dashboard. Clicking it does nothing. No errors in console.

### To Reproduce
1. Log into demo.
2. Create a new message to yourself regarding a patient.
3. Click "send"
4. Browse to the patient regarding whom you just sent message.
5. Open Messages section and click "Complete"

Screen Shot 2021-06-25 at 10 47 31 AM

### Expected behavior

Message should disappear (marked inactive)

### Client configuration

- Browser: Chrome
- OpenEMR version: 6.0.0 Patch 2
- Operating system: Mac Big Sur

### PR DESCRIPTION
**Pull request by sjpadgett**
- moved event handler to demographic context
- cleaned up pnote_fragment
- added back stats.php load on pnote loading.

Fixes #4481

### CODE REVIEW

**Comment by sjpadgett** [comment]
@bradymiller Please keep me honest on these older scripts.

File: interface/patient_file/summary/pnotes_full.php [hunk 1]
```diff
@@ -225,11 +225,15 @@
...
+    // @todo Brady I had this commented from when I did the demo cleanup.
+    // now I'm unsure even though stats is loaded elsewhere in demo loading,it may be used
+    // in pnotes when loaded elsewhere. Not even sure what the script is for!
+    // I put back however, i'm still unsure that it doesn't cause conflict in demo being loaded twice.
+    $("#stats_div").load("stats.php",
         {
             csrf_token_form: <?php echo js_escape(CsrfUtils::collectCsrfToken()); ?>
         }
-    );*/
+    );
```
Comment (bradymiller) [inline interface/patient_file/summary/pnotes_full.php:236]: hi @sjpadgett , was uncommenting this needed to fix a bug?
(otherwise would continue to leave it out since agree seems odd to load it twice)

**Comment by bradymiller** [comment]
@sjpadgett , looks good to me :)

File: interface/patient_file/summary/pnotes_full.php (hunk 1 above)
Comment (sjpadgett) [reply interface/patient_file/summary/pnotes_full.php]: nope just wanted to make sure my first instinct was correct. thanks.
Since I can bring php8 fixes back to v6 will go ahead and include them in this PR.

**Comment by sjpadgett** [comment]
Merging because most php fixes are with CCM and I can't bring that back to v6 until I figure out how I'm going to handle legacy ccda service.
Will cherry pick if no conflicts with pick.

btw: ccda care plan changes are done so new PR soon.

**Comment by bradymiller** [comment]
2DV
