### PR TITLE
fix for email in portal create credentials widget and portal login

### LINKED ISSUE #5864: portal login user name empty after create credentials
### Describe the bug

after credentials are created for the portal the `login_name` is empty if no emails have been entered in the `Contact` section of demographics and the field is not able to be edited

Screenshot from 2022-10-21 16-15-11

going directly to the patient portal to login results in something went wrong
Screenshot from 2022-10-21 16-08-45

this would affect installs where the email is not required in the portal login
Screenshot from 2022-10-25 10-18-49

### Expected behavior
be able to login initially which takes you to change username/password screen without having to reset credentials
Screenshot from 2022-10-21 16-18-52

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5864

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a

**Comment by adunsulag** [comment]
@stephenwaite Isn't there a flag that forces the account name to be the email address?  Have you tested this with the flag that uses the email address as the account name?  I'm just looking at this and wondering why I'm not seeing the bug, my account name uses the email address and I wonder if that is the difference.

**Comment by bradymiller** [comment]
Actually when I think about it, pretty sure it already uses the portal user id on first login without explicitly setting it (so shouldn't be an issue to explicitly set it); the nice thing about using the user id on first login is that it can never be duplicated/same as another patient. Will test it out on master.

**Comment by bradymiller** [comment]
I take that back, it is populating it with the trusted email. So if that email is empty, then will be blank. To minimize changes, would use the patient account name only if the trusted email is empty.

**Comment by bradymiller** [comment]
also looks like the positive sign to nowhere in the patient portal widget has resurfaced :)

image

**Comment by stephenwaite** [comment]
ready for another review :smiling_face_with_tear:

File: interface/patient_file/summary/create_portallogin.php [hunk 1]
```diff
@@ -169,11 +169,9 @@ function filterTwigTemplateData($twig, $pid, $templateName, $data)
 
     array_push($query_parameters, $pid);
     if (sqlNumRows($res)) {
-        // TODO: @adunsulag is there a reason why we don't audit the fact that the patient credentials were created and updated?
-        // That seems like a pretty important security event we want to be aware of.
```
Comment (bradymiller) [inline interface/patient_file/summary/create_portallogin.php:173]: pretty sure i didn't log these into audit engine since this means the hashes will get stored in the log table and be able to view them via log reports. prob best not to do that. if need to audit changes would instead make a newEvent() call via EventAuditLogger to log this manually (then it won't bring in the sensitive info).

File: portal/index.php [hunk 2]
```diff
@@ -357,14 +357,14 @@ function enableVerifyBtn(){
                     </div>
                 </div>
                 <div class="form-row my-3">
-                    <label class="col-md-2 col-form-label" for="pass"><?php echo !$_SESSION['onetime'] ? xlt('Current Password') : ''; ?></label>
+                    <label class="col-md-2 col-form-label" for="pass"><?php echo empty($_SESSION['onetime']) ? xlt('Current Password') : ''; ?></label>
                     <div class="col-md">
-                        <input class="form-control" name="pass" id="pass" <?php echo $_SESSION['onetime'] ? 'type="hidden" ' : 'type="password" '; ?> autocomplete="none" value="<?php echo attr($_SESSION['onetime']);
-                        $_SESSION['password_update'] = $_SESSION['onetime'] ? 2 : 1;
+                        <input class="form-control" name="pass" id="pass" <?php echo $_SESSION['onetime'] ?? null ? 'type="hidden" ' : 'type="password" '; ?> autocomplete="none" value="<?php echo attr($_SESSION['onetime'] ?? '');
```
Comment (bradymiller) [inline portal/index.php:362]: this line threw me off a bit. would put parenthesis around the `($_SESSION['onetime'] ?? null)`, then more clear

File: src/Patient/Cards/PortalCard.php [hunk 3]
```diff
@@ -71,7 +71,7 @@ private function setOpts()
         $this->opts = [
             'acl' => ['patients', 'dem'],
             'initiallyCollapsed' => (getUserSetting(self::CARD_ID . '_expand') == 0),
-            'add' => true,
+            'add' => false,
```
Comment (bradymiller) [inline src/Patient/Cards/PortalCard.php:74]: 118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a

File: templates/patient/partials/portal.html.twig [hunk 4]
```diff
@@ -28,20 +28,27 @@ The Patient Portal card for the Medical Record Dashboard
...
-
+    {% endif %}
 
     {% if isPortalAllowed == false %}
         <div class="alert alert-warning" role="alert">
             <p class="font-weight-bold">{{  "Portal Access"|xlt }}</p>
             <p> {{ "Allow Patient Portal in Choices."|xlt }} </p>
-        </div> 
+        </div>
+    {% elseif isContactEmail == false %}
```
Comment (bradymiller) [inline templates/patient/partials/portal.html.twig:38]: what happens if there is no contact email but not enforcing email for sign on?
(looks like nothing will show up)

Comment (bradymiller) [reply templates/patient/partials/portal.html.twig:38]: prob do:
```
{% elseif isContactEmail == false  and isEnforceSigninEmailPortal == true %}
```

File: interface/patient_file/summary/create_portallogin.php [hunk 5]
```diff
@@ -11,20 +11,25 @@
...
-use OpenEMR\Common\Csrf\CsrfUtils;
-use OpenEMR\Common\Twig\TwigContainer;
-use OpenEMR\Common\Utils\RandomGenUtils;
+use OpenEMR\Common\ {
+    Auth\AuthHash,
+    Csrf\CsrfUtils,
+    Logging\EventAuditLogger,
+    Twig\TwigContainer,
+    Utils\RandomGenUtils,
+};
```
Comment (bradymiller) [inline interface/patient_file/summary/create_portallogin.php:32]: haven't seen this before. is there documentation on this (to ensure will work on older php versions). thoughts by others on this?

File: portal/index.php (hunk 2 above)
Comment (bradymiller) [reply portal/index.php:362]: sorry for the confusion, i meant the line above (but also nicer on the line below :) )

File: interface/patient_file/summary/create_portallogin.php (hunk 5 above)
Comment (stephenwaite) [reply interface/patient_file/summary/create_portallogin.php:32]: think have put a few of these in the codebase in the recent past

https://www.php.net/manual/en/language.namespaces.importing.php#121785

Comment (bradymiller) [reply interface/patient_file/summary/create_portallogin.php:32]: since that comment is many years old, then no worries on older php versions :)
fine by me

File: interface/patient_file/summary/create_portallogin.php [hunk 6]
```diff
@@ -165,13 +170,22 @@ function filterTwigTemplateData($twig, $pid, $templateName, $data)
         error_log('OpenEMR Error : OpenEMR is not working because unable to create a hash.');
         die("OpenEMR Error : OpenEMR is not working because unable to create a hash.");
     }
-    array_push($query_parameters, $hash);
 
+    array_push($query_parameters, $hash);
     array_push($query_parameters, $pid);
+
+    EventAuditLogger::instance()->newEvent(
+        "patient access",
```
Comment (bradymiller) [inline interface/patient_file/summary/create_portallogin.php:178]: oops, just noted this. for this parameter, would not have spacing since think throws off parsing of it in logger code. would use dash instead `patient-access`

File: interface/patient_file/summary/create_portallogin.php [hunk 7]
```diff
@@ -165,13 +170,22 @@ function filterTwigTemplateData($twig, $pid, $templateName, $data)
...
+        $_SESSION['authUser'],
+        "Default",
```
Comment (bradymiller) [inline interface/patient_file/summary/create_portallogin.php:180]: also, here, best to use $_SESSION['authProvider']
(if we ever in future make use of that group thingy)

File: interface/patient_file/summary/create_portallogin.php (hunk 5 above)
Comment (sjpadgett) [reply interface/patient_file/summary/create_portallogin.php:32]: This was an issue prior to PHP 7 but okay now

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV

**Comment by stephenwaite** [comment]
jarosiewicz-mr-bean
