### PR TITLE
show issue type in 'add issue' form from encounter form

### LINKED ISSUE #7563: issue type not shown in encounter add issue form
when adding an issue from within an encounter form one must choose the type, but the names of types are not displayed next to the small radio buttons used to choose

### To Reproduce
 to reproduce, open an encounter form, either a new encounter or a pre-existing one. click 'add issue'
image

### Expected behavior
something like this
Screenshot from 2024-07-17 11-45-16

### Client configuration

- Browser: firefox
- OpenEMR version: 7.0.3-dev, 
- Operating system: ubuntu

### PR DESCRIPTION
**Pull request by ruthkonyn**
Fixes #7563

#### Short description of what this resolves:
 Type name not displayed next to radio button when choosing which issue type to add from an encounter form

#### Changes proposed in this pull request:
adds Type name to radio button when choosing which issue type to add from an encounter form

### CODE REVIEW

**Comment by see-k-er** [comment]
.

File: interface/patient_file/summary/add_edit_issue.php [hunk 1]
```diff
@@ -813,6 +813,7 @@ function divclick(cb, divid) {
                                             $disabled = (!AclMain::aclCheckIssue($key, '', ['write', 'addonly'])) ? " disabled" : '';
                                             $str = '<input type="radio" name="form_type" value="%s" onclick="newtype(%s)" %s %s>';
                                             echo vsprintf($str, [attr($index), attr_js($index), $checked, $disabled]);
+                                            echo text($value[1] . " "); /*rm - display issue type name */
```
Comment (bradymiller) [inline interface/patient_file/summary/add_edit_issue.php:816]: hi @ruthkonyn , fix looks and test well. Would also skip the radio button for when $key == 'medical_device' (ie. only process lines 815 and 816 when $key != 'medical_device') since that issue type is not supported by this toggle mechanism (if toggle on it, it is not correctly transitioned, and I don't think spending the work to support that would be worth the effort)

Comment (ruthkonyn) [reply interface/patient_file/summary/add_edit_issue.php]: thanks, have done this - apologies the commit message was slightly misstyped! - but i don't think there's an easy way to change the message? if it's important i can fix with a recommit

Comment (ruthkonyn) [reply interface/patient_file/summary/add_edit_issue.php]: one failing test "Test / PHP 8.3 - Apache - MariaDB 10.6 (pull_request) " which i think i can ignore?

Comment (adunsulag) [reply interface/patient_file/summary/add_edit_issue.php]: I'll re-run it.  That test is flaky sometimes with our CI engine and the way github throttles too many parallel test executions.

Comment (adunsulag) [reply interface/patient_file/summary/add_edit_issue.php]: @bradymiller if this looks fine now with the change, let's bring it in.

**Comment by bradymiller** [comment]
code looks good and bringing in. thanks for the fix @ruthkonyn !
