### PR TITLE
fix: default units to 1 for sales by item report

### LINKED ISSUE #7964: bug: sales by item report qty
### Describe the bug

if units for a procedure is null then it should default to 1 so that the number of procs can be added

Image

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7964

### CODE REVIEW

File: interface/reports/sales_by_item.php [hunk 1]
```diff
@@ -221,7 +223,7 @@ function thisLineItem($patient_id, $encounter_id, $rowcat, $description, $transd
         <?php } ?>
   <td class="detail">
             <?php if ($GLOBALS['sales_report_invoice'] == 0 || $GLOBALS['sales_report_invoice'] == 2) { ?>
-   <a href='../patient_file/pos_checkout.php?ptid=<?php echo attr_url($patient_id); ?>&enc=<?php echo attr_url($encounter_id); ?>'>
+   <a href='../patient_file/pos_checkout.php?ptid=<?php echo attr_url($patient_id); ?>&enc=<?php echo attr_url($encounter_id); ?>' target='_blank'>
```
Comment (bradymiller) [inline interface/reports/sales_by_item.php:226]: Need to add following attribute `rel='noopener'` for security reasons (basically locks out javascript from trying to do anything to the frame that this new frame originates from)
```
<a href='../patient_file/pos_checkout.php?ptid=<?php echo attr_url($patient_id); ?>&enc=<?php echo attr_url($encounter_id); ?>' target='_blank' rel='noopener'>

**Comment by bradymiller** [comment]
just noted one minor issue, otherwise looks great :)

File: interface/reports/sales_by_item.php (hunk 1 above)
Comment (stephenwaite) [reply interface/reports/sales_by_item.php]: did find the below at https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noopener 
Screenshot from 2025-02-05 12-32-35

Comment (bradymiller) [reply interface/reports/sales_by_item.php]: nice! Sound like not needed since an <a> element.

**Comment by adunsulag** [comment]
@stephenwaite I don't think your failures (php 8.4) are related to your code change.  I think its ok to bring this in.
