### PR TITLE
fix(billing): prevent sending blank statement emails

### LINKED ISSUE #10485: bug: emailLogin() sends blank email when message is empty
### Describe the bug

`emailLogin()` in `interface/billing/sl_eob_search.php` does not validate its `$message` parameter. If called with an empty string, it sends a blank email to the patient with the subject "[Facility Name] Patient Statement Bill" and an empty body.

### Expected behavior

`emailLogin()` should return early (or throw) when `$message` is empty rather than sending a blank email to a patient.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #10485

#### Short description of what this resolves:

`emailLogin()` silently sent blank emails when called with an empty or markup-only message, and all failure paths returned `false` which callers ignored.

#### Changes proposed in this pull request:

- `emailLogin()` throws instead of returning `false`: `InvalidArgumentException` for empty message (contract violation), `RuntimeException` for email validation, config, and send failures
- Call site (moved into the per-patient loop by #8327) catches `RuntimeException` and sets `$alertmsg`, so one patient's failure doesn't abort the batch
- Remove dead `upload_file_to_client_email()` function (sole call site removed by #8327)
- Add type annotations: native param/return types and PHPDoc `non-empty-string` constraint
- Replace `empty()` checks with explicit null/empty-string checks

#### Does your code include anything generated by an AI Engine? Yes

Claude Code (Claude Opus 4.5) was used to implement this fix.

### CODE REVIEW

File: interface/billing/sl_eob_search.php [hunk 1]
```diff
@@ -180,19 +180,30 @@ function era_callback(&$out): void
...
 
-function emailLogin($patient_id, $message)
+/**
+ * Email a patient statement bill.
+ *
+ * @param non-empty-string $message
+ * @throws \InvalidArgumentException if message has no text content
+ * @throws \RuntimeException if the email cannot be sent
+ */
+function emailLogin(int $patient_id, string $message): void
```
Comment (stephenwaite) [inline interface/billing/sl_eob_search.php:190]: thanks for fixing @kojiromike ! While here should this function name be improved and disambiguated from this [private function](https://github.com/openemr/openemr/blob/master/src/Services/PatientAccessOnsiteService.php#L254)?

Comment (kojiromike) [reply interface/billing/sl_eob_search.php:190]: @stephenwaite not part of this PR IMO. That's why I created #10487
