### PR TITLE
bug openemr 9619 fix gender unk code

### LINKED ISSUE #9620: bug: Fix openemr:generate-access-token when no offline_access scope is present
### Describe the bug

Attempt to generate an access token without an offline_access scope and the access token fails to validate due to missing trusted_user db record in the command generation flow.

```
php bin/console openemr-dev:api-generate-access-token -c HO7nZOliImyPJKZg2CtV5gBks9hOL4xMXBY9q5DPVNw --scopes=user/Patient.rs
```

When hitting an api endpoint for GET /apis/default/fhir/Patient you get an error message of 
"invalid Trusted User.  Refresh Token revoked or logged out"

### Expected behavior
Tokens should be usable w/o requiring a refresh token for offline_access.

### PR DESCRIPTION
**Pull request by adunsulag**
- **This fixes issue #9619 gender code**
- **Fixes #9620 generate access token**
- **Fix rector issues**

### CODE REVIEW

File: src/Services/FHIR/FhirPatientService.php [hunk 1]
```diff
@@ -377,18 +377,42 @@ private function parseOpenEMRPatientTelecom(FHIRPatient $patientResource, $dataR
...
-            }
-        }
+
+        // http://hl7.org/fhir/R4/valueset-administrative-gender.html
+        // 3.1.1,7.0.0 gender -> male | female | other | unknown
+
+        $genderValue = match($genderValue) {
+            'male','female' => $genderValue
+            // unk -> 'unknown' per HL7 spec
+            ,'unk' => 'unknown'
```
Comment (kojiromike) [inline src/Services/FHIR/FhirPatientService.php:412]: It seems odd to me that our phpcs/phpcbf doesn't have an opinion about the comma going here.
