### PR TITLE
Some sql upgrade mods

### LINKED ISSUE #3855: icd10 in rel-502 upgrade script
https://github.com/openemr/openemr/blob/d1cd5f8354c4560a04be21503300bea278d9be9c/sql/5_0_1-to-5_0_2_upgrade.sql#L605-L610

hi @bradymiller , is it okay to replace these lines with the 2020 files and was the previous commit okay without touching the version counter?

thank you

### LINKED ISSUE #3885: 5.0.3 upgrade sql v6.0
### Describe the bug
First pass hung up towards end.
Second pass gave below.
image

Third pass finished.

This is on my development database i've carried around since v4.1 so could be a fluke or bares watching.

### PR DESCRIPTION
**Pull request by sjpadgett**
- prevent custom module from including no exist bootstrap
- numerous sql upgrade improvements

Fixes #3885 

#### Short description of what this resolves:

See issue for more info

### CODE REVIEW

**Comment by sjpadgett** [comment]
one day i'll figure out why these past commits pop in my branches occasionally!

**Comment by bradymiller** [comment]
Difficult to test since don't have a mega database to test. Prob gonna figure out a quick way to add a million rows to something that is populating uuid's to be able to watch this in action.

**Comment by bradymiller** [comment]
ran this quick script to allow testing of this better (it added 10000 blank rows to procedure_result (which the ugprade script then added uuid's to)
```
<?php
$ignoreAuth = true; // no login required
require_once('interface/globals.php');
for ($i=0; $i<10000; $i++) {
    sqlStatement("INSERT INTO `procedure_result` (`date`) VALUES (NOW())");
}
echo "done";
?>
```

File: library/ajax/sql_server_status.php [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+ * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
+ */
+
+/*
+ * I wrote this mainly to show server activity for transaction intensive upgrades
+ * where the user can know we are still working though no activity from upgrade sequence.
+ * Not sure I can do csrf here!
+ * */
+
+$ignoreAuth = true;
```
Comment (bradymiller) [inline library/ajax/sql_server_status.php:19]: Regarding security, couldn't a bad actor just keep polling this script over web and collect data?

Gotta be a way to secure this, but too late to think clearly over here :)

Comment (sjpadgett) [reply library/ajax/sql_server_status.php:19]: yep, I'll get a csrf working for it. Polling has issues still where I may need to rethink some of it. Turning it off is proving a little stubborn.

File: sql_upgrade.php [hunk 2]
```diff
@@ -70,52 +72,141 @@
...
             </div>
         </div>
-        <div class="jumbotron p-4">
+        <div>
             <form class="form-inline" method='post' action='sql_upgrade.php'>
-                <div class="form-group mb-3">
-                    <label>Please select the prior release you are converting from:</label>
-                    <select class='ml-3 form-control' name='form_old_version'>
+                <div class="form-group mb-1">
+                    <label><?php echo xlt("Please select the prior release you are converting from"); ?>:</label>
```
Comment (bradymiller) [inline sql_upgrade.php:152]: One thing to always keep in mind is this script is running a "special" OpenEMR where the codebase is current but the database foorprint can be really old. This is the reason never added translations since wasn't sure where it may break in prior openemr database footprints (ie. if the query in the current codebase may have columns not in the old database footprint). However, the translation query and database elements have been stable for a long time (the only thing i thin added over last 10 years has been the rtl flag, which is not even used in the query, so I think we are at a point where running translations in this script is safe and makes sense. Thanks for doing this.

File: library/ajax/sql_server_status.php (hunk 1 above)
Comment (bradymiller) [reply library/ajax/sql_server_status.php:19]: If the csrf token is provided to the sql_upgrade.php script, though, then would just take a 1-2 punch to run this script (run sql_upgrade.php and scrape the csrf) to heart's content without auth.
We gotta figure out a way, though, to get this concept in. May need to figure out how to limit scope or where the calls originate from or go to, though.

File: sql_upgrade.php (hunk 2 above)
Comment (sjpadgett) [reply sql_upgrade.php:152]: Good point Brady. During doing this it was always in the back of my mind of hum, i'd of thought Brady would have done this by now so, now I know why. thanks.

File: library/ajax/sql_server_status.php (hunk 1 above)
Comment (sjpadgett) [reply library/ajax/sql_server_status.php:19]: Okay, i'm dwelling on it. Now that you've reminded me about legacy, makes it a little more difficult!
I'm now thinking that we add a flag to upgrade script to only use this feature for what we know to be long running upgrades.
And only then give user a button to take a snapshot of server activity if concerned where upgrade is activity wise.

Comment (bradymiller) [reply library/ajax/sql_server_status.php:19]: Note in this case, we could deal with legacy by adding anything needed to the database foorprint upfront. For example, if decided to store/retrieve from a new longtext field in version table called upgrade_status, then would just add this upfront if does not yet exist.

**Comment by sjpadgett** [comment]
Finally got back to this. Got language and rtl worked out:
image
I was going to add a heartbeat but, I think having server process scroll give enough clue as to status.

File: sql_upgrade.php [hunk 3]
```diff
@@ -69,81 +70,143 @@
...
+
+$res2 = sqlStatement("select * from lang_languages where lang_description = ?", array($GLOBALS['language_default']));
+for ($iter = 0; $row = sqlFetchArray($res2); $iter++) {
+    $result2[$iter] = $row;
+}
+
+if (count($result2) == 1) {
+    $defaultLangID = $result2[0]["lang_id"];
+    $defaultLangName = $result2[0]["lang_description"];
+    $direction = (int)$result2[0]["lang_is_rtl"] === 1 ? 'rtl' : 'ltr';
```
Comment (bradymiller) [inline sql_upgrade.php:82]: just note this lang_is_rtl field is rather new, so just make sure logic is ok if it doesn't exist

File: library/ajax/sql_server_status.php [hunk 4]
```diff
@@ -20,25 +20,33 @@
...
 require_once(__DIR__ . '/../../interface/globals.php');
 
+use OpenEMR\Common\Csrf\CsrfUtils;
+
+if (!empty($_POST)) {
+    if (!CsrfUtils::verifyCsrfToken($_POST["csrf_token_form"])) {
+        CsrfUtils::csrfNotVerified();
+    }
+}
+
```
Comment (bradymiller) [inline library/ajax/sql_server_status.php:30]: Bad actor can still attack this by running sql_upgrade, scraping csrf from it, and then running this script continually to capture random queries that are run on the server. This makes it harder but the vulnerability is still here. Even a auth user having access to this could be problematic (bad actor receptionist just collecting queries all day). Been putting thought into this and can't figure out a way to secure this thing. Again, late at night, though, so maybe just need some daylight :)

Comment (bradymiller) [reply library/ajax/sql_server_status.php:30]: If we could just tie this query to only ever be called by sql upgrade logic within the sql upgrade functions.

Comment (bradymiller) [reply library/ajax/sql_server_status.php:30]: Maybe a invisible iframe in sql-upgrade script that runs a script with these queries and stores them in temp place in sql column or drive that the polling script then collects from. Maybe option or would that also be vulnerable?

Comment (bradymiller) [reply library/ajax/sql_server_status.php:30]: Yep, I think that would also be vulnerable. Like an impossible game of chicken or the egg. brain hurts.
@sjpadgett , will need to await your fine mind to solve this dilemma :)

Comment (sjpadgett) [reply library/ajax/sql_server_status.php:30]: I put csrf in to lock down the sql query script. I'm only interested in activity so i'm going to only return the query command, ie alter,update, select etc.. 
If somebody wants to watch that scroll by all day, cool...

Comment (bradymiller) [reply library/ajax/sql_server_status.php:30]: sounds good. knew your fine mind would sort it out :)

Comment (sjpadgett) [reply library/ajax/sql_server_status.php:30]: yeah right, about as fine as wine in a carton!:) I'm prob fix this then bring in. I've got to quit these diversion and concentrate on onc...

Comment (bradymiller) [reply library/ajax/sql_server_status.php:30]: finer than my mind. i was gonna suggest just having the script return random uplifting quotes : https://www.davidmarotz.com/quotes.php
:)

**Comment by sjpadgett** [comment]
this should work
image

**Comment by sjpadgett** [comment]
made to make a little better sense. bringing in for testing...
image
