### PR TITLE
Fix qualifier defaulting for form Miscellaneous Billing Options for HCFA-1500

### LINKED ISSUE #8427: bug: MBO (Misc Billing Options) bugs
### Describe the bug

please see https://community.open-emr.org/t/claim-frequency-code-requirement/25665
and https://community.open-emr.org/t/question-about-lines-14-15-on-billing-forms/25549

there's also an older unaddressed issue, https://github.com/openemr/openemr/issues/1511

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by moussa854**
Fixes #8427 

#### Short description of what this resolves:
- Changed some radio buttons to dropdown menus.
- Fixed some wording to be consistent with the CMS-1500.
- Fixed auto-population of some fields.

#### Changes proposed in this pull request:

Converted Checkboxes to Dropdowns:

- "Box 10 A. Employment related"
- "Box 10 B. Auto Accident"
- "Box 10 C. Other Accident"
- "Box 20. Is Outside Lab used?" 
 
These fields were changed from checkboxes to dropdown menus, each offering "Yes", "No", and a blank default option. This allows for more explicit data entry (e.g., clearly selecting "No" which now saves as "0"). The backend saving logic in save.php was confirmed to be compatible with these changes.

Updated Field Labels:

- The label "Box 10 D. EPSDT Referral Code" was changed to "Box 10 D. Claim Codes (Designated by NUCC)".
- The label "Box 22. Medicaid Resubmission Code (ICD-10)" was changed to "Box 22. Resubmission Code".

Removed auto fill in boxes 14, 15, and 17

### CODE REVIEW

**Comment by stephenwaite** [comment]
Hi @moussa854, code looks good, thanks for the improvements!

See guidance on [file level doc block](https://www.open-emr.org/wiki/index.php/How_to_Document_Your_Code_Properly#File-Level_DocBlock) and add yourself to the author and copyright please for each of the files changed.

File: interface/forms/misc_billing_options/new.php [hunk 1]
```diff
@@ -97,42 +97,77 @@
...
+                        <span class="text"><?php echo xlt('Select Yes/No where appropriate'); ?><br /><br /></span>
                         <div class="form-group">
-                            <label><?php echo xlt('Box 10 A. Employment related'); ?>:
-                                <input type="checkbox" name="employment_related" id="box10a" value="1"
-                                    <?php
-                                    if (!empty($obj['employment_related']) && ($obj['employment_related'] == "1")) {
-                                        echo "checked";
-                                    } ?> />
-                            </label>
+                            <label for="employment_related"><?php echo xlt('Box 10 A. Employment related'); ?>:</label>
```
Comment (stephenwaite) [inline interface/forms/misc_billing_options/new.php:103]: above this would add a comment that the ai generated code by google-labs-jules starts

File: interface/forms/misc_billing_options/new.php [hunk 2]
```diff
@@ -97,42 +97,77 @@
...
+                                if (!empty($obj['employment_related']) && $obj['employment_related'] == "1") {
+                                    echo "selected";
+                                }
+                                ?>><?php echo xlt('Yes'); ?></option>
+                                <option value="0" <?php
+                                if (isset($obj['employment_related']) && $obj['employment_related'] == "0") {
+                                    echo "selected";
+                                }
+                                ?>><?php echo xlt('No'); ?></option>
+                            </select>
```
Comment (stephenwaite) [inline interface/forms/misc_billing_options/new.php:120]: then below this add a comment that the ai gen'ed code ends please

File: interface/forms/misc_billing_options/new.php [hunk 3]
```diff
@@ -97,42 +97,77 @@
...
                         </div>
                         <div class="form-row mt-3">
                             <div class="col-md">
-                                <label><?php echo xlt('Box 10 B. Auto Accident'); ?>:</label>
-                                <input type="checkbox" name="auto_accident" id="box10b" value="1"
-                                    <?php
-                                    if (!empty($obj['auto_accident']) && ($obj['auto_accident'] == "1")) {
-                                        echo "checked";
-                                    } ?> />
```
Comment (stephenwaite) [inline interface/forms/misc_billing_options/new.php:117]: same for this block

File: interface/forms/misc_billing_options/new.php [hunk 4]
```diff
@@ -97,42 +97,77 @@
...
                             </div>
                         </div>
                         <div class="form-group">
-                            <label><?php echo xlt('Box 10 C. Other Accident'); ?>:</label>
-                            <input type="checkbox" name="other_accident" id="box10c" value="1"
-                                <?php
-                                if (!empty($obj['other_accident']) && ($obj['other_accident'] == "1")) {
-                                    echo "checked";
-                                } ?> />
+                            <label for="other_accident"><?php echo xlt('Box 10 C. Other Accident'); ?>:</label>
```
Comment (stephenwaite) [inline interface/forms/misc_billing_options/new.php:154]: and this block too please

File: interface/forms/misc_billing_options/new.php [hunk 5]
```diff
@@ -234,22 +269,34 @@
                         </div>
                         <div class="form-row mt-3">
                             <div class="col-md">
-                                <label><?php echo xlt('Box 20. Is Outside Lab used?'); ?>:</label>
-                                <input type="checkbox" name="outside_lab" id="outside_lab" value="1"
-                                    <?php
-                                    if (!empty($obj['outside_lab']) && ($obj['outside_lab'] == "1")) {
-                                        echo "checked";
-                                    } ?> />
+                                <label for="outside_lab"><?php echo xlt('Box 20. Is Outside Lab used?'); ?>:</label>
```
Comment (stephenwaite) [inline interface/forms/misc_billing_options/new.php:281]: and this block too needs the ai used at the beginning and end of the changes please

File: library/options.inc.php [hunk 6]
```diff
@@ -236,10 +236,17 @@ function generate_select_list(
 
             $optionValue = attr($lrow ['option_id']);
 
+            // If $currvalue is explicitly an empty string, it should select the empty option,
```
Comment (stephenwaite) [inline library/options.inc.php:239]: would add a comment that the below logic was ai assisted by jules

File: src/Billing/MiscBillingOptions.php [hunk 7]
```diff
@@ -53,13 +53,21 @@ public function __construct()
 
     public function generateDateQualifierSelect($name, $options, $obj)
     {
-        echo     "<select name='" . attr($name) . "'>";
+        $current_value = $obj[$name] ?? null;
```
Comment (stephenwaite) [inline src/Billing/MiscBillingOptions.php:57]: finally this block of code please, sorry for the tediousness of this but maybe jules can help here too :)

**Comment by moussa854** [comment]
Done.
Next time I will ask Jules to mark the begining and end of changes

**Comment by stephenwaite** [comment]
thanks @moussa854 !

If you can fix the styling I think it's good to go. Can ignore the phpstan failing.

**Comment by moussa854** [comment]
It looks like everything passed except the phpstan

**Review by stephenwaite — APPROVED** [review]
Nice!

**Comment by stephenwaite** [comment]
thanks @moussa854, bringing in!
