### PR TITLE
fix: separate out pt and enc billing note

### LINKED ISSUE #7287: billing_note duplication
### Describe the bug

[This PR](https://github.com/openemr/openemr/pull/5843), adds the ability to edit the encounter billing note. However, since the textarea contains both the patient billing note and the encounter billing note, the encounter billing note will be incorrectly appended to and will continue to be duplicated each time the invoice form is saved, due to [this line](https://github.com/openemr/openemr/blob/00aebcde951ccbc13744b97341fe4c012c4eafa8/interface/billing/sl_eob_invoice.php#L435).

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7287

### CODE REVIEW

File: interface/billing/sl_eob_invoice.php [hunk 1]
```diff
@@ -430,9 +430,9 @@ function updateFields(payField, adjField, balField, coPayField, isFirstProcCode)
             }
         }
 
-        if ($_POST['billing_note']) {
+        if ($_POST['enc_billing_note']) {
             // save last closed level
```
Comment (surfacehazard) [inline interface/billing/sl_eob_invoice.php:434]: // save encounter billing note

**Comment by bradymiller** [comment]
2DV-2
