### PR TITLE
fix(portal): Save when using dd/mm/yyyy

### LINKED ISSUE #10228: Portal Appointment save fails.
### Describe the bug

Save fails for date in locale set to European date DD/MM.YYYY as reported on forum post.
### To Reproduce

Set config locale to DD/MM.YYYY,
Try to create an appointment in portal.

### Client configuration

- Browser: all
- OpenEMR version: 7.0.4
- Operating system:

### LINKED ISSUE #10235: Setup random fail with collate exception
### Describe the bug

Several issues posted on forum concerning collate not being passed a string value. in install setup
### Client configuration

- Browser:
- OpenEMR version:7.0.4
- Operating system: nginx apache

### PR DESCRIPTION
**Pull request by sjpadgett**
fix(portal): format date to system date for available event slots
fix(portal): translate error messages

Fixes #10228
Fixes #10235

### CODE REVIEW

File: tests/Tests/Isolated/Immunization/ImmunizationSqlInjectionFixTest.php [hunk 1]
```diff
@@ -178,10 +178,8 @@ public function testMultiplePatientIdsWithInvalidOnes(): void
     /**
      * Test empty patient_id handling
      */
-    public function testEmptyPatientId(): void
+    public function testEmptyPatientId($patient_id): void
```
Comment (sjpadgett) [inline tests/Tests/Isolated/Immunization/ImmunizationSqlInjectionFixTest.php]: @kojiromike Had to modify this currently unused test method for phpstan. Thought you'd want to see.

**Comment by sjpadgett** [comment]
thanks @kojiromike

**Comment by sjpadgett** [comment]
I think our test have it out for me!:)

File: tests/Tests/Isolated/Immunization/ImmunizationSqlInjectionFixTest.php (hunk 1 above)
Comment (kojiromike) [reply tests/Tests/Isolated/Immunization/ImmunizationSqlInjectionFixTest.php]: I think it's resolved now if you rebase.

Comment (sjpadgett) [reply tests/Tests/Isolated/Immunization/ImmunizationSqlInjectionFixTest.php]: yeah it's already resolved. thanks

**Comment by gl2007** [comment]
from this convo, seems like I have pull the code and merge it into 7.0.4 release? Otherwise would just taking the whole code from Github here and running would be wiser to avoid any other issues fixed but not yet released?
