### PR TITLE
fix: checking for empty user in AllergyIntoleranceService

### LINKED ISSUE #6930: bug: allergies are displayed with duplicates on upgrade to 7.0.2 due to missing user value in lists table
### Describe the bug

write concise description of what the bug is.

### To Reproduce

0. use the easy dev docker with demo data, `openemr-cmd drid`
1. Add a bunch of users who are not authorized, aka external providers, with the addr book or sql import the uploaded file
2. login as admin
3. click on Phil
4. notice repetitive values of penicillin

[external_providers.txt](https://github.com/openemr/openemr/files/12898434/external_providers.txt)

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6930

#### Short description of what this resolves:
adding a string search field checking to make sure a user value exists in lists prevents the sql statement from returning duplicates

#### Changes proposed in this pull request:
above and also check for empty string in users.npi

interestingly this will cause allergies to not display in the UI if a provider with an npi didn't enter it

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
actually, looks like getting lots of ci testing errors in services with this PR

**Comment by bradymiller** [comment]
Also, need to ensure allergies and other lists items in the ui do not depend on npi stuff. Is there a way to fix that?

**Comment by stephenwaite** [comment]
going to have to try and fix the phpunit test since have added a new parameter i think

**Comment by stephenwaite** [comment]
believe have got it correct now and 1 test will fail in the allergy intolerance service since the demo data allergy does not have an authorized user value

maybe we want to run something in the sql upgrade that assumes all allergies were entered by an authorized user

File: src/Services/AllergyIntoleranceService.php [hunk 1]
```diff
@@ -88,7 +88,7 @@ public function search($search, $isAndCondition = true)
             FROM users
             -- US CORE only allows physicians or patients to be our allergy recorder
             -- so we will filter out anyone who is not actually a practitioner (May 14th 2021)
-            WHERE users.npi IS NOT NULL -- we only want actual physicians here rather than all users
+            WHERE users.authorized = 1
```
Comment (bradymiller) [inline src/Services/AllergyIntoleranceService.php:91]: @adunsulag and @stephenwaite ,
Guessing this will break inferno since i recall weirdness where allergies needed to be associated with actual physicians.

The problem here is that allergies many time are entered in by staff and we really need to ensure that all allergies are shown/reported (ie. high risk of hurting patients if do not).

Would there be a way to get around this?

File: sql/7_0_1-to-7_0_2_upgrade.sql [hunk 2]
```diff
@@ -577,4 +577,11 @@ ALTER TABLE `x12_partners` ADD COLUMN `x12_claim_status_endpoint` tinytext;
 
 #IfMissingColumn x12_partners x12_attachment_endpoint
 ALTER TABLE `x12_partners` ADD COLUMN `x12_attachment_endpoint` tinytext;
+#EndIf
+
+#IfRow lists type allergy
+SET @username = (SELECT `username` FROM `users` WHERE `authorized` = 1 AND `active` = 1 LIMIT 1);
+UPDATE `lists` SET `user` = @username WHERE `type` = 'allergy' AND (`user` = '' OR `user` IS NULL);
+SET @user = (SELECT `user` FROM `lists` WHERE `type` = 'allergy');
```
Comment (stephenwaite) [inline sql/7_0_1-to-7_0_2_upgrade.sql:585]: looks like will have to create a special function in `SQLUpgradeService` to update each user who's `npi` is empty since this will fail when the subquery returns more than 1 row

File: src/Services/AllergyIntoleranceService.php (hunk 1 above)
Comment (stephenwaite) [reply src/Services/AllergyIntoleranceService.php]: doesn't seem practical or realistic for inferno to require only physicians to enter allergies

registered nurses are a good example of a clinician who wouldn't have an npi

Comment (stephenwaite) [reply src/Services/AllergyIntoleranceService.php]: registered nurses probably are under the purview of a physician or other practitioner who does have an npi so that is a fallback

that might mean reworking the allergy issue input as well then

Comment (adunsulag) [reply src/Services/AllergyIntoleranceService.php]: @stephenwaite looking at the specification, it is nullable.  So we can remove the NPI check but what we will need to do is return the NPI number as part of the service and then check in the FHIR service for the NPI number.  If the NPI number is null we don't populate the recorder.  We'd want to test it all with inferno, but I think that will address this issue.


Essentially in FHIRAllergyIntoleranceService.php:L166-L170 it becomes:
```php
if (isset($dataRecord['practitioner']) && !empty($dataRecord['practitioner_npi']) {
            $recorder = new FHIRReference();
            $recorder->setReference('Practitioner/' . $dataRecord['practitioner']);
            $allergyIntoleranceResource->setRecorder($recorder);
        }
```

AllergyIntoleranceService.php then becomes:
```php
$sql = "SELECT lists.*,
        lists.pid AS patient_id,
        lists.title,
        lists.comments,
        practitioners.uuid as practitioner,
        practitioners.practitioner_npi,
        practitioners.practitioner_uuid,
        // .....
        LEFT JOIN (
            select
            users.uuid
            ,users.uuid AS practitioner_uuid
            ,users.npi AS practitioner_npi,
            ,users.username
            ,users.facility AS organization
            FROM users
            -- US CORE only allows physicians or patients to be our allergy recorder
            -- so we will filter out anyone who is not actually a practitioner (May 14th 2021)
            WHERE users.npi IS NOT NULL -- we only want actual physicians here rather than all users
        ) practitioners ON practitioners.username = lists.user
        // .....
```

Comment (stephenwaite) [reply src/Services/AllergyIntoleranceService.php]: what's the link to the spec?

Comment (adunsulag) [reply src/Services/AllergyIntoleranceService.php]: https://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-allergyintolerance.html  They have the differential table, but if you click on the full view it will show the recorder property.

Comment (stephenwaite) [reply src/Services/AllergyIntoleranceService.php]: thanks @adunsulag

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear
