### PR TITLE
fix(reports): prevent inflated totals in Financial Summary by Service Code

### LINKED ISSUE #8651: Financial Summary by Service Code report incorrect totals
The codes database table allows for multiple rows with the same code but varied modifiers.

This clause in the query to populate the Financial Summary by Service Code report does not account for that:

https://github.com/openemr/openemr/blob/551ea97338336d52e9d0e880d8c52c62081d14c8/interface/reports/svc_code_financial_report.php#L224

This results in an incorrect calculation of the totals included in the report, as the amounts for a particular code will be multiplied by how many times it appears in the codes table.

Modifying the line to the following would fix the issue:

`"LEFT JOIN (select code, max(financial_reporting) as financial_reporting from codes group by code) AS c ON c.code = b.code " .`

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #8651

#### Short description of what this resolves:

The Financial Summary by Service Code report produces inflated totals (billed, paid, adjusted, balance) when the `codes` table contains multiple rows for the same code value with different modifiers.

#### Changes proposed in this pull request:

**Primary fix — Cartesian product on codes JOIN:**

The `LEFT OUTER JOIN codes AS c ON c.code = b.code` matches every modifier variant, creating a Cartesian product that multiplies all SUM aggregates. For example, if code `99213` has 3 modifier rows in `codes`, every billing row for that code gets tripled.

Replace the direct join with a subquery that collapses modifier variants via `GROUP BY code, code_type`, and join on both `code` and `code_type` (through `code_types.ct_id`):

```sql
-- Before (buggy):
LEFT OUTER JOIN codes AS c ON c.code = b.code

-- After (fixed):
INNER JOIN code_types AS ct ON ct.ct_key = b.code_type AND ct.ct_fee = '1'
LEFT OUTER JOIN (
    SELECT code, code_type, MAX(financial_reporting) AS financial_reporting
    FROM codes
    GROUP BY code, code_type
) AS c ON c.code = b.code AND c.code_type = ct.ct_id
```

**Additional fixes to pre-existing query bugs:**

- `c.financial_reporting` was in SELECT without aggregation or GROUP BY — non-deterministic when a code maps to multiple code types. Wrapped in `MAX()`.
- `ORDER BY fe.date, fe.id` without those columns in GROUP BY — non-deterministic. Simplified to `ORDER BY b.code`.
- "Important Codes" filter used `WHERE c.financial_reporting = '1'` which excludes billing rows before aggregation. Moved to `HAVING MAX(c.financial_reporting) = '1'` so all billing amounts are included for codes that have any financial_reporting flag.
- `Balance` column redundantly recomputed all three SUMs in SQL. Now computed in the DTO from `billed - paid - adjusted`.

**Refactoring:**

- Extract query logic into `FinancialSummaryReportService` with a `ServiceCodeSummary` readonly DTO
- Service accepts `DateTimeInterface` for date params, `?int` for facility/provider (null = all)
- Report file handles only rendering; type conversion from POST strings happens at the boundary

**Tests:**

- 7 integration tests: single code, duplicate modifiers (core bug), financial reporting filter, MAX across modifiers, facility filter, provider filter, LEFT JOIN null behavior
- 4 e2e browser tests: page load, empty submit, correct totals, important codes filter, duplicate modifier non-inflation

**Note:** The `ar_activity` subquery groups by `(pid, encounter, code)` without `modifier`, which can cause a similar inflation when billing has multiple rows for the same `(pid, encounter, code)` with different modifiers. This is a separate pre-existing bug and should be filed as its own issue.

#### If you answered yes: Verify that each file that has AI generated code has a description that describes what AI engine was used and that the file includes AI generated code. Sections of code that are entirely or mostly generated by AI should be marked with a comment header and footer that includes the AI engine used and stating the code was AI.

All new files (`ServiceCodeSummary.php`, `FinancialSummaryReportService.php`, `FinancialSummaryReportServiceTest.php`, `SvcCodeFinancialReportTest.php`) and the modifications to `svc_code_financial_report.php` were generated with Claude Code (Claude Opus 4.5).

### CODE REVIEW

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+            $binds[] = $providerId;
+        }
+
+        if ($financialReportingOnly) {
+            $query .= " AND c.financial_reporting = '1'";
+        }
+
+        $query .= ' GROUP BY b.code ORDER BY b.code, fe.date, fe.id';
+
+        $records = QueryUtils::fetchRecords($query, $binds);
```
Comment (kojiromike) [inline src/Services/Reports/FinancialSummaryReportService.php:101]: Perhaps the DTO should have a `fromArray` method so we can get to sanity quicker.

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+        if (!is_array($records)) {
+            return [];
+        }
+
+        $results = [];
+        foreach ($records as $record) {
+            if (!is_array($record)) {
+                continue;
```
Comment (kojiromike) [inline src/Services/Reports/FinancialSummaryReportService.php]: how could a single row not be an array?

File: src/Services/Reports/FinancialSummaryReportService.php (hunk 1 above)
Comment (kojiromike) [reply src/Services/Reports/FinancialSummaryReportService.php:101]: Added `ServiceCodeSummary::fromArray()` and removed the defensive guards. The `is_array` checks were scaffolding to satisfy PHPStan level 10 on `mixed` types from `fetchRecords()` — replaced with a `@var` annotation on the return value.

File: src/Services/Reports/ServiceCodeSummary.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+ * @package   OpenEMR
+ * @link      http://www.open-emr.org
+ * @author    Michael A. Smith <michael@opencoreemr.com>
+ * @copyright Copyright (c) 2026 OpenCoreEMR Inc <https://opencoreemr.com/>
+ * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
+ */
+
+namespace OpenEMR\Services\Reports;
+
+class ServiceCodeSummary
```
Comment (Firehed) [inline src/Services/Reports/ServiceCodeSummary.php]:
```suggestion
readonly class ServiceCodeSummary
```
and make the constructor args normal

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+            $query .= " AND c.financial_reporting = '1'";
+        }
+
+        $query .= ' GROUP BY b.code ORDER BY b.code, fe.date, fe.id';
+
+        /** @var array<int, array{code: string, units: string, billed: string, PaidAmount: string, AdjustAmount: string, Balance: string, financial_reporting: string|null}> $records */
+        $records = QueryUtils::fetchRecords($query, $binds);
+
+        $results = [];
+        foreach ($records as $record) {
```
Comment (Firehed) [inline src/Services/Reports/FinancialSummaryReportService.php]: style: `array_map(ServiceCodeSummary::fromArray(...), $records)`?

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+namespace OpenEMR\Services\Reports;
+
+use OpenEMR\Common\Database\QueryUtils;
+
+class FinancialSummaryReportService
+{
+    /**
+     * Get financial summary data grouped by service code.
+     *
+     * @param string $fromDate Start date in YYYY-MM-DD format
```
Comment (Firehed) [inline src/Services/Reports/FinancialSummaryReportService.php]: It's probably asking too much right now, but if this could take actual `DateTimeInterface` params, it'd be lovely.

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 6]
```diff
@@ -0,0 +1,108 @@
...
+     * @param string $toDate   End date in YYYY-MM-DD format
+     * @param int    $facilityId Filter by facility (0 = all)
+     * @param int    $providerId Filter by provider (0 = all)
+     * @param bool   $financialReportingOnly Limit to codes flagged for financial reporting
+     * @return ServiceCodeSummary[]
+     */
+    public function getServiceCodeSummary(
+        string $fromDate,
+        string $toDate,
+        int $facilityId = 0,
```
Comment (Firehed) [inline src/Services/Reports/FinancialSummaryReportService.php]: Seeing the only (?) call site, I don't think there's any reason for these to be optional params with defaults.

I also am not a fan of the `0 == all` thing (and especially not the `$facilityId > 0` later on); `?int` and null checks would be a bit more semantically accurate.

File: src/Services/Reports/FinancialSummaryReportService.php [hunk 7]
```diff
@@ -0,0 +1,108 @@
...
+            SQL;
+        $binds[] = $fromDate . ' 00:00:00';
+        $binds[] = $toDate . ' 23:59:59';
+
+        if ($facilityId > 0) {
+            $query .= ' AND fe.facility_id = ?';
+            $binds[] = $facilityId;
+        }
+
+        if ($providerId > 0) {
```
Comment (Firehed) [inline src/Services/Reports/FinancialSummaryReportService.php]: See comment in constructor; applies to check above as well.

File: src/Services/Reports/ServiceCodeSummary.php (hunk 3 above)
Comment (kojiromike) [reply src/Services/Reports/ServiceCodeSummary.php]: Done — switched to `readonly class` with normal constructor args.

File: src/Services/Reports/FinancialSummaryReportService.php (hunk 4 above)
Comment (kojiromike) [reply src/Services/Reports/FinancialSummaryReportService.php]: Done — `array_map(ServiceCodeSummary::fromArray(...), $records)`

File: src/Services/Reports/FinancialSummaryReportService.php (hunk 6 above)
Comment (kojiromike) [reply src/Services/Reports/FinancialSummaryReportService.php]: Done — changed to `?int` with `null` defaults and `\!== null` checks. The report file now converts the POST values to `?int` at extraction time (null = all, int = filter to that ID).

File: src/Services/Reports/FinancialSummaryReportService.php (hunk 5 above)
Comment (kojiromike) [reply src/Services/Reports/FinancialSummaryReportService.php]: Agreed that would be nicer. Leaving as-is for now since the report file hands us raw strings from POST, but it would be a good follow-up.

Comment (kojiromike) [reply src/Services/Reports/FinancialSummaryReportService.php]: I changed Claude's mind and made it go with DateTimes anyway

**Comment by kojiromike** [comment]
@Firehed ready for re-review

**Review by Firehed — APPROVED** [review]

**Comment by stephenwaite** [comment]
Super fix @kojiromike ! Suppose you wanted a summary for every code/modifier pair in the codes table in case that was interesting or important to the A/R team. I guess that would be a new feature :)

**Comment by kojiromike** [comment]
@stephenwaite sounds like it.
