### PR TITLE
Validations view Development

### LINKED ISSUE #5328: CCDA detail view in Export missing style
Invalid file name.

### LINKED ISSUE #5357: Insurance and Address Services are broken.
### Describe the bug
On new insurance company insert, false is always return causing the new fresh id to not be returned and a new address entry is missed.

The workflow assumption is that after insert, the new table record id is fetched from the newly created record. If only this was true and normally it would be. 

However, insurance_companies and address table do not use auto increment thus will not generate a new record id whereas the returned value from action will be 0 or false. Current logic traps for empty as a failed insert causing a returned false.

Simply put, if table id is not an auto increment then doesn't have a value to return. We should get a helpful die on fail however, unsure that will percolate to user.

### PR DESCRIPTION
**Pull request by sjpadgett**
- fix missing style sheet in export detail view

Fixes #5328 Fixes #5357

#### Short description of what this resolves:
Develop view in CCM import for validation results of schematron and XSD.

### CODE REVIEW

**Comment by sjpadgett** [comment]
Have to find a way to merge qrda duplicate patient that send content with no association with an encounter. This makes no sense no matter how you look at it from an emr POV. 

image

If I didn't care so much about the community, I'd be all over ONC concerning this. What emr generates qrda with only an observation. In cda you could have a relationship template to show the relationship to its encounter via id extension. QRDA only gives date which appears to be same date as encounter of the template housing the rest of the report. 

I guess I'll pull down all patients from SLI test setup and go through them and check for this scenario. Was not an issue in all my testing on the 6.2.2 cypress where I found this after setting up a 6.3.0 cypress on our test cypress.

@stephenwaite Since it may take a minute for me to get approved on SLI site, would you download all patients and email to me?

**Comment by sjpadgett** [comment]
Looks like we can't pull down known good as SLI is not in debug mode so, there goes the easy way! And sure enough, first measure has dupl for merge where our merge will add the encounter I create on import when needed to populate an imported encounter form. BMI observation in this case.
I don't know why I document this stuff but I hope it will trigger a thought of "Oh yeah, I saw that somewhere!" at some point.:)

image

**Comment by sjpadgett** [comment]
@adunsulag Here is how I manage validation for UI

image

**Comment by sjpadgett** [comment]
no errors

image

**Comment by sjpadgett** [comment]
@bradymiller If you're around and want to beat me up, soon'd be the time.:)
I want to merge as some critical stuff here for testing.

**Comment by sjpadgett** [comment]
@adunsulag Is this what you need or is it some intertwined author?

```
  <informant>
    <assignedEntity>
      <id root="2.16.840.1.113883.19.5"/>
      <representedOrganization>
        <id root="2.16.840.1.113883.19.5"/>
      </representedOrganization>
    </assignedEntity>
  </informant>
```

**Comment by adunsulag** [comment]
@sjpadgett This is the specific error:
Error - Consol Referral Note (V2) SHALL contain exactly one [1..1] informationRecipient, where its type is Information Recipient (CONF:1198-31589)

Looks like it comes from this rule:
SHALL contain exactly one [1..1] informationRecipient (CONF:1198-31589).
This informationRecipient SHALL contain exactly one [1..1] intendedRecipient (CONF:1198-31590).
This intendedRecipient SHOULD contain zero or more [0..*] addr (CONF:1198-31591).
This intendedRecipient SHOULD contain zero or more [0..*] telecom (CONF:1198-31592).
This intendedRecipient SHALL contain exactly one [1..1] informationRecipient (CONF:1198-31593).
This informationRecipient SHALL contain at least one [1..*] US Realm Person Name (PN.US.FIELDED) (identifier: 2.16.840.1.113883.10.20.22.5.1.1) (CONF:1198-31594).

From here: http://www.hl7.org/ccdasearch/templates/2.16.840.1.113883.10.20.22.1.14.html

**Comment by sjpadgett** [comment]
> Error - Consol Referral Note (V2)

what test do you get this. this is strange and I can't find an example of what this is suppose to look like

File: src/Services/Cda/CdaValidateDocuments.php [hunk 1]
```diff
@@ -119,20 +134,19 @@ public function validateXmlXsd($document, $type)
...
-        } else {
+
+        $xsd_log['xsd'] = [];
+        if (!$dom->schemaValidate($xsd)) {
             $errors = libxml_get_errors();
             foreach ($errors as $error) {
-                error_log($this->formatXsdError($error));
+                $detail = $this->formatXsdError($error);
+                $xsd_log['xsd'][] = $detail;
+                error_log($detail);
```
Comment (bradymiller) [inline src/Services/Cda/CdaValidateDocuments.php:144]: looks like a lingering debug line

Comment (bradymiller) [reply src/Services/Cda/CdaValidateDocuments.php:144]: oh wait, looks like it is meant to be there to report errors :)

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php [hunk 2]
```diff
@@ -174,7 +176,7 @@ public function importNewPatient($document): void
      * @param   $document_id    Document id
      */
 
-    public function importCore($xml_content)
+    public function importCore($xml_content, $doc_id = null)
```
Comment (bradymiller) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:179]: would just make sure this function also works if $doc_id is null (ie. skip places that need it) since there is an option to import ccda's without saving the actual ccda in the documents:
https://github.com/openemr/openemr/blob/master/contrib/util/ccda_import/import_ccda.php#L18-L22

**Comment by bradymiller** [comment]
2DV (1)

**Review by bradymiller — APPROVED** [review]

**Comment by adunsulag** [comment]
@sjpadgett great work on all of this.  As far as that error.  I think they have an erroneous output of 'Consul' as the error is with the Referral Note template and its coming from the ETT tool.
