### PR TITLE
fix(db): rename misspelled 'declne_to_specfy' value in race

### LINKED ISSUE #10385: fix: rename misspelled 'declne_to_specfy' value in race list options
## Summary

The `race` list option contains a misspelled value `declne_to_specfy` that should be `decline_to_specify`.

## Location

- Table: `list_options` (likely `list_id = 'race'`)
- Current value: `declne_to_specfy`
- Correct value: `decline_to_specify`

## Code reference

`src/Services/FHIR/FhirPatientService.php:437` has a workaround with a TODO comment:

```php
if ($race === 'declne_to_specfy') { // TODO: we should rename this misspelled value in the database
```

## Required changes

1. Add SQL migration to rename the value in `list_options`
2. Update any `patient_data` records that reference this value
3. Remove the hardcoded workaround in `FhirPatientService.php`

## Notes

This is a data migration, not just a code change. Need to ensure backwards compatibility for existing patient records.

### PR DESCRIPTION
**Pull request by phantom930**
Fixes #10385 

# Summary
The race list option contains a misspelled value `declne_to_specfy` that should be `decline_to_specify`.

# Changes proposed in this pull request
- Added SQL migration to rename the value in `list_options`
- Updated any `patient_data` records that reference this value
- Removed the hardcoded workaround in `FhirPatientService.php`
- Ensured backwards compatibility for existing patient records.

### CODE REVIEW

File: interface/procedure_tools/ereqs/ereq_universal_form.php [hunk 1]
```diff
@@ -346,7 +346,7 @@ function ereqForm($pid, $encounter, $form_id, $reqStr = null, $doDoc = true, $gb
         $pdfContent .= '<table class="cor-edi-main-table" style="margin-bottom:6px;">';
         $pdfContent .= '<tbody>';
         $pdfContent .= '<tr>';
-        $race = ["declne_to_specfy" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
+        $race = ["decline_to_specify" => 9, "decline_to_specify" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
```
Comment (kojiromike) [inline interface/procedure_tools/ereqs/ereq_universal_form.php]:
```suggestion
        $race = ["decline_to_specify" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
```

File: interface/procedure_tools/labcorp/ereq_form.php [hunk 2]
```diff
@@ -346,7 +346,7 @@ function ereqForm($pid, $encounter, $form_id, $reqStr = null, $doDoc = true, $gb
         $pdfContent .= '<table class="cor-edi-main-table" style="margin-bottom:6px;">';
         $pdfContent .= '<tbody>';
         $pdfContent .= '<tr>';
-        $race = ["declne_to_specfy" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
+        $race = ["decline_to_specify" => 9, "decline_to_specify" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
```
Comment (kojiromike) [inline interface/procedure_tools/labcorp/ereq_form.php]:
```suggestion
        $race = ["decline_to_specify" => 9, "amer_ind_or_alaska_native" => 3, "Asian" => 4, "black_or_afri_amer" => 2, "native_hawai_or_pac_island" => 5, "white" => 1];
```

File: sql/8_0_1-to-8_0_2_upgrade.sql
Comment (kojiromike) [inline sql/8_0_1-to-8_0_2_upgrade.sql:1]: This should be sql/8_0_0-to-8_0_1_upgrade.sql

File: interface/procedure_tools/ereqs/ereq_universal_form.php (hunk 1 above)
Comment (phantom930) [reply interface/procedure_tools/ereqs/ereq_universal_form.php]: Resolved it

File: interface/procedure_tools/labcorp/ereq_form.php (hunk 2 above)
Comment (phantom930) [reply interface/procedure_tools/labcorp/ereq_form.php]: Resolved it

File: sql/8_0_1-to-8_0_2_upgrade.sql
Comment (phantom930) [reply sql/8_0_1-to-8_0_2_upgrade.sql:1]: @kojiromike , Moved it to `sql/8_0_0-to-8_0_1_upgrade.sql`

**Review by kojiromike — APPROVED** [review]

**Comment by phantom930** [comment]
@kojiromike I just resolved the white space hook issue and waiting for your approval for workflows

**Comment by kojiromike** [comment]
@phantom930 thanks for the contribution!

File: sql/8_0_0-to-8_0_1_upgrade.sql [hunk 3]
```diff
@@ -137,3 +137,25 @@ INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`) VALUES ('org
...
+UPDATE `list_options` SET `option_id` = 'decline_to_specify' WHERE `list_id` = 'race' AND `option_id` = 'declne_to_specfy';
+#EndIf
+
+#IfRow2D list_options list_id language option_id declne_to_specfy
+UPDATE `list_options` SET `option_id` = 'decline_to_specify' WHERE `list_id` = 'language' AND `option_id` = 'declne_to_specfy';
+#EndIf
+
+#IfRow2D list_options list_id ethrace option_id declne_to_specfy
+UPDATE `list_options` SET `option_id` = 'decline_to_specify' WHERE `list_id` = 'ethrace' AND `option_id` = 'declne_to_specfy';
+#EndIf
```
Comment (bradymiller) [inline sql/8_0_0-to-8_0_1_upgrade.sql:161]: @phantom930  , missing `ethnicity` block on the above #IfRow2D stuff

File: sql/8_0_0-to-8_0_1_upgrade.sql [hunk 4]
```diff
@@ -137,3 +137,25 @@ INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`) VALUES ('org
...
 ALTER TABLE `facility` ADD `organization_type` VARCHAR(50) NOT NULL DEFAULT 'prov' COMMENT 'Organization type as defined by HL7 Value Set: OrganizationType';
 #EndIf
+
+--
+-- Rename the misspelled list_options option_id from 'declne_to_specfy' to 'decline_to_specify',
+-- and update any patient_data.race records that reference the old value.
+-- See: https://github.com/openemr/openemr/issues/10385
+--
+
+#IfColumn patient_data race
```
Comment (bradymiller) [inline sql/8_0_0-to-8_0_1_upgrade.sql:147]: @phantom930 , to completely skip this when not needed would do this instead
```
#IfRow patient_data race declne_to_specfy
```

Also need to convert for these columns in patient_data:
language
ethnicity

**Comment by bradymiller** [comment]
hi @kojiromike , I don't think the database issues in this PR were addressed.

File: sql/8_0_0-to-8_0_1_upgrade.sql (hunk 4 above)
Comment (bradymiller) [reply sql/8_0_0-to-8_0_1_upgrade.sql:147]: hi @kojiromike ,
Confirmed this was addressed in following fixes for master and rel-810:
https://github.com/openemr/openemr/pull/11876
https://github.com/openemr/openemr/pull/11893

(however see below for a fix that has not yet been brought in)

File: sql/8_0_0-to-8_0_1_upgrade.sql (hunk 3 above)
Comment (bradymiller) [reply sql/8_0_0-to-8_0_1_upgrade.sql:161]: hi @kojiromike ,
This one was not addressed yet. Sorry it took so long for me to look at this (ie. couple days from release).

Confirmed this was NOT addressed in following PRs for master and rel-810:
https://github.com/openemr/openemr/pull/11876
https://github.com/openemr/openemr/pull/11893

File: sql/8_0_0-to-8_0_1_upgrade.sql (hunk 4 above)
Comment (bradymiller) [reply sql/8_0_0-to-8_0_1_upgrade.sql:147]: ~~hi @kojiromike , oh goodness, I just noted that `ethrace` also need a block here.~~
(disregard above striked out comment; not a column in patient_data, so not needed)
