### PR TITLE
custom delete form for procedure and change to associated Qdm service

### LINKED ISSUE #5358: procedure form delete doesn't mark procedure_order as deleted
### Describe the bug

when you delete the procedure form from the encounter the associated procedure_order_id should be marked as deleted

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5358

### CODE REVIEW

File: interface/forms/procedure_order/delete.php [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+                </form>
+            </div>
+        </div>
+    </div>
+<script>
+// jQuery stuff to make the page a little easier to use
+
+$(function () {
+    $("#confirmbtn").on("click", function() { return ConfirmDelete(); });
+    $("#cancel").on("click", function() { location.href='<?php echo "$rootdir/patient_file/encounter/$returnurl";?>'; });
```
Comment (bradymiller) [inline interface/forms/procedure_order/delete.php:112]: since javascript context would do following for escaping (note removal of the single quotes):
```
$("#cancel").on("click", function() { location.href=<?php echo js_escape("$rootdir/patient_file/encounter/$returnurl"); ?>; });
```

File: interface/forms/procedure_order/delete.php [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+ * @copyright Copyright (c) 2022 Stephen Waite <stephen.waite@cmsvt.com>
+ * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
+ */
+
+require_once("../../globals.php");
+require_once($GLOBALS['srcdir'] . "/forms.inc");
+
+use OpenEMR\Common\Csrf\CsrfUtils;
+use OpenEMR\Common\Logging\EventAuditLogger;
+use OpenEMR\Core\Header;
```
Comment (bradymiller) [inline interface/forms/procedure_order/delete.php:23]: should have a acl check here

**Comment by bradymiller** [comment]
just noted 2 minor isssues

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
2DV
