### PR TITLE
Fixes #2324 Rest API Fatal Error.

### LINKED ISSUE #2324: Rest API Fatal Error if site id is invalid
So I ran the CURL API request with basic default data but had no idea what to put for scope so I left it as site id.  It triggers a fatal error because it cannot find the translation text() function on line 133  
```
curl -X POST -H 'Content-Type: application/json' 'http://172.20.0.4/apis/api/auth' \
-d '{
    "grant_type":"password",
    "username": "admin",
    "password": "pass",
    "scope":"site id" 
}'
````
Error log:
```
[Mon Mar 25 21:12:20.252255 2019] [php7:error] [pid 560] [client 172.20.0.1:59780] PHP Fatal error:  Uncaught Error: Call to undefined function text() in /var/www/localhost/htdocs/openemr/interface/globals.php:133\nStack trace:\n#0 /var/www/localhost/htdocs/openemr/apis/dispatch.php(67): require_once()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/globals.php on line 133
```

I believe its a simple fix of just requiring once the htmlspecialchars.inc.php file.  I will submit a pull request for the fix as well as update the API documentation about the site id information.

### PR DESCRIPTION
**Pull request by adunsulag**
The Rest API was fatally failing if you sent an invalid site id.  The code was using the escape function of text() but that file is not loaded until later on in the codebase.  I could have moved the load order of the files so that composer (which in turn loads htmlspecialchars.inc.php) would load earlier, but this appeared to be the safer approach to minimize any system changes by just calling htmlspecialchars(..) directly.

Also documented what the scope parameter is supposed to be in the REST API as it was unclear with the example 'site id' for a newcomer to the system.

### CODE REVIEW

File: interface/globals.php [hunk 1]
```diff
@@ -130,8 +130,11 @@
         }
     }
 
+    // for both REST API and browser access we can't proceed unless we have a valid site id.
+    // since this is user provided content we need to escape the value but we use htmlspecialchars instead
+    // of text() as our helper functions are loaded in later on in this file.
     if (empty($tmp) || preg_match('/[^A-Za-z0-9\\-.]/', $tmp)) {
-        die("Site ID '". text($tmp) . "' contains invalid characters.");
+        die("Site ID '". htmlspecialchars($tmp, ENT_NOQUOTES) . "' contains invalid characters.");
```
Comment (sjpadgett) [inline interface/globals.php]: I thinking this isn't the right place to do this. Best to qualify the request in the rest interface and return a 401 or 404 back to client. Not sure how we would do that before globals is loaded. Or, one really should not echo back where a login or credential check fails. Just saving hackers time:). So really, that error in globals should be Invalid Url...

Comment (bradymiller) [reply interface/globals.php]: This change makes sense (no matter what do for the rest interface) since text() is being called before it is even defined. I'd bring this change in for core OpenEMR fix and then work on a rest interface solution separately.

Comment (adunsulag) [reply interface/globals.php]: If I knew enough of the system I would do what you suggested @sjpadgett as that would be my preference from a security and just good API best practice.  For the new developer I'd also throw the error into the error log so the developer could know what went wrong while keeping information from the hacker.  I'm just learning the system however, so I did the minimum to avoid the fatal error and a more comprehensive overhaul of the REST process flow is warranted.

Comment (adunsulag) [reply interface/globals.php]: @sjpadgett Reading your request I see you want me to just change the verbiage to invalid url.  I can make that change and still log the error for the developer.

Comment (sjpadgett) [reply interface/globals.php]: Nope just leave as is and we'll let the security folks determine after review all our similar messages.
If you're done, i'll bring in..

Comment (adunsulag) [reply interface/globals.php]: I guess I was too aggressive :)  I went ahead and changed it to be the invalid url format and pushed it while logging the error.  I won't touch it at this point and y'all can tell me how to proceed.

File: interface/globals.php [hunk 2]
```diff
@@ -134,7 +134,9 @@
     // since this is user provided content we need to escape the value but we use htmlspecialchars instead
     // of text() as our helper functions are loaded in later on in this file.
     if (empty($tmp) || preg_match('/[^A-Za-z0-9\\-.]/', $tmp)) {
-        die("Site ID '". htmlspecialchars($tmp, ENT_NOQUOTES) . "' contains invalid characters.");
+	echo "Invalid URL";
```
Comment (mdsupport) [inline interface/globals.php]: Isn't REST requester expecting json response?

File: interface/globals.php (hunk 1 above)
Comment (sjpadgett) [reply interface/globals.php]: It'd be fine. I'll just get my way on this one:) I'll bring in after you fix travis.
FOUND 4 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------------------
 137 | ERROR | [x] Spaces must be used to indent lines; tabs are not allowed
 137 | ERROR | [x] Line indented incorrectly; expected at least 8 spaces, found 4
 139 | ERROR | [x] Spaces must be used to indent lines; tabs are not allowed
 139 | ERROR | [x] Line indented incorrectly; expected at least 8 spaces, found 4
----------------------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY

File: interface/globals.php (hunk 2 above)
Comment (sjpadgett) [reply interface/globals.php]: request has already been made. this is after and will die..

File: interface/globals.php (hunk 1 above)
Comment (adunsulag) [reply interface/globals.php]: That's what I get for using VIM to do a quick fix.

File: interface/globals.php [hunk 3]
```diff
@@ -130,8 +130,13 @@
         }
     }
 
+    // for both REST API and browser access we can't proceed unless we have a valid site id.
+    // since this is user provided content we need to escape the value but we use htmlspecialchars instead
+    // of text() as our helper functions are loaded in later on in this file.
     if (empty($tmp) || preg_match('/[^A-Za-z0-9\\-.]/', $tmp)) {
-        die("Site ID '". text($tmp) . "' contains invalid characters.");
+        echo "Invalid URL";
+        error_log("Request with site id '". htmlspecialchars($tmp, ENT_NOQUOTES) . "' contains invalid characters.");
```
Comment (bradymiller) [inline interface/globals.php]: Don't need to escape stuff going to log:
```
error_log("Request with site id '" . $tmp . "' contains invalid characters.");
```
(that definitely will fix the text() issue :) )

Comment (adunsulag) [reply interface/globals.php]: Is that the project preference? I've always in the past escaped stuff going to logs as there are php security exploits that can occur through php attackers remotely including the error_log.  Had to fix a compromised wordpress site where that occurred once.

Comment (adunsulag) [reply interface/globals.php]: Here's OWASP's take on it: https://www.owasp.org/index.php/Log_Injection

File: interface/globals.php (hunk 2 above)
Comment (mdsupport) [reply interface/globals.php]: I know request has already been made.  I also know echo before die is going to generate output that a browser client will see. 

The comment was specifically about making sure that response as seen by REST requesters are properly formatted per specifications.

File: interface/globals.php (hunk 3 above)
Comment (bradymiller) [reply interface/globals.php]: hi @adunsulag ,
I wasn't aware of that. The attacker is running the error log output through html?

File: interface/globals.php (hunk 2 above)
Comment (sjpadgett) [reply interface/globals.php]: which brings us full circle to my original comment. The validation should be made in api which I will address soon.

File: interface/globals.php (hunk 3 above)
Comment (bradymiller) [reply interface/globals.php]: Interesting. Just added this to our Code Security page:
https://www.open-emr.org/wiki/index.php/Codebase_Security#Log_Injection
(html escaping variables that go to log is a good plan for now)

Comment (bradymiller) [reply interface/globals.php]: thanks @adunsulag ! Code is ready for codebase.
