### PR TITLE
fix: set deleted flag for forms when delete person

### LINKED ISSUE #6319: bug: delete patient bug due to history form saved in portal
### Describe the bug

write concise description of what the bug is.
Mohammed described on the forum:
https://community.open-emr.org/t/delete-patient-gives-error-related-to-the-id-of-the-record/20165/10

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6319 

#### Short description of what this resolves:
instead of deleting forms we can set the deleted flag to 1 and this also avoids having to manage the different names of the `form_dir` created via the portal

### CODE REVIEW

File: interface/patient_file/deleter.php [hunk 1]
```diff
@@ -239,11 +237,13 @@ function popup_close() {
 
                 $res = sqlStatement("SELECT * FROM forms WHERE pid = ?", array($patient));
                 while ($row = sqlFetchArray($res)) {
-                    form_delete($row['formdir'], $row['form_id'], $row['pid'], $row['encounter']);
+                    row_modify(
+                        "forms",
+                        "deleted = 1",
+                        "pid = '" . $row['pid'] . "' AND form_id = '" . $row['form_id'] . "'"
```
Comment (bradymiller) [inline interface/patient_file/deleter.php:243]: should use sql escaping here since this goes into a sql query:
```
"pid = '" . add_escape_custom($row['pid']) . "' AND form_id = '" . add_escape_custom($row['form_id']) . "'"
```

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
dance-bear
