### PR TITLE
Clinic Rules and Reminders

### LINKED ISSUE #3550: Patient add/view not working
Hello,

I am onwindows 10, using php 7.3 and running development version 5.0.3 of openemr. whenever I try to add a new patient or view the patient, it allows me to enter the patient details but while saving, it shows a white page. The data are saved in the databae but they are not displayed. 

The php error log shows this - 

[Sun May 24 18:44:08.230389 2020] [php7:error] [pid 3796:tid 1900] [client ::1:51322] PHP Fatal error:  Uncaught TypeError: Argument 5 passed to exist_procedure_item() must be an instance of stirng or null, string given, called in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php on line 1784 and defined in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php:2001\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(1784): exist_procedure_item(2, 'INR', 'CPT4:85610', '', '', 'ge', '1', '', '', '2020-06-07 18:4...')\n#1 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(1260): procedure_check(2, Array, Array, '2020-06-07 18:4...')\n#2 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(832): test_targets(2, 'rule_inr_measur...', '', '2020-06-07 18:4...')\n#3 C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php(222): test_rules_clinic('', 'active_alert', '2020-05-24 18:4...', 'reminders-due', 2, '', 'default', Array, 'primary', NULL, NULL, 'arnabnaha6885')\n#4 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\summary\\demographics.php(60): active_alert_summary(2, 'reminders-due', '2020-05-24 18:4...', 'default' in C:\\xampp\\htdocs\\openemr\\library\\clinical_rules.php on line 2001, referer: http://localhost/openemr/interface/main/tabs/main.php?token_main=YYbJruGqHoTHGk5SvIeatAokVFMQjhKqXhigm2MN

### PR DESCRIPTION
**Pull request by sjpadgett**
- fix a misspelling in param
- some tuning
- delete an invalid foreach in reminders

Fixes #3550

### CODE REVIEW

**Comment by sjpadgett** [comment]
still testing

**Comment by sjpadgett** [comment]
Working okay for me but this module needs some serious tuning. Starting with profiling it.
@bradymiller you see any issues?

File: library/clinical_rules.php [hunk 1]
```diff
@@ -628,7 +629,7 @@ function test_rules_clinic($provider = '', $type = '', $dateTarget = '', $mode =
                 $provider_item['prov_fname'] = $urow['fname'];
                 $provider_item['npi'] = $urow['npi'];
                 $provider_item['federaltaxid'] = $urow['federaltaxid'];
-                array_push($results, $provider_item);
```
Comment (bradymiller) [inline library/clinical_rules.php:631]: yep, I was a bit `array_push` crazy back in the day :)

Comment (sjpadgett) [reply library/clinical_rules.php:631]: Doesn't gain much but every bit counts. It's the recursive array_merges in loops that eat up cycles. Still it's a rather complicated module but needs some tlc.

File: library/clinical_rules.php [hunk 2]
```diff
@@ -1814,7 +1810,6 @@ function appointment_check($patient_id, $dateTarget = '')
 
   // Set current date
     $currentDate = date('Y-m-d H:i:s');
-    $currentDateRound = date('Y-m-d', $dateCurrent);
```
Comment (bradymiller) [inline library/clinical_rules.php:1817]: fare thee well, unused variable :)

File: library/clinical_rules.php [hunk 3]
```diff
@@ -1731,7 +1727,7 @@ function database_check($patient_id, $filter, $interval = '', $dateTarget = '')
             if (exist_database_item($patient_id, $temp_df[1], $temp_df[2], $temp_df[3], $temp_df[4], $temp_df[5], $temp_df[6], $intervalType, $intervalValue, $dateTarget)) {
                 // Record the match
                 if ($cond_loop > 0) { // For multiple condition check
-                    $isMatch = $isMatch && true;
+                    $isMatch = $isMatch && 1;
```
Comment (bradymiller) [inline library/clinical_rules.php:1730]: this is an odd line

File: library/reminders.php [hunk 4]
```diff
@@ -227,15 +228,15 @@ function update_reminders($dateTarget = '', $patient_id = '', $start = null, $ba
         // as described above, need to pass in each patient_id
         // Collect all patient ids
         $patientData = buildPatientArray('', '', '', $start, $batchSize);
-        for ($iter = 0; $row = sqlFetchArray($rez); $iter++) {
+        // comment below as doesn't make sense. where's $rez? sjp 05/27/20
+        /*for ($iter = 0; $row = sqlFetchArray($rez); $iter++) {
             $patientData[$iter] = $row;
-        }
+        }*/
```
Comment (bradymiller) [inline library/reminders.php:234]: yep, that unused for block needs to go. this probably fell out when updated the rule engine to support batches (this was added for when running thousands of patients in a reports).

File: library/reminders.php [hunk 5]
```diff
@@ -244,6 +245,7 @@ function update_reminders($dateTarget = '', $patient_id = '', $start = null, $ba
                 $patient_id_complete .= "," . $patient['pid'];
             }
         }
+        $collectedReminders = array_merge([], $collectedReminders, $tempCollectReminders);
```
Comment (bradymiller) [inline library/reminders.php:248]: this should be ok, but rec testing to ensure ok

**Comment by bradymiller** [comment]
code looks good to me. would just make sure the collected reminders thing tests ok.

File: library/clinical_rules.php (hunk 3 above)
Comment (sjpadgett) [reply library/clinical_rules.php:1730]: $isMatch is a conditional otherwise you're just setting to each other. still strange but, I just wanted to get the var types to agree. otherwise, beats me why it's there.

File: library/reminders.php (hunk 5 above)
Comment (sjpadgett) [reply library/reminders.php:248]: This is the easy one. I get why some of the others are the way they're used so, won't be so easy to refactor. Another day perhaps!:)

File: src/RestControllers/AuthRestController.php [hunk 6]
```diff
@@ -247,7 +247,7 @@ public function isValidToken($tokenRaw)
         } else { // $_SESSION['api'] == "oemr" || $_SESSION['api'] == "fhir"
             // For core api or fhir api
             $_SESSION['authUser'] = $tokenResult['username'];
-            $_SESSION['authUserId'] = $tokenResult['user_id'];
+            $_SESSION['authUserID'] = $tokenResult['user_id'];
```
Comment (bradymiller) [inline src/RestControllers/AuthRestController.php:250]: doh, that was likely my doing...

Comment (sjpadgett) [reply src/RestControllers/AuthRestController.php:250]: I saw awhile back. Was driving me nuts.:)
