### PR TITLE
fix: `unset` on nonexistent variable

### LINKED ISSUE #8827: `unset` on undefined variables
There are five places in the codebase where `unset(...)` is called on names that have never been assigned in the current scope.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #8827

#### Short description of what this resolves:

Fix `unset` on undefined variables.

#### Changes proposed in this pull request:

Remove `unset` calls where they are not doing anything.

### CODE REVIEW

File: src/Common/Auth/OneTimeAuth.php [hunk 1]
```diff
@@ -330,7 +330,6 @@ public function processOnetime($token, $redirect_token): array
             }
         } catch (OneTimeAuthExpiredException $e) {
             $this->systemLogger->error("Failed " . $e->getMessage());
-            unset($auth);
```
Comment (bradymiller) [inline src/Common/Auth/OneTimeAuth.php:333]: auth is set in line 323

Comment (bradymiller) [reply src/Common/Auth/OneTimeAuth.php:333]: oh, i think i get it. auth will not be set here since that means the function it called threw an error/exception. correct?

**Review by bradymiller — APPROVED** [review]

File: src/Common/Auth/OneTimeAuth.php (hunk 1 above)
Comment (kojiromike) [reply src/Common/Auth/OneTimeAuth.php:333]: phpstan is being confusing here, because technically it could be set, but it might not be set, too. 

But the real question is why bother unsetting a variable (and deal with it potentially not being set) just before it goes out of scope?

**Comment by kojiromike** [comment]
Discovering #8829 has made me a bit nervous about some of the phpstan findings. Marking this as draft until that's resolved.
