### PR TITLE
Additional printed forms cleanup - headers/footers, middle name and suffix visibility

### LINKED ISSUE #5764: Printable Reports Don't Have Proper Headers/Footers
### Describe the bug

*(As a quick note to start, this work is being driven by my employer, [Altispeed Technologies](https://altispeed.com/). I'm actively working on this issue. Any screenshots shown use test data, and are not associated with any real patient.)*

I was exploring the codebase for custom reports, and I found this block: https://github.com/openemr/openemr/blob/master/interface/patient_file/report/custom_report.php#L249

It would seem to suggest that the HTML output would have a single line at the top with the information, which I'm able to reproduce as such:

image

However, when I select `Download PDF` rather than `Generate Report`, I'm met with the following:

image

Also, that line only prints on the first page, at the top.

I've tried to use mPDF's `SetHTMLHeader()` function (and related functions) to accomplish this task in my local testing, taking into account the scope of `$pdf`, to no avail. It would be a lot cleaner to have the header and footer functions working on the printed report.

Any advice on steps forward? Is this related to #5614?

### Client configuration

- Browser: Firefox Nightly
- OpenEMR version: 7.0.0.1 / `master`
- Operating system: Ubuntu 22.04 / Kinetic
- [PHP 8.1 directly from the Ubuntu archive](https://launchpad.net/ubuntu/+source/php8.1)
- mPDF version 8.1.0

### PR DESCRIPTION
**Pull request by tsimonq2**
Fixes #5764, #5767 - **ready for review**

This pull request includes several pieces of cleanup...
 - `genFacilityTitle()` only accepts path strings now, and not full HTML blobs with an `` tag. This is to ensure the HTML stays escaped, therefore, all generation of the `` tag has been moved here.
   - Some manual CSS-related overrides were added to `genFacilityTitle()`, since the print*able* and print*ed* reports looked much different (See `Download PDF` vs `Generate Report`)
 - Inclusion of HTML headers and footers, at least from `printable.php` and `custom_report.php`, has been moved to the new `genPatientHeaderFooter()` function. This is much more consistent-looking than before, but if there's any other file I should standardize in this way, please let me know
 - Includes middle names and suffixes when generating patient name text

### CODE REVIEW

File: interface/forms/LBF/printable.php [hunk 1]
```diff
@@ -280,13 +280,12 @@
...
 $ma_logo_path = "sites/" . $_SESSION['site_id'] . "/images/ma_logo.png";
 if (is_file("$webserver_root/$ma_logo_path")) {
-    // Would use max-height here but html2pdf does not support it.
-    // TODO - now use mPDF, so should test if still need this fix
-    $logo = "<img src='$web_root/$ma_logo_path' style='height:" . attr(round($FONTSIZE * 5.14)) . "pt' />";
+    $logo = "<img src='$web_root/$ma_logo_path' style='max-height:8%' />";
+    echo genFacilityTitle($formtitle, -1, $logo);
 } else {
     $logo = "<!-- '$ma_logo_path' does not exist. -->";
+    echo genFacilityTitle($formtitle, -1);
```
Comment (stephenwaite) [inline interface/forms/LBF/printable.php:287]: yes-gif-5

File: interface/patient_file/report/custom_report.php [hunk 2]
```diff
@@ -262,23 +264,13 @@ function zip_content($source, $destination, $content = '', $create = true)
...
-                ?>
-                <a href="javascript:window.close();"><h1><?php echo text($titleres['lname']) . ", " . text($titleres['fname']); ?></h1></a>
-                <?php
-                echo "<br clear='all' /></td><td align='right'>";
+                $logo = "";
                 if (file_exists($practice_logo)) {
                     $logo_path = $GLOBALS['OE_SITE_WEBROOT'] . "/images/" . basename($practice_logo);
-                    echo "<img class='h-auto' style='max-width:250px;' src='$logo_path'>"; // keep size within reason
-                    echo "</td><td>";
+                    $logo = "<img class='h-auto' style='max-height:8%;' src='". $logo_path . "'>";
```
Comment (stephenwaite) [inline interface/patient_file/report/custom_report.php:270]: this might need an `attr()`
```
                    $logo = "<img class='h-auto' style='max-height:8%;' src='". attr($logo_path) . "'>";

File: library/patient.inc [hunk 3]
```diff
@@ -197,15 +197,15 @@ function getFacility($facid = 0)
 function genFacilityTitle($repname = '', $facid = 0, $logo = '')
 {
     $s = '';
-    $s .= "<table class='ftitletable'>\n";
+    $s .= "<table class='ftitletable' width='100%'>\n";
     $s .= " <tr>\n";
     if (empty($logo)) {
-        $s .= "  <td class='ftitlecell1'>" . text($repname) . "</td>\n";
+        $s .= "  <td align='left' class='ftitlecell1'>" . $repname . "</td>\n";
```
Comment (stephenwaite) [inline library/patient.inc:203]: replace text($repname)

File: library/patient.inc [hunk 4]
```diff
@@ -197,15 +197,15 @@ function getFacility($facid = 0)
...
     } else {
-        $s .= "  <td class='ftitlecell1'>" . $logo . "</td>\n";
-        $s .= "  <td class='ftitlecellm'>" . text($repname) . "</td>\n";
+        $s .= "  <td align='left' class='ftitlecell1'>" . $logo . "</td>\n";
+        $s .= "  <td align='left' class='ftitlecellm'>" . $repname . "</td>\n";
```
Comment (stephenwaite) [inline library/patient.inc:206]: and here too

**Comment by stephenwaite** [comment]
nice improvements @tsimonq2 !

**Comment by tsimonq2** [comment]
Thanks! Not quite done yet :wink:

File: interface/patient_file/report/custom_report.php (hunk 2 above)
Comment (tsimonq2) [reply interface/patient_file/report/custom_report.php:270]: Works fine, adding just in case + testing, thanks

File: library/patient.inc (hunk 3 above)
Comment (tsimonq2) [reply library/patient.inc:203]: Fixed with next commit push

File: library/patient.inc (hunk 4 above)
Comment (tsimonq2) [reply library/patient.inc:206]: Fixed with next commit push

File: interface/patient_file/printed_fee_sheet.php [hunk 5]
```diff
@@ -356,9 +356,9 @@ function printlog_before_print() {
 $logo = '';
 $ma_logo_path = "sites/" . $_SESSION['site_id'] . "/images/ma_logo.png";
 if (is_file("$webserver_root/$ma_logo_path")) {
-    $logo = "<img src='$web_root/$ma_logo_path' style='height:" . round(9 * 5.14) . "pt' />";
+    $logo = "$web_root/$ma_logo_path";
```
Comment (bradymiller) [inline interface/patient_file/printed_fee_sheet.php:359]: 2DV

File: library/patient.inc [hunk 6]
```diff
@@ -409,6 +409,34 @@ function getEmployerData($pid, $given = "*")
...
 
+// Generate a consistent header and footer, used for printed patient reports
+function genPatientHeaderFooter($pid, $DOS = null)
+{
+    $patient_dob = getPatientData($pid, "DATE_FORMAT(DOB,'%m/%d/%Y') as DOB_TS");
+    $patient_name = getPatientName($pid);
+
+    // Header
+    $s = '<htmlpageheader name="PageHeader1"><div style="text-align: right; font-weight: bold;">';
+    $s .= $patient_name . '&emsp;DOB: ' . text($patient_dob['DOB_TS']);
```
Comment (bradymiller) [inline library/patient.inc:420]: text() around $patient_name

File: library/patient.inc [hunk 7]
```diff
@@ -409,6 +409,34 @@ function getEmployerData($pid, $given = "*")
...
+    if ($DOS) {
+        $s .= '&emsp;DOS: ' . $DOS;
```
Comment (bradymiller) [inline library/patient.inc:422]: text() around $DOS

**Comment by bradymiller** [comment]
code looks good. just noted couple escaping issues.

File: interface/patient_file/printed_fee_sheet.php (hunk 5 above)
Comment (tsimonq2) [reply interface/patient_file/printed_fee_sheet.php:359]: :partying_face:

**Comment by tsimonq2** [comment]
I was just informed that in order to make the generated printed forms "legal," on the LBF forms there will need to be one more change to make the header show up on the first page. Unless additional feedback is raised, or other areas of the code that would benefit from this cleanup are highlighted, following this commit this PR is done.

Thanks.

**Comment by bradymiller** [comment]
hi @tsimonq2 , assuming this is ready for codebase now that the first page header fix is in. code looks good and bringing in. thanks!
