### PR TITLE
fix: ccda zip import and php warnings and deprecations

### LINKED ISSUE #7411: BUG: Unable to import CCDA XML files in Docker 7.0.3
### Describe the bug

Import of CCDA XML file to OpenEMR is unsuccessful in Docker 7.0.3. The following error is seen in the error.log file. 

`PHP Warning:  Undefined array key 1 in /var/www/localhost/htdocs/openemr/controllers/C_Document.class.php on line 806, referer: http://localhost:8009/interface/modules/zend_modules/public/carecoordination/upload?id=1
`

### To Reproduce
image

1. Go to Modules, then CareCordination
2. Go to Import and then CCDA or QRDA
3. Click on the import button and choose a CCDA file to import
4. Page reloads with no new import

### Expected behavior

In Docker 7.0.2, the import of CCDA file is successful and it's entry can be seen in the Import CCDA page. Similar behaviour is expected in Docker 7.0.3.

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.3
- Operating system: Ubuntu 22.04

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7411 #7417

### CODE REVIEW

**Comment by sjpadgett** [comment]
At L-1015 in interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
Change to:
`if ($componentCount > 0) {`

This will fix issue with zip though only tested to depth of 1 dir.

File: src/Services/Cda/CdaTemplateParse.php [hunk 1]
```diff
@@ -373,12 +373,14 @@ public function fetchEncounterPerformed($entry): void
...
-            $this->templateData['field_name_value_array']['encounter'][$i]['date'] = ($entry['encounter']['effectiveTime']['value'] ?? null) ?: $entry['encounter']['effectiveTime']['low']['value'] ?? null;
-            $this->templateData['field_name_value_array']['encounter'][$i]['date_end'] = $entry['encounter']['effectiveTime']['high']['value'] ?? null;
+            if (!empty($this->templateData['field_name_value_array']['encounter'][$i])) {
+                $this->templateData['field_name_value_array']['encounter'][$i]['extension'] = $entry['encounter']['id']['extension'];
+                $this->templateData['field_name_value_array']['encounter'][$i]['root'] = $entry['encounter']['id']['root'];
+                $this->templateData['field_name_value_array']['encounter'][$i]['date'] = ($entry['encounter']['effectiveTime']['value'] ?? null) ?: $entry['encounter']['effectiveTime']['low']['value'] ?? null;
+                $this->templateData['field_name_value_array']['encounter'][$i]['date_end'] = $entry['encounter']['effectiveTime']['high']['value'] ?? null;
+            }
```
Comment (sjpadgett) [inline src/Services/Cda/CdaTemplateParse.php:381]: Can't do.  This may/will initially be empty but is init'ed by import data.

This is the parser for the import and the $this->templateData is unknowable and we should allow all arrays to be populated even with empty or null because those values may be a trigger in the actual DB import which happens after user reviews.

Please remove all conditionals put in and allow those arrays be init'ed. If they aren't they may end up causing warnings in DB import if they are expected but not there.

I hope I've been clear and if not please let me know.

Comment (sjpadgett) [reply src/Services/Cda/CdaTemplateParse.php:381]: Looks like this is only place that concerns me otherwise thanks for fixing these.

Comment (sjpadgett) [reply src/Services/Cda/CdaTemplateParse.php:381]: Just want to show how this break encounters. Otherwise import to patient is working better than I hoped but I see on area I need to investigate, vitals only populates using first encounter and not all vitals which I do parse and show in ccda.
I may do some fixes and push to your branch if that's okay?

image

Comment (sjpadgett) [reply src/Services/Cda/CdaTemplateParse.php:381]: You'd think Stephen I'd have better things to do besides picking on!:)

**Review by sjpadgett — APPROVED** [review]
thanks

**Comment by stephenwaite** [comment]
thank you @sjpadgett !

**Comment by bradymiller** [comment]
dance-bear
