### PR TITLE
fix(claimrev): replace hardcoded dev URLs with configurable settings

### LINKED ISSUE #10743: ClaimRev: Hardcoded stale ngrok URL for development environment
## Summary

The development environment configuration returns a hardcoded ngrok URL that is certainly no longer valid.

## Location

`interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php` lines 97-105

## Current Code

```php
public function getApiServer()
{
    if ($this->getGlobalSetting(self::CONFIG_OPTION_ENVIRONMENT) == "S") {
        return "https://testapi.claimrev.com";
    } elseif ($this->getGlobalSetting(self::CONFIG_OPTION_ENVIRONMENT) == "D") {
        return "https://9a89-174-128-131-22.ngrok.io";  // Stale!
    }
    return "https://api.claimrev.com";
}
```

## Problem

- Ngrok URLs are temporary and expire when the tunnel restarts
- Anyone setting environment to "D" gets connection failures
- No way to configure a custom development URL

## Suggested Fix

Either remove the development environment option entirely, or make the dev API server URL configurable via a global setting.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #10743

## Description
The ClaimRev module had hardcoded URLs for the development environment (ngrok URL for API, and fixed URLs for OAuth scope/authority). These URLs are temporary or environment-specific, causing connection failures.

## Changes
- Add configurable "Development API Server URL" setting
- Add configurable "Development Scope URL" setting  
- Add configurable "Development Authority URL" setting
- When environment is "D", use the configured URLs instead of hardcoded values
- Return empty string when dev URLs are not configured (fails clearly rather than silently)
- Reformat settings array to use trailing commas

## AI Disclosure
Yes

### CODE REVIEW

File: interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php]: create mappings for these.

Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php]: create mappings for these.

File: interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php [hunk 1]
```diff
@@ -103,7 +104,7 @@ public function getApiServer()
         if ($this->getGlobalSetting(self::CONFIG_OPTION_ENVIRONMENT) == "S") {
             return "https://testapi.claimrev.com";
         } elseif ($this->getGlobalSetting(self::CONFIG_OPTION_ENVIRONMENT) == "D") {
-            return "https://9a89-174-128-131-22.ngrok.io";
+            return $this->getGlobalSetting(self::CONFIG_OPTION_DEV_API_URL) ?: '';
         }
         return "https://api.claimrev.com";
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php]: create mappings for these.

File: interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php [hunk 2]
```diff
@@ -129,6 +130,12 @@ public function getGlobalSettingSectionConfiguration()
...
             ]
+            ,self::CONFIG_OPTION_DEV_API_URL => [
+                'title' => 'Development API Server URL'
+                ,'description' => 'API server URL when environment is set to D (Development)'
+                ,'type' => GlobalSetting::DATA_TYPE_TEXT
+                ,'default' => ''
+            ]
             ,self::CONFIG_OPTION_CLIENTID => [
                 'title' => 'Client ID'
                 ,'description' => 'Contact ClaimRev for the client ID'
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/src/GlobalConfig.php]: reformat this to use trailing commas, not leading commas.
