### PR TITLE
Fix #3734: add override css to fix multiple arrow issue

### LINKED ISSUE #3734: Sorting Arrow Issue
### Describe the bug

Multiple Arrow Colliding with each other

### To Reproduce

image

Steps to reproduce the behaviour:
1. Goto Patients->Select Any Patient-> Add/Edit Allergy-> Add Coding
2. Now Add/Codes Model  (```interface/patient_file/encounter/find_code_dynamic.php```) will have the following error

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3734 

#### Short description of what this resolves:
Add override CSS to fix multiple arrow issue

image

### CODE REVIEW

File: interface/patient_file/encounter/find_code_dynamic.php [hunk 1]
```diff
@@ -49,6 +50,18 @@
 
 <?php Header::setupHeader(['opener', 'datatables', 'datatables-dt', 'datatables-bs', 'datatables-colreorder']); ?>
```
Comment (stu01509) [inline interface/patient_file/encounter/find_code_dynamic.php:52]: Hi  @bradymiller and @tywrenn 

Why not remove the `datatables-dt`, Are any library or feature depend on it? I found it will cause the `datatables-bs` looks odd. e.g. double arrow issue.

Comment (bradymiller) [reply interface/patient_file/encounter/find_code_dynamic.php:52]: hi @stu01509 ,
If removing it causes no problems (and avoids the override), then would remove it (I do recall in the past that doing this messed up some of the styling in paging stuff, but maybe it was just a collision of some other css).

Comment (bradymiller) [reply interface/patient_file/encounter/find_code_dynamic.php:52]: If possible, would also remove where it's used in other places (then we can remove it completed from package.json).

Comment (stu01509) [reply interface/patient_file/encounter/find_code_dynamic.php]: Hi @bradymiller, sir

Thanks for your explanation, I remove ` datatable-dt ` and override CSS, and do a little bit test. It looks like good.

Comment (bradymiller) [reply interface/patient_file/encounter/find_code_dynamic.php]: @stu01509 , sounds great. once travis gives the ok, I'll bring it in. thanks! -brady
