### PR TITLE
fix(tabs): add title for eRx tab

### LINKED ISSUE #9129: V7 e-prescribe bug
### Describe the bug
https://community.open-emr.org/t/v7-e-prescribe-bug/26260

### To Reproduce

Image

### PR DESCRIPTION
**Pull request by juggernautsei**
Fixes #9129

#### Short description of what this resolves:
Tab not showing proper label

### CODE REVIEW

File: interface/main/tabs/js/custom_bindings.js [hunk 1]
```diff
@@ -81,7 +81,14 @@ ko.bindingHandlers.location={
...
                     // setting the title will hide the spinner and remove the Loading... text
-                    tabData.title(xl("Unknown"));
+                    var currentUrl = tabData.url();
+                    // eRx pages can be direct eRx.php URLs, newcrop redirects, or demographics page (which often means eRx context)
+                    var isErxPage = currentUrl && (
+                        currentUrl.indexOf('/interface/eRx.php') !== -1 ||
+                        currentUrl.indexOf('newcrop') !== -1 ||
+                        (currentUrl.indexOf('demographics.php') !== -1 && tabData.name() === 'pat')
+                    );
+                    tabData.title(isErxPage ? xl('Ensora eRx') : xl("Unknown"));
```
Comment (kojiromike) [inline interface/main/tabs/js/custom_bindings.js]: You could write this with more modern ECMA:

```suggestion
                    const currentUrl = tabData.url?.() ?? '';

                    // eRx pages can be direct eRx.php URLs, newcrop redirects, or demographics page (which often means eRx context)
                    const erxMarkers = ['/interface/eRx.php', 'newcrop'];
                    const isErxPage =
                      (currentUrl && erxMarkers.some(marker => currentUrl.includes(marker))) ||
                      (currentUrl.includes('demographics.php') && tabData.name?.() === 'pat');
                      tabData.title(xl(isErxPage ? 'Ensora eRx' : 'Unknown +');
```

btw, does `xl()` know how to translate `Unknown +`?

Comment (juggernautsei) [reply interface/main/tabs/js/custom_bindings.js]: No it does not know what Unknown + is. But Brady always said to leave them out. 
Thanks for the review. I will up my coding style to a more modern approach.

File: interface/main/tabs/js/custom_bindings.js [hunk 2]
```diff
@@ -81,7 +81,15 @@ ko.bindingHandlers.location={
...
-                    tabData.title(xl("Unknown"));
+                    const currentUrl = tabData.url?.() ?? '';
+
+                    // eRx pages can be direct eRx.php URLs, newcrop redirects, or demographics page (which often means eRx context)
+                    const erxMarkers = ['/interface/eRx.php', 'newcrop'];
+                    const isErxPage =
+                        (currentUrl && erxMarkers.some(marker => currentUrl.includes(marker))) ||
+                        (currentUrl.includes('demographics.php') && tabData.name?.() === 'pat');
+
+                    tabData.title(xl(isErxPage ? 'Ensora eRx' : 'Unknown') + (isErxPage ? '' : '+'));
```
Comment (stephenwaite) [inline interface/main/tabs/js/custom_bindings.js]: have to jsEscape too, learned all about it in https://github.com/openemr/openemr/pull/9297

oh maybe not if it was only xl() before

**Comment by kojiromike** [comment]
@juggernautsei — Following up on the review comments from November. Do you plan to push an update here, or would you like me to push the suggested changes to your branch directly?

**Comment by juggernautsei** [comment]
@kojiromike, push the suggested changes to this branch, please.

**Comment by kojiromike** [comment]
@juggernautsei — I pushed a small cleanup: removed the `demographics.php` check from the eRx detection since that branch only runs for cross-origin iframes, and demographics.php is a local page (so it would be handled by the `if (cwDocument)` branch instead). The eRx.php and newcrop markers are sufficient to catch the actual case.

**Review by kojiromike — APPROVED** [review]
Looks good — the eRx URL detection correctly handles the cross-origin tab title case.
