### PR TITLE
fix: check for empty postParseEvent ccda import

### LINKED ISSUE #7347: bug: ccda import fails on empty postParseEvent
### Describe the bug

origin:
https://community.open-emr.org/t/nothing-to-display-uploading-a-valid-c-cda-file-to-care-coordination-for-import

looks like the ccda export is adding an odd `<component/>` after the immunizations, in these cases believe it's where there are no immunizations to be reported, not sure if exploring this would mean going into the ccdaservice js world 

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7347

### CODE REVIEW

File: src/Services/Cda/CdaTemplateParse.php [hunk 1]
```diff
@@ -97,7 +97,9 @@ public function parseCDAEntryComponents($components): array
                     }
                 }
             }
-            $this->templateData = $postParseEvent->getTemplateData();
+            if (!empty($postParseEvent)) {
```
Comment (bradymiller) [inline src/Services/Cda/CdaTemplateParse.php:100]: Does empty() function work on objects?

Comment (adunsulag) [reply src/Services/Cda/CdaTemplateParse.php:100]: It'd be safer to check the instance type.  Empty will work, but if someone returns a string or something other than an object having a getTemplateData() method this will blow up
```
if ($postParseEvent instanceof CDAPostParseEvent)
```

**Comment by stephenwaite** [comment]
remaining errors from native ccda export to ccda import:

> Schema Definition Errors - (3)
Error 1871: Element '{urn:hl7-org:v3}tbody': Missing child element(s). Expected is ( {urn:hl7-org:v3}tr ). on line 1
Error 1839: Element '{urn:hl7-org:v3}time', attribute 'value': [facet 'pattern'] The value 'Invalid date' is not accepted by the pattern '[0-9]{1,8}|([0-9]{9,14}|[0-9]{14,14}\.[0-9]+)([+\-][0-9]{1,4})?'. on line 1
Error 1871: Element '{urn:hl7-org:v3}component': Missing child element(s). Expected is one of ( {urn:hl7-org:v3}realmCode, {urn:hl7-org:v3}typeId, {urn:hl7-org:v3}templateId, {urn:hl7-org:v3}section ). on line 1

> Schematron Errors - (8)
Error: This patientRole SHALL contain at least one [1..*] telecom (CONF:1198-5280).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.1' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This assignedAuthor SHALL contain at least one [1..*] telecom (CONF:1198-5428).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.1' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This effectiveTime SHALL contain exactly one [1..1] low (CONF:1198-14838).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.1' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This effectiveTime SHALL contain exactly one [1..1] low (CONF:1198-8454).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.2' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This effectiveTime SHALL contain exactly one [1..1] high (CONF:1198-8455).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.2' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This patientRole SHALL contain at least one [1..*] telecom (CONF:1198-5280).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.2' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This assignedAuthor SHALL contain at least one [1..*] telecom (CONF:1198-5428).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.2' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
Error: This effectiveTime SHALL contain exactly one [1..1] low (CONF:1198-14838).
Error Context: cda:ClinicalDocument[cda:templateId[@root='2.16.840.1.113883.10.20.22.1.2' and @extension='2015-08-01']]
Where: /ClinicalDocument[1]
Line# 1
