### PR TITLE
ins subscriber name validation fixes see #7477

### LINKED ISSUE #7477: bug: Insurance coverage save fails for payer relationship self when subscriber name has different casing
If you have a patient with existing insurance coverage where the subscriber relationship is 'self' and you save the name with a different case (lowercase, uppercase, mixed case), then the save fails with an error of 'Subscriber name must match patient name for self relationship'.  Most people wouldn't trigger this in the UX but it can easily happen via the API.

The system should do a case insensitive match on the name.

OpenEMR version: OpenEMR versions 7.0.2 and up with the new insurance validation checks.

This bug was introduced in this PR #7197

### PR DESCRIPTION
**Pull request by adunsulag**
This puts in multibyte case insensitive validation on the subscriber previous name fields.  Due to unicode character sets having multiple uppercase characters that correspond to a single lowercase and viceversa with many lowercase to a single uppercase, name identifiers are normalized into unicode NFKC form before comparison.

Fixes #7477

### CODE REVIEW

**Review by stephenwaite — APPROVED** [review]

File: src/Validators/CoverageValidator.php [hunk 1]
```diff
@@ -112,7 +112,21 @@ function (Validator $context) {
...
+                                        // TODO: look at normalizing the multi-byte strings to better handle international languages where multiple unicode characters correspond to the same uppercase or lowercase character
+                                        if (
+                                            ($previousName['previous_name_first'] == $values['subscriber_fname']
+                                                || mb_strtolower($previousName['previous_name_first']) == mb_strtolower($values['subscriber_fname'])
+                                            )
+                                            &&
+                                            ($previousName['previous_name_last'] == $values['subscriber_lname']
+                                                || mb_strtolower($previousName['previous_name_last']) == mb_strtolower($values['subscriber_lname'])
+                                            )
+                                        ) {
```
Comment (bradymiller) [inline src/Validators/CoverageValidator.php:129]: could  just bite bullet and put following function in sanitize.inc.php (this file always including in all scripts):
```
function mb_is_string_equal_ci($string1, $string2): bool
{
    if ($string1 == $string2) {
        return true;
    }

    $string1_normalized = Normalizer::normalize($string1, Normalizer::FORM_KC);
    $string2_normalized = Normalizer::normalize($string2, Normalizer::FORM_KC);
    return mb_strtolower($string1_normalized) === mb_strtolower($string2_normalized)
            || mb_strtoupper($string1_normalized) === mb_strtoupper($string2_normalized);
}
```

Comment (bradymiller) [reply src/Validators/CoverageValidator.php:129]: then have a nice function to use for when doing name lookups etc. that will support internationalization (and it will get tested over time)

Comment (bradymiller) [reply src/Validators/CoverageValidator.php:129]: could also throw bunch of basic unit testing on function at ci akin to this (nice way to test things without needing to manually run them through the api to test):
https://github.com/openemr/openemr/blob/master/tests/Tests/Unit/PasswordVerifyTest.php

Comment (adunsulag) [reply src/Validators/CoverageValidator.php:129]: I'll look at building out the unit tests and getting this in.

Comment (adunsulag) [reply src/Validators/CoverageValidator.php:124]: @bradymiller I went ahead and wrote a unit test and implemented the mb_is_string_equal_ci function.  Let me know what you think.

File: composer.json [hunk 2]
```diff
@@ -81,7 +81,8 @@
     },
     "config": {
         "platform": {
-            "php": "8.1"
+            "php": "8.1",
+            "ext-intl": "8.1"
```
Comment (bradymiller) [inline composer.json:85]: Just checking if above line is needed. Generally less is better in these composer.json things.

File: library/sanitize.inc.php [hunk 3]
```diff
@@ -177,3 +177,26 @@ function dateEmptySql($sqlColumn, $time = false, $rev = false)
...
+{
+    if ($string1 == $string2) {
+        return true;
+    }
+
+    $string1_normalized = Normalizer::normalize($string1, Normalizer::FORM_KC);
+    $string2_normalized = Normalizer::normalize($string2, Normalizer::FORM_KC);
+    return mb_strtolower($string1_normalized) === mb_strtolower($string2_normalized)
+        || mb_strtoupper($string1_normalized) === mb_strtoupper($string2_normalized);
+}
```
Comment (bradymiller) [inline library/sanitize.inc.php:202]: dance-bear

File: src/Validators/CoverageValidator.php [hunk 4]
```diff
@@ -112,7 +112,16 @@ function (Validator $context) {
...
                                     $found = false;
                                     foreach ($previousNames as $previousName) {
-                                        if ($previousName['previous_name_first'] == $values['subscriber_fname'] && $previousName['previous_name_last'] == $values['subscriber_lname']) {
+                                        // do a strict equality and then we can do multibyte comparison for localizations
+                                        // note if we want to handle more comprehensive multibytes
+                                        // we need to do some normalizations as per this stackoverflow post: https://stackoverflow.com/a/38855868
+                                        // I'm not incorporating the normalization techniques yet as we need to better understand their implications before
+                                        // applying the fix
+                                        // TODO: look at normalizing the multi-byte strings to better handle international languages where multiple unicode characters correspond to the same uppercase or lowercase character
```
Comment (bradymiller) [inline src/Validators/CoverageValidator.php:120]: looks like above comments need updating

**Comment by bradymiller** [comment]
Hi @adunsulag , just noted couple minor issues. Otherwise looks great!

File: composer.json (hunk 2 above)
Comment (adunsulag) [reply composer.json:85]: The Normalizer class is built into the php international extension.  Without the extension the functionality will fatal error.  I thought it'd be best to be explicit about the dependency than to have it work for some people (you install it automatically w/ docker) and not work for others.

File: src/Validators/CoverageValidator.php (hunk 4 above)
Comment (adunsulag) [reply src/Validators/CoverageValidator.php]: Resolved

File: library/sanitize.inc.php [hunk 5]
```diff
@@ -177,3 +177,26 @@ function dateEmptySql($sqlColumn, $time = false, $rev = false)
 
     return $stat;
 }
+
+/**
+ * Compares a multibyte unicode string identifier in a case insensitive way to see if the two strings
+ * are semantically identical.  Note that NFKC will treat several 'similar' semantically meaning texts as the same and so
+ * should be used for identifiers (things such as proper nouns, etc).
```
Comment (stephenwaite) [inline library/sanitize.inc.php:184]: hi @adunsulag, should this comment say `should not be used`?

Comment (adunsulag) [reply library/sanitize.inc.php:184]: I thought about having two separate functions one to be used for general text and one to be used for identifiers, but I decided to just go with the single function.  If you see value in it, I can make the two functions.

File: composer.json (hunk 2 above)
Comment (adunsulag) [reply composer.json:85]: @bradymiller are you ok with keeping this in?

Comment (bradymiller) [reply composer.json:85]: hi @adunsulag , sorry for the delayed reply on this. I generally just use platform to force the build to be compatible with the lowest supported php version (in this case 8.1), so it does not use the php version that is on the server where the build is happening. No need for packages here. Can force dependencies in the require section, but don't do this since the build is generally not done on the actual server.

Comment (adunsulag) [reply composer.json:85]: @bradymiller php-intl isn't a package, its a php extension, you can't actually install it w/ composer, the intent is to warn anyone that does a composer install that their server is not setup properly as it is missing the php extension that OpenEMR relies upon, people can bypass it by doing: 

composer install --ignore-platform-reqs

We can remove the warning but if someone is missing the php extension anywhere that extension is used will fail.
