### PR TITLE
Import FontAwesome into SCSS/SASS (#3539)

### LINKED ISSUE #3539: Integrate Font Awesome with our SCSS/SASS
Font Awesome is something that our system uses everywhere. What's great now is the new Font Awesome has SASS/SCSS integration support which I wasn't aware of until now. Since we use this basically all the time, I have decided that we should integrate Font Awesome with our themes. This will allow us to customize Font Awesome and change things if we need to.

Here is how I plan to tackle this:
- [x] Remove autoloading Font Awesome in config.yaml
- [x] Add exception to gulp for Font Awesome and reconfigure gulp in an easier way to handle these sort of exceptions
- [x] Add Font Awesome to all themes
- [x] Change `/interface/themes/core/FontAwesome.scss` to use Font Awesome's SCSS/SASS mixins and addons [as stated here](https://fontawesome.com/how-to-use/on-the-web/using-with/sass).

### PR DESCRIPTION
**Pull request by tywrenn**
Fixes #3539

#### Short description of what this resolves:

Imports Font Awesome into the SCSS/SASS that we have.

### CODE REVIEW

**Comment by tywrenn** [comment]
This still needs work but so far it's working

**Comment by bradymiller** [comment]
hi @tywrenn , Very nice! Just let me know when it's ready to come into codebase.

**Comment by tywrenn** [comment]
@bradymiller ready to merge

**Comment by tywrenn** [comment]
Woops lemme fix travis

**Comment by tywrenn** [comment]
Done

**Comment by bradymiller** [comment]
hi @tywrenn , Bringing in. Thanks for the improvements! -brady

File: gulpfile.js [hunk 1]
```diff
@@ -205,12 +205,14 @@ function install(done) {
...
-            } else if (key == 'bootstrap' || key == 'bootstrap-rtl' || key == 'bootswatch') {
-                // bootstrap, bootstrap-v4-rtl, and bootswatch are special and need to copy dist and scss
+            } else if (key == 'bootstrap' || key == 'bootstrap-rtl' || key == 'bootswatch' || key == '@fortawesome/fontawesome-free') {
+                // bootstrap, bootstrap-v4-rtl, bootswatch, and fontawesome are special and need to copy dist and scss
                 gulp.src('node_modules/' + key + '/dist/**/*')
                     .pipe(gulp.dest(config.dist.assets + key + '/dist'));
                 gulp.src('node_modules/' + key + '/scss/**/*')
                     .pipe(gulp.dest(config.dist.assets + key + '/scss'));
+                gulp.src('node_modules/' + key + '/webfonts/**/*')
+                    .pipe(gulp.dest(config.dist.assets + key + '/webfonts'));
```
Comment (bradymiller) [inline gulpfile.js:215]: @tywrenn , to clarify, this webfonts is only needed for fontawesome, correct?
(if so, then I'll put a quick if block there; not really for functionality just in case we decide to reorg the code in future and will be clear what dirs are needed for each package)
