### PR TITLE
cqm source of payment for insurance companies

### LINKED ISSUE #5342: QRDA needs to map payer to SOP code type in valueset
### Describe the bug

in order to send a QRDA I to cypress for testing we'll either have to add another dropdown called payer to the encounter form so that the find code popup will allow you to select the payer code from the valueset list or we'll have to map existing payer types in `insurance_companies` to the valueset list

#5286

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5342

### CODE REVIEW

File: sql/6_1_0-to-7_0_0_upgrade.sql [hunk 1]
```diff
@@ -663,3 +663,7 @@ SET sql_mode = '';
 UPDATE `patient_data` SET `deceased_date` = NULL WHERE `deceased_date` = '0000-00-00 00:00:00';
 SET sql_mode = @currentSQLMode;
 #EndIf
+
+#IfMissingColumn insurance_companies cqm_sop
+ALTER TABLE `insurance_companies` ADD `cqm_sop` int(5) NOT NULL COMMENT 'HL7 Source of Payment for eCQMs';
```
Comment (bradymiller) [inline sql/6_1_0-to-7_0_0_upgrade.sql:668]: no need for the `(5)` since it basically does nothing for int fields

**Review by bradymiller — APPROVED** [review]
