### PR TITLE
fix configure order display

### LINKED ISSUE #5244: configure orders and results page display
### Describe the bug

extra `'`s

### To Reproduce

Screenshot from 2022-04-25 16-15-32

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5244

### CODE REVIEW

File: interface/orders/types_ajax.php [hunk 1]
```diff
@@ -20,7 +20,7 @@
 
 $render = '';
 
-$render .= "'<table class=\"table\">";
+$render .= "<table class=\"table\">";
```
Comment (bradymiller) [inline interface/orders/types_ajax.php:23]: 2DV (1)

**Review by bradymiller — APPROVED** [review]
