### PR TITLE
fix(claimrev): throw exceptions on API failures instead of returning error values

### LINKED ISSUE #10737: ClaimRev: Null pointer errors when API calls fail
## Summary

Multiple methods in `ClaimRevApi.php` access object properties without null checks. When `curl_exec()` fails or `json_decode()` returns null, these cause fatal errors in PHP 8+.

### ClaimRevApi.php:54-61
```php
$result = curl_exec($ch);
$data = json_decode($result);
if (property_exists($data, 'access_token')) {  // $data could be null!
```

`property_exists(null, ...)` throws TypeError in PHP 8+.

### ClaimRevApi.php:99
```php
if ($data->isError) {  // No null check on $data
```

### EligibilityTransfer.php:86
```php
if ($result->isFatalError) {  // $result could be boolean false
```

## Impact

- API failures cause fatal PHP errors instead of graceful handling
- No error logging when curl fails
- Difficult to debug connectivity issues

## Suggested Fix

Add null/false checks before accessing properties and log curl errors.

### PR DESCRIPTION
**Pull request by kojiromike**
## Summary
Fixes #10737

Add proper error handling for `curl_exec()` and `json_decode()` failures that would otherwise cause fatal PHP 8+ errors when accessing properties on `false`/`null` values.

## Changes proposed in this pull request
- Add explicit TLS verification (`CURLOPT_SSL_VERIFYPEER`, `CURLOPT_SSL_VERIFYHOST`) to all curl calls
- Check `curl_exec()` result before `json_decode()` and log errors via SystemLogger
- Check `json_decode()` result before `property_exists()` calls
- Add `property_exists()` check for `isError` in `uploadClaimFile()`
- Add `property_exists()` check for `isFatalError` in `saveEligibility()`
- Update PHPStan baseline for new error handling code

## AI Disclosure
Yes

### CODE REVIEW

File: interface/modules/custom_modules/oe-module-claimrev-connect/src/ClaimRevApi.php [hunk 1]
```diff
@@ -122,20 +147,34 @@ public static function getReportFiles($reportType, $token)
...
+        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 2);
         curl_setopt($ch, CURLOPT_URL, $url);
         curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
+
         $result = curl_exec($ch);
+        if ($result === false) {
+            (new SystemLogger())->error('ClaimRev: cURL error in ' . __FUNCTION__, ['error' => curl_error($ch)]);
+            curl_close($ch);
+            return '';
```
Comment (kojiromike) [inline interface/modules/custom_modules/oe-module-claimrev-connect/src/ClaimRevApi.php]: If we return '' here, does that mean the http server returns a 200? Shouldn't we return a 500 here?
