### PR TITLE
Fix for insertEncounter where creating an encounter always use current date

### LINKED ISSUE #5872: Encounter Post API - Date is saving as current date instead of data passed]
### Describe the bug

I have been working with the API for Encounter, the date always defaults to today instead of the one passed on the POST API. please help

For example:
{
“date”: “2020-11-10”,
“onset_date”: “”,
“reason”: “Pregnancy Test”,
“facility”: “Owerri General Hospital”,
“pc_catid”: “5”,
“facility_id”: “3”,
“billing_facility”: “3”,
“sensitivity”: “normal”,
“referral_source”: “”,
“pos_code”: “0”,
“external_id”: “”,
“provider_id”: “1”,
“class_code”: “AMB”
}

the date that is being saved to the db is the current date instead of “date”: “2020-11-10”.

### To Reproduce
more info here https://community.open-emr.org/t/encounter-post-api-date-is-saving-as-current-date-instead-of-data-passed/18550

### Client configuration

OpenEMR Version 
I’m using OpenEMR version 7.0

Browser:
I’m using: brave/chrome

Operating System
I’m using: WINDOWS

### PR DESCRIPTION
**Pull request by MichaelValet**
There was already a pull request for this issue (#5873) but was never merged.

Fixes #5872

#### Short description of what this resolves:
This allows to put the date of the encounter when creating it instead of needing to update it after

### CODE REVIEW

File: src/Services/EncounterService.php [hunk 1]
```diff
@@ -359,7 +359,7 @@ public function insertEncounter($puuid, $data)
         $encounter = generate_id();
         $data['encounter'] = $encounter;
         $data['uuid'] = UuidRegistry::getRegistryForTable(self::ENCOUNTER_TABLE)->createUuid();
-        $data['date'] = date("Y-m-d");
+        if($data['date'] == NULL) $data['date'] = date("Y-m-d");
```
Comment (adunsulag) [inline src/Services/EncounterService.php:362]: Not sure this will pass the style checker.  May need to make it 
```
if($data['date'] == NULL) {
   $data['date'] = date("Y-m-d");
}
```
Another option would be to do this.
```
if(empty($data['date'])) {
   $data['date'] = date("Y-m-d");
}
```

**Comment by stephenwaite** [comment]
hi @MichaelValet , to get around the php styling errors does this work for you?

       $data['date'] = (empty($data['date'])) ? date("Y-m-d") : $data['date'];

**Comment by MichaelValet** [comment]
Thanks @adunsulag , I fixed the styling issue

**Comment by stephenwaite** [comment]
bringing on in @MichaelValet, thanks for the contribution!

jumping
