### PR TITLE
fixes Outdated drug destroyed interface

### LINKED ISSUE #3155: Outdated drug destroyed interface
### Describe the bug
Interface: Drug destroyed
1. `$nbsp` in place of blank data
2. Old Table
3. Wrong Redirect

### To Reproduce
https://www.loom.com/share/a23e39b8e5664e0097a1b042c79582af

### Client configuration

- Browser: Ubuntu 18.04
- Operating system: Chrome 20

### PR DESCRIPTION
**Pull request by im-Amitto**
Fixes #3155 

https://www.loom.com/share/b01ea711bfb84fad9d3bd3f134ef3e9f

### CODE REVIEW

File: interface/reports/destroyed_drugs_report.php [hunk 1]
```diff
@@ -26,30 +26,120 @@
...
+.paginate_button:hover{
+  background: transparent!important;
 }
 </style>
 
 <script language="JavaScript">
 
+// Process click on destroyed drug.
+function doclick(id, lot) {
+ dlgopen('../drugs/destroy_lot.php?drug=' + id + '&lot=' + lot, '_blank', 600, 475);
```
Comment (bradymiller) [inline interface/reports/destroyed_drugs_report.php]: just need some url encoding here:
```
dlgopen('../drugs/destroy_lot.php?drug=' + encodeURIComponent(id) + '&lot=' + encodeURIComponent(lot), '_blank', 600, 475);
```

**Comment by im-Amitto** [comment]
@bradymiller fixed :)

**Comment by bradymiller** [comment]
hi @im-Amitto , Testing well and code looks good, so bringing into codebase. I don't even recognize that module anymore :)
Thanks for the improvements! -brady
