### PR TITLE
fix: registration modal fix to ensure complete decoupling

### LINKED ISSUE #8334: Registration modal fix to ensure complete decoupling
Registration modal fix to ensure complete decoupling
(if email opt out is NULL and telemetry had been opted out, then should only show the email dialog)

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #8334

~~(prob gonna do a little more work to make it clear what getProductStatus() is for by renaming it to getProductStatusDialog() and then offshooting the call from the about page to a small new function for collecting the email adress)~~ DONE

### CODE REVIEW

**Comment by bradymiller** [comment]
@sjpadgett ,
I think this will do. I should of made my prior work more clear that basically hijacked that function for the dialog display :)
I've just got to test it a bit more (had to go to sleep :) ).

**Comment by sjpadgett** [comment]
cool, I'll test some more also tomorrow. tired here as well, good night.

File: src/Services/ProductRegistrationService.php [hunk 1]
```diff
@@ -55,21 +56,27 @@ public function getProductStatus(): array
...
-            if ($optOut == null) {
-                $row['allowEmail'] = 1;
-            }
-            if (empty($telemetry_disabled)) {
-                $row['allowTelemetry'] = 1;
+                if ($optOut == null) {
+                    $row['allowEmail'] = 1;
+                }
+                if ($telemetry_disabled == null) {
+                    $row['allowTelemetry'] = 1;
```
Comment (sjpadgett) [inline src/Services/ProductRegistrationService.php:67]: @bradymiller In current actions, $row['allowTelemetry'] should be enabled if $telemetry_disabled == 0 otherwise, none of the event collection routines will run to report telemetry.
Recommend a new flag collectTelemetryEvents or something. It'd be used in three places currently portal JS, Top Nav from tabs_view_model.js and API dispatcher.

Comment (sjpadgett) [reply src/Services/ProductRegistrationService.php:67]: Just a reminder to remove the exposed unused 
```
case 'allUsageData':
            $result = $telemetryService->reportUsageData();
            echo json_encode($result);
            break;
```

In track_portal_events.php

Comment (bradymiller) [reply src/Services/ProductRegistrationService.php:67]: will remove that chunk of code in commit to PR tonight :)

Comment (bradymiller) [reply src/Services/ProductRegistrationService.php:67]: The three places that assess if telemetry is disabled now use your handydandy TelemetryService::isTelemetryEnabled() call :)

Comment (sjpadgett) [reply src/Services/ProductRegistrationService.php:67]: when in doubt, write a method!:)

File: interface/main/tabs/main.php [hunk 2]
```diff
@@ -121,7 +122,7 @@
     const isSms = "<?php echo !empty($GLOBALS['oefax_enable_sms'] ?? null); ?>";
     const isFax = "<?php echo !empty($GLOBALS['oefax_enable_fax']) ?? null?>";
     const isServicesOther = (isSms || isFax);
-    const allowTelemetry = <?php echo js_escape($allowTelemetry); ?>;
+    var telemetryEnabled = <?php echo js_escape(TelemetryService::isTelemetryEnabled()); ?>;
```
Comment (bradymiller) [inline interface/main/tabs/main.php:125]: @sjpadgett , for some reason I needed to have this set as a var for it to be seen by tabs_view_model.js script. There are some comments above about how let/const may be out of scope when try to call from other places. This also allows it to be modified (ie. would be nice to turn it on when opt-in rather than needing to logout/login; this is very optional since only gonna gain a little bit of data, but have the option to add this).

File: src/Telemetry/TelemetryService.php [hunk 3]
```diff
@@ -42,7 +42,7 @@ public static function isTelemetryEnabled(): int
     {
         // Check if telemetry is disabled in the product registration table.
         $isEnabled = sqlQuery("SELECT `telemetry_disabled` FROM `product_registration` WHERE `telemetry_disabled` = 0")['telemetry_disabled'] ?? null;
-        if ((int)$isEnabled === 0) {
+        if (!is_null($isEnabled)) {
```
Comment (bradymiller) [inline src/Telemetry/TelemetryService.php:45]: @sjpadgett , This was returning 1 no matter what. I am guessing that forcing null to into makes it a zero. The above change works nicely on testing (when no entry, when null, when 0, and when 1).

**Comment by bradymiller** [comment]
hi @sjpadgett ,
Couple things I noted on testing:
- need to scrub the web path from the portal event_url in the event record for portal events
- noted that api scopes are stored in event_label api event record. will this break the varchar 255 when lots of scopes?

File: src/Telemetry/TelemetryService.php (hunk 3 above)
Comment (sjpadgett) [reply src/Telemetry/TelemetryService.php:45]: yeah I should know better. lol I just told Ruth about this!

**Comment by sjpadgett** [comment]
see here. is this not enough?

        $eventUrl = preg_replace('/\?.*$/', '', $data['eventUrl'] ?? '');

**Comment by bradymiller** [comment]
1. Looks like event_label is varchar 255 in database.sql and upgrade script

2. http://localhost:8300/portal/patient/onsitedocuments showing in my portal event_url (note full path not showing in the api or core menu events)

File: interface/main/tabs/main.php (hunk 2 above)
Comment (sjpadgett) [reply interface/main/tabs/main.php:125]: I put that note in back when I did the jsGlobals!

**Comment by sjpadgett** [comment]
> 1. Looks like event_label is varchar 255 in database.sql and upgrade script
> 2. http://localhost:8300/portal/patient/onsitedocuments showing in my portal event_url (note full path not showing in the api or core menu events)

event_label needs to be varchar because it is a unique key. MariaDB or MySql(forget) doesn't like TEXT as unique keys so I changed in master.
http://localhost:8300/portal/patient/onsitedocuments is by design unless PHI is sneaking by. Some of the portal events I want the drill down and the card structures were engineered to be easy to id cards thus the *-go.

**Comment by sjpadgett** [comment]
Scopes are saved to eventTarget a text column.

```

// Report to Telemetry
// Be nice to find a centralized place to catch failed requests.
try {
    (new TelemetryService())->trackApiRequestEvent([
        'eventType' => 'API',
        'eventLabel' => strtoupper($_SESSION['api'] ?? 'UNKNOWN'),
        'eventUrl' => $restRequest->getRequestMethod() . ' ' . $resource,
        'eventTarget' => json_encode($GLOBALS['oauth_scopes'] ?? []),
    ]);
    exit;
```

**Comment by sjpadgett** [comment]
@bradymiller Nope not weird simply I missed a commit, sorry. I don't think I missed any others but I'll check. Whatever you think is best for portal url maybe normalize the domain!
```

// Report to Telemetry
// Be nice to find a centralized place to catch failed requests.
try {
    (new TelemetryService())->trackApiRequestEvent([
        'eventType' => 'API',
        'eventLabel' => strtoupper($_SESSION['api'] ?? 'UNKNOWN'),
        'eventUrl' => $restRequest->getRequestMethod() . ' ' . $resource,
        'eventTarget' => json_encode($GLOBALS['oauth_scopes'] ?? []),
    ]);
    exit;
} catch (\Exception $e) {
    $logger->error("dispatch.php telemetry error", ['exception' => $e]);
}

```

File: apis/dispatch.php [hunk 4]
```diff
@@ -414,9 +414,9 @@
 try {
     (new TelemetryService())->trackApiRequestEvent([
         'eventType' => 'API',
-        'eventLabel' => json_encode($GLOBALS['oauth_scopes'] ?? []),
-        'eventUrl' => $resource,
-        'eventTarget' => $restRequest->getRequestMethod() . ' ' . $_SESSION['api'],
+        'eventLabel' => strtoupper($_SESSION['api'] ?? 'UNKNOWN'),
+        'eventUrl' => $restRequest->getRequestMethod() . ' ' . $resource,
+        'eventTarget' => json_encode($GLOBALS['oauth_scopes'] ?? []),
```
Comment (bradymiller) [inline apis/dispatch.php:419]: @sjpadgett , just put in your code for this fix. Also made the parameter type an array instead of mixed. and dropped reportUsageData case from track_events.php since realized not being used anywhere.

**Comment by bradymiller** [comment]
btw, above testing well :)

**Comment by sjpadgett** [comment]
@bradymiller Use if you want

TelemetryService.php L-73
// Sanitize URL by stripping query parameters and location parts.
$eventUrl = $this->normalizeUrl($data['eventUrl'] ?? '');

```

    function normalizeUrl(string $url): string {
        // query string is not needed for telemetry
        $parsed = parse_url($url);
        $path = $parsed['path'] ?? '';
        $fragment = isset($parsed['fragment']) ? '#' . $parsed['fragment'] : '';
        $normalized = preg_replace('#^/(interface|portal|modules|sites|openemr)?#', '', $path);

        return ltrim($normalized . $fragment, '/');
    }
```

File: src/Telemetry/TelemetryService.php [hunk 5]
```diff
@@ -179,10 +183,23 @@ public function reportUsageData(): int|bool
...
+        $parsed = parse_url($url);
+        $path = $parsed['path'] ?? '';
+        $fragment = isset($parsed['fragment']) ? '#' . $parsed['fragment'] : '';
+        if (!empty($GLOBALS['webroot'])) {
+            $normalized = preg_replace('#^(' . $GLOBALS['webroot'] . ')?#', '', $path);
+        } else {
+            $normalized = $path;
+        }
+        return ($normalized . $fragment);
+    }
```
Comment (bradymiller) [inline src/Telemetry/TelemetryService.php:204]: @sjpadgett , this is working nicely and basically look like urls that core is bringing in now. only doing this on the portal urls. 
Thank goodness had mechanism to test webroot via easy dev:
```
webroot-management:
  cwb, change-webroot-blank          Change webroot to be blank (this is default setting of environment)
  cwo, change-webroot-openemr        Change webroot to be openemr
```

**Comment by bradymiller** [comment]
Added debug log support for events and couldn't help myself and added support to turn on the top.telemetryEnabled flag when consent for telemetry (so do not need to logout/login for it to start collecting telemetry).

File: src/Telemetry/TelemetryService.php (hunk 5 above)
Comment (sjpadgett) [reply src/Telemetry/TelemetryService.php:224]: yep empty webroot is an issue that bites us all the time for those that alias elsewhere. I try to remember to test on localhost but still get caught. Nice catch!

**Comment by sjpadgett** [comment]
We may want to collect what API grant type is being used.

**Comment by bradymiller** [comment]
Testing well and bringing this in. Gonna need a break from this for at least 24 hours (testing all the different possibilities is a bit crazy :) ). Will also stage this on the PR for patch 4.
regarding the api grant stuff, another day, another PR :)

**Comment by bradymiller** [comment]
Brought in rel-703 for patch 7.0.3.4: #8338
