### PR TITLE
Change in tabs management.

### LINKED ISSUE #4153: Tab switching on patient selection is strange.
### Describe the bug
Patient Finder refresh after selection.
Why does Patient finder now refresh after new patient selection click?
It causes focus change back and forth between Dashboard tab. Sometimes ends on Patient Finder tab instead of Dashboard.

Also, is it a feature in openemr to auto focus on Encounter tab when opening new patient chart? I can't seem to nail down why this happens sometimes while not other times. I seem to remember this back on v4+ at some point.

This will drive folks nuts!
note: I found this on an upgrade from 5.0.1
@bradymiller we really need to get this fixed before/include in v6.0 release.

### PR DESCRIPTION
**Pull request by sjpadgett**
- changed anonymous generated event in navigateTabs to a oneshot event.

Fixes #4153

### CODE REVIEW

File: interface/main/tabs/js/tabs_view_model.js [hunk 1]
```diff
@@ -131,7 +131,7 @@ function navigateTab(url,name,afterLoadFunction,loading_label='')
         if(typeof afterLoadFunction !== 'function'){
             $( "body" ).off( "load", "iframe[name='"+name+"']");
         } else {
-            $("iframe[name='"+name+"']").on('load', function () {
+            $("iframe[name='"+name+"']").one('load', function () {
```
Comment (bradymiller) [inline interface/main/tabs/js/tabs_view_model.js:134]: dang, one vowel bug fix. that deserves OpenEMR fans!
2DV

Comment (sjpadgett) [reply interface/main/tabs/js/tabs_view_model.js:134]: aw shucks! for me.
I happenstance across another to fix. when opening document from encounter history then return from documents, we open a new dashboard tab....

Comment (sjpadgett) [reply interface/main/tabs/js/tabs_view_model.js:134]: Going to have to wait to fix document return from encounter as it uses browser history.
Bringing in
