### PR TITLE
fix(setup): nginx config doc path fix.

### LINKED ISSUE #10525: fix(setup.php): nginx config documentation path fix. edi and era are subdir in documents dir.
nginx config documentation path fix. edi and era are subdir in documents dir.

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #10525

### CODE REVIEW

**Comment by bradymiller** [comment]
Looks like codecov full codebase mode ci is broken. going to bring in since unrelated to this PR.

File: setup.php [hunk 1]
```diff
@@ -1660,7 +1660,7 @@ function cloneClicked() {
                         <h5>1. Deny access to sensitive directories</h5>
                         <p>The <code>\"" . $docsDirectoryGlob . "\"</code> directory contains patient information. Block all direct web access to it:</p>
                         <pre><code>"
-                            . text("location ~* ^/sites/*/(documents|edi|era) {") . "\n"
+                            . text("location ~* ^/sites/*/documents {") . "\n"
```
Comment (bradymiller) [inline setup.php:1663]: @kojiromike , Let me know if have problem with this change (happy to change in a new PR if needed). Expediting this since need to get into rel-800 for testing.
