### PR TITLE
fix(php): explicit precedence for `??`

### LINKED ISSUE #8969: PHP null coalescing operator (??) precedence bugs with comparison operators
## Description

Found 25 instances where the `??` (null coalescing) operator is used with incorrect precedence in comparison or logical operations. Due to PHP operator precedence, these expressions evaluate incorrectly.

## Problem

The `??` operator has lower precedence than comparison operators (`>`, `<`, `==`, `===`) and logical operators (`&&`, `||`). Without parentheses, expressions like:

```php
$var ?? '' == 'value'
```

are parsed as:

```php
$var ?? ('' == 'value')  // Wrong: evaluates to $var ?? false
```

instead of:

```php
($var ?? '') == 'value'  // Correct
```

### Comparison with `>` (2 instances)
- `interface/main/calendar/find_appt_popup.php:179`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php:946`

### Logical `&&` operator (1 instance)
- `library/ajax/set_pt.php:24`

### Equality `==` (18 instances)
- `interface/billing/edit_payment.php:599`
- `interface/forms/eye_mag/a_issue.php:763`
- `interface/forms/eye_mag/php/eye_mag_functions.php:336`
- `interface/forms/eye_mag/php/eye_mag_functions.php:471`
- `interface/forms/eye_mag/php/eye_mag_functions.php:498`
- `interface/forms/eye_mag/php/eye_mag_functions.php:598`
- `interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php:59`
- `interface/modules/custom_modules/oe-module-weno/src/Services/ModuleService.php:190`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:356`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:358`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:360`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:362`
- `interface/reports/collections_report.php:707`
- `interface/reports/collections_report.php:1132`
- `interface/super/edit_globals.php:192`
- `library/custom_template/add_context.php:41`
- `library/custom_template/add_context.php:43`
- `library/custom_template/add_context.php:183`

### Strict equality `===` (4 instances)
- `interface/forms/procedure_order/common.php:1317`
- `interface/forms/procedure_order/common.php:1318`
- `interface/forms/procedure_order/common.php:1319`
- `interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:285`

## Fix

Add parentheses around the `??` expression:

```php
// Before
if ($_REQUEST['facility'] ?? '' > 0) {

// After
if (($_REQUEST['facility'] ?? '') > 0) {
```

## Detection

Found using: `git grep -n "?? '' ==" '*.php' '*.inc'` and similar patterns for other operators.

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #8969

#### Short description of what this resolves:

Explicitly group the null coalescing (`??`) operator with parentheses to ensure coalescing is done before comparison.

#### Changes proposed in this pull request:

- [x] Add parens around null coalescing operations where needed.

### CODE REVIEW

**Comment by kojiromike** [comment]
Note, I don't know of a way to prevent this from coming up again in new code. It can't be caught by classical analysis (as discussed in the admin meeting). Maybe we can find a way to set an AI to the task of catching it.

**Comment by bradymiller** [comment]
yep, agree that would be nice to prevent this in future code. Claude offered off some cool things that can do:


Great idea! Yes, you can set up AI-powered code review in GitHub Actions. Here are several approaches:

## 1. **OpenAI/Anthropic API Integration** (Most Flexible)

Create a custom GitHub Action that uses Claude or GPT-4 to review code:

```yaml
name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id: changed-files
        run: |
          git diff origin/${{ github.base_ref }}...HEAD --name-only > changed_files.txt
      
      - name: AI Review with Claude
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          npm install @anthropic-ai/sdk
          node review.js
      
      - name: Post Review Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const review = fs.readFileSync('review_output.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: review
            });
```

**review.js:**
```javascript
const Anthropic = require('@anthropic-ai/sdk');
const fs = require('fs');

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY
});

async function reviewCode() {
  const changedFiles = fs.readFileSync('changed_files.txt', 'utf8')
    .split('\n')
    .filter(f => f.endsWith('.php'));
  
  let allReviews = [];
  
  for (const file of changedFiles) {
    const code = fs.readFileSync(file, 'utf8');
    
    const message = await client.messages.create({
      model: 'claude-sonnet-4-5-20250929',
      max_tokens: 4096,
      messages: [{
        role: 'user',
        content: `Review this PHP code for bugs, focusing on:
- Operator precedence issues (especially with ??, ?:, and comparisons)
- Type coercion bugs
- Logic errors

Code:
\`\`\`php
${code}
\`\`\`

List any issues found with line numbers and suggested fixes.`
      }]
    });
    
    allReviews.push(`## ${file}\n${message.content[0].text}\n`);
  }
  
  fs.writeFileSync('review_output.txt', allReviews.join('\n'));
}

reviewCode();
```

## 2. **Existing AI Code Review Tools**

### **CodeRabbit** (Recommended)
- Uses AI (GPT-4/Claude) specifically for PR reviews
- Easy GitHub integration
- Free for open source

```yaml
# Just enable at coderabbit.ai - no YAML needed
```

### **Codium AI (PR-Agent)**
```yaml
name: PR Agent
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    steps:
      - uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## 3. **Combine Static Analysis + AI**

Best approach - use PHPStan/Psalm first, then AI for what they miss:

```yaml
name: Code Quality

on: [pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Run PHPStan first
      - name: PHPStan
        run: |
          composer require --dev phpstan/phpstan
          vendor/bin/phpstan analyse --error-format=json > phpstan.json || true
      
      # Then AI review on remaining code
      - name: AI Deep Review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # Send PHPStan results + code to AI for deeper analysis
          node ai-review.js
```

## 4. **Quick Win: Configure PHPStan Better**

PHPStan can actually catch the `?? '' > 0` bug with strict rules:

```neon
# phpstan.neon
parameters:
    level: 9
    strictRules:
        allRules: true
    reportUnmatchedIgnoredErrors: true
```

**My recommendation:** Start with **CodeRabbit** (easiest) or build a custom Claude integration (most powerful for your specific use case). The precedence bug you showed should definitely be catchable with AI review!

File: interface/forms/procedure_order/common.php [hunk 1]
```diff
@@ -1314,9 +1314,9 @@ function doWait(e) {
...
                                 <select name='form_order_abn' id='form_order_abn' class='form-control'>
-                                    <option value="not_required" <?php echo $row['order_abn'] ?? '' === 'not_required' ? ' selected' : '' ?>><?php echo xlt('Not Required'); ?></option>
-                                    <option value="required" <?php echo $row['order_abn'] ?? '' === 'required' ? ' selected' : '' ?>><?php echo xlt('Required'); ?></option>
-                                    <option value="signed" <?php echo $row['order_abn'] ?? '' === 'signed' ? ' selected' : '' ?>><?php echo xlt('Signed'); ?></option>
+                                    <option value="not_required" <?php echo ($row['order_abn'] ?? '') === 'not_required' ? ' selected' : '' ?>><?php echo xlt('Not Required'); ?></option>
+                                    <option value="required" <?php echo ($row['order_abn'] ?? '') === 'required' ? ' selected' : '' ?>><?php echo xlt('Required'); ?></option>
+                                    <option value="signed" <?php echo ($row['order_abn'] ?? '') === 'signed' ? ' selected' : '' ?>><?php echo xlt('Signed'); ?></option>
```
Comment (sjpadgett) [inline interface/forms/procedure_order/common.php:1319]: Okay.

File: interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php [hunk 2]
```diff
@@ -56,7 +56,7 @@
     $weno_zipcode = $_GET['weno_zipcode'] ?? false ?: '';
     $weno_only = $_GET['weno_only'] == 'true' ? 'True' : '';
     $full_day = $_GET['full_day'] == 'true' ? 'Yes' : '';
-    $weno_test_pharmacies = $_GET['test_pharmacy'] ?? '' == 'true' ? 'True' : '';
+    $weno_test_pharmacies = ($_GET['test_pharmacy'] ?? '') == 'true' ? 'True' : '';
```
Comment (sjpadgett) [inline interface/modules/custom_modules/oe-module-weno/scripts/weno_pharmacy_search.php:59]: This was working! still okay

File: interface/modules/custom_modules/oe-module-weno/src/Services/ModuleService.php [hunk 3]
```diff
@@ -187,7 +187,7 @@ public static function statusPharmacyDownloadReset(): bool
     {
         $logService = new WenoLogService();
         $log = $logService->getLastPharmacyDownloadStatus();
-        if ($log['status'] ?? '' == 'Failed') {
+        if (($log['status'] ?? '') == 'Failed') {
```
Comment (sjpadgett) [inline interface/modules/custom_modules/oe-module-weno/src/Services/ModuleService.php:190]: Okay

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php [hunk 4]
```diff
@@ -353,13 +353,13 @@ public function importCore($xml_content, $doc_id = null): void
         } else {
             $tel = $xml['recordTarget']['patientRole']['telecom'] ?? '';
             if (!empty($tel)) {
-                if ($tel['use'] ?? '' == 'MC') {
+                if (($tel['use'] ?? '') == 'MC') {
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php:356]: all okay

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php [hunk 5]
```diff
@@ -943,7 +943,7 @@ private function sanitizeZip($zipLocation)
                     $patientCountHash[$patientNameIndex];
                 }
             } elseif ($componentCount == ($patientDocumentsIndex + 1)) {
-                if ($patientCountHash[$patientNameIndex] ?? '' > $maxDocuments) {
+                if (($patientCountHash[$patientNameIndex] ?? '') > $maxDocuments) {
```
Comment (sjpadgett) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php:946]: okay

**Review by sjpadgett — APPROVED** [review]
I looked over the code I touch a lot and see no harm caused by the changes.

I consider this a PHP bug! They just plopped the null coalesce w/o thought. Either parse or precedent level. I could argue this and be content doing so:)

Anyway this was a good catch but what happens when PHP figures out this is a bug?
