### PR TITLE
Fix #3081 categories button and confirm form

### LINKED ISSUE #3081: Categories Details Button and Confirm form
### Describe the bug

Categories Details button style.
Confirm form not used Bootstrap theme.

### To Reproduce

1. Go to the Administrator > Clinic
2. Click the Calendar
3. Choose Categories 
4. See the go button and click it.
5. See the confirm form.

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system:  Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3081 

#### Short description of what this resolves:
Add button to Bootstrap style.
Fix confirm form Bootstrap pills tab style.

Untitled

### CODE REVIEW

**Comment by im-Amitto** [comment]
@stu01509 Nice BS4 updaes :) , you need to get rid of the merge conflict though.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 1]
```diff
@@ -39,21 +40,20 @@ function postcalendar_admin_modifyconfig($msg = '', $showMenu = true)
...
+
     $output->Text($header);
-    if ($showMenu) {
-        $output->Text(postcalendar_adminmenu());
-    }
 
     if (!empty($msg)) {
-        $output->Text('<center><div style="padding:5px; border:1px solid green; background-color: lightgreen;">');
+        $output->Text(postcalendar_adminmenu("clearCache"));
+        $output -> Text('<div class="alert alert-success ml-1 mr-1 text-center" role="alert">');
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: Can use `mx-1` here inplace of `ml-1 mr-1`

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 2]
```diff
@@ -39,21 +40,20 @@ function postcalendar_admin_modifyconfig($msg = '', $showMenu = true)
...
     $output->SetInputMode(_PNH_VERBATIMINPUT);
 
-    $header = "<html><head><title>" . xlt("Calendar") . "</title></head>";
-    $header .= <<<EOF
-	
-	<body bgcolor=
-EOF;
-    $header .= '"' . attr($GLOBALS['style']['BGCOLOR2']) . '">';
+    $header = "<html><head><title>" . xlt("Calendar") . "</title>";
+    $header .= Header::setupHeader('', false)  . '</head><body>';
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: I am not sure if passing `''` is necessary

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 3]
```diff
@@ -67,12 +67,11 @@ function postcalendar_admin_categoriesConfirm()
     $output->SetInputMode(_PNH_VERBATIMINPUT);
     $header = <<<EOF
 	<html>
-	<head></head>
-	<body bgcolor=
+	<head>
 EOF;
-    $header .= '"' . attr($GLOBALS['style']['BGCOLOR2']) . '">';
+    $header .= Header::setupHeader('', false)  . '</head><body><div class="container">';
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: I am not sure if passing `''` is necessary

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 4]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
     }
 
-    $output->Text(postcalendar_adminmenu());
+    $output->Text(postcalendar_adminmenu("category"));
 
     if (!empty($e)) {
-        $output->Text('<div style="padding:5px; border:1px solid red; background-color: pink;">');
-        $output->Text('<center><b>' . text($e) . '</b></center>');
-        $output->Text('</div><br />');
+        $output -> Text('<div class="alert alert-danger ml-1 mr-1" role="alert">');
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: Can use mx-1 here

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 5]
```diff
@@ -441,18 +440,18 @@ function postcalendar_admin_categories($msg = '', $e = '', $args = array())
...
+        $output->Text('<span class="text-center font-weight-bold">'. text($e) .'</span>');
+        $output -> Text('</div><br />');
     }
 
     if (!empty($msg)) {
-        $output->Text('<div style="padding:5px; border:1px solid green; background-color: lightgreen;">');
-        $output->Text('<center><b>' . text($msg) . '</b></center>');
-        $output->Text('</div><br />');
+        $output -> Text('<div class="alert alert-success ml-1 mr-1" role="alert">');
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: Can use mx-1 here

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 6]
```diff
@@ -813,26 +843,24 @@ function postcalendar_admin_testSystem()
...
     }
     if (strlen($error) > 0) {
-        $info .= "<br /><div style=\"color: red;\">$error</div>";
+        $info .= "<br /><div class='text-danger'>$error</div>";
     }
     array_push($infos, array('smarty compile dir',  $info));
 
     $header = <<<EOF
-	<html>
+	<h1>
```
Comment (im-Amitto) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: I am not sure about this

File: interface/main/calendar/modules/PostCalendar/pnadmin.php (hunk 1 above)
Comment (stu01509) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: Good ideas :)

File: interface/main/calendar/modules/PostCalendar/pnadmin.php (hunk 2 above)
Comment (stu01509) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: I am not sure too, But I just follow @bradymiller, sir tell me import bootstrap syntax.

https://github.com/openemr/openemr/pull/3069#pullrequestreview-369196139

File: interface/main/calendar/modules/PostCalendar/pnadmin.php (hunk 6 above)
Comment (stu01509) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: Thanks for your noticed.

File: interface/main/calendar/modules/PostCalendar/pnadmin.php (hunk 2 above)
Comment (bradymiller) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: yep, that was my bad. Gonna likely bring this into codebase soon after review. I'll then do a quick commit to remove those.

Comment (stu01509) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: Thank you :)

**Comment by bradymiller** [comment]
hi @stu01509 , Code looks good and this is testing well, so bringing this into the codebase. Gonna make a couple adjustments on a follow up commit. Rec updating your repo to most recent codebase for future branches. Thanks for the improvements! -brady

File: interface/main/calendar/modules/PostCalendar/pnadmin.php (hunk 2 above)
Comment (bradymiller) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: @im-Amitto , trying to remove the '' in the first parameter throws a parsing error:
```
Header::setupHeader(, false)
```
Since we have to set the second parameter to false, I think we are stuck with the `''`. Let me know if there's another way I'm not thinking of.

Comment (im-Amitto) [reply interface/main/calendar/modules/PostCalendar/pnadmin.php]: I guess he just feel alone. let's give him his `''` or we can use `[]`which is his default value in case or we can go with `undefined`, so many fish in the sea.
