### PR TITLE
fix: set default X12 partner if only 1 effective insurance

### LINKED ISSUE #7501: bug: default x12 partner not selected in billing manager
### Describe the bug

if there's a charge entry made into a fee sheet before the insurance company is assigned the billing manager may load the item without the x12 partner selected

Screenshot from 2024-06-19 16-32-12

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7501

### CODE REVIEW

**Comment by bradymiller** [comment]
kung-fu-baby-funny

File: interface/billing/billing_report.php [hunk 1]
```diff
@@ -1117,12 +1117,16 @@ function criteriaSelectHasValue(select) {
...
+                                    $insuranceCount = count($effective_insurances ?? []);
 
                                     foreach ($effective_insurances as $key => $row) {
                                         $insuranceName = sqlQuery("SELECT `name` FROM `insurance_companies` WHERE `id` = ?", array($row['provider']))['name'];
                                         $x12Partner = sqlQuery("SELECT `x12_default_partner_id` FROM `insurance_companies` WHERE `id` = ?", array($row['provider']))['x12_default_partner_id'];
                                         $lhtml .= "<option value=\"" . attr(substr($row['type'], 0, 1) . $row['provider']) . "\"";
-                                        if ($key == $last_level_closed) {
+                                        if (
+                                            $key == $last_level_closed
+                                            || $insuranceCount = 1
```
Comment (stephenwaite) [inline interface/billing/billing_report.php:1128]:
```
|| $insuranceCount == 1
```

note to self, wait for Brady's review first :)
