### PR TITLE
test(background-services): add shell-out CLI integration test

### LINKED ISSUE #11686: Add shell-out integration test for bin/console background:services
# Add shell-out integration test for `bin/console background:services`

Currently no test invokes the production cron path the way cron/Kubernetes CronJob actually do. Every `bin/console background:services` unit test uses `Symfony\Component\Console\Tester\CommandTester`, which constructs the command class in-process and bypasses everything between `cron -> /usr/bin/env php -> bin/console -> kernel boot -> command dispatch`. That's precisely the stack where the bugs flagged in this epic hide:

- #11677 / opencoreemr/chart-oce-openemr#114 — exit code on no-op outcomes (caught by unit test, but only because the mapping lives on the command class)
- #11672 — `$_SERVER['PHP_SELF']` missing under CLI (would have been caught by any test that actually shelled out)
- Future: a service function that assumes a web request context, a migration that breaks the Registry upsert, a `bin/console` regression from a Symfony upgrade

## What

Add `tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php` in the existing `services` suite (runs via `build_test services` in `ci/ciLibrary.source`, exercised across the full `ci/apache_*` matrix). The test:

1. Registers a probe service via `BackgroundServiceRegistry` (short interval, a function that flips a sentinel row or writes a temp file).
2. Shells out via `proc_open` to `bin/console background:services run --name=<probe>` (captures stdout, stderr, exit code).
3. Asserts exit 0, expected stdout marker, and that the probe function actually executed (sentinel row present / temp file written).
4. Second case: calls the same binary with no `--name`, asserts exit 0 and that the probe advanced.
5. Third case: calls immediately again (probe will be `not_due`); asserts exit 0 (the #11677 regression shape) and no second execution.
6. Tears down by `unregister()`.

Zero CI-config changes — `services` is already in the test matrix at `.github/workflows/test.yml` line 120, `ciLibrary.source`'s `_exec` runs inside the openemr container so `bin/console` picks up the same DB, config, and PHP environment as production.

## Why

This is the one test shape that proves the epic's deliverables actually work under the execution environment that the chart PR opencoreemr/chart-oce-openemr#114 deploys. Without it, we're fixing bugs in a codebase whose production orchestration path has no regression coverage at all.

## Notes

- `proc_open` is already used elsewhere in the repo (e.g., `tests/Tests/E2e/` for bookend scripts) so the pattern is familiar.
- Needs a small guard for `bin/console`'s path (use `__DIR__ . '/../../../../bin/console'` or similar — verify the services suite's working directory).
- Probe function should be defined in a test-only file that the probe service's `require_once` points at; keep it outside any autoloaded path so it can't leak into production.

### PR DESCRIPTION
**Pull request by kojiromike**
## Summary

Adds an integration test that shells out to `bin/console background:services run` via `Symfony\Component\Process`, proving the full production cron path (cron → php → bin/console → kernel boot → command dispatch) actually runs a registered service. Every other test in this area drives the command class in-process via `CommandTester` and short-circuits that chain.

The test registers a probe service whose function writes to a sentinel file in the temp dir, invokes the real binary, and asserts exit code, stdout marker, and sentinel contents.

Runs in the existing `services` test suite — no CI config changes.

## Status

Draft. Two of the three cases from #11686 are in:

- `testRunByNameExecutesProbeViaShell` — `run --name=<probe>` → exit 0, success marker, sentinel written exactly once.
- `testImmediateRerunIsNotDueAndDoesNotExecuteAgain` — re-run within the interval → exit 2 (current behavior), not-due warning, sentinel unchanged. Inline TODO flips this to exit 0 once #11677 lands.

Deferred:
- Case from the issue that calls `run` with no `--name`. `handleRun` currently errors when `--name` is missing — orthogonal to #11686, will file or bundle later.

Closes #11686 once the remaining case is decided.

## Test plan

- [ ] `docker compose exec openemr /root/devtools services-test` with the new test class
- [ ] Confirm probe sentinel path is stable inside the services container
- [ ] Decide whether to bundle the #11677 fix here or keep them separate

### CODE REVIEW

File: tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php [hunk 1]
```diff
@@ -0,0 +1,200 @@
...
+    private function sentinelLineCount(): int
+    {
+        if (!is_file($this->sentinelPath)) {
+            return 0;
+        }
+        $contents = file_get_contents($this->sentinelPath);
+        if ($contents === false || $contents === '') {
+            return 0;
+        }
+        return substr_count($contents, "\n");
```
Comment (kojiromike) [inline tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php]:
```suggestion
        return substr_count($contents ?: '', "\n");
```

File: tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+    {
+        if (is_file($this->sentinelPath)) {
+            unlink($this->sentinelPath);
+        }
+    }
+
+    private function sentinelLineCount(): int
+    {
+        if (!is_file($this->sentinelPath)) {
+            return 0;
```
Comment (kojiromike) [inline tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php]: This is not covered in testing. Is there any way to use type declarations to guarantee that by the time sentinelLineCount runs, $this->sentinelPath is a file? For example `cliProbeSentinelPath` should guarantee it returns a file.

File: tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php (hunk 1 above)
Comment (kojiromike) [reply tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php]: Took this one step further: dropped both defensive guards (`is_file` and `$contents === false || ''`) and replaced them with explicit `assertFileExists` / `assertNotFalse` calls inside `sentinelLineCount`. That turns the missing/unreadable-file case into a clear test failure instead of a silent `return 0` that would later show up as an unhelpful "expected 1, got 0". See 878d53c221.

File: tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php (hunk 2 above)
Comment (kojiromike) [reply tests/Tests/Services/Background/BackgroundServicesCliIntegrationTest.php]: PHP's type system can't express "this path is a file" — and the sentinel legitimately doesn't exist at construction time (it's created by the subprocess). Closest equivalent is an assertion-level precondition, which is what I went with: `sentinelLineCount` now calls `$this->assertFileExists(...)` before reading. That gives us a test-grade failure message ("Sentinel file must exist before counting probe executions") the first time the precondition is violated, rather than the old dead `return 0` that was never covered. See 878d53c221.

Also added `@codeCoverageIgnore` on `markCliProbeSentinel` with a comment explaining the cross-process measurement limitation — same rationale as the data-provider carve-out documented in `CLAUDE.md`.
