### PR TITLE
Fix #3062 calendar text link

### LINKED ISSUE #3062: Calendar text link change to Bootstrap tabs.
### Describe the bug

Calendar text link change to Bootstrap tabs.

### To Reproduce

1. Go to Administrator > Clinic
2. Click Calendar 
3. See all text links

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3062

#### Short description of what this resolves:
Change text links to Bootstrap pills tab.
Refine Clear Cache success message.

### CODE REVIEW

**Comment by bradymiller** [comment]
I am being a bit thrown off on the initial screen where the Clear Smarty Cache is selected but the screen is blank (since in actuality, nothing is selected). Is there a way to have none of the items selected?

**Comment by bradymiller** [comment]
travis is failing because of the following php 7.2 parsing error (note 7.3 and 7.4 are fine):
```
PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in ./interface/main/calendar/modules/PostCalendar/pnadmin.php on line 779
```

File: interface/main/calendar/modules/PostCalendar/pnadmin.php [hunk 1]
```diff
@@ -39,21 +39,22 @@ function postcalendar_admin_modifyconfig($msg = '', $showMenu = true)
 
     $output->SetInputMode(_PNH_VERBATIMINPUT);
 
-    $header = "<html><head><title>" . xlt("Calendar") . "</title></head>";
+    $header = "<html><head><title>" . xlt("Calendar") . "</title>";
+    $header .= '<link rel="stylesheet" href="../../../public/assets/bootstrap/dist/css/bootstrap.min.css"></head>';
```
Comment (bradymiller) [inline interface/main/calendar/modules/PostCalendar/pnadmin.php]: Rather than include bootstrap directly do this, would consider:
1. `use OpenEMR\Core\Header;` at line 30
2. change above line to:
```
$header .= Header::setupHeader('', false)  . '</head>';
```

**Comment by bradymiller** [comment]
review complete

**Comment by tywrenn** [comment]
Already noticed the outdated table that hasn't been bootstrap'd on the first screenshot

**Comment by stu01509** [comment]
Hi @bradymiller,

I've been fixed clear smarty cache selected problem.
Please review it again :)

Thank you.

**Comment by stu01509** [comment]
Hi @tywrenn,

I will fix it in another PR, 
Thanks for your mention :)

**Comment by bradymiller** [comment]
hi @stu01509 ,
This is definitely an improvement, so bringing this into codebase. Thanks for the improvements! -brady

@tywrenn , agree it can be improved, but do note there is another issue that will solve many of the minor issues in the long-term: https://github.com/openemr/openemr/issues/2949

**Comment by bradymiller** [comment]
also, regarding the travis fail on the php7.2 parsing, this appears to be just a fluke and I have a whitespacing fix to deal with this after I bring in this PR.

**Comment by bradymiller** [comment]
Warning to other code integrators. @stephenwaite @sjpadgett @sunsetsystems @robertdown
It looks like there is a bug in github now where 'squash and merge' are assigning the commit to the integrator (this is the second time it has happened to me today) instead of the author of the PR. I am going to fix this be reverting the commit and recommitting it with correct author.
