### PR TITLE
Fix #3174 patient encounter form field alignment

### LINKED ISSUE #3174: UI Issue: Patient Encounter Form field alignment
### Describe the bug

Patient Encounter Form field alignment.

### To Reproduce

1. In Past Encounters and Documents click item
2. See the Encounter
3. Click edit button
4. See the form

image

### Client configuration

- Browser: Firefox 73.0.1（64 bit）
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by stu01509**
Fixes #3174 

#### Short description of what this resolves:
Adjust form field alignment.
Refine button color and add font-awesome icon.
Refactor js syntax, e.g., ```var``` to ```const```

image

image

### CODE REVIEW

File: interface/forms/newpatient/common.php [hunk 1]
```diff
@@ -528,18 +533,18 @@ function cancelClickedOld() {
             <?php //can change position of buttons by creating a class 'position-override' and adding rule text-align:center or right as the case may be in individual stylesheets ?>
             <div class="form-row">
                 <div class="col-sm-12 text-left position-override">
-                    <button type="button" class="btn btn-secondary btn-save" onclick="top.restoreSession(); saveClicked(undefined);"><?php echo xlt('Save');?></button>
+                    <button type="button" class="btn btn-primary" onclick="top.restoreSession(); saveClicked(undefined);"><i class="fa fa-floppy-o mr-1" aria-hidden="true"></i><?php echo xlt('Save');?></button>
                     <?php if ($viewmode || empty($_GET["autoloaded"])) { // not creating new encounter ?>
-                        <button type="button" class="btn btn-link btn-cancel btn-separate-left" onClick="return cancelClickedOld()"><?php echo xlt('Cancel');?></button>
+                        <button type="button" class="btn btn-danger btn-cancel btn-separate-left" onClick="return cancelClickedOld()"><?php echo xlt('Cancel');?></button>
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]: per recent styling guidelines, lets:
1. use btn-secondary
2. remove btn-cancel and add the cancel icon (from https://github.com/openemr/openemr/blob/master/interface/themes/core/FontAwesome.scss#L29) to the button

File: interface/forms/newpatient/common.php [hunk 2]
```diff
@@ -528,18 +533,18 @@ function cancelClickedOld() {
...
                     <?php } else { // not $viewmode ?>
-                    <button class="btn btn-link btn-cancel btn-separate-left link_submit" onClick="return cancelClickedNew()">
+                    <button class="btn btn-danger btn-cancel btn-separate-left link_submit" onClick="return cancelClickedNew()">
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]: per recent styling guidelines, lets:
1. use btn-secondary
2. remove btn-cancel and add the cancel icon (from https://github.com/openemr/openemr/blob/master/interface/themes/core/FontAwesome.scss#L29) to the button

Comment (stu01509) [reply interface/forms/newpatient/common.php]: I confused in item 2 add the cancel icon,
cancel icon existed in FontAwesome.scss,

Do you mean to add a floppy icon?

**Comment by stu01509** [comment]
Hi @bradymiller 

I only modify btn-danger to btn-secondary in this commit.

File: interface/forms/newpatient/common.php (hunk 2 above)
Comment (bradymiller) [reply interface/forms/newpatient/common.php]: sorry, I should of been more clear on this.

the goal is to not use the btn classes used in https://github.com/openemr/openemr/blob/master/interface/themes/core/FontAwesome.scss

In this case the btn-cancel is using fontawesome icon `\f00d`, which is fa-times

So, will look something like:
```
<button type="button" class="btn btn-secondary btn-separate-left" onClick="return cancelClickedOld()"><i class="fa fa-times mr-1" aria-hidden="true"></i><?php echo xlt('Cancel');?></button>
```

Comment (bradymiller) [reply interface/forms/newpatient/common.php]: hi @stu01509 ,
Also, lets incorporate this rec from the styling guide:
If you have a group of two or more buttons, be sure to use the btn-group class

And will need to fix the merge conflict

(then this should be good for the codebase :) )

**Comment by stu01509** [comment]
Hi @bradymiller 

Thanks for your notice, Please review it again.
Thank you 👍

File: interface/forms/newpatient/common.php (hunk 2 above)
Comment (sjpadgett) [reply interface/forms/newpatient/common.php]: @bradymiller 
Now why in the world and since when is it taboo to have standard save,delete and cancel buttons defined. We're going to be chasing our tails if ever we decide to change an icon. Plus why insist a dev have to do that extra work in design. Button design look and feel is part of the theme and should be defined in one place to keep theme consistent through out. Let's not get to carried away here.

I agree to not allow custom default button overrides for sizing, spacing etc or even overriding the button itself like theme light does a lot. Btn-save, btn-cancel, btn upload and on are all over core code and doing this is not a coding compromise but just makes sense.

Comment (bradymiller) [reply interface/forms/newpatient/common.php]: hi @sjpadgett ,
Just following the styling guide as discussed per @tywrenn . This is definitely the time to figure these things out and what you state is very, very, very reasonable (ie. I am ok with whatever the community decides in this regard), so rec discussing this issue there so we can come to a good centralized conclusion on this asap:
https://github.com/openemr/openemr/issues/3160

Comment (bradymiller) [reply interface/forms/newpatient/common.php]: hi @sjpadgett and @stu01509 ,
I posted this issue on the styling issue. The more I think about, the more what @sjpadgett states makes total sense. We can essentially just use the buttons classes simply for icons:
https://github.com/openemr/openemr/blob/master/interface/themes/core/FontAwesome.scss#L19-L110

Comment (bradymiller) [reply interface/forms/newpatient/common.php]: I'm gonna post some rec changes based on above

File: interface/forms/newpatient/common.php [hunk 3]
```diff
@@ -486,7 +491,7 @@ function cancelClickedOld() {
                             <div class="pb-1">
                                 <div class="btn-group" role="group">
                                     <?php if (AclMain::aclCheckCore('patients', 'med', '', 'write')) { ?>
-                                   <a href="../../patient_file/summary/add_edit_issue.php" class="btn btn-primary btn-sm enc_issue" onclick="top.restoreSession()"><?php echo xlt('Add Issue'); ?></a>
+                                   <a href="../../patient_file/summary/add_edit_issue.php" class="btn btn-primary btn-sm enc_issue" onclick="top.restoreSession()"><i class="fa fa-plus mr-1"></i><?php echo xlt('Add Issue'); ?></a>
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]:
```
<a href="../../patient_file/summary/add_edit_issue.php" class="btn btn-add btn-primary btn-sm enc_issue" onclick="top.restoreSession()"><?php echo xlt('Add Issue'); ?></a>
```

File: interface/forms/newpatient/common.php [hunk 4]
```diff
@@ -528,13 +533,14 @@ function cancelClickedOld() {
...
                 <div class="col-sm-12 text-left position-override">
-                    <button type="button" class="btn btn-secondary btn-save" onclick="top.restoreSession(); saveClicked(undefined);"><?php echo xlt('Save');?></button>
-                    <?php if ($viewmode || empty($_GET["autoloaded"])) { // not creating new encounter ?>
-                        <button type="button" class="btn btn-link btn-cancel btn-separate-left" onClick="return cancelClickedOld()"><?php echo xlt('Cancel');?></button>
-                    <?php } else { // not $viewmode ?>
-                    <button class="btn btn-link btn-cancel btn-separate-left link_submit" onClick="return cancelClickedNew()">
-                            <?php echo xlt('Cancel'); ?></button>
-                    <?php } // end not $viewmode ?>
+                    <div class="btn-group" role="group">
+                        <button type="button" class="btn btn-primary" onclick="top.restoreSession(); saveClicked(undefined);"><i class="fa fa-floppy-o mr-1" aria-hidden="true"></i><?php echo xlt('Save');?></button>
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]:
```
<button type="button" class="btn btn-save btn-primary" onclick="top.restoreSession(); saveClicked(undefined);"><?php echo xlt('Save');?></button>
```

File: interface/forms/newpatient/common.php [hunk 5]
```diff
@@ -528,13 +533,14 @@ function cancelClickedOld() {
...
+                        <?php if ($viewmode || empty($_GET["autoloaded"])) { // not creating new encounter ?>
+                            <button type="button" class="btn btn-secondary btn-separate-left" onClick="return cancelClickedOld()"><i class="fa fa-times mr-1" aria-hidden="true"></i><?php echo xlt('Cancel');?></button>
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]:
```
<button type="button" class="btn btn-cancel btn-secondary btn-separate-left" onClick="return cancelClickedOld()"><?php echo xlt('Cancel');?></button>
```

File: interface/forms/newpatient/common.php [hunk 6]
```diff
@@ -528,13 +533,14 @@ function cancelClickedOld() {
...
+                        <?php } else { // not $viewmode ?>
+                        <button class="btn btn-secondary btn-separate-left link_submit" onClick="return cancelClickedNew()"><i class="fa fa-times mr-1" aria-hidden="true"></i><?php echo xlt('Cancel'); ?></button>
```
Comment (bradymiller) [inline interface/forms/newpatient/common.php]:
```
<button class="btn btn-cancel btn-secondary btn-separate-left link_submit" onClick="return cancelClickedNew()"><?php echo xlt('Cancel'); ?></button>
```

**Comment by bradymiller** [comment]
hi @stu01509 ,
Rec making changes and then will bring this into codebase. Supporting button icons in this fashion (via adding a class from https://github.com/openemr/openemr/blob/master/interface/themes/core/FontAwesome.scss#L19-L110 ) will be much easier to code and maintain.

**Comment by stu01509** [comment]
Hi @bradymiller 

I agreed with this way, This way is very simple to maintain our font-awesome style, We just need to focus on FontAwesome.scss file.

Also, I finished the requested change, Please review again.

**Comment by bradymiller** [comment]
hi @stu01509 , Code looks good and testing well, so bringing into codebase.Thanks for the improvements! -brady
