### PR TITLE
fix: use getTimeFormat for encounter date of service datetime picker

### LINKED ISSUE #7202: bug: encounter date of service time format
### Describe the bug

https://community.open-emr.org/t/time-format-is-this-a-bug/21836/15

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #7202

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @stephenwaite , fun stuff :)
1. Would ensure the scripts that use this datepicker with time with formatinput turned also convert the time correctly to ensure no weirdness (botht the php script and this javascript need to do the same thing)
2. Also would incorporate these change in the new library/js/xl/jquery-datetimepicker-2-5-4-translated.js script (btw, i think there is a bug in that script if you follow the logic; hint: what happens if params.showSeconds is true and params.formatInput is false :) )

**Comment by stephenwaite** [comment]
testing well, thanks for the review, not sure about your hint but it made me take a deep :diving_mask:

File: interface/forms/note/new.php [hunk 1]
```diff
@@ -83,9 +83,9 @@
 
                             <td>
                                 <span class="text"><?php echo xlt('Date'); ?></span>
-                                <input class="datepicker form-control" type='text' size='10' class='datepicker' name='date_of_signature' id='date_of_signature'
-                                       value='<?php echo attr(date('Y-m-d', time())); ?>'
-                                       title='<?php echo xla('yyyy-mm-dd'); ?>' />
+                                <input class="datepicker form-control" type='text' size='16' class='datepicker' name='date_of_signature' id='date_of_signature'
+                                       value='<?php echo attr(oeFormatDateTime(date('Y-m-d H:i', time()), $GLOBALS['time_display_format'])); ?>'
```
Comment (bradymiller) [inline interface/forms/note/new.php:87]: Note if follow oeFormatDateTime to oeFormatTime, no need to set the 2nd parameter (if defaults to 'global' which then uses $GLOBALS['time_display_format'])

Comment (bradymiller) [reply interface/forms/note/new.php:87]: note that when formatInput is used the entry needs to be standardized at some point before going into the daatabase (via the DateTimeToYYYYMMDDHHMMSS() function ).
This form also has a discrepancy in it's view.php for this date widget.

Comment (bradymiller) [reply interface/forms/note/new.php:87]: So 2 things happen for internat to work on the datetimes.
A standard datetime is converted to the localize format via oeFormatDateTime in the datepicker
When saved or used in scripts it is converted back to the standard datetime via the DateTimeToYYYYMMDDHHMMSS function
(rec checking out DateTimeToYYYYMMDDHHMMSS use in code to get an idea how it works)

File: interface/reports/amc_tracking.php [hunk 2]
```diff
@@ -202,7 +202,7 @@ function provide_sum_pat(patient_id,encounter_id) {
                         <?php echo xlt('Begin Date'); ?>:
                       </td>
                       <td>
-                         <input type='text' name='form_begin_date' id="form_begin_date" size='20' value='<?php echo attr(oeFormatDateTime($begin_date, 0, true)); ?>' class='datepicker form-control' />
+                         <input type='text' name='form_begin_date' id="form_begin_date" size='20' value='<?php echo attr(oeFormatDateTime($begin_date, $GLOBALS['time_display_format'], true)); ?>' class='datepicker form-control' />
```
Comment (bradymiller) [inline interface/reports/amc_tracking.php:205]: in cases where you need to use the 2nd parameter (since need to set the second parameter to true, would just use the '"global" string instead of the actual global)

File: library/js/xl/jquery-datetimepicker-2-5-4.js.php [hunk 3]
```diff
@@ -41,6 +41,8 @@
  * @license   https://github.com/openemr/openemr/blob/master/LICENSE GNU General Public License 3
```
Comment (bradymiller) [inline library/js/xl/jquery-datetimepicker-2-5-4.js.php:41]: will need to ensure the new library/js/xl/jquery-datetimepicker-2-5-4-translated.js has same logic for the fixed time stuff

**Comment by adunsulag** [comment]
@stephenwaite I realize the other PR I brought in is now creating issues.  Do you want this in 7.0.2.1 patch?  Or do we bump to 7.0.2.2?  I won't be able to revisit this until Wednesday if you need me to pull down and review.

**Comment by stephenwaite** [comment]
Hi @adunsulag. I think @bradymiller addressed that for me so I'll take another crack at this with the hopes of getting it in patch 1.

**Comment by sjpadgett** [comment]
@bradymiller Would you take a quick look so maybe I can get in patch? Or i'll have to pull down and test

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
code looks great!

2DV

**Comment by adunsulag** [comment]
Removed milestone, as the issue is now connected to the milestone to avoid duplicates.
