### PR TITLE
display correct name when 'choices' group name is changed

### LINKED ISSUE #7670: patient portal card on dashboard mentions 'demographics choices' even if the group has been renamed
### Describe the bug
patient portal card on dashboard mentions 'demographics choices' even if the group has been renamed to something other than choices

### To Reproduce
use admin -> forms -> layouts -> demographics to rename the 'choices' group to something else, e.g. 'Options' 
got to a patient's dashboard
make sure that ' allow patient portal' is not set to YES
look at Patient Portal card, it will appear like this, instead of 'Demographics Options'

Screenshot from 2024-08-13 11-35-05
 
### Expected behaviour

the card should say 'Allow Patient Portal in Demographics Options

### Client configuration

- Browser: firefox
- OpenEMR version: 7.0.3-dev
- Operating system: ubuntu

### PR DESCRIPTION
**Pull request by ruthkonyn**
Fixes #7670

#### Short description of what this resolves:
patient portal card on dashboard mentions 'demographics choices' even if the group has been renamed to something other than choices 

#### Changes proposed in this pull request:
PostalCard.php now looks for the group's name (group 4) in the db and uses the new name - or reverts to 'Choices' if the group name is not returned

### CODE REVIEW

File: src/Patient/Cards/PortalCard.php [hunk 1]
```diff
@@ -78,6 +85,7 @@ private function setOpts()
             'identifier' => self::CARD_ID,
             'title' => xl('Patient Portal') . ' / ' . xl('API Access'),
             'templateVariables' => [
+                'allowpp' => xl('Allow Patient Portal in Demographics ' . $groupName),
```
Comment (bradymiller) [inline src/Patient/Cards/PortalCard.php:88]: can't include leading/trailing spacing in translations and need to translate the group title with a special translation function:
```
'allowpp' => xl('Allow Patient Portal in Demographics' . ' ' . xl_layout_label($groupName)),
```

Comment (bradymiller) [reply src/Patient/Cards/PortalCard.php:88]: actually, would just pass the $groupName into the twig template:
```
'allowpp' => $groupName,
```

File: templates/patient/partials/portal.html.twig [hunk 2]
```diff
@@ -33,7 +33,7 @@ The Patient Portal card for the Medical Record Dashboard
     {% if isPortalAllowed == false %}
         <div class="alert alert-warning" role="alert">
             <p class="font-weight-bold">{{  "Portal Access"|xlt }}</p>
-            <p> {{ "Allow Patient Portal in Demographics Choices."|xlt }} </p>
+            <p> {{ allowpp }} </p>
```
Comment (bradymiller) [inline templates/patient/partials/portal.html.twig:36]:
```
<p> {{ "Allow Patient Portal in Demographic"|xlt }} {{ allowpp|xlLayoutLabel|text }} </p>
```

Note need to add a new xlLayoutLabel function in src/Common/Twig/TwigExtension.php (would put it above the xlListLabel function):
```
            new TwigFilter(
                'xlLayoutLabel',
                function ($string) {
                    return xl_layout_label($string);
                }
            ),
```

File: src/Patient/Cards/PortalCard.php (hunk 1 above)
Comment (ruthkonyn) [reply src/Patient/Cards/PortalCard.php:88]: thanks @bradymiller - i'm doing your first suggestion as it needs the complete string  'Allow Patient Portal in Demographics <groupName>' - rather than simply '<groupName>'

File: templates/patient/partials/portal.html.twig (hunk 2 above)
Comment (ruthkonyn) [reply templates/patient/partials/portal.html.twig]: many thanks @bradymiller - have implemented it the way you suggest in the twig template.

**Comment by ruthkonyn** [comment]
in the past i've ignored the failing Nginx - MariaDB test?

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
hi @ruthkonyn , Code looks great and bringing in. Thanks for the fix!

**Comment by bradymiller** [comment]
btw, ok to fail up to a couple of the ci Test/PHP* runs since these runs just break every once in a while
