### PR TITLE
fixes: CDR engine fixes for duplicate use of actions across rules in addition to an optimization

### LINKED ISSUE #7153: Clinical Rules - several fixes
Entering this issue as part of pull request

I will create individual issues for these items in order to facilitate discussion, with more details in each issue. This is a summary issue for purposes of the PR

I am providing updated code to these files, in order to address several bugs and logic issues in
library\clinical_rules.php

Topics addressed:
-- divide by zero error in calculate_percentage()
-- Reminder Details page showing status of "not due" or "past due" but not "due soon" or "due".
-- Logic deficiencies in evaluating filters and targets:
-- -- logic does not properly handle results of criteria evaluation across categories of data, such as filters on both diagnoses and gender
-- -- logic inappropriately modified right-side boundary for target intervals when determining rule status, resulting in inappropriate rule conclusions
-- -- logic inappropriately applied date intervals during filter evaluation, and unnecessarily performs filter evaluation multiple times

### LINKED ISSUE #7157: Clinical Rules - dates and filters
My topic # 5
Adding an issue for discussing the role of dates in evaluating demographic filters

Initially, my contention was that when evaluating rule filters on an individual patient (for populating Clinical Reminders widget in the patient's dashboard, or the Clinical Reminders details page), dates (other than "today") and intervals should not be part of that calculation

In looking at this more closely, the problem really is that demographic filters are currently being evaluated against 3 timepoints, based on a rule's warning and past due interval values. I contend that doing these three calculations, each with different timepoints, is not appropriate. Filters should be evaluated once for each rule, at the timepoint passed to test_filter() (and test_rules_clinic()) as $dateTarget.

I looked at the rule filter definitions in CDR_Rules_tables. None appear to require performing a date-based calculation. I do agree that if one is running a report, and wanting the analysis to be based on some point in time in past, then some filter calculations might need a time reference. Example would be: what was the reminder status on a patient if the report were run 3 years ago. For that, the age filters would need to calculate the patient's age as of 3 years ago. Similarly, one might want to know what diagnoses were established in the patient as of 3 years ago.
I don't see anything in the filter syntax in the rule_filter table that defines a timepoint, or an interval. For example, I could imagine a filter that wants to find patients who had diabetes added to the diagnosis list sometime in the past 12 months (and not just at any time in the past). There is nothing in the editor gui that allows specifying this interval, and I don't see a way to store this lookback period length in the filter definition in the rule_filter table. 

test_rules_clinic() takes $dateTarget as a parameter. If valued, and if $mode is not 'report', then calculate_reminder_dates() takes $dateTarget and calculates $target_dates, which are based on the warning and past due intervals specified for the rule.
For example, if $dateTarget is "today", and warning: 1 month, past due: 2 months, then $target_dates will have values: T+1M, T, and T-2M. These 3 values are used to loop through the calls to test_filter() and test_targets(), and are called $dateFocus when passed to these functions.

I have no issue with using these three $dateFocus values when calling test_targets(). But I don't see a value in passing each of the three $dateFocus values to test_filter(). I do see value to passing just $dateTarget to test_filter(), and evaluating the filter as of that date.

test_filter() evaluates a filter against the passed $dateFocus value (and calls this value $dateTarget in test_filter() ). It uses its $dateTarget value in age calculations. It also passes its $dateTarget value to database_check(), lists_check() and procedure_check().

In these check functions, it examines an item relative to this $dateTarget value

So, in checking to see if an ICD code exists (via lists_check()), it compares the lists row's date, begdate and enddate values against $dateTarget. It is thus checking to see if the ICD code was defined and valid at the time of $dateTarget, via this logic, with the three ?s assigned to the current value of $dateTarget passed to test_filter():

`"AND ( (`begdate` IS NULL AND `date`<=?) OR (`begdate` IS NOT NULL AND `begdate`<=?) ) " .
"AND ( (`enddate` IS NULL) OR (`enddate` IS NOT NULL AND `enddate`>=?) )`

The problem with this approach is:
-- the three $target_dates values were defined, based on the warning and past due interval values, in order to determine if the rule was "not due", "due soon", "due" or "past due"
-- suppose an ICD code was entered 2 weeks ago and did not have a begdate or enddate associated with it, just a "date" value of 2 weeks ago
-- on the first call to test_filter(), $dateTarget will be T+1M. The date-based test will succeed and the filter will be "true"
-- on the second call to test_filter(), $dateTarget will be T and the filter will be "true"
-- on the third call to test_filter(), $dateTarget will be T-2M. date will not be less than T-2M, and the filter will fail, so the rule will not be considered applicable during the attempt to see if the rule status is "past due"

This problem can be solved by passing $dateTarget, instead of $dateFocus, to test_filter() when looping in test_rules_clinic(). It is fine to pass $dateFocus to test_target(), but not test_filter(). This is not what is in my code in the PR, so I will have to update the PR code

Note that this approach will execute each a call to test_filter() 3 times, each time with the same parameters, so the system is doing 3x the work required in evaluating filters

### LINKED ISSUE #7161: Clinical Rules - interval boundaries used in evaluating target instances
My topic #4
Right-side boundary of intervals used in target evaluation should be now() instead of now() + warning interval or now - past due interval
This is necessary when more than one target exists in a target/action group
Without this fix, a target may be inappropriately considered not satisfied

Discussion:
In a target/action group, there can be multiple targets. 
A target configuration includes defining an interval, such as 3 months, or 1 year. 
In evaluating a rule against a patient's data, the filters are first checked.
If the filter check succeeds, then the targets in each target/action group are checked.
The collection of targets in a target group is checked against 3 possible intervals:
-- #1:  now() + warning interval - target interval -> now() + warning interval    (example: T - 11M - T + 1M)
-- #2: now() - target interval -> now().  (example: T - 12M -> T)
-- #3: now() - target interval - past due interval -> now - past due interval (example: T - 14 M -> T - 2M)
The examples are based on a warning interval of 1 month, a past due interval of 2 months, and a target interval of 1 year

Note that even though an interval can be specified when editing each target, only the most recently specified interval is saved and used in processing all targets across all target/action groups. The entered value is linked to the rule, not the target. It would be nice if the editor and the rule_target table allowed specifying a target-specific interval, but that does not seem to be the case

test_target() is called once for each interval, and in each call, it processes all of the targets in a target group
First, interval #1 is tested.
If instances of the targets in a target group are found with dates that are in interval #1, the rule is deemed "not due". 
Otherwise, if instances of the targets are found with dates that are in interval #2, the rule is deemed "due soon"
Otherwise, if instances of the targets are found with dates that are in interval #3, the rule is deemed "due"
Otherwise, the rule is deemed "past due". This happens if the instances of the target have a date that is prior to the start of interval #3, or if no instances of the targets are found

Note that targets can be required or optional, much like filters
They can also be inclusion, or exclusion, and can have a frequency specified (i.e. the # of times an instance of the target needs to be found during an interval)
If some targets in a group are required, and others optional, only the required ones matter, and the specified number of instances of all required targets need to be found during an interval in order for the target group to be satisfied.
If all targets are optional, then the specified number of instances of at least one of the optional targets needs to be found in the interval.

The interval boundaries used by the logic cause difficulties when there is more that one target defined in a target/action group

Example: a rule's target/action group has two required targets. Each has a frequency of "= 1" and is required and "inclusion". The target interval is 3 months. The rule's warning interval is 2 weeks, and the past due interval is 1 month. Each target is looking for a completion of a custom form.
The logic will use intervals of
#1: T-3M+2W -> T+2W
#2: T-3M -> T
#3: T-3M-1M -> T-1M

Suppose an instance of a form for target #1 has a date of T-3M-1W, and an instance of a form for target #2 has a date of T-1W

The logic will first test interval #1. It will find an instance of target #2's form in the interval, but not target #1's form, so the test will fail and the status will not be "not due"
The logic will then test interval #2. It will again find an instance of target #2's form in the interval, but not target #1's form, so the test will fail and the status will not be "due soon"
The logic will then test interval #3. It will now not find an instance of target #2's form in the interval, but will find target #1's form. Since both are required, the test will again fail and the status will not be "due" (which would seem the appropriate status), and instead be declared to be "past due". This failure is inappropriate, and is due to interval's right-side boundary being T-1M. If it were T (which would seem appropriate), the test would have succeeded. An instance of both forms would have been found in this modified interval, and the targets in the target group declared satisfied

The simple fix to this issue is to modify sql_interval_string() to return intervals whose right-side boundary is T instead of 
T + warning interval for the first interval
and
T - past due interval
for the third interval
(the right-side boundary is already T for the second interval)
The left side boundaries for the intervals would remain unchanged

### LINKED ISSUE #7266: fix reminder_results_integrate() to work when same actions are used in different rules
fix reminder_results_integrate() to work when same actions are used in different rules

### PR DESCRIPTION
**Pull request by bradymiller**
fixes #7266
Fixes #7153
Fixes #7157
Fixes #7161

CDR engine fixes for duplicate use of actions across rules in addition to an optimization

The optimization both clarifies the code regarding which $reminder_due status is chosen and also minimizes the calls to reminder_results_integrate, which could get resource intensive if overuse it.

Also brought in fixes from https://github.com/openemr/openemr/pull/7160

### CODE REVIEW

**Comment by bradymiller** [comment]
hi @hanksterr7 , Interestingly this fix/optimization amplifies that filter bug (where iterating through the filter on all the dates rather than just the target date), which you have fixed in your PR. Because of this, I think it may be best to get your PR into the codebase before this PR.

**Comment by hanksterr7** [comment]
@bradymiller : Interesting. Let me review what you are doing in these changes. Thanks

**Comment by bradymiller** [comment]
hi @hanksterr7 ,
Thanks for the detailed analysis. I'll clarify my comments in the code in the unclear places especially regarding mode.
There are 3 modes:
- 'report' mode is for the report at Reports->Clinic->Standard Measures. This mode only tests 1 datetarget.
- 'reminders-due' is the main mode which runs the passive-alerts/active-alerts/patient reminders (explained these three things below, which are set for each rule in Admin->Practice->Alerts). Goal of this mode is to just show the user what is due.
    - Passive Alerts are in the Clinical Reminders widget in the patient summary screen
    - Patient Reminders are in the Patient Reminders widget in the patient summary screen
    - Active Alerts will show up in a popup when open up the patient summary screen
- 'reminders-all' mode is used in the advanced part of the Clinical Reminders widget in the patient summary screen (click the edit icon at the top right of that widget). The special thing in this mode is that 'Not Due' reminders are shown.

File: library/clinical_rules.php [hunk 1]
```diff
@@ -2777,30 +2781,6 @@ function collect_database_label($label, $table)
     return $returnedLabel;
 }
 
-/**
```
Comment (bradymiller) [inline library/clinical_rules.php:2780]: to help with the review on this, I just removed this function since it was not being used.

**Comment by bradymiller** [comment]
hi @hanksterr7 .
I incorporated your filter fix in this PR, so this code would work correctly. Gave you authorship to the commit that has the filter fix code, which i followed with another commit that had some minor changes in your code. So far testing well. Plan to repeat extensive testing before bringing this in. Let me know if you have thoughts/issues.

**Comment by hanksterr7** [comment]
Hi @bradymiller 
Finally got to reviewing your latest commit. Looks good! (and I like the additional comments in the code)
Comments:
-- of course, still need to get the rest of my changes into the code, for better managing multiple targets and filters (including adjusting the target interval being tested to end on $dateTarget instead of $dateFocus + one of the three interval duration criteria), and better handling of optional vs required targets/filters
-- In your line 1261, you have $action = $actionArray[0];. If $actionArray is not set, this cause an error to be thrown. I recall this happening to me, but I don't recall what rule/data config would repro that. But wrapping the code block in "if ($actionArray) {" is harmless. I suggest adding that.
-- I also note that $pass_target is again getting incremented any time a target passes (for rule statuses of not_due, due_soon or due), which I think is the desired behavior. At one point, when you had wrapped the "if ($passTarget)" section in a test for ($dateCounter == 1), which was causing $passTarget to get updated only if rule status was "not_due", and not if "due_soon" or "due". $pass_target is used in calculate_percentage(). You might want to add a comment that $percentage, as calculated by calculate_percentage(), should be updated even if the rule status is "due", and not just "not_due" or "due_soon". If a rule is "due", that means the patient is no longer meeting criteria, so I'm unclear whether the percentage being reported should should consider the rule as successful when its status is "due". Certainly, both "not_due" and "due soon" suggest the patient is compliant with rule criteria.
Thanks!
-- Hank

**Comment by bradymiller** [comment]
@hanksterr7 ,
I just bundled all your work from your PR into a commit (with your authorship) and put it into this PR. All that's left now is some more testing before this all gets into the codebase (and just in time for the first 7.0.2 patch :) ). Plan to bring this in as a merge so authorship of commits are maintained (ie. you get duly deserved credit for all your work and fixes in this myriad maze of code that i created :) ).

**Comment by bradymiller** [comment]
hi @hanksterr7 ,
That percentage value is only used for report mode. Not sure why i calculate it for every mode and will look into migrating it into a block of code only run during report mode. Note report mode only tests one target date.

**Comment by hanksterr7** [comment]
Hi @bradymiller 
I have compared the code in in this PR with what was in #7160 and all looks good! Nice to see all the #7160 changes incorporated into #7268
I don't have any additional comments
Looking forward to seeing the results of your additional testing, and hopefully merging this in soon
Thanks for all the review you have done of my suggested changes
-- Hank

**Comment by stephenwaite** [comment]
testing well with the demo data!

great job!

freedom-roadtrip

**Comment by hanksterr7** [comment]
@stephenwaite, if you can, try creating some complicated rules that have multiple filters and targets, where the different filters and targets are of different category types (e.g. age, vs vitals, vs diagnoses, vs social hx, vs appointments), and where you have a mix of inclusion and exclusion filters/targets, and where the dates of data the targets are looking at varies relative to the due soon/due/past due intervals (such as having one target, such a diagnosis, entered a week ago, and a blood pressure entered one year less a week ago, for a target interval of 1 year, and a warning interval of one month, and a past due interval of 2 months. That scenario is what my changes tried to make work better. Compare behavior of that scenario in current release vs what this PR is doing. Thanks

**Comment by hanksterr7** [comment]
Here are some tests you can do, to see how behavior changes when using the code in this PR compared to the code in the main branch. Note that the main branch has already been patched to cause the required/optional labels in the Rules UI to now be correct

This could be helpful to include in release notes

Preparation:
-- create Rule #1 with configuration:
-- -- passive
-- -- warning 1 month, past due 2 months
-- -- demographic filters: none
-- -- target: custom: assessment: alcohol, completed: yes, frequency: >= 1, optional: yes, inclusion: yes, interval: 1 day
-- -- action: custom: assessment: alcohol, custom input: yes
The above rule allows Assessment: Alcohol to show in the reminders widget in patient dashboard, giving easy access to modifying the date and completion choice for instances of this this custom item

-- create Rule #2, with configuration:
-- -- passive
-- -- warning 1 month, past due 2 months
This is the rule that will be modified for the tests below. The rest of the configuration depends on the test being done

-- create a patient with age: 25, gender: female, Medical Problem: ICD10 diagnosis: Chronic Obstructive Pulmonary Disease, J44.9 (or any problem of your choosing), begin date; blank, end date: blank (modify date will be set to the date you created the problem)


issues being tested/fixed:
-- Issue #1: age/gender filters treated as required, even though UI lets these be declared as optional
Test by modifying Rule #2 to have
-- demographic filters:
-- -- age min 30 years, optional: yes, inclusion: yes
-- -- age max 40 years, optional: yes, inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using main branch code for library\clinical_rules.php:
Refresh dashboard. Education: blood pressure will not be in the list, because the age min filter does not succeed, and the age max filter does not get tested, even though both are optional: yes
Change the filters to age min: 20 years, age max: 30 years.  Education: blood pressure now shows (with status: past due, since no instance of Education: Blood Pressure has been created), since both filters succeed.
Change the filters to age min: 20 years, age max: 22 years. Education: blood pressure does not show. So both filters are being treated as required, even though they were declared as optional
Using PR code for library\clinical_rules.php, observe results matching expectations for optional filters

-- Issue #2: optional filter failure in one category doesn't allow checking optional or required filter in next category
Order in which filter categories are checked:
-- Inclusions
-- -- age min
-- -- age max
-- -- gender
-- -- db (custom, lifestyle, custom table)
-- -- lists (diagnoses, meds, surgeries, allergies)
-- -- procedures
-- Exclusions:
-- -- lists
Test by modifying Rule #2 to have
-- demographic filters:
-- -- custom: Assessment: Alcohol, completed: yes, frequency: >= 1, optional: yes, inclusion: yes
-- -- diagnosis: ICD10 diagnosis: Chronic Obstructive Pulmonary Disease, J44.9, optional: yes, inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using main branch code:
Refresh dashboard. Observe that Education: Blood Pressure does not show in reminder widget
This is because the optional Assessment: Alcohol filter does not succeed (since no instance of this custom item has been created yet), and, inappropriately, the diagnosis filter does not get checked (which would have succeeded), so the rule is considered not applicable to the patient.
Create an instance of Assessment: Alcohol, completed: yes, date: T-3M. Refresh dashboard. Education: Blood Pressure will show, with status: "past due" (since no instance of Education: Blood Pressure has been created)
If modify the Assessment: Alcohol instance to have date: T-1W, the status will inappropriately change to "due", for reasons explained in the next issue.
If modify the Assessment: Alcohol instance to have completed: no, Education: Blood Pressure will again not show since the Assessment: Alcohol filter never succeeds and the diagnosis filter inappropriately again does not get checked.
Using PR code, Education: Blood Pressure will appropriately show as "past due", regardless of existence, date, or completed status of the Assessment: Alcohol instance


-- Issue #3: rule gets status of "due" instead of "past due" if filter data has date between T-PastDueInterval and T. 
$dateFocus is used when checking filters (db, lists, procedure). sql includes <dateField> <= $dateFocus (or <dateStartField> <= $dateFocus and <dateEndField> >= $dateFocus). If data for filter has start date between T-PastDueInterval and T, and data for target is in past due range, rule gets status of due instead of past due since processing for 3rd pass stops after filter failure, with status remaining "due" inappropriately
This is since rule status is set at end of a $dateFocus pass to state rule has if filter passes and target does not pass.
pass 1: -> due soon
pass 2: -> due
pass 3: -> past due
If filter and target succeed during a $dateFocus pass, the previously set state persists unchanged.
Test by modifying Rule #2 to have:
-- demographic filter:
-- -- Custom: Assessment: Alcohol, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using Main Branch code
Refresh dashboard. 
Find the Assessment: Alcohol item and set it to have: completed: yes, date: T-1W
Refresh dashboard
Observe Education: Blood Pressure shows, but inappropriately with status "due" instead of "past due". Should be "past due" since no instance of Education: Blood Pressure exists.
Click "Education: Blood Pressure" in  reminder widget and create an instance of this custom item, with completed: yes, date: T-9M (so is in "past due" range). Dashboard continues to show status as "due" instead of "past due". Change date to T-7M. Status remains "due". Change date to one week sooner than T-6M. Status appropriately changes to "due soon". Change date to T-1W. Education: Blood Pressure disappears from reminder widget but shows in reminder details with status: "not due" (or maybe blank, depending if fix for reminder details status values has been applied to main branch).
The above happens because, on the third pass of checking filters/targets, $dateFocus is T-2M, so the Assessment: Alcohol instance is not found (its date is sooner than T-2M), the filter is deemed not applicable for pass #3, and the status of "Due", set in pass #2, persists.
Change criteria for Assessment: Alcohol filter to be completed: no
Refresh dashboard. Education: Blood Pressure now does not show. This happens because Assessment: Alcohol filter never succeeds
Change criteria for Assessment: Alcohol filter to be completed: yes, date: T-3M.
Refresh the dashboard. Education: Blood Pressure shows with appropriate status as the date of the Education: Blood Pressure instance is changed between T-9M, T-7M, one week sooner than T-6M, and T-3M
Using PR code, Education: Blood Pressure status matches the date of the Education: Blood Pressure instance, when Assessment: Alcohol date is T-1W

-- Issue #4: if have two required targets, one with data date between T-PastDueInterval and T, and the other in "due" range, rule shows as past due instead of due, since on no $dateFocus pass do both targets succeed. 
Happens because during the three $dateFocus passes, the intervals checked are:
T-targetInterval+warningInterval -> T+warningInterval
T-targetInterval -> T
T-targetInterval-pastDueInterval -> T-pastDueInterval
This is fixed in the PR by using these intervals instead:
T-targetInterval+warningInterval -> T
T-targetInterval -> T
T-targetInterval-pastDueInterval -> T
Test by modifying Rule #2 to have a filter that always succeeds (e.g. age or gender), and two targets in a target/action group, one for Assessment: Alcohol, and the other for Education: Blood Pressure. Both: frequency: >= 1, optional: no, inclusion: yes, interval: 6 months. 
action: custom: education: blood pressure, custom input: yes
Set the dates for instances of the two targets as described above and observe status
Using PR code, rule status will correspond to the date of the older target instance

-- Issue #5: if have more than one target in a target/action group, and if optional ones in a category do not succeed, subsequent categories are not checked. Reasons are same as for Issue #2.
Also, only targets with inclusion: yes are checked. Any with inclusion: no are ignored.
Order in which target categories are checked:
-- Inclusion: 
-- -- db
-- -- procedure
-- -- appointment
Test using the guidelines described in the various issues above, but would need to have a target in two of the three categories listed to perform an appropriate test
PR code handles tests of optional targets across target categories properly, but does not add support for exclusion targets.

**Comment by hanksterr7** [comment]
Hi @bradymiller  and @stephenwaite

To help you do some testing of of the changes in my code, I offer what is below

These will show how behavior changes when using the code in this PR compared to the code in the main branch. Note that the main branch has already been patched to cause the required/optional labels in the Rules UI to now be correct

This could be helpful to include in release notes

Preparation:
-- create Rule https://github.com/openemr/openemr/pull/1 with configuration:
-- -- passive
-- -- warning 1 month, past due 2 months
-- -- demographic filters: none
-- -- target: custom: assessment: alcohol, completed: yes, frequency: >= 1, optional: yes, inclusion: yes, interval: 1 day
-- -- action: custom: assessment: alcohol, custom input: yes
The above rule allows Assessment: Alcohol to show in the reminders widget in patient dashboard, giving easy access to modifying the date and completion choice for instances of this this custom item

-- create Rule https://github.com/openemr/openemr/pull/2, with configuration:
-- -- passive
-- -- warning 1 month, past due 2 months
This is the rule that will be modified for the tests below. The rest of the configuration depends on the test being done

-- create a patient with age: 25, gender: female, Medical Problem: ICD10 diagnosis: Chronic Obstructive Pulmonary Disease, J44.9 (or any problem of your choosing), begin date; blank, end date: blank (modify date will be set to the date you created the problem)

issues being tested/fixed:
-- Issue https://github.com/openemr/openemr/pull/1: age/gender filters treated as required, even though UI lets these be declared as optional
Test by modifying Rule https://github.com/openemr/openemr/pull/2 to have
-- demographic filters:
-- -- age min 30 years, optional: yes, inclusion: yes
-- -- age max 40 years, optional: yes, inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using main branch code for library\clinical_rules.php:
Refresh dashboard. Education: blood pressure will not be in the list, because the age min filter does not succeed, and the age max filter does not get tested, even though both are optional: yes
Change the filters to age min: 20 years, age max: 30 years. Education: blood pressure now shows (with status: past due, since no instance of Education: Blood Pressure has been created), since both filters succeed.
Change the filters to age min: 20 years, age max: 22 years. Education: blood pressure does not show. So both filters are being treated as required, even though they were declared as optional
Using PR code for library\clinical_rules.php, observe results matching expectations for optional filters

-- Issue https://github.com/openemr/openemr/pull/2: optional filter failure in one category doesn't allow checking optional or required filter in next category
Order in which filter categories are checked:
-- Inclusions
-- -- age min
-- -- age max
-- -- gender
-- -- db (custom, lifestyle, custom table)
-- -- lists (diagnoses, meds, surgeries, allergies)
-- -- procedures
-- Exclusions:
-- -- lists
Test by modifying Rule https://github.com/openemr/openemr/pull/2 to have
-- demographic filters:
-- -- custom: Assessment: Alcohol, completed: yes, frequency: >= 1, optional: yes, inclusion: yes
-- -- diagnosis: ICD10 diagnosis: Chronic Obstructive Pulmonary Disease, J44.9, optional: yes, inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using main branch code:
Refresh dashboard. Observe that Education: Blood Pressure does not show in reminder widget
This is because the optional Assessment: Alcohol filter does not succeed (since no instance of this custom item has been created yet), and, inappropriately, the diagnosis filter does not get checked (which would have succeeded), so the rule is considered not applicable to the patient.
Create an instance of Assessment: Alcohol, completed: yes, date: T-3M. Refresh dashboard. Education: Blood Pressure will show, with status: "past due" (since no instance of Education: Blood Pressure has been created)
If modify the Assessment: Alcohol instance to have date: T-1W, the status will inappropriately change to "due", for reasons explained in the next issue.
If modify the Assessment: Alcohol instance to have completed: no, Education: Blood Pressure will again not show since the Assessment: Alcohol filter never succeeds and the diagnosis filter inappropriately again does not get checked.
Using PR code, Education: Blood Pressure will appropriately show as "past due", regardless of existence, date, or completed status of the Assessment: Alcohol instance

-- Issue https://github.com/openemr/openemr/pull/3: rule gets status of "due" instead of "past due" if filter data has date between T-PastDueInterval and T.
$dateFocus is used when checking filters (db, lists, procedure). sql includes <= $dateFocus (or <= $dateFocus and >= $dateFocus). If data for filter has start date between T-PastDueInterval and T, and data for target is in past due range, rule gets status of due instead of past due since processing for 3rd pass stops after filter failure, with status remaining "due" inappropriately
This is since rule status is set at end of a $dateFocus pass to state rule has if filter passes and target does not pass.
pass 1: -> due soon
pass 2: -> due
pass 3: -> past due
If filter and target succeed during a $dateFocus pass, the previously set state persists unchanged.
Test by modifying Rule https://github.com/openemr/openemr/pull/2 to have:
-- demographic filter:
-- -- Custom: Assessment: Alcohol, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes
-- target: custom: education: blood pressure, completed: yes, frequency: >= 1, optional: yes or no (doesn't matter), inclusion: yes, interval: 6 months
-- action: custom: education: blood pressure, custom input: yes
Using Main Branch code
Refresh dashboard.
Find the Assessment: Alcohol item and set it to have: completed: yes, date: T-1W
Refresh dashboard
Observe Education: Blood Pressure shows, but inappropriately with status "due" instead of "past due". Should be "past due" since no instance of Education: Blood Pressure exists.
Click "Education: Blood Pressure" in reminder widget and create an instance of this custom item, with completed: yes, date: T-9M (so is in "past due" range). Dashboard continues to show status as "due" instead of "past due". Change date to T-7M. Status remains "due". Change date to one week sooner than T-6M. Status appropriately changes to "due soon". Change date to T-1W. Education: Blood Pressure disappears from reminder widget but shows in reminder details with status: "not due" (or maybe blank, depending if fix for reminder details status values has been applied to main branch).
The above happens because, on the third pass of checking filters/targets, $dateFocus is T-2M, so the Assessment: Alcohol instance is not found (its date is sooner than T-2M), the filter is deemed not applicable for pass https://github.com/openemr/openemr/pull/3, and the status of "Due", set in pass https://github.com/openemr/openemr/pull/2, persists.
Change criteria for Assessment: Alcohol filter to be completed: no
Refresh dashboard. Education: Blood Pressure now does not show. This happens because Assessment: Alcohol filter never succeeds
Change criteria for Assessment: Alcohol filter to be completed: yes, date: T-3M.
Refresh the dashboard. Education: Blood Pressure shows with appropriate status as the date of the Education: Blood Pressure instance is changed between T-9M, T-7M, one week sooner than T-6M, and T-3M
Using PR code, Education: Blood Pressure status matches the date of the Education: Blood Pressure instance, when Assessment: Alcohol date is T-1W

-- Issue https://github.com/openemr/openemr/pull/4: if have two required targets, one with data date between T-PastDueInterval and T, and the other in "due" range, rule shows as past due instead of due, since on no $dateFocus pass do both targets succeed.
Happens because during the three $dateFocus passes, the intervals checked are:
T-targetInterval+warningInterval -> T+warningInterval
T-targetInterval -> T
T-targetInterval-pastDueInterval -> T-pastDueInterval
This is fixed in the PR by using these intervals instead:
T-targetInterval+warningInterval -> T
T-targetInterval -> T
T-targetInterval-pastDueInterval -> T
Test by modifying Rule https://github.com/openemr/openemr/pull/2 to have a filter that always succeeds (e.g. age or gender), and two targets in a target/action group, one for Assessment: Alcohol, and the other for Education: Blood Pressure. Both: frequency: >= 1, optional: no, inclusion: yes, interval: 6 months.
action: custom: education: blood pressure, custom input: yes
Set the dates for instances of the two targets as described above and observe status
Using PR code, rule status will correspond to the date of the older target instance

-- Issue https://github.com/openemr/openemr/pull/5: if have more than one target in a target/action group, and if optional ones in a category do not succeed, subsequent categories are not checked. Reasons are same as for Issue https://github.com/openemr/openemr/pull/2.
Also, only targets with inclusion: yes are checked. Any with inclusion: no are ignored.
Order in which target categories are checked:
-- Inclusion:
-- -- db
-- -- procedure
-- -- appointment
Test using the guidelines described in the various issues above, but would need to have a target in two of the three categories listed to perform an appropriate test
PR code handles tests of optional targets across target categories properly, but does not add support for exclusion targets.

**Comment by bradymiller** [comment]
fyi, getting close on this. Just a bit more testing (guessing will get into codebase over the weekend)

**Comment by stephenwaite** [comment]
setup an [up for grabs demo](https://www.open-emr.org/wiki/index.php/Development_Demo#Beta_-_Up_For_Grabs_Demo)

**Comment by hanksterr7** [comment]
@stephenwaite : what is the "up for grabs demo"? Is my code included in it? Is there anything I need to do to help make this happen?
Thanks
-- Hank

**Comment by hanksterr7** [comment]
@stephenwaite and @bradymiller 
I compared the behavior of rules in the alpha demo vs the standard (release) demo
I ran the tests listed below, following the instructions I listed in my prior message, and can confirm that all rule functions work properly in the alpha version, and do not work properly in the release version
-- age + gender optional demographic filters
-- asmt: appointment + medication: lisinopril, both optional demographic filters
-- asmt: appointment demog (instance 3 days ago), education bp target. rule never shows as past due in release
-- demog filter: age min > 2 years. targets: asmt: appointment (instance 3 days ago) and educ: bp (instance 7 months ago). rule shows as past due in release. shows as due in alpha

The alpha system behaves as I would expect, based on my fixes
Thanks

**Comment by bradymiller** [comment]
hi @hanksterr7 ,
Thanks for the testing. My testing also working well. So bringing this in. Will bring it into rel-702 (so will be in next patch) this evening. Thanks for the awesome work on this!

**Comment by stephenwaite** [comment]
smaller_excited_elephant

way to go @hanksterr7 @bradymiller !!!

**Comment by hanksterr7** [comment]
Great to see all my changes now in the master branch! Thanks everyone for all the effort and support
