### PR TITLE
fix #6085, ins search fixes

### LINKED ISSUE #6085: not able to set insurance in demographics through `Search/Add`
### Describe the bug

Search for an ins
Screenshot from 2023-01-10 16-25-25
Close the form and the Ins should be selected in the dropdown
Screenshot from 2023-01-10 16-25-40

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6085

### CODE REVIEW

File: interface/new/new_comprehensive.php [hunk 1]
```diff
@@ -637,7 +637,7 @@ function end_group()
                                     ?>
                               </select>
                               <div class="input-group-append">
-                                <a class='btn btn-primary text-white medium_modal' href='../practice/ins_search.php' onclick='ins_search(<?php echo attr($i); ?>)'><?php echo xlt('Search/Add Insurer'); ?></a>
+                                <a class='btn btn-primary text-white medium_modal' href='../practice/ins_search.php' onclick='ins_search(<?php echo attr_js($i); ?>)'><?php echo xlt('Search/Add Insurer'); ?></a>
```
Comment (bradymiller) [inline interface/new/new_comprehensive.php:640]: dance-bear

**Review by bradymiller — APPROVED** [review]
