### PR TITLE
 cms122 laboratory test performed issues

### LINKED ISSUE #5391: cms122 laboratory test performed issues
### Describe the bug

 do not include deleted procedures for qrda I lab test performed
need a result date and end date for procedure results form
need to support relevant period

### To Reproduce

1. Add a '....'

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #5391

### CODE REVIEW

**Review by bradymiller — APPROVED** [review]

**Comment by bradymiller** [comment]
118382341-53d9d600-b5c2-11eb-8b7e-220bbab8468a

**Comment by stephenwaite** [comment]
thanks @bradymiller 

talked it over with @adunsulag and this gets us passing on @sjpadgett's CMS122 with relevantPeriod and will pass SLI's relevant datetime

problem was we weren't recording the result date on manual entry in the procedure results screen
Screenshot from 2022-05-28 13-07-23

**Review by bradymiller — APPROVED** [review]

File: src/Services/Qdm/Services/LaboratoryTestService.php [hunk 1]
```diff
@@ -63,6 +67,16 @@ public function makeQdmModel(QdmRecord $recordObj)
             'relevantDatetime' => new DateTime([
                 'date' => $record['date']
             ]),
+            'relevantPeriod' => new Interval([
+                'low' => new DateTime([
+                    'date' => $record['date']
+                ]),
+                'high' => new DateTime([
+                    'date' => $record['date_end'] ?: null
```
Comment (adunsulag) [inline src/Services/Qdm/Services/LaboratoryTestService.php:75]: I guess the mustache templates will skip relevantPeriod if the high date is empty right?  I was thinking we'd put this in a conditional and only populate if we have a date end but I think this is taken care of in the mustache template.  So this all looks good to me.

File: interface/orders/orders_results.php [hunk 2]
```diff
@@ -616,6 +622,18 @@ class='form-control'
                                 class='form-control'
                                 value='<?php echo attr($result_text); ?>' />
                         </td>
+                        <td class="text-nowrap">
+                                <input type='text' size='13' name='form_result_date[<?php echo attr($lino); ?>]'
+                                    id='form_result_date[<?php echo attr($lino); ?>]'
+                                    class='form-control datetimepicker' value='<?php echo attr($date_result); ?>'
```
Comment (adunsulag) [inline interface/orders/orders_results.php:628]: This needs to be $result_date instead of $date_result.

File: interface/orders/orders_results.php [hunk 3]
```diff
@@ -616,6 +622,18 @@ class='form-control'
...
+                                    title='<?php echo xla('Date and time of this result'); ?>' />
+                        </td>
+                        <td class="text-nowrap">
+                                <input type='text' size='13' name='form_result_date_end[<?php echo attr($lino); ?>]'
+                                    id='form_result_date_end[<?php echo attr($lino); ?>]'
+                                    class='form-control datetimepicker' value='<?php echo attr($date_result_end); ?>'
```
Comment (adunsulag) [inline interface/orders/orders_results.php:634]: This needs to be $result_date_end instead of $date_result_end.  That makes it so the date shows up on the save.

**Comment by adunsulag** [comment]
@stephenwaite I just went through a bunch of tests on Jerry's cypress and they all appear to be working.  It does look like your iss5391 isn't on the latest master when I pulled your branch as measure 130 breaks on SLI.  Jerry recently fixed this in master though and your branch is missing my enhanced ccda search stuff.  Overall though running your tests passed every single measure on Jerry's instance so I'm going to say this is fine to bring in once the display bugs are fixed.

I found a display bug where the output of the start and end date for the result are not being displayed.  Once that is fixed this should be ready to go.
