### PR TITLE
random patient generator related updates

### LINKED ISSUE #4720: Layout Editor save broken
### Describe the bug
When saving any layout the result changes label column and data columns to 1 0 respectively. Unknown at this time if over writes in tables or just a display issue. Perhaps something to do with new additions on code(s). Also we need to address breaking up the single row edit line into a view that is more user friendly.

Before save

image

After:

image

### To Reproduce
Edit any layout and save.

Fails on dev demo which is a couple weeks behind master.

### PR DESCRIPTION
**Pull request by bradymiller**
@sjpadgett , just had several php8 related warnings to fix. The time per patient has increased from average of 0.4 seconds per patient to 1.5 seconds per patient, which is likely because the labs are now correctly being imported (by the way, all the importing looks great and much improved from before, so the OpenEMR fans are happy!). I'll see if can find any way to speed things up, although it's currently at a really good speed (would work out to 57600 patient imports per day, so getting to 1 million would take awhile :) ). Another really good thing is that the speed isn't slowly down as more patients are added (this was an issue in past that was a pain to fix), so overall the random patient generator is in great shape! thanks!

Pasted a sample run of 1000 patients below:
```
Starting patients import
50 patients imported (65 total seconds) (1.3 average seconds per patient for last 50 patients)
100 patients imported (145 total seconds) (1.6 average seconds per patient for last 50 patients)
150 patients imported (212 total seconds) (1.34 average seconds per patient for last 50 patients)
200 patients imported (288 total seconds) (1.52 average seconds per patient for last 50 patients)
250 patients imported (362 total seconds) (1.48 average seconds per patient for last 50 patients)
300 patients imported (480 total seconds) (2.36 average seconds per patient for last 50 patients)
350 patients imported (550 total seconds) (1.4 average seconds per patient for last 50 patients)
400 patients imported (607 total seconds) (1.14 average seconds per patient for last 50 patients)
450 patients imported (672 total seconds) (1.3 average seconds per patient for last 50 patients)
500 patients imported (745 total seconds) (1.46 average seconds per patient for last 50 patients)
550 patients imported (827 total seconds) (1.64 average seconds per patient for last 50 patients)
600 patients imported (890 total seconds) (1.26 average seconds per patient for last 50 patients)
650 patients imported (959 total seconds) (1.38 average seconds per patient for last 50 patients)
700 patients imported (1034 total seconds) (1.5 average seconds per patient for last 50 patients)
750 patients imported (1126 total seconds) (1.84 average seconds per patient for last 50 patients)
800 patients imported (1187 total seconds) (1.22 average seconds per patient for last 50 patients)
850 patients imported (1248 total seconds) (1.22 average seconds per patient for last 50 patients)
900 patients imported (1308 total seconds) (1.2 average seconds per patient for last 50 patients)
950 patients imported (1388 total seconds) (1.6 average seconds per patient for last 50 patients)
1000 patients imported (1456 total seconds) (1.36 average seconds per patient for last 50 patients)
Completed patients import (1000 patients) (1456 total seconds) (1.456 average seconds per patient)
Started uuid creation
Completed uuid creation (1509 total seconds; 0.41916666666667 total hours)
Completed run for following number of random patients: 1000
```

fixes #4720

### CODE REVIEW

**Comment by adunsulag** [comment]
Congatulations @sjpadgett and @bradymiller.  Great to see the importer fixes going on.

**Comment by sjpadgett** [comment]
Happy to hear @bradymiller. I'm fairly sure I could optimize the imports of procedure/labs now I know the work flow is correct. Setting up to bypass the audits for batch imports would help.

I don't understand why the windows version of PHP doesn't show the warnings you see! Perplexing but thanks for testing and fixing...

File: src/Services/Cda/CdaTemplateImportDispose.php [hunk 1]
```diff
@@ -1228,21 +1228,21 @@ public function insertImportedUser($value, $create_user_name = false)
         $userName = "";
 
         if (!empty($value['provider_fname'])) {
-            $value['provider_name'] = $value['provider_fname'] ?: 'External';
-            $value['provider_family'] = $value['provider_lname'] ?: 'Provider';
+            $value['provider_name'] = $value['provider_fname'] ?? 'External';
+            $value['provider_family'] = $value['provider_lname'] ?? 'Provider';
```
Comment (sjpadgett) [inline src/Services/Cda/CdaTemplateImportDispose.php:1232]: This changes the logic. There's a difference between a null and empty string when null coalescing. $value mostly won't ever be undefined to coalesce to null so if $value is empty 'External' string will not populate. The change will break logic.

So this was not a mistake. It shouldn't throw any warnings either. To reiterate: if $value = "" your changes will return "" and not 'External'

Comment (sjpadgett) [reply src/Services/Cda/CdaTemplateImportDispose.php:1232]: Or if warnings it could be written
`$value['provider_name'] = ($value['provider_fname'] ?? '') ?: 'External';`

Comment (bradymiller) [reply src/Services/Cda/CdaTemplateImportDispose.php:1232]: Warnings happen with elvis if variable is not set. Yep, figured these changes may do something and got a headache trying to work out difference between elvis and null coelescing https://www.fparedes.com/blog/null-coalescing-vs-elvis-operator-php/ :)

Completely agree with your suggestion and will make the changes :)
