### PR TITLE
refactor(php): fix case-sensitive constant names

### LINKED ISSUE #9133: `SensitiveConstantNameRector` - php names are case-sensitive

### PR DESCRIPTION
**Pull request by kojiromike**
Fixes #9133

#### Short description of what this resolves:

Apply `SensitiveConstantNameRector` rule.

#### Changes proposed in this pull request:

- [x] chore(rector): set SensitiveConstantNameRector
- [x] refactor(php): fix case-sensitive constant names

### CODE REVIEW

File: interface/billing/print_daysheet_report_num2.php [hunk 1]
```diff
@@ -132,7 +132,7 @@
 // sort array in assending order
     sort($final_list);
 
-    $all4 = array_natsort($ret, pid, fulname, asc);
+    $all4 = array_natsort($ret, \PID, \FULNAME, \ASC);
```
Comment (kojiromike) [inline interface/billing/print_daysheet_report_num2.php]: @openemr/admins I'm guessing these aren't constants, but should have been quoted strings?

**Comment by kojiromike** [comment]
@openemr/admins Everything rector found here is clearly a bug, but not the bug rector thinks it is. I have updated everything to quote the names as string literals instead of what rector wanted to do, which was convert everything to constants.
