### PR TITLE
USCDI v3 CCDA

### LINKED ISSUE #8647: CCDA ONC 2025 Updates
- This is a close outline of current status and needs. I expect this will grow some but this gives me some organization to get started.

[ ] **Demographics** - Sex Assigned at Birth
    - Include 'sexAssignedAtBirth' using HL7 value set

[ ] **Demographics** - Gender Identity
    - Add 'genderIdentity' under demographics or social history

[ ] **Demographics** - Sexual Orientation
    - Add 'sexualOrientation' using appropriate SNOMED/HL7 codes

[x] **Demographics** - Pregnancy Status
    - Include as observation (e.g., SNOMED '77386006')

**[x ] Demographics** - Advance Directives - this was added to support MU
    - Support directive type, status, and responsible party

**[x] Demographics** - Health Insurance Info
    - Ensure structure matches USCDI v3 (payer name, coverage, subscriber)

[ ] **Demographics** - Substance Use
    - Add history under social history with standard codes

[x] **Care Team** - Broader Roles
    - Include case managers, caregivers with appropriate role codes

**[x] CCDA Templates** - Correct Template IDs
    - Ensure valid template OIDs and extensions

**[x] CCDA Templates** - Code Systems
    - Update SNOMED, LOINC, RXNORM, CVX, NUCC as needed

**[x] Provenance** - Custodian and Author Info
    - Verify organization and author metadata are correctly included

[x] **Provenance** - Record Target
    - Add patient identity metadata block

[ x] **Confidentiality** - Confidentiality Tags
    - Support DS4P codes like 'N', 'R' in document header

**[x] Export & Validation** - Filter by Date
    - Enable patient exports by date range

**[x] Export & Validation** - Select Sections
    - Allow patient to select sections to export

[~] **Export & Validation** - Scorecard Validation
    - Validate against ONC CCDA Scorecard

[~] **Export & Validation** - Inferno Testing
    - Run and pass Inferno CCDA tests

Claude code review b(1) USCDI V3

Based on my research and the code analysis, here's a comprehensive outline for ONC 170.315(b)(1) Transitions of Care requirements as they apply to USCDI v3 for 2025:
ONC 170.315(b)(1) Transitions of Care - USCDI v3 Requirements Outline
I. Core Requirement Overview
The USCDI is referenced as part of the data requirements in the updated "transitions of care" certification criterion (§ 170.315(b)(1)), which also specifies that for certification to that criterion, the C-CDA must be used as the syntax to hold all of the USCDI data. [OpenEMR Features - OpenEMR Project Wiki](https://www.open-emr.org/wiki/index.php/OpenEMR_Features)
II. USCDI v3 New Data Classes (Added to Transitions of Care)
A. Health Status Data Class
New for USCDI v3 - Must be included in C-CDA:

Functional Status (already in your code: getFunctionalStatus())
Mental/Cognitive Status (already in your code: getMentalStatus())
Disability Status (new requirement)

B. Insurance Data Class
This data class includes seven new elements: Coverage Status, Relationship to Subscriber, Member Identifier, Subscriber Identifier, Payer Identifier, Group Identifier, and Coverage Type. [§170.315(b)(1) Transitions of care](https://www.hhs.gov/guidance/sites/default/files/hhs-guidance-documents/2006093871-kq-b1tp.pdf)
Your Code Status: ✅ Well-positioned - Your populatePayer() function already handles most of these:

Coverage Status ✅
Relationship to Subscriber ✅
Member Identifier ✅
Subscriber Identifier ✅
Payer Identifier ✅
Group Identifier (may need enhancement)
Coverage Type (may need enhancement)

III. Enhanced Existing USCDI Data Requirements
A. Patient Demographics (Enhanced)
Your Code: populateDemographics() - ✅ Strong foundation

Race/Ethnicity (enhanced granularity)
Sexual Orientation (USCDI v3 addition)
Gender Identity (USCDI v3 addition)

B. Care Team Information (Enhanced)
Your Code: populateCareTeamMembers() - ✅ Excellent implementation

Provider Role (enhanced)
Care Team Member Contact Information
Code Enhancement Needed: Additional metadata for care transitions

C. Medications (Enhanced)
Your Code: populateMedication() - ✅ Good foundation

Enhanced medication reconciliation data
Medication adherence information (new)

IV. Technical Implementation Requirements for Your OpenEMR Code
A. Immediate Code Updates Needed:

Insurance Data Enhancement:

javascript// Enhance populatePayer() function
- Add Group Identifier mapping
- Add Coverage Type with setting-based logic
- Enhance relationship codes

Demographics Enhancement:

javascript// Update populateDemographics() function  
- Add Sexual Orientation fields
- Add Gender Identity fields
- Enhance race/ethnicity granularity

Health Status Addition:

javascript// Add new function: populateDisabilityStatus()
// Integrate with existing getFunctionalStatus() and getMentalStatus()
B. C-CDA Template Updates Required:

Care Plan Document Template updates
Continuity of Care Document (CCD) template enhancements
Referral Note template updates (your code already handles this)

C. FHIR Integration Enhancements:

FHIR R4 compatibility for USCDI v3 mapping
Enhanced US Core Profile alignment

V. Testing & Validation Requirements
A. Real-World Testing (2025):

Document exchange with USCDI v3 data elements
Care transition scenario testing
Insurance data exchange validation

B. Standards Compliance:

C-CDA R2.1 with USCDI v3 extensions
Direct messaging compatibility
FHIR R4 US Core alignment

VI. Implementation Priority for Your Code
High Priority (Must Have for 2025):

Insurance data class implementation (enhance populatePayer())
Sexual orientation/gender identity in demographics
Disability status documentation

Medium Priority (Recommended):

Enhanced care team metadata
Medication adherence tracking
Improved functional status integration

Low Priority (Future Enhancement):

Advanced quality measure reporting
Enhanced provenance tracking

VII. Your Code's Strengths for USCDI v3:
✅ Excellent care team implementation
✅ Comprehensive clinical data coverage
✅ Good payer/insurance foundation
✅ Robust demographic handling
✅ Strong C-CDA generation framework
Bottom Line: Your OpenEMR CCDA generator is well-positioned for USCDI v3 compliance. The main gaps are in the new Insurance and Health Status data classes, which would require targeted enhancements rather than major architectural changes.

### LINKED ISSUE #8851: Related Persons
Need to record related persons to patient. 
Since we have Guardian I though to add three more persons for total of four
Or clone Guardian to new Group.
I want to avoid another widget

### LINKED ISSUE #8894: Crash trying to create an SDOH assessment
### Describe the bug

I get an error page and a traceback when trying to create an SDOH for a synthetic patient.

```
[Wed Sep 17 13:36:05.551337 2025] [php:error] [pid 406:tid 406] [client 172.18.0.1:63414] PHP Fatal error:  Uncaught
TypeError: OpenEMR\\Services\\Sdoh\\HistorySdohService::goalsToText(): Argument #1 ($goals) must be of type array, nu
ll given, called in /var/www/localhost/htdocs/openemr/interface/patient_file/history/history_sdoh_widget.php on line
75 and defined in /var/www/localhost/htdocs/openemr/src/Services/Sdoh/HistorySdohService.php:162\nStack trace:\n#0 /v
ar/www/localhost/htdocs/openemr/interface/patient_file/history/history_sdoh_widget.php(75): OpenEMR\\Services\\Sdoh\\
HistorySdohService::goalsToText()\n#1 {main}\n  thrown in /var/www/localhost/htdocs/openemr/src/Services/Sdoh/History
SdohService.php on line 162
```

### To Reproduce

1. Start up docker/development-easy.
2. Use openemr-cmd to generate at least one patient.
3. In the web ui, navigate to a patient.
4. Click "assessments" and then create a new SDOH assessment.

### Expected behavior

The SDOH assessment should complete without error.

### Client configuration

- Browser: Firefox
- OpenEMR version: 7.0.4 / master
- Operating system: Docker/macOS

### LINKED ISSUE #8909: Care plan is missing an end date and status.
### Describe the bug

Care plan is missing an end date and status required for both FHIR and CCDA.
Add and expand table and add list for status.

### PR DESCRIPTION
**Pull request by sjpadgett**
fix payer template issues from b1 test tool
add plan name and correct oid's
Is passing IG
- add new SDOH Interventions GUI and CCDA section activity components and Treatment Plan Intervention and planned procedures. Whew, say that three times.
- Add new Related Persons e.g. Granddad, spouse etc. to Demographics. Most likely a new form panel in Contacts.

Fixes #8851 
Fixes #8647 
Fixes #8894
Fixes #8909

### CODE REVIEW

**Comment by sjpadgett** [comment]
[170.315_b1_toc_amb_svap_uscdiv3_sample1_v1.pdf](https://github.com/user-attachments/files/21942518/170.315_b1_toc_amb_svap_uscdiv3_sample1_v1.pdf)
@adunsulag Check out page 10+ for SDOH Maybe will help you get an idea what test is looking for...

**Comment by bradymiller** [comment]
2DV-2

**Comment by sjpadgett** [comment]
@juggernautsei check out

File: interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php [hunk 1]
```diff
@@ -230,18 +231,81 @@ public function getPatientdata($pid, $encounter): string
...
+        left join list_options AS l3 ON l3.list_id=? AND l3.option_id=religion
+        left join list_options AS l4 ON l4.list_id=? AND l4.option_id=language
+        where pid=?";
+
         $appTable = new ApplicationTable();
         $row = $appTable->zQuery($query, array('race', 'ethnicity', 'religious_affiliation', 'language', $pid));
-        // Render previous names
+
+        // --- Related persons (pull once; reuse in XML) ---
+        $relatedPersonService = new DemographicsRelatedPersonsService();
```
Comment (kojiromike) [inline interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php:402]: Where is this class defined?

Comment (sjpadgett) [reply interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php:402]: Yeah it's in another PR so notice is valid...

**Comment by sjpadgett** [comment]
y'all get mad at me but the e2e test at least don't make sense to run every commit. this is nuts too me!
Waitng for one or to to pass or fail befor database

**Comment by sjpadgett** [comment]
Should have failed by now so moving on.

**Comment by sjpadgett** [comment]
Did the test browser access paths change. My last dev config to run e2e test no longer works 
$this->crawler = $this->client->request('GET', '/interface/login/login.php?site=default&testing_mode=1');

**Comment by sjpadgett** [comment]
local runs to completion so ????

**Comment by bradymiller** [comment]
hi @sjpadgett , rec ignoring this issue since not from this code (pretty sure causing a timing issue that is not directly related). Confirmed fails on my local but again not directly related to your PR. Will work on a fix on the e2e code.

**Comment by bradymiller** [comment]
@sjpadgett , Looks like there is a break (hooray for e2e testing :) ) in the code. If I put the last name in the patient finder box on main frame, then get error popup on the patient finder:
`DataTables warning: table id=pt_table - Invalid JSON response. For more information about this error, please see https://datatables.net/tn/1`
(the funtional testing searches for the test patient's last name in the main patient finder box, which is why it then breaks in the patient finder whenever it tries to open the patient)

Can any of your code in this PR cause this?

**Comment by bradymiller** [comment]
Regarding the break in the main frame search finder. I confirmed this is testing well in master, so there must be something in this PR that is breaking this (got no clue what it is though :) ).

**Comment by sjpadgett** [comment]
Thanks Brady, I saw where it was breaking about 4am but too tired to run it down. Will let you know.

**Comment by sjpadgett** [comment]
I can't duplicate. This test only breaks with new relate person database changes and datatables is not reliable and has been throwing that error forever. The problem with these e2e test are if they don't follow exactly a set in time workflow they complain.

Still curious what in database is causing this to manifest and may be able to fix the annoying datatable json empty error.

**Comment by bradymiller** [comment]
Hi @sjpadgett ,

I confirmed that it works in master to place the patient last name in the patient finder selector in the top frame and click the corresponding find button in the top frame. It opens in the patient finder and shows the patient on the list.

I confirmed that the above does not work in this PR. When do above, it opens the patient finder and throws an error instead of showing the patient list. So, from my testing, it is a new bug in this PR. And it shows functional testing is doing its job here :)

My guess is there is a layout setting in the related persons tables that are flagging it to be included in the search, which breaks since the columns are not in the patient_data table (could be totally wrong since just  a guess).

**Comment by sjpadgett** [comment]
Also test is creating duplicate patients looking over after test.

**Comment by bradymiller** [comment]
php error log when try to use the top frame search finder a couple times:
```
ERROR: OpenEMR SQL Escaping ERROR of the following string: relatedaddress_1, referer: http://localhost:8300/interface/main/finder/dynamic_finder.php?search_any=asdasd
[Wed Sep 03 17:05:59.292325 2025] [php:notice] [pid 1147:tid 1147] [client 172.19.0.1:41416] ERROR: OpenEMR SQL Escaping ERROR of the following string: relatedaddress_1, referer: http://localhost:8300/interface/main/finder/dynamic_finder.php?search_any=sdfsdf
[Wed Sep 03 17:06:05.887768 2025] [php:notice] [pid 1179:tid 1179] [client 172.19.0.1:51556] ERROR: OpenEMR SQL Escaping ERROR of the following string: relatedaddress_1, referer: http://localhost:8300/interface/main/finder/dynamic_finder.php?search_any=S
```

I think this means this code is trying to validate a column name in patient_data, which does not exist. So somehow they are getting incorporated into the search_any algorithm

**Comment by bradymiller** [comment]
I think can fix it here (probably will also need to add related to beginning of your static entries; would even consider `related_` to all your entries to ensure no issues with folks that start their custom ids with related):
https://github.com/openemr/openemr/blob/master/interface/main/finder/dynamic_finder_ajax.php#L43-L46

**Comment by bradymiller** [comment]
If above is the fix, then i think functional testing (ie. a very sad "e2e" whom performs its job hundreds of times per day without appreciation or acknowledgement :) ) may require a thank you for avoiding a bug in a critical place :)

File: sql/database.sql [hunk 2]
```diff
@@ -14187,3 +14187,172 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+                              `codes`)
+VALUES ('DEM', 'relatedphone_3', '9', 'Phone', 340, 2, 1, 20, 63, '', 1, 1, '', '', 'Phone', 0, '', 'F', '', '', '');
+INSERT INTO `layout_options` (`form_id`, `field_id`, `group_id`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`, `validation`,
+                              `codes`)
+VALUES ('DEM', 'relatedworkphone_3', '9', 'Work Phone', 350, 2, 1, 20, 63, '', 1, 1, '', '', 'Work Phone', 0, '', 'F', '', '', '');
+INSERT INTO `layout_options` (`form_id`, `field_id`, `group_id`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`, `validation`,
+                              `codes`)
+VALUES ('DEM', 'relatedemail_3', '9', 'Email', 360, 2, 1, 20, 63, '', 1, 1, '', '', 'Related Email Address', 0, '', 'F', '', '', '');
```
Comment (bradymiller) [inline sql/database.sql]: Would put these in the section with all the other layout options to ensure we do not lose track of these

File: sql/database.sql [hunk 3]
```diff
@@ -14187,3 +14187,172 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+    `relatedstate_3`        VARCHAR(31)  DEFAULT NULL,
+    `relatedpostalcode_3`   VARCHAR(15)  DEFAULT NULL,
+    `relatedcountry_3`      VARCHAR(31)  DEFAULT NULL,
+    `relatedphone_3`        VARCHAR(25)  DEFAULT NULL,
+    `relatedworkphone_3`    VARCHAR(25)  DEFAULT NULL,
+    `relatedemail_3`        VARCHAR(254) DEFAULT NULL,
+
+    PRIMARY KEY (`pid`),
+    KEY `uuid_idx` (`uuid`)
+) ENGINE = InnoDB;
```
Comment (bradymiller) [inline sql/database.sql]: would place this alphabetically so it end up near patient_data

File: sql/database.sql (hunk 2 above)
Comment (sjpadgett) [reply sql/database.sql]: I though you wanted new sql in order of implementation or I'd done this in the first place!

Comment (bradymiller) [reply sql/database.sql]: hi @sjpadgett , sorry for the misunderstanding. order of implementation is in the sql upgrade script. best to place the database.sql stuff within especially when has other very relevant code (it's honestly not something i really mention on reviews since not too into keeping it alphabetical unless as in this case there is very relevant code in there).

Comment (sjpadgett) [reply sql/database.sql]: will do and makes perfect sense

**Comment by sjpadgett** [comment]
I've tried hard to duplicate and can't Brady. I though it'd be on of those that is os related. I'm even using a fully populated test db! Haven't tried on chrome though.

**Comment by sjpadgett** [comment]
> I think can fix it here (probably will also need to add related to beginning of your static entries; would even consider `related_` to all your entries to ensure no issues with folks that start their custom ids with related):

I don't understand. column are prepended with related!
However turns out search any is never on on my system regardless of config value!

**Comment by sjpadgett** [comment]
got it but config option was broken by whoever add delimiter to search

**Comment by sjpadgett** [comment]
Added interventions to be available with goals for SDOH Assessments. Interventions are formatted and saved as FHIR ServiceRequest resources. Below show resources as text formatted for user.

image

File: interface/main/finder/dynamic_finder_ajax.php [hunk 4]
```diff
@@ -36,14 +36,14 @@
...
+// persists not allowing easy way to unset any for normal search but opted not.
 //
 if ($searchAny) {
     $_GET['sSearch'] = $searchAny;
     $layoutCols = sqlStatement(
         "SELECT field_id FROM layout_options WHERE form_id = 'DEM'
-            AND field_id not like ? AND field_id not like ? AND uor !=0",
-        array('em\_%', 'add%')
+            AND field_id not like ? AND field_id not like ? AND field_id not like ? AND uor !=0",
+        array('em\_%', 'add%', 'related\_%')
```
Comment (bradymiller) [inline interface/main/finder/dynamic_finder_ajax.php:46]: kung-fu-baby-funny

File: interface/patient_file/history/history_sdoh.php [hunk 5]
```diff
@@ -100,15 +106,14 @@ function render_list_select($field, $list_id, $current, $placeholder = 'Select..
 </head>
 <body class="body_top">
     <div class="container-xl mb-3">
-        <form method="post" action="history_sdoh_save.php?pid=<?php echo attr_url($pid); ?>" onsubmit="top.restoreSession()">
+        <form method="post" action="history_sdoh_save.php?pid=<?php echo ($pid); ?>" onsubmit="top.restoreSession()">
```
Comment (bradymiller) [inline interface/patient_file/history/history_sdoh.php]: would keep above (unless it was breaking something)

File: interface/patient_file/history/history_sdoh.php [hunk 6]
```diff
@@ -171,7 +176,7 @@ function render_list_select($field, $list_id, $current, $placeholder = 'Select..
                         ?>
                         <div class="col-12 col-md-6">
                             <div class="card h-100 mb-2">
-                                <div class="card-header font-weight-bold"><?php echo text($label); ?></div>
+                                <div class="card-header font-weight-bold"><?php echo $label; ?></div>
```
Comment (bradymiller) [inline interface/patient_file/history/history_sdoh.php]: would keep above (unless it was breaking something or has already been escaped)

File: interface/patient_file/history/history_sdoh.php [hunk 7]
```diff
@@ -265,18 +270,18 @@ function render_list_select($field, $list_id, $current, $placeholder = 'Select..
...
                             <label><?php echo xlt("Interventions / Referrals"); ?></label>
-                            <textarea class="form-control" rows="3" name="interventions"><?php echo text(v($info, 'interventions')); ?></textarea>
+                            <textarea class="form-control" rows="3" name="interventions" placeholder="<?php echo xla('Assessment calculated Treatment Plan Interventions resources display here after assessment is saved.') ?>" readonly><?php echo text($interventions_text); ?></textarea>
                         </div>
                     </div>
                 </div>
 
                 <div class="mb-4">
                     <button type="submit" class="btn btn-primary"><?php echo xlt("Save"); ?></button>
-                    <a class="btn btn-secondary" href="<?php echo attr($GLOBALS['webroot'] . '/interface/patient_file/history/history_sdoh_widget.php?pid=' . urlencode($pid)); ?>">
```
Comment (bradymiller) [inline interface/patient_file/history/history_sdoh.php:275]: i also usually don't escape the entire url and could focus it on just the $pid with attr_url (same for line 284 below)

**Comment by bradymiller** [comment]
2DV (1)

File: interface/patient_file/history/history_sdoh.php (hunk 6 above)
Comment (sjpadgett) [reply interface/patient_file/history/history_sdoh.php]: followed you review note that was already escaped. took your word for but will recheck thanks

File: interface/patient_file/history/history_sdoh.php (hunk 7 above)
Comment (sjpadgett) [reply interface/patient_file/history/history_sdoh.php:275]: yeah I haven't train Goober to escape urls yet but he does a great job on all the other of our escaping so I will send him back for retraining!:)

**Comment by sjpadgett** [comment]
Finally a big hurtle done with Health Concerns section passing finally. Some of these test are on the very edge and even ONC admits many times never used. Even saw that a test requirement was justified because Epic does it!
Anyway I need to merge this soon so other may test and use up to this point.
However since related person is contained in this PR I am trying to decide if I go a different way as I've received some pushback to using a non-relational limited LBF Group for Related.

Personally I'm hesitant to use additional addresses and I tend towards changing care teams renaming to patient support contacts or something because I want to remove all the LBF dependencies for these custom datatypes. At some point we keep LBF for encounter forms and replace on the front end.
I think LBF was a terrific feature and have defended it many times but I thing we have outgrown it and are hacking our way forward. I know Jerry again!

I do think the push back is valid and I am being paid for this so it's only right I pay close attention to peer review from the community.

I would like to get feedback from admins if I should take a different approach. thanks

**Comment by bradymiller** [comment]
hi @sjpadgett , I think your current approach is totally fine. Can make it fancier, if somebody wants to take that up, in the future (ie. would be easy upgrade/migration path). Goal now is to get it in and ensure we get onc done :)

**Comment by sjpadgett** [comment]
will do, thanks

**Comment by sjpadgett** [comment]
@bradymiller A little help. local test fails
C:\xampp\php\php.exe -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 C:/xampp/htdocs/openemr/vendor/phpunit/phpunit/phpunit --configuration C:\xampp\htdocs\openemr\phpunit.xml --teamcity
Testing started at 12:22 AM ...
Testing started at 12:22 AM ...
PHPUnit 11.5.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.2.12
Configuration: C:\xampp\htdocs\openemr\phpunit.xml
Test needs to check if the intervals are updated
C:\xampp\htdocs\openemr\tests\Tests\Unit\ClinicalDecisionRules\ControllerEditTest.php:131

FAILED to show login page
Failed asserting that two strings are identical.
Expected :'OpenEMR Login'
Actual   :'Object not found!'

Could be a dozen reason can't login. I have tested database creation okay wiyh PR changes.
I loaded easy dev after purge and was able to login, create patient and create new encounter all working. My new stuff, SDOH Assessment, Related Persons and Tribal work fine. I'm too tired to fire up headless

**Comment by bradymiller** [comment]
hi @sjpadgett , Will check it out. Error reporting looks eerily similar to that issue in past when the patient finder in the main top frame was not working. Will test it out now and let you know what i see.

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 8]
```diff
@@ -612,7 +612,296 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+-- DEM Layout: Tribal Affiliations
+-- Resequence group by order of 10
+-- =========================
+#IfNotRow2D layout_options form_id DEM field_id tribal_affiliations
+SET @group_id =(SELECT `group_id` FROM layout_options WHERE field_id='religion' AND form_id='DEM');
+SET @seq_start := 0;
+UPDATE `layout_options` SET `seq` = (@seq_start := @seq_start+1)*10 WHERE group_id = @group_id AND form_id='DEM' ORDER BY `seq`;
+SET @seq_add_to = (SELECT seq FROM layout_options WHERE group_id = @group_id AND field_id='religion' AND form_id='DEM');
+INSERT INTO `layout_options` (`form_id`, `field_id`, `group_id`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`, `validation`, `codes`) VALUES ('DEM','tribal_affiliations',@group_id,'Tribal Affiliations',@seq_add_to+10,1,1,0,0,'tribal_affiliations',1,1,'','','Tribal Affiliations entries',0,'','F','','','');
+ALTER TABLE `patient_data` ADD `tribal_affiliations` TEXT;
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql:834]: don't see this new column added in database.sql file

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 9]
```diff
@@ -612,7 +612,296 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+#Endif
+
+-- =========================
+-- form_history_sdoh: grouped adds
+-- =========================
+#IfTable form_history_sdoh
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: Looks like this table in database.sql, so would instead check if the `instrument_score` column is missing and then run block of code adding the columns in standard fashion.

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 10]
```diff
@@ -612,7 +612,296 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+ALTER TABLE form_history_sdoh
+    ADD COLUMN IF NOT EXISTS instrument_score INT NULL,
+    ADD COLUMN IF NOT EXISTS positive_domain_count INT NULL,
+    ADD COLUMN IF NOT EXISTS extended_domains JSON NULL,
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: we can't use JSON. it will break cross compatibility with mysql and mariadb.

Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: basically need to make it a TEXT and store the JSON there.

Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: Consider this a showstopper on this PR until addressed.

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 11]
```diff
@@ -612,7 +612,296 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+    ADD COLUMN IF NOT EXISTS declined_flag TINYINT(1) NULL,
+    ADD COLUMN IF NOT EXISTS disability_status VARCHAR(50) NULL,
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: would place the DEFAULT to left of NULL so is duplicate/same as the upgrade stuff (i know they do same thing, but just easier now and in future when comparing this duplicated code)

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 12]
```diff
@@ -612,7 +612,296 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+    ADD COLUMN IF NOT EXISTS disability_status_notes TEXT NULL,
+    ADD COLUMN IF NOT EXISTS disability_scale TEXT NULL,
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: For above 2 lines, need to remove the NULL (this has already been done in the upgrade script.)

File: sql/database.sql [hunk 13]
```diff
@@ -5255,18 +5295,47 @@ INSERT INTO list_options (list_id, option_id, codes,title, seq) VALUES ('physici
...
+INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`, `activity`, `subtype`, `edit_options`, `timestamp`, `last_updated`) VALUES ('Industry','999999','Unemployed',150,0,0,'',NULL,'999999',0,0,1,'',1,'2025-09-17 02:02:03','2025-09-16 22:02:03');
+INSERT INTO `list_options` (`list_id`, `option_id`, `title`, `seq`, `is_default`, `option_value`, `mapping`, `notes`, `codes`, `toggle_setting_1`, `toggle_setting_2`, `activity`, `subtype`, `edit_options`, `timestamp`, `last_updated`) VALUES ('Industry','UNKNOWN','Unknown',160,0,0,'',NULL,'UNKNOWN',0,0,1,'',1,'2025-09-17 02:02:03','2025-09-16 22:02:03');
 -- Occupation
-
-INSERT INTO `list_options` (`list_id`, `option_id`, `title`) VALUES('lists','Occupation','Occupation');
-INSERT INTO list_options ( list_id, option_id, title, seq ) VALUES ('Occupation', 'lawyer', 'Lawyer', 10);
-INSERT INTO list_options ( list_id, option_id, title, seq ) VALUES ('Occupation', 'engineer', 'Engineer', 20);
-INSERT INTO list_options ( list_id, option_id, title, seq ) VALUES ('Occupation', 'site_worker', 'Site Worker', 30);
```
Comment (bradymiller) [inline sql/database.sql:5268]: Wouldn't overwrite a current list. Would instead create a new list with different name/list_id. Note this will also not work in the upgrade script.

**Comment by bradymiller** [comment]
hi @sjpadgett ,

Completed code review and noted some issues in the database stuff. Also note we can't use JSON since they are not cross compatible with mysql and mariadb (do note this analysis was completed in more distant past and potentially may not be true on the more modern versions; however it will require extensive testing to ensure database backups can be migrated back and forth between mysql and mariadb, which is why would go with easier/quicker route of storing as a TEXT or LONGTEXT etc.).

The functional testing is failing because of the Patient Finder. Same bug when enter a name in the patient finder box on top main frame and click search (it then goes to the patient finder tab and throws a javascript error and error log shows a break in the sql query on patient_finder since looking for the related* stuff in patient_data table). This is super weird, because I definitely remember you having a commit somewhere that fixed this while also normalizing the related column names to ensure do not conflict with patient_data custom columns.

File: sql/database.sql [hunk 14]
```diff
@@ -13386,6 +13453,57 @@ CREATE TABLE `onetime_auth` (
...
+-- --------------------------------------------------------
+-- Table Patient Related Person LBF DEM group data table
+-- --------------------------------------------------------
+
+DROP TABLE IF EXISTS `patient_related_persons`;
+CREATE TABLE `patient_related_persons`
+(
+    `pid`                   BIGINT UNSIGNED NOT NULL,
+    `uuid`                  binary(16)   DEFAULT NULL,
+    `relatedfirstname_1`    VARCHAR(63)  DEFAULT NULL,
```
Comment (bradymiller) [inline sql/database.sql]: note need to restructure column names and layout stuff to `related_` as you did in the upgrade script.

**Comment by bradymiller** [comment]
Here was the restructure commit in this PR to that change columns to `related_` to prevent skipping custom related columns in patient_data on search:
https://github.com/openemr/openemr/pull/8797/commits/7b5b2033a3760508f76fda91c60520fa9f3cf314

And here was the patient finder fix commit in this PR:
https://github.com/openemr/openemr/pull/8797/commits/ce8d5afab6bf4b08531b027647d3e26eea2c547d

Note that you need to restructure the stuff in database.sql also (ie. to `related_`) as you did in the upgrade script. When that is done, then the functional testing should start working.

**Comment by bradymiller** [comment]
hi @sjpadgett , review complete. Huge amount of nice work here. Just some database cleanup needed.

**Comment by bradymiller** [comment]
fyi, also did some research on JSON column type and the dumpfiles are still not compatible. If you take a dumpfile from mariadb and then try to use it on mysql, it will break (this is because mariadb dumps it as LONGTEXT with some weird json attribute). So will need to change the JSON column type to TEXT/LONGTEXT.

File: sql/database.sql (hunk 13 above)
Comment (sjpadgett) [reply sql/database.sql:5268]: Not overwriting because at this point the list doesn't exist and maintains legacy for access of occupation and industry in Employer group.
While I made a late change in upgrade to prevent list update I have since fixed and new list items will append to existing.
It's that or delete list the add new.
New list is not appropriate because these list are old legacy in Employer plus tied to ccda and fhir so list name integrity is important. But thanks you caught my boo boo when I late added meta tags in upgrade.
Btw: JSON was Goobers fault!:)

File: sql/7_0_3-to-7_0_4_upgrade.sql (hunk 11 above)
Comment (sjpadgett) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: no clue!

File: sql/database.sql [hunk 15]
```diff
@@ -348,7 +348,7 @@ CREATE TABLE `categories_seq` (
 -- Inserting data for table `categories_seq`
 --
 
-INSERT INTO `categories_seq` VALUES (31);
+INSERT INTO `categories_seq` VALUES (34);
```
Comment (stephenwaite) [inline sql/database.sql]: :man_dancing: 

sorry to interfere again :), have to bump `version.php` if you didn't already

File: version.php [hunk 16]
```diff
@@ -28,7 +28,7 @@
 // is a database change in the course of development.  It is used
 // internally to determine when a database upgrade is needed.
 //
-$v_database = 514;
+$v_database = 516;
```
Comment (stephenwaite) [inline version.php:31]: you got it!

**Comment by sjpadgett** [comment]
What's up with [Test / PHP 8.4 - apache - mariadb 11.4 (pull_request)] 38 minutes and still going!

**Comment by bradymiller** [comment]
@sjpadgett , no need to wait on that at this time (if all other tests are passing). also can disregard codecov stuff since still working out issues on that (check out my post on other PR regarding this).

**Comment by bradymiller** [comment]
To better explain, we have had that long running test for some time, which will track testing coverage, so takes a long time. I think as of today, this coverage info is now going to codedev tool which will be super helpful on tracking code testing coverage. On my PR's, that test is not something that i wait for if all the other tests are passing. At some point in mid-term or long-term this may change (when starting to push for testing on code) and hopefully by then we will have speed up that coverage test.

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 17]
```diff
@@ -612,7 +612,294 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+       ('Industry','445110','Supermarkets and Other Grocery Stores',80,'445110.006564',1),
+       ('Industry','238210','Electrical Contractors',90,'238210.004871',1),
+       ('Industry','621111','Offices of Physicians (except Mental Health)',100,'621111.009165',1),
+       ('Industry','531110','Lessors of Residential Buildings',110,'531110.007615',1),
+       ('Industry','484121','General Freight Trucking, Long-Distance',120,'484121.007193',1),
+       ('Industry','812111','Barber Shops',130,'812111.011099',1),
+       ('Industry','522110','Commercial Banking',140,'522110.007773',1),
+       ('Industry','999999','Unemployed',150,'999999',1),
+       ('Industry','UNKNOWN','Unknown',160,'UNKNOWN',1)
+ON DUPLICATE KEY UPDATE option_id=VALUES(option_id), title=VALUES(title), codes=VALUES(codes), activity=VALUES(activity);
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: hi @sjpadgett , 
Still don't understand:
1. Why using the `ON DUPLICATE KEY` in all these queries
2. And still seems like the original 3 Industry list items will remain in the upgrade database, but not be in the new database?

File: sql/7_0_3-to-7_0_4_upgrade.sql [hunk 18]
```diff
@@ -612,7 +612,294 @@ VALUES ('sdoh_instruments', 'hunger_vital_sign', 'Hunger Vital Sign (2-item)', 1
...
+       ('tribal_affiliations','zuni','Zuni Tribe (NM)',110,'337',1),
+       ('tribal_affiliations','other_specify','Other (specify)',120,'000',1)
+ON DUPLICATE KEY UPDATE title=VALUES(title), notes=VALUES(notes), activity=VALUES(activity);
+#EndIf
+
+/* -------- ODH Industry (optional; used if you capture industry) -------- */
+#IfNotRow2D list_options list_id Industry option_id 541110
+INSERT INTO list_options (list_id, option_id, title, seq, is_default, option_value, notes, activity)
+VALUES ('lists','Industry','ODH Industry',0,0,0,'NAICS-based industry codes from ODH',1)
+ON DUPLICATE KEY UPDATE title=VALUES(title), notes=VALUES(notes);
```
Comment (bradymiller) [inline sql/7_0_3-to-7_0_4_upgrade.sql]: i think this is one of only 2 elements (lists-Industry and lists-Occupation) where the ON DUPLICATE will do what you want (where composite list_id/option_id key will equal a prior entry)

File: sql/7_0_3-to-7_0_4_upgrade.sql (hunk 17 above)
Comment (sjpadgett) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: The original 3 industry items aren't valid in any useful way so for new database we don't want them and going forward use only correct value sets.
Left the three legacy values in and appended the correct coded list. Did so to maintain legacy data. My preference is to delete the list and replace with new corrected list values.

I don't get what the big deal is. There are actually several more lists that need to go or be updated to reflect modern reporting. I try hard to impact users as little as possible but sometime it's necessary.
I removed the duplicate test on new lists but I feel more comfortable having the duplicate checks.

File: sql/7_0_3-to-7_0_4_upgrade.sql (hunk 18 above)
Comment (sjpadgett) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: true but having the duplicate doesn't hurt anything. still I removed.

**Comment by sjpadgett** [comment]
updated status widget 
image

File: sql/7_0_3-to-7_0_4_upgrade.sql (hunk 17 above)
Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: hi @sjpadgett , Sorry for confusion. Definitely ok to replace old list as long as consistent (since it was specific for ccda stuff) in new database and upgraded database. I was just pointing out that there will be divergence of a new database and and upgraded database (the upgraded database will still continue to have the legacy items whereas the new database will not).

Comment (bradymiller) [reply sql/7_0_3-to-7_0_4_upgrade.sql]: We do have a crazy mechanism/widget in layouts where can have a backup list. Since had this type of issue back in past with ethnicity/race. So can keep an old list around for mapping of old items, but only allow selection of items from the new list (in addition to only the old item that is already selected/mapped (and as i recall shows a warning to change to something else in that case)). Thus can keep mapping of old stuff, but only allow new list use for future use. Not saying it should be used in this case or anything, but it is one of those weird things that can be helpful every decade or so :)

File: interface/patient_file/history/history_sdoh_widget.php [hunk 19]
```diff
@@ -74,8 +74,14 @@ function hs_clip(?string $s, int $len = 80): string
 $goals_arr = json_decode($info['goals'] ?? '[]', true);
 $goals_text = HistorySdohService::goalsToText($goals_arr, [
     'include_category' => true,
-    'include_measure'  => true,
-    'include_due'      => true
+    'include_measure' => true,
+    'include_due' => true
+]);
+$interventions_arr = json_decode($info['interventions'] ?? '[]', true);
+$interventions_text = HistorySdohService::interventionsToText($interventions_arr, [
```
Comment (adunsulag) [inline interface/patient_file/history/history_sdoh_widget.php:110]: @sjpadgett  I'm getting a fatal error for this line here.   It looks like HistorySdohService namespace is: **OpenEMR\Services\Sdoh\HistorySdohService;**  but this doesn't work on case-sensitive file systems as the folder name is SDOH.  Either the folder needs to be renamed or the namespaces everywhere this class is used need to renamed to Sdoh.

Here is the error.
```
[Thu Sep 18 14:32:31.496727 2025] [php:error] [pid 1566:tid 1566] [client 172.19.0.1:38676] PHP Fatal error:  Uncaught Error: Class "OpenEMR\\Services\\Sdoh\\HistorySdohService" not found in /var/www/localhost/htdocs/openemr/interface/patient_file/history/history_sdoh_widget.php:75\nStack trace:\n#0 {main}\n  thrown in /var/www/localhost/htdocs/openemr/interface/patient_file/history/history_sdoh_widget.php on line 75, referer: https://localhost:9300/interface/patient_file/summary/demographics.php?set_pid=1&is_new=1
```

Comment (sjpadgett) [reply interface/patient_file/history/history_sdoh_widget.php:110]: Nutz, thanks. Maybe one day Linux will grow up to be a real O.S. :)

**Comment by sjpadgett** [comment]
Disability Status assessment is not required, at least not so far, in ccda Functional Status section but Hunger is in Social. I have a feeling it was missed by ONC and will be wanted at some point so I'm going to add while on this mess. You watch though that just by me being proactive, ccda service is going to give me grief!:)

**Comment by sjpadgett** [comment]
Disability Assessment entry done and pass. This completes scenario one. Next three should not be to difficult but I haven't looked into closely. Only answered questions are included.
```
<entry typeCode="DRIV">
            <observation classCode="OBS" moodCode="EVN">
              <templateId root="2.16.840.1.113883.10.20.22.4.505" extension="2023-05-01"/>
              <templateId root="2.16.840.1.113883.10.20.22.4.505"/>
              <id nullFlavor="UNK"/>
              <code code="89571-4" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Overall disability status CUBS"/>
              <statusCode code="completed"/>
              <effectiveTime value="20250921"/>
              <value xsi:type="CD" code="LA29243-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="I'm Vulnerable."/>
              <entryRelationship typeCode="COMP">
                <observation classCode="OBS" moodCode="EVN">
                  <templateId root="2.16.840.1.113883.10.20.22.4.86"/>
                  <id nullFlavor="UNK"/>
                  <code code="69859-7" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Difficulty walking or climbing stairs"/>
                  <statusCode code="completed"/>
                  <value xsi:type="CD" code="LA33-6" codeSystemName="LOINC" displayName="Yes"/>
                </observation>
              </entryRelationship>
              <entryRelationship typeCode="COMP">
                <observation classCode="OBS" moodCode="EVN">
                  <templateId root="2.16.840.1.113883.10.20.22.4.86"/>
                  <id nullFlavor="UNK"/>
                  <code code="69861-3" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC" displayName="Difficulty seeing"/>
                  <statusCode code="completed"/>
                  <value xsi:type="CD" code="LA33-6" codeSystemName="LOINC" displayName="Yes"/>
                </observation>
              </entryRelationship>
            </observation>
          </entry>
```

**Comment by sjpadgett** [comment]
@bradymiller 
I added industry and occupation as new lists and put originals back. I couldn't get the backup list to work and I couldn't find if the backup list is used anywhere. So I don't know and will leave up to you.
I can attest that the occupation entry in ccda is correct but we won't be able to supply the correct code ONC test looks for. Meets spec though.

@adunsulag I had to fix form_observation table changes to be compatible to mariadb < 10.5 and mysql < 8.0 

This is ready to merge as far as I'm concern. 

I'll be around for a couple hour working on care plan changes if I'm needed.

**Comment by sjpadgett** [comment]
@adunsulag 
I went ahead and added the requested end date and status to care plan to this PR mainly because of database and new lists. Thought it'd be more organized.

If it covers FHIR needs and you need to continue your work, you guys can merge.

image

**Comment by sjpadgett** [comment]
forgot uuid for SDOH assessment, added. Now I'm done!:)
