### PR TITLE
fix: fee sheet delete save current

### LINKED ISSUE #6960: Bug - Fee sheet delete move data
### Describe the bug

There is a bug on the fee sheet when a line is removed from the fee sheet. All the data for that line that is removed is moved down to the next line making the line information incorrect.

### To Reproduce

https://youtu.be/We2PQvhE76w
Watch the video for the steps to repeat. 

### Expected behavior

The selected line to be deleted and the remaining lines to remain in tact. 

### Client configuration

- Browser:
- OpenEMR version:
- Operating system:

### PR DESCRIPTION
**Pull request by stephenwaite**
Fixes #6960 

#### Short description of what this resolves:
fix Save Current behavior by removing old post data and also provide immediate visual feedback when clicking delete on an item

### CODE REVIEW

File: interface/forms/fee_sheet/new.php [hunk 1]
```diff
@@ -300,7 +300,7 @@ function echoServiceLines(): void
             }
 
             echo "  <td class='billcell text-center'><input type='checkbox' name='bill[" . attr($lino) . "][del]' " .
-            "value='1'" . ($li['del'] ? " checked" : "") . " /></td>\n";
+            "value='1'" . (text($li['del']) ? " checked" : "") . " onchange='toggleDeleteStrike(this)' /></td>\n";
```
Comment (bradymiller) [inline interface/forms/fee_sheet/new.php]: shouldn't need to escape the conditional
(won't break anything, but not getting outputted to html so don't need to do)

**Review by bradymiller — APPROVED** [review]
